chef/data_bags/crowbar/migrate/ipmi/101_bmc_interface.rb, chef/data_bags/crowbar/template-ipmi.json, chef/data_bags/crowbar/template-ipmi.schema, crowbar_framework/app/models/node.rb, crowbar_framework/app/views/barclamp/ipmi/_edit_attributes.html.haml, crowbar_framework/config/locales/ipmi/en.yml
Add support for specifying the bmc_interface type in the IPMI barclamp.
Drive-by converting tabs to spaces in the JSON template file.
Co-Authored-By: Eugen Block <e.block@suse.com>
requests?**
=> ipmi: Add support for bmc_interface (bsc#1046567)

chef/data_bags/crowbar/migrate/ipmi/101_bmc_interface.rb, chef/data_bags/crowbar/template-ipmi.json, chef/data_bags/crowbar/template-ipmi.schema, crowbar_framework/app/models/node.rb, crowbar_framework/app/views/barclamp/ipmi/_edit_attributes.html.haml, crowbar_framework/config/locales/ipmi/en.yml
Add support for specifying the bmc_interface type in the IPMI barclamp.
The interface was always hardcoded to lanplus, so provide that as the
default.
Drive-by converting tabs to spaces in the JSON template file.
Co-Authored-By: Eugen Block <e.block@suse.com>
(cherry picked from commit aa5972d9a48b590d37ca53f9e2fc174ac082b11c)
requests?**
=> [stable/4.0] ipmi: Add support for bmc_interface (bsc#1046567)

chef/cookbooks/barclamp/libraries/nic.rb, chef/cookbooks/network/recipes/default.rb
Currently, when adding slaves to a bond, the interface will be brought
down and then back up. If wicked is not told about this state of
affairs, wicked will add the configured IP address back onto the
interface when it is bought back up.
To counteract this, we run wicked ifdown for any slave interface, as
well as no longer bringing the slave back up immediately and then run
wicked ifup all if the template files have changed, so it isn't run every
time chef fires.
Note, this partially brings back what we reverted with
41e310cf21642cf0dc2f2fa0b7294c1db7821b59, but calling "ifup" instead of
"ifreload" has the advantage that will not take the interfaces down
temporary. It will also keep all IP addresses that are not managed by
wicked (i.e. the pacemaker managed cluster VIPs). So we should …
=> [stable/4.0] network: Use wicked to control bond slaves (bsc#1035127)

.travis.yml, chef/cookbooks/barclamp/.rspec, chef/cookbooks/barclamp/Gemfile, chef/cookbooks/barclamp/Rakefile, chef/cookbooks/barclamp/libraries/barclamp_library.rb, chef/cookbooks/barclamp/spec/libraries/barclamp_library_spec.rb, chef/cookbooks/barclamp/spec/spec_helper.rb
dm_multipath devices were being skipped while its paths were being included
in the array of unclaimed devices, allowing the DRBD recipe to claim them
and later fail while running pvcreate.
Introduce two new methods in Disk for checking whether the device (or its
holder) is named as "mpath-*".
=> Unclaimed disks: improve handling of multipath devices (bsc#1031065)

.travis.yml, chef/cookbooks/barclamp/.rspec, chef/cookbooks/barclamp/Gemfile, chef/cookbooks/barclamp/Rakefile, chef/cookbooks/barclamp/libraries/barclamp_library.rb, chef/cookbooks/barclamp/spec/libraries/barclamp_library_spec.rb, chef/cookbooks/barclamp/spec/spec_helper.rb
dm_multipath devices were being skipped while its paths were being included
in the array of unclaimed devices, allowing the DRBD recipe to claim them
and later fail while running pvcreate.
Introduce two new methods in Disk for checking whether the device (or its
holder) is named as "mpath-*".
This will make sure that when having a multipath device with several holders
we add to the unclaimed list only the multipath device and we ignore
the holders.
(cherry picked from commit dd2cde1b8a232e73c13035c994b6bdca7389034a)
=> [4.0] Unclaimed disks: improve handling of multipath devices (bsc#1031065)

chef/cookbooks/network/recipes/default.rb
If a physical interface has VLAN(s) configured with a custom MTU set but
the underlying physical network is not used directly and has no MTU in
its config, use the MTU from the VLAN interface for the parent device.
If there are multiple VLANs, use the highest MTU for the parent.
Also, if the physical parent from a VLAN interface is configured but the
MTU is lower than one of its VLAN interfaces, abort the chef-client run
and raise a useful error message.
(cherry picked from commit fc4152dd2aa903959e9f978b1fb48f51f7146420)
Backported as requested on https://github.com/crowbar/crowbar-core/pull/1230 by @vuntz
=> [3.0] network: Set MTU for VLAN parent interface (bsc#1024279)

.travis.yml, chef/cookbooks/barclamp/.rspec, chef/cookbooks/barclamp/Gemfile, chef/cookbooks/barclamp/Rakefile, chef/cookbooks/barclamp/libraries/barclamp_library.rb, chef/cookbooks/barclamp/spec/libraries/barclamp_library_spec.rb, chef/cookbooks/barclamp/spec/spec_helper.rb
dm_multipath devices were being skipped while its paths were being included
in the array of unclaimed devices, allowing the DRBD recipe to claim them
and later fail while running pvcreate.
Introduce two new methods in Disk for checking whether the device (or its
holder) is named as "mpath-*".
This will make sure that when having a multipath device with several holders
we add to the unclaimed list only the multipath device and we ignore
the holders.
(cherry picked from commit dd2cde1b8a232e73c13035c994b6bdca7389034a)
=> [3.0] Unclaimed disks: improve handling of multipath devices (bsc#1031065)

chef/cookbooks/barclamp/libraries/nic.rb, chef/cookbooks/network/recipes/default.rb
Currently, when adding slaves to a bond, the interface will be brought
down and then back up. If wicked is not told about this state of
affairs, wicked will add the configured IP address back onto the
interface when it is bought back up.
To counteract this, we run wicked ifdown for any slave interface, as
well as no longer bringing the slave back up immediately and then run
wicked ifup all if the template files have changed, so it isn't run every
time chef fires.
Note, this partially brings back what we reverted with
41e310cf21642cf0dc2f2fa0b7294c1db7821b59, but calling "ifup" instead of
"ifreload" has the advantage that will not take the interfaces down
temporary. It will also keep all IP addresses that are not managed by
wicked (i.e. the pacemaker managed cluster VIPs). So we should …
=> [stable/3.0] network: Use wicked to control bond slaves (bsc#1035127)

chef/cookbooks/crowbar/files/default/knife.rb
Just a small QOL patch.
Before we would need to specify with the "-o" option
the full path to the cookbook location in the local machine
when dealing with cookbook uploads.
As this location is fixed, we can just add it to the knife.rb
file and avoid specifying it.
=> crowbar: use the default cookbook path in the knife.rb file

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/application.rb
Stolen from https://github.com/crowbar/crowbar-core/pull/896/ to rebase and improve (if needed)
crowbar: Use a thread pool when acquiring/release chef-client locks.
=> Use threads to acquire/release locks in apply_role

crowbar_framework/lib/crowbar/lock/shared_non_blocking.rb
In order to avoid circular dependencies when using threading
we should explicitly require the appropriate modules that we
are gonna use.
=> crowbar: explicitly require the modules to avoid circular dependencies

crowbar_framework/app/models/service_object.rb
Before the threading patch we were waiting for ALL of the nodes
being applied to finish their chef runs. After what looked like a typo
we were only looking at the nodes locked, which ignores the admin node.
So it could happen that the admin node was running the chef client
and it was ignored, not filling properly the templates for bind
thus not allowing the other dns server nodes to transfer zones,
which made the multi-dns test fail all the time randomly
=> crowbar: Fix the wait for the chef daemons

crowbar_framework/app/models/service_object.rb
Before the threading patch we were waiting for ALL of the nodes
being applied to finish their chef runs. After what looked like a typo
we were only looking at the nodes locked, which ignores the admin node.
So it could happen that the admin node was running the chef client
and it was ignored, not filling properly the templates for bind
thus not allowing the other dns server nodes to transfer zones,
which made the multi-dns test fail all the time randomly
(cherry picked from commit af14a7b70248e7890274282dc6816f48a27bba98)
=> [4.0] crowbar: Fix the wait for the chef daemons

chef/cookbooks/bind9/recipes/default.rb, chef/cookbooks/bind9/templates/default/named.conf.default-zones.erb, chef/cookbooks/bind9/templates/default/zone.erb
http://bugzilla.suse.com/show_bug.cgi?id=1036601
Tells bind to use the admin IP as source for zone transfers, even if VIPs from pacemaker are the primary addr at the moment.
requests?**
=> bind: set transfer-source to avoid xfer failures (bsc#1036601)

crowbar_framework/app/models/service_object.rb
See the usage of the method in the code:
```
valid_nodes.reject! do |node|
node_is_invalid_for_role(node.name, role)
end
```
Note that crowbar-ceph is using the old name, so it needs to be fixed together with this.
=> Fix confusing name of the method that does the opposite than claims

chef/cookbooks/apache2/templates/default/apache2.conf.erb
There was a missing " in the template, leading to errors while uploading
the recipe manually to the chef server
Cant believe this was there for over 2 years and everything worked! Did nobody uploaded the apache2 recipe manually in those 2 years :rofl:
=> apache2: fix apache2.conf template

chef/cookbooks/apache2/templates/default/apache2.conf.erb
There was a missing " in the template, leading to errors while uploading
the recipe manually to the chef server
(cherry picked from commit 4a60c80c636b7b364d929f955e5c082a16201837)
=> [3.0] apache2: fix apache2.conf template

chef/cookbooks/apache2/templates/default/apache2.conf.erb
There was a missing " in the template, leading to errors while uploading
the recipe manually to the chef server
(cherry picked from commit 4a60c80c636b7b364d929f955e5c082a16201837)
=> [4.0] apache2: fix apache2.conf template

chef/cookbooks/barclamp/libraries/barclamp_library.rb, crowbar_framework/app/models/node.rb
NVMe device does not match any of the conditions to be a claimed disk
hence always unclaimed. Adding the pattern to the regex makes it claimable.
=> Allow setting NVMe drive in ceph (bsc #1051298)

.knife-test.rb, .travis.yml
Use the installed knife command to check for cookbook
syntax. This will catch ruby issues on the cookbooks and also
template issues that we are not checking right now.
=> testing: use knife to check syntax of cookbooks

crowbar_framework/lib/crowbar/validator/network_validator.rb
The previous network validator take the first private IP from the
system and expect that this is the admin IP.  This work OK in case
that eth0 is listed before eth1, but this is something that do not
happends always.
This change use the FQND information to deduce the admin IP, as
install-suse-cloud is doing.
=> Fix network_validator (bsc#1025642)

chef/cookbooks/barclamp/libraries/barclamp_library.rb
Apparently there is a way to get nodes in a state without the [:network]
attribute being set. it shouldn't harm to just continue as if
nothing would have happened.
requests?**
=> Avoid crashing chef on listing "installing" nodes (bsc#1050278)

chef/cookbooks/ipmi/recipes/ipmi-discover.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/utils/libraries/helpers.rb
it seems .fetch on symbols doesn't work for Chef attributes, and the
behavior is subtle different for "def []" instead. so with other words:
node.fetch(:crowbar_wall) -> IndexError: Key crowbar_wall does not
exist
node[:crowbar_wall] -> works
node["crowbar_wall] -> works
node.fetch("crowbar_wall") -> works
This seemingly harmless HoundCI fix entirely broke the boot device
and dns export logic of Cloud 7+.
card, bug references, testing advice or dependencies …
=> Fix chef node attribute lookup

chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
When the network is restarted, it might not come up fast enough the
the next chef-client run may fail with:
Errno::EHOSTUNREACH: No route to host - connect(2) for "192.168.76.10" port 4000
Waiting for the admin server to be reachable should fix this.
requests?**
=> provisioner: Wait for admin server after net restart (bsc#1054191)

chef/cookbooks/barclamp/libraries/barclamp_library.rb, chef/cookbooks/provisioner/recipes/bootdisk.rb
On Systems with HP Smart Array Controllers, the discovery image
detects cciss udev links but those don't actually exist during
installation because for unknown reasons the installation system
doesn't actually load the cciss module. So skip them and prefer
wwn's, those are hopefully unique enough.
Funny side story: In at least one case, the cciss- link was based on the
controller's serial number (which is the same for both devices that
were attached). you just had one job..
**Is there additional information worth sharing like …
=> Bootdisk detection: Skip cciss, prefer wwn's

crowbar_framework/config/repos-cloud.yml
This change fixes the current pikecloud8 crowbar allocation failures
Adds missing pike repository tags.
requests?**
=> Add Cloud8/Pike repository tags

crowbar_framework/app/models/service_object.rb
Currently, if a locking failure occurs, the lock variable will be unset
and an empty lock will be added to the lock queue. This is a problem
when it comes time to release locks, where the error "undefined method
`release' for nil:NilClass" will occur and cause a proposal failure.
This patch ensures that only successfully acquired locks make it into
the lock queue.
=> crowbar: Don't store invalid locks (bsc#1055669)

bin/crowbar_batch
e.g. when forgetting the 'proposal:' key
`crowbar batch build invalid.yaml`
was failing with a cryptic error:
```
/opt/dell/bin/barclamp_lib.rb:532:in `eval': no implicit conversion of String into Integer (TypeError)
from /opt/dell/bin/crowbar_batch:116:in `import_or_build'
from /opt/dell/bin/crowbar_batch:90:in `build'
from (eval):1:in `run_sub_command'
from /opt/dell/bin/barclamp_lib.rb:532:in `eval'
from /opt/dell/bin/barclamp_lib.rb:532:in `run_sub_command'
from /opt/dell/bin/barclamp_lib.rb:536:in `run_command'
from /opt/dell/bin/crowbar_batch:580:in `main'
from /opt/dell/bin/crowbar_batch:583:in `<main>'
```
We make sure the data we got is structured as a hash
=> batch: properly fail on invalid yaml

crowbar_framework/lib/crowbar/event_dispatcher.rb
Rebase of PR #952 but only including the new infrastructure class
For usage examples, see:
https://github.com/crowbar/crowbar-core/pull/952
https://github.com/crowbar/crowbar-ha/pull/171
https://github.com/crowbar/crowbar-openstack/pull/717
There are several cases where we have events that should trigger some
activity in some other part of Crowbar. For instance:
- when the public name of a node is saved, it may impact the endpoint
of an OpenStack service
- when the public name of the VIP of haproxy is changed, it impacts the
endpoint of OpenStack services
- when the keystone proposal is applied, we may want to reapply all
proposals that depend on keystone
What we need for this is the ability to notify about the events in the
rails application and then dispatch the notifications to hooks …
=> Create event hook infrastructure

crowbar_framework/lib/crowbar/event_dispatcher.rb
Rebase of PR #952 but only including the new infrastructure class
For usage examples, see:
https://github.com/crowbar/crowbar-core/pull/952
https://github.com/crowbar/crowbar-ha/pull/171
https://github.com/crowbar/crowbar-openstack/pull/717
There are several cases where we have events that should trigger some
activity in some other part of Crowbar. For instance:
- when the public name of a node is saved, it may impact the endpoint
of an OpenStack service
- when the public name of the VIP of haproxy is changed, it impacts the
endpoint of OpenStack services
- when the keystone proposal is applied, we may want to reapply all
proposals that depend on keystone
What we need for this is the ability to notify about the events in the
rails application and then dispatch the notifications to hooks …
=> [4.0] Create event hook infrastructure

chef/cookbooks/dhcp/templates/default/dhcpd.conf.erb
Without the specific dhcp option:
always-reply-rfc1048 true;
Some machines fail to boot (DL160) and print something like this on the
console:
```
Loading Linux ...
error: time out opening `suse-...../loader/linux`
Loading initial ramdisk ...
error: you need to load the kernel first.
Press any key to...
```
=> dhcp fix for UEFI (bsc#961536)

configs/crowbar.service
Due to this change
https://github.com/crowbar/crowbar-core/commit/6edc8727442d3054bf22df7d4d579e1fdc8ab519#diff-0191694d58feeb77cc86bffcc5a68a83R30
Apache2 is "restarted" instead of "reloaded" during installation (as well as during restore).
Due to the dependency type "Requires" in
https://github.com/crowbar/crowbar-core/blob/stable/4.0/configs/crowbar.service#L4
Puma is also restarted when Apache2 is.
Due to Puma restarting during a crowbar restore the background thread is killed which performs the restore. Thus the restore never finishes.
This PR fixes this issue by changing the dependency from Puma to Apache2 to "Wants". With this starting Puma also starts Apache2. But Puma will not be shut down if Apache2 fails, stops or restarts.
See also: …
=> change systemd dependency from crowbar to apache to Wants

crowbar_framework/app/models/node.rb
ruby's system method requires all args passed to the shell as single string
(no whitespace separated multi strings in one variable)
none of the ipmi commands work, otherwise
it splits the given command into multiple values for the system function
requests?**
=> properly pass command args to bmc_cmd

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
It fixes bug https://bugzilla.suse.com/show_bug.cgi?id=1036762
Filter is added to the backend to block access to the upgrade API. All `/upgrade` endpoints return fixed JSON error message which will be displayed directly in CLI and will pop-up when user tries to run prechecks in the UI.
requests?**
https://trello.com/c/m8ROv8Hg/437-bug-1036762-upgrade-api-accessible-in-cloud7
=> Disable upgrade API in Cloud8

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
backport of #1314
direct cherry-pick was not possible due to version-based file checks
=> Disable upgrade API in Cloud7

chef/data_bags/crowbar/migrate/ipmi/102_bmc_nat_enable.rb, chef/data_bags/crowbar/template-ipmi.json, chef/data_bags/crowbar/template-ipmi.schema, crowbar_framework/app/models/ipmi_service.rb, crowbar_framework/app/views/barclamp/ipmi/_edit_attributes.html.haml, crowbar_framework/config/locales/ipmi/en.yml
NATing IPMI access through Admin Server is not ideal in some cases.
STONITH based on this can trigger fencing if Admin Server is (temporarily) not accessible.
This change adds option to disable BMC NAT feature.
Access from nodes to IPMI plane needs to be configured externally for this to work properly.
requests?**
https://trello.com/c/Q7laJy5q/91-readonly-ipmi-use-existing-ipmi-settings-no-bmc-nat
=> ipmi: Option to disable BMC NAT

chef/cookbooks/ipmi/recipes/ipmi-configure.rb, chef/data_bags/crowbar/migrate/ipmi/103_bmc_reconfigure.rb, chef/data_bags/crowbar/template-ipmi.json, chef/data_bags/crowbar/template-ipmi.schema, crowbar_framework/app/models/ipmi_service.rb, crowbar_framework/app/views/barclamp/ipmi/_edit_attributes.html.haml, crowbar_framework/config/locales/ipmi/en.yml
**NOTE: https://github.com/crowbar/crowbar-ha/pull/232 is needed to complete this functionality wrt STONITH**
When IPMI boards are pre-configured with static IPs/users Crowbar should not try to allocate new IPs or change passwords. Only the discovery part should be done by Crowbar to detect the settings.
New option is added which disables all write operations on IPMI interface.
requests?**
https://trello.com/c/Q7laJy5q/91-readonly-ipmi-use-existing-ipmi-settings-no-bmc-nat
=> Read only ipmi

chef/cookbooks/apache2/metadata.rb, chef/cookbooks/apache2/recipes/default.rb, chef/cookbooks/utils/providers/systemd_service_restart.rb, chef/cookbooks/utils/resources/systemd_service_restart.rb, chef/cookbooks/utils/templates/default/systemd_service_restart.conf.erb
This resource adds (or removes) a systemd config snippet for a service,
to change the behavior to Restart=on-failure for that service. This
means systemd will automatically restart the service on failures, which
makes a relatively good self-healing solution without pacemaker.
See systemd.service(5) for details on Restart=
Note that the fetch_name_from_service_resource attribute of this
resource enables automatically fetching the systemd service name from
the service resource, which helps remove duplication of code in the
cookbooks when the service name is being overridden in the attributes of
the service resource. For instance, this will work as expected:
```
service "foobar" do
service_name "notfoobar"
end
utils_systemd_service_restart "foobar"
```
=> Add utils_systemd_service_restart LWRP

chef/cookbooks/apache2/metadata.rb, chef/cookbooks/apache2/recipes/default.rb, chef/cookbooks/utils/providers/systemd_service_restart.rb, chef/cookbooks/utils/resources/systemd_service_restart.rb, chef/cookbooks/utils/templates/default/systemd_service_restart.conf.erb
This resource adds (or removes) a systemd config snippet for a service,
to change the behavior to Restart=on-failure for that service. This
means systemd will automatically restart the service on failures, which
makes a relatively good self-healing solution without pacemaker.
See systemd.service(5) for details on Restart=
Note that the fetch_name_from_service_resource attribute of this
resource enables automatically fetching the systemd service name from
the service resource, which helps remove duplication of code in the
cookbooks when the service name is being overridden in the attributes of
the service resource. For instance, this will work as expected:
```
service "foobar" do
service_name "notfoobar"
end
utils_systemd_service_restart "foobar"
```
Backport of …
=> [4.0] Add utils_systemd_service_restart LWRP

chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/templates/default/chef_client.erb, chef/data_bags/crowbar/migrate/provisioner/201_chef_splay.rb, chef/data_bags/crowbar/template-provisioner.json, chef/data_bags/crowbar/template-provisioner.schema
For large installations many concurrent chef-client runs can cause significant load on chef-server and crowbar.
Exposing `splay` parameter enables users to increase it to distribute the chef-server load caused by chef-clients.
requests?**
https://trello.com/c/dcIa46O8/118-change-chef-client-splay
=> provisioner: Make chef splay configurable

chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/templates/default/chef_client.erb, chef/data_bags/crowbar/migrate/provisioner/103_chef_splay.rb, chef/data_bags/crowbar/template-provisioner.json, chef/data_bags/crowbar/template-provisioner.schema
backport of #1334 
NOTE: I'm not sure if migration is backported properly (i.e. should the number be moved to Cloud7 range?)
=> [4.0] provisioner: Make chef splay configurable

crowbar_framework/app/controllers/dashboard_controller.rb
/clusters rendered the HTML view of clusters but didn't provide json version for use in crowbar-client (needed for filtering of deployment lists).
Handler was added to properly render json view of clusters data.
requests?**
https://trello.com/c/zxBV0sly/89-remove-deleted-nodes-from-proposals-using-the-cli
=> Add json version of /clusters endpoint

chef/cookbooks/bind9/recipes/default.rb, chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/dhcp/metadata.json, chef/cookbooks/dhcp/recipes/default.rb, chef/cookbooks/logging/recipes/common.rb, chef/cookbooks/network/recipes/default.rb, chef/cookbooks/nfs-server/metadata.json, chef/cookbooks/nfs-server/recipes/default.rb, chef/cookbooks/ntp/recipes/default.rb, chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/templates/default/tftp.service.erb, chef/cookbooks/resolver/recipes/default.rb
This offers some automatic recovery, which is nice. It turns out it's
also recommended by systemd documentation, in case a service is
long-running, which is the case here.
It's worth mentioning that in the past, the periodic chef-client has
been providing this, to some extent. But this means the recovery could
take up to 15 minutes. It was actually not working in the case of the
chef server infrastructure (chef-server, chef-solr, couchdb, etc.), and
systemd can really help here.
This is of course disabled when a service is managed by Pacemaker, as we
do not want to have systemd interfere with Pacemaker in that case. Note
that this commit doesn't touch any service managed by Pacemaker, though.
=> all: Make systemd restart services on failures

crowbar_framework/app/models/node.rb
After chef_splay was added, node state can change to "unknown" because interval between chef-client runs can be longer.
This change adds chef_splay to calculation to get upper limit for chef-client run properly.
requests?**
https://trello.com/c/WXL2ZVg6/148-crowbar-consider-splay-when-calculating-node-status
=> Add chef_splay to allowed time without update

chef/cookbooks/bind9/recipes/default.rb, chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/dhcp/metadata.json, chef/cookbooks/dhcp/recipes/default.rb, chef/cookbooks/logging/recipes/common.rb, chef/cookbooks/network/recipes/default.rb, chef/cookbooks/nfs-server/metadata.json, chef/cookbooks/nfs-server/recipes/default.rb, chef/cookbooks/ntp/recipes/default.rb, chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/templates/default/tftp.service.erb, chef/cookbooks/resolver/recipes/default.rb
This offers some automatic recovery, which is nice. It turns out it's
also recommended by systemd documentation, in case a service is
long-running, which is the case here.
It's worth mentioning that in the past, the periodic chef-client has
been providing this, to some extent. But this means the recovery could
take up to 15 minutes. It was actually not working in the case of the
chef server infrastructure (chef-server, chef-solr, couchdb, etc.), and
systemd can really help here.
This is of course disabled when a service is managed by Pacemaker, as we
do not want to have systemd interfere with Pacemaker in that case. Note
that this commit doesn't touch any service managed by Pacemaker, though.
(cherry picked from commit 3d24a0f4cbcf23783ef44cc0e07e67fb02f8f105)
=> [4.0] all: Make systemd restart services on failures

chef/cookbooks/barclamp/libraries/barclamp_library.rb, crowbar_framework/app/models/node.rb
DASD drives in s390x use a different name schema than other devices, like sda or hda. Change the regular expression to recognize them.
Indirectly this fix a bug in crowbar, where the nodes appears without hard disk information. Also is required for the Cinder barclamp, in order to create the partition and assign it to the cinder-volume group.
Tested in the Dallas system
=> s390x: recognize DASD drives

chef/cookbooks/nfs-server/metadata.json, chef/cookbooks/nfs-server/recipes/default.rb
This breaks in some mkcloud scenarios:
nfsserver.service: Service has Restart= setting other than no, which isn't allowed for Type=oneshot services. Refusing.
=> nfs-server: Revert systemd Restart= bits for nfs services

crowbar_framework/app/models/service_object.rb
Until now, we saved the role for the applied proposal early in
apply_role. However, apply_role could fail after that but still before
apply_role_pre_chef_client, resulting in the role containing incomplete
data (since apply_role_pre_chef_client is used to process the role and
add some info, like "use HA").
In case of such a failure (and that can happen when we fail to get a
lock for a node), then a periodic chef-client run would use a role with
incomplete information, possibly leading to changing the config on the
node wrongly.
Closes https://github.com/sap-oc/crowbar-openstack/issues/34
=> crowbar: Do not save applied proposal as role too early in apply_role

chef/cookbooks/network/recipes/default.rb
the openvswitch .service file is of Type=oneshot which is not
compatible with Restart=on-failure .
=> network: Partly revert 3d24a0f4cb - do not add Restart= for ovs

chef/cookbooks/utils/libraries/restart_manager.rb, chef/cookbooks/utils/libraries/service.rb, crowbar_framework/app/controllers/api/restart_management_controller.rb, crowbar_framework/config/application.rb, crowbar_framework/config/experimental.yml, crowbar_framework/config/routes.rb, crowbar_framework/lib/crowbar/data_bag_config.rb, crowbar_framework/spec/controllers/api/restart_management_controller_spec.rb, crowbar_framework/spec/fixtures/offline_chef/data_bag_item_crowbar-config-disallow_restart.json, crowbar_framework/spec/fixtures/offline_chef/data_bag_item_crowbar-config.json, crowbar_framework/spec/requests/api_versioning_spec.rb
Allow end users to set a barclamp as "no service reboots allowed" to avoid automatic service restarts by chef .
There is several parts to this:
- A new experimental config file to enable/disable experimental features like this one.
- Found at crowbar_framework/config/experimental.yml
- Gets loaded into the rails config at crowbar start, available at `Rails.application.config.experimental`
- A chef dsl service resource monkey-patching
- allows us to skip the service restart in case that a flag is set on the `crowbar-config -> disallow_restarts` databag
- allows us to set the flag `node[cookbook_name][:requires_restart]` if a restart was skipped due to the `disallow_restart` flag with the barclamp, service name that requires restart, timestamp, and identification if this is a pacemaker …
=> Managing mandatory service restarts on chef runs

chef/cookbooks/utils/libraries/restart_manager.rb, chef/cookbooks/utils/libraries/service.rb, crowbar_framework/app/controllers/api/restart_management_controller.rb, crowbar_framework/config/application.rb, crowbar_framework/config/experimental.yml, crowbar_framework/config/routes.rb, crowbar_framework/lib/crowbar/data_bag_config.rb, crowbar_framework/spec/controllers/api/restart_management_controller_spec.rb, crowbar_framework/spec/fixtures/offline_chef/data_bag_item_crowbar-config-disallow_restart.json, crowbar_framework/spec/fixtures/offline_chef/data_bag_item_crowbar-config.json, crowbar_framework/spec/requests/api_versioning_spec.rb
Allow end users to set a barclamp as "no service reboots allowed" to avoid automatic service restarts by chef .
There is several parts to this:
A new experimental config file to enable/disable experimental features like this one.
Found at crowbar_framework/config/experimental.yml
Gets loaded into the rails config at crowbar start, available at Rails.application.config.experimental
A chef dsl service resource monkey-patching
allows us to skip the service restart in case that a flag is set on the crowbar-config -> disallow_restarts databag
allows us to set the flag node[cookbook_name][:requires_restart] if a restart was skipped due to the disallow_restart flag with the barclamp, service name that requires restart, timestamp, and identification if this is a pacemaker service.
Several new …
=> [4.0] Backport disallow chef restarts

chef/cookbooks/utils/libraries/restart_manager.rb
This used to work as it was part of the chef DSL which provides the
handy helper data_bag_item but it stopped working as soon as we moved it
from there into an external file, as we no longer have access to that
helper method and need to use the full path to the class to load a
databag item
=> utils: fix data bag loading on RestartManager

chef/cookbooks/utils/libraries/restart_manager.rb
This used to work as it was part of the chef DSL which provides the
handy helper data_bag_item but it stopped working as soon as we moved it
from there into an external file, as we no longer have access to that
helper method and need to use the full path to the class to load a
databag item
(cherry picked from commit c610bb53c4075a5cef59829dd7c530204bba3f3a)
Backport of: https://github.com/crowbar/crowbar-core/pull/1363
=> [4.0] utils: fix data bag loading on RestartManager

crowbar_framework/Gemfile
SLE is updating rails to 4.2.9 so let's use and test against this release.
=> gem: Use rails 4.2.9

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/experimental.yml, crowbar_framework/lib/crowbar/deployment_queue.rb
If we set the experimental skip_unready_nodes config to true and provide
a list of roles, we try to skip nodes that are not ready from the
deployment of the barclamp so we dont need all nodes to be ready to
deploy a barclamp.
This is useful when dealing with a high number of nodes (i.e.
nova-compute) and we dont need all those other nodes to be ready to add
a new node to a role
Background:
When changing the DNS forwarder in the DNS barclamp all nodes of the cloud must be ready and accessible to apply the change, although the change does not affect all nodes.
There must be a way to only target affected or a selected sub-set of nodes:
just ignore not ready/not accessible nodes (they will be automatically updated on their next local chef-client run)
Backport of: …
=> [4.0] Backport skip unready nodes deployment

chef/cookbooks/utils/libraries/restart_manager.rb
It looks like when you use fetch to fetch an attribute from the node
object we get the direct value, which if modified (deleted/updated)
doesnt get to be reflected into the node object, so when we deleted the
restart flag from a service and the node was saved, the modification we
did was not saved.
Instead, lets just ask for forgiveness when trying to delete the
attribute by using rescue to save from any issues of attributes not
existing when deleting the flags.
=> utils: Fix restart flag removal

chef/cookbooks/utils/libraries/restart_manager.rb
It looks like when you use fetch to fetch an attribute from the node
object we get the direct value, which if modified (deleted/updated)
doesnt get to be reflected into the node object, so when we deleted the
restart flag from a service and the node was saved, the modification we
did was not saved.
Instead, lets just ask for forgiveness when trying to delete the
attribute by using rescue to save from any issues of attributes not
existing when deleting the flags.
(cherry picked from commit 9d19923bf4dc4a3c75dcb16d4cfcd2ec4fdbbb63)
Backport-of: https://github.com/crowbar/crowbar-core/pull/1368
=> [4.0] utils: Fix restart flag removal

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/experimental.yml, crowbar_framework/lib/crowbar/deployment_queue.rb
If we set the experimental skip_unready_nodes config to true and provide
a list of roles, we try to skip nodes that are not ready from the
deployment of the barclamp so we dont need all nodes to be ready to
deploy a barclamp.
This is useful when dealing with a high number of nodes (i.e.
nova-compute) and we dont need all those other nodes to be ready to add
a new node to a role
Background: 
When changing the DNS forwarder in the DNS barclamp all nodes of the cloud must be ready and accessible to apply the change, although the change does not affect all nodes.
There must be a way to only target affected or a selected sub-set of nodes:
just ignore not ready/not accessible nodes (they will be automatically updated on their next local chef-client run)
=> Remove unready nodes from deployment

chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/crowbar/templates/default/apache.conf.erb
Without this patch, when crowbar is deployed with the HTTP+HTTPS option
and the user is connected with HTTPS, any redirect (such as after a
proposal is applied or when a node is deleted) will force the user back
to an HTTP connection. This is obviously insecure. This patch adds a
setting to the crowbar apache vhost to forward the request protocol to
rails so that the ssl property of the rails request object will be set
and the redirect_to method in rails will do the right thing.
=> crowbar: Forward protocol to rails (bsc#1059733)

crowbar_framework/app/models/service_object.rb, crowbar_framework/lib/schema_migration.rb
This allows to execute barclamp specific maintenance code after a
schema migration ran for a proposal and its role. Subclasses, e.g.
DatabaseService can overwrite the default implementation (which is
a no-op).
This is a PR is laying the groundwork in order to fix:
https://bugzilla.suse.com/show_bug.cgi?id=1058876
=> schema_migration: Provide a hook into ServiceObject (bsc#1058876)

chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/crowbar/templates/default/apache.conf.erb
Without this patch, when crowbar is deployed with the HTTP+HTTPS option
and the user is connected with HTTPS, any redirect (such as after a
proposal is applied or when a node is deleted) will force the user back
to an HTTP connection. This is obviously insecure. This patch adds a
setting to the crowbar apache vhost to forward the request protocol to
rails so that the ssl property of the rails request object will be set
and the redirect_to method in rails will do the right thing.
(cherry picked from commit 7970e517ec619f254b6276c81213d29b81977728)
=> [4.0] crowbar: Forward protocol to rails (bsc#1059733)

chef/cookbooks/utils/providers/systemd_override_limits.rb, chef/cookbooks/utils/resources/systemd_override_limits.rb, chef/cookbooks/utils/templates/default/systemd_override_limits.conf.erb
Some services require modifications to the system resource limits, such
as the maximum number of open files, that we cannot necessarily predict
a reasonable default for. Without this patch, there is no way to control
those limits from crowbar and they must be changed manually. This patch
adds a LWRP to allow setting resource limits.
Currently only the LimitNOFILE (systemd's name for the maximum
number of open files) limit is supported.
Traditionally this was managed by editing limits for service users
installed by packages in /etc/security/limits.conf. This is no longer
effective under systemd, though the documentation of this reality is
poor and the best reference I can find for this is a comment in a bug
report[1].
Since limits.conf is no longer effective, this patch manages limits by …
=> utils: Add systemd override LWRP

chef/cookbooks/network/recipes/default.rb, chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
Update the wicked pre-up scriptlets for OVS bridges to keep the "secure" ovs fail-mode on all neutron managed bridges (br-public, br-fixed), with the exception of those that are also used to implement the "admin" network, which needs to be enabled during boot.
Previously, all neutron managed OVS bridges were configured by wicked scriptlets to be in a "standalone" fail-mode during boot, which contributed to a condition that could enable outside traffic to be unconditionally forwarded through them if:
- the node is hard-reset (which doesn't give wicked a chance to remove the OVS bridges as it would during a graceful shutdown)
- the neutron openvswitch agent fails during startup in such a way that leaves the br-int OVS bridge configured to forward all traffic unconditionally
Implications:
- …
=> network: keep ovs secure fail-mode (bsc#1063772)

chef/cookbooks/utils/providers/systemd_override_limits.rb, chef/cookbooks/utils/resources/systemd_override_limits.rb, chef/cookbooks/utils/templates/default/systemd_override_limits.conf.erb
Some services require modifications to the system resource limits, such
as the maximum number of open files, that we cannot necessarily predict
a reasonable default for. Without this patch, there is no way to control
those limits from crowbar and they must be changed manually. This patch
adds a LWRP to allow setting resource limits.
Currently only the LimitNOFILE (systemd's name for the maximum
number of open files) limit is supported.
Traditionally this was managed by editing limits for service users
installed by packages in /etc/security/limits.conf. This is no longer
effective under systemd, though the documentation of this reality is
poor and the best reference I can find for this is a comment in a bug
report[1].
Since limits.conf is no longer effective, this patch manages limits by …
=> [4.0] utils: Add systemd override LWRP

chef/cookbooks/network/recipes/default.rb, chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
(backport of #1366)
Update the wicked pre-up scriptlets for OVS bridges to keep the "secure" ovs fail-mode on all neutron managed bridges (br-public, br-fixed), with the exception of those that are also used to implement the "admin" network, which needs to be enabled during boot.
Previously, all neutron managed OVS bridges were configured by wicked scriptlets to be in a "standalone" fail-mode during boot, which contributed to a condition that could enable outside traffic to be unconditionally forwarded through them if:
- the node is hard-reset (which doesn't give wicked a chance to remove the OVS bridges as it would during a graceful shutdown)
- the neutron openvswitch agent fails during startup in such a way that leaves the br-int OVS bridge configured to forward all traffic …
=> [4.0] network: keep ovs secure fail-mode (bsc#1063772)

crowbar_framework/app/models/chef_object.rb, crowbar_framework/app/models/node.rb, crowbar_framework/app/models/role_object.rb, crowbar_framework/spec/fixtures/offline_couchdb/roles_all.json, crowbar_framework/spec/support/offline_couchdb.rb
We want to squeeze every second possible out of dashboard/`crowbarctl node list`.
Fetching of all roles and passing them to Node constructor gives some performance improvement over loading them one by one.
requests?**
https://trello.com/c/kQ1eLgYY/122-evaluate-performance-of-admin-node-on-scale-cloud
=> Prefetch all roles during node listing

chef/cookbooks/provisioner/recipes/base.rb, chef/data_bags/crowbar/template-provisioner.json, crowbar_framework/app/models/node.rb
In large clouds multipe chef-clients connecting to chef-server at the same time can increase load on the admin server.
Chef's SPLAY parameter controls random factor to chef-client interval.
This gives better load distribution for large clouds by avoiding multiple chef-clients connect to chef-server at the same time.
requests?**
https://trello.com/c/YyJWDjew/159-chef-splay-default-settings-documentation
=> Increase default chef_splay

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/experimental.yml
Provides a method that barclamps can override to skip a node from the list of nodes in which run is gonna run.
Provides this with a default of allowing all nodes to avoid issues and only will trigger the check if the experimental option is enabled.
Kind of stolen from https://github.com/vuntz/crowbar-core/commit/321c736a17404413505649e286543e7d9a79cc83
=> Skip chef run on nodes when applying

chef/cookbooks/barclamp/libraries/barclamp_library.rb, crowbar_framework/app/models/node.rb
NVMe device does not match any of the conditions to be a claimed disk
hence always unclaimed. Adding the pattern to the regex makes it claimable.
(cherry picked from commit 15e207f82c2f4fd286269bc4d9c99c116109db59)
=> [4.0] Allow setting NVMe drive in ceph (bsc#1051298)

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/experimental.yml
Provides a method that barclamps can override to skip a node from the list of nodes in which run is gonna run.
Provides this with a default of allowing all nodes to avoid issues and only will trigger the check if the experimental option is enabled.
Kind of stolen from vuntz/crowbar-core@321c736
Backport-of: https://github.com/crowbar/crowbar-core/pull/1374
=> [4.0]  Skip chef run on nodes when applying

chef/cookbooks/ohai/files/default/plugins/linux/uefi.rb
It seems it's possible to configure UEFI to have CurrentBoot pointing to
a non-existing entry. Let's deal with that.
=> ohai: Do not fail dealing with UEFI config with invalid CurrentBoot

crowbar_framework/app/helpers/nodes_helper.rb, crowbar_framework/app/models/node.rb, crowbar_framework/app/views/nodes/_buttons_power.html.haml, crowbar_framework/app/views/nodes/_show.html.haml
When IPMI interfaces are pre-configured and/or read-only mode is enabled discovered IPMI info was not used to display links in UI.
After this change, the links will be shown as soon as there is some IPMI address discovered from the BMC.
requests?**
https://trello.com/c/Gxhc3uD3/107-show-ipmi-link-in-ui-as-soon-as-the-addresses-are-available-in-crowbarwall
=> Show IPMI links earlier

.travis.yml, Dangerfile, Gemfile
Currently, we have no automated way of enforcing or encouraging good patch proposal practices, and it is therefore left up to the reviewer to notice and request changes for improper commit formatting and pull request structure. This is a problem because we have not actually formally agreed to rules around pull request structure, and the importance of enforcing it is subjective to each reviewer. This patch sets up a basic commit linter using Danger[1]. For now, the checks it performs are limited to the default commit formatting checks from the commit-lint plugin[2] as well as a check for the existence of merge commits in a pull request. For now, the checks are set to "warn" and will post comments but will not fail a build.
The bot will use the github account susecloudcommitpolice. Using …
=> Set up Danger for commit linting

crowbar_framework/app/models/service_object.rb
There was 2 mistakes on the original method. The first, we were
iterating over the elements but only using one value instead of k,v so
it led to the value of r being the whole k+v which broke the hash
lookup. The second is that the initialization of the cleaned_elements
was a hash but a hash doesnt have the << method.
For the first, the correct way of iterating over a hash and extracting
the k,v is now used.
For the second, we initialize the attribute to an array as expected
=> crowbar_framework: fix skip_unchanged_nodes

crowbar_framework/app/models/service_object.rb
There was 2 mistakes on the original method. The first, we were
iterating over the elements but only using one value instead of k,v so
it led to the value of r being the whole k+v which broke the hash
lookup. The second is that the initialization of the cleaned_elements
was a hash but a hash doesn't have the << method
For the first, the correct way of iterating over a hash and extracting
the k,v is now used
For the second, we initialize the attribute to an array as expected
(cherry picked from commit 70ab89e)
Backport-of: https://github.com/crowbar/crowbar-core/pull/1395
=> [4.0] crowbar_framework: fix skip_unchanged_nodes

Dangerfile
Since we usually prefix commit messages with their component, it doesn't
make sense to require it to be capitalized.
=> Disable subject_cap danger check

chef/cookbooks/ohai/files/default/plugins/crowbar.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb
When using bonds, all slave interfaces adopt the same mac address, and
therefore their permanent mac address is "hidden". This results in the
DHCP config not being fully complete since some MAC addresses are not
known, and therefore we cannot configure anything for them.
This may lead to nodes rebooting and reinstalling because there's no
DHCP config telling the node to not boot from that interface, or to boot
from disk, and therefore this falls back to the discovery image, which
will trigger some automatic reinstall (since the node is known).
=> Find and use permanent addresses of interfaces for dhcp config

chef/cookbooks/ohai/files/default/plugins/crowbar.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb
When using bonds, all slave interfaces adopt the same mac address, and
therefore their permanent mac address is "hidden". This results in the
DHCP config not being fully complete since some MAC addresses are not
known, and therefore we cannot configure anything for them.
This may lead to nodes rebooting and reinstalling because there's no
DHCP config telling the node to not boot from that interface, or to boot
from disk, and therefore this falls back to the discovery image, which
will trigger some automatic reinstall (since the node is known).
Backport of https://github.com/crowbar/crowbar-core/pull/1398
=> [4.0] Find and use permanent addresses of interfaces for dhcp config

chef/cookbooks/ohai/files/default/plugins/crowbar.rb
The ohai plugin that forcefully up'ed all physical interfaces
can cause harm on a configuration where multiple physical interfaces
are connected to the same switch/native vlan. in that case
the ARP lookup seemingly randomly flips between the mac addresses
of both causing hard to debug hangs on the cloud due to ip/arp
mismatch.
In our case, eth1 was not configured to be used by crowbar and thus had a MTU of 1500, while traffic leaving eth0 was assuming that replies with 9000 bytes could be received.
in the error case /var/log/chef/client.log had
```
[2017-10-23T11:37:11+00:00] INFO: *** Chef 10.32.2 ***
[2017-10-23T11:47:13+00:00] ERROR: Timeout connecting …
```
=> ohai: don't up interfaces

chef/cookbooks/bmc-nat/metadata.rb, chef/cookbooks/build-essential/metadata.rb, chef/cookbooks/crowbar-hacks/metadata.rb, chef/cookbooks/deployer/metadata.rb, chef/cookbooks/dns/metadata.rb, chef/cookbooks/ipmi/metadata.rb, chef/cookbooks/kernel-panic/metadata.rb, chef/cookbooks/nfs-client/metadata.rb, chef/cookbooks/nfs-server/metadata.json, chef/cookbooks/ohai/metadata.rb, chef/cookbooks/openssl/metadata.rb, chef/cookbooks/provisioner/metadata.rb, chef/cookbooks/repos/metadata.rb, chef/cookbooks/resolver/metadata.rb, chef/cookbooks/runit/metadata.rb, chef/cookbooks/suse-manager-client/metadata.rb, chef/cookbooks/updater/metadata.rb
There is no reason to not have the name in all the cookbooks metadata
and it collides when using tools as some tools use the metadata name for
identification instead of just resorting to the directory name.
Plus it makes all cookbooks have the similar base metadata
=> chef: add names to cookbook metadata

crowbar_framework/app/models/service_object.rb
We also need to take into account the heartbeat as nodes that were not
probably shut down will still have the state "ready".Therefore we should
not look at the raw state attribute, but we should use the method that
interprets that raw state attribute.
=> crowbar: Fix skip_unready_nodes' for unready nodes

crowbar_framework/app/models/dns_service.rb, crowbar_framework/app/models/ntp_service.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/app/models/service_object.rb
By using skip_batch_for_node? we can avoid running chef on nodes that do
not change role and if there is no attribute change for the barclamp.
Does not skip nodes that have changed roles, all nodes if
attributes have changed and when deploying the barclamp for the first
time.
Barclamps on witch this check will run are configured in experimental
configuration file
Requires: #1401
=> skip unchanged nodes from chef run

crowbar_framework/app/models/service_object.rb
We also need to take into account the heartbeat as nodes that were not
probably shut down will still have the state "ready".Therefore we should
not look at the raw state attribute, but we should use the method that
interprets that raw state attribute.
(cherry picked from commit ad7557522936b72267b2cd5ee0c5715fea5e0775)
Backport of https://github.com/crowbar/crowbar-core/pull/1410
=> [4.0] crowbar: Fix skip_unready_nodes' for unready nodes

crowbar_framework/app/models/dns_service.rb, crowbar_framework/app/models/ntp_service.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/app/models/service_object.rb
By using skip_batch_for_node? we can avoid running chef on nodes that do
not change role and if there is no attribute change for the barclamp.
Does not skip nodes that have changed roles, all nodes if
attributes have changed and when deploying the barclamp for the first
time.
Barclamps on witch this check will run are configured in experimental
configuration file
Backport of #1408
=> [4.0] Backport skip unchanged nodes from chef run

chef/cookbooks/utils/libraries/role_recipe.rb
When a node is in error state, it seems the chef apply fails
with
[2017-11-03T00:42:02-04:00] FATAL: NoMethodError: undefined method `key?' for nil:NilClass
This is due to "applying_for" not being set.
requests?**
=> crowbar: Avoid nil crash on applying errored nodes

crowbar_framework/app/models/service_object.rb
On first sight the code looked like it was using `THREAD_POOL_SIZE` threads but it was one less. In addition the logging was misleading.
Fix creation of threads and logging.
requests?**
=> Fix thread pool creation and logging

chef/cookbooks/utils/libraries/role_recipe.rb
When a node is in error state, it seems the chef apply fails
with
[2017-11-03T00:42:02-04:00] FATAL: NoMethodError: undefined method `key?' for nil:NilClass
This is due to "applying_for" not being set.
(cherry picked from commit 96cb9b6f24b2ceeb1cc806b33eb23fdde6b02d46)
Backport of https://github.com/crowbar/crowbar-core/pull/1412
=> [4.0] crowbar: Avoid nil crash on applying errored nodes

crowbar_framework/app/models/deployer_service.rb
By using skip_batch_for_node? we can avoid running chef on nodes that do
not change role and if there is no attribute change for the barclamp.
Does not skip nodes that have changed roles, all nodes if
attributes have changed and when deploying the barclamp for the first
time.
=> Deployer : Skip batches when nothing has changed

crowbar_framework/vendor/assets/stylesheets/bootstrap/_forms.scss, crowbar_framework/vendor/assets/stylesheets/bootstrap/_variables.scss
This is required for some visual tweak in crowbar-ha, where a button is
put inside a heading of a list group. Without it, the button doesn't
look correctly aligned vertically.
Improves https://github.com/crowbar/crowbar-ha/pull/276
=> crowbar: Add CSS rule for form-group in heading

chef/cookbooks/network/recipes/default.rb
(originally at https://github.com/crowbar/crowbar-core/pull/1228, description copied)
iterate over all the children to obtain the max mtu that we need to
set to a parent nic. Before this, only the first vlan children of a parent
was used to set an mtu value, failing afterwards if the next vlan had a bigger
value.
Introduced in #1084
=> network: set max mtu of a parent to the max of its children

crowbar_framework/app/models/deployer_service.rb
By using skip_batch_for_node? we can avoid running chef on nodes that do
not change role.
Does not skip nodes that have changed roles, all nodes when deploying
the barclamp for the first time.
(cherry picked from commit f921aad8e86aab375ff6ce740c2f0565d4dac24b)
Backport of https://github.com/crowbar/crowbar-core/pull/1416
=> [4.0] Deployer : Skip batches when nothing has changed

chef/cookbooks/ohai/files/default/plugins/crowbar.rb
Everywhere else in ohai/chef, we use uppercase MAC addresses, so let's
ensure that what we get from ethtool is also uppercase.
=> ohai: Use uppercase for permanent MAC addresses

chef/cookbooks/ohai/files/default/plugins/crowbar.rb
Everywhere else in ohai/chef, we use uppercase MAC addresses, so let's
ensure that what we get from ethtool is also uppercase.
(cherry picked from commit 415dcafd4469abc868a7b893452cf1bdb10d3ca1)
Backport of https://github.com/crowbar/crowbar-core/pull/1438
=> [4.0] ohai: Use uppercase for permanent MAC addresses

chef/cookbooks/utils/libraries/restart_manager.rb
For checking the disallow_restart flags, we load a databag item. At the
moment, it was loaded every time we were checkign the flag for a
service.
By caching it, we get some small performance improvement, but we also
get consistency by making sure that the flag doesn't get changed in the
middle of a chef run.
=> utils: Load databag item once per run

chef/cookbooks/utils/libraries/restart_manager.rb
For checking the disallow_restart flags, we load a databag item. At the
moment, it was loaded every time we were checkign the flag for a
service.
By caching it, we get some small performance improvement, but we also
get consistency by making sure that the flag doesn't get changed in the
middle of a chef run.
=> [4.0] utils: Load databag item once per run

crowbar_framework/vendor/assets/stylesheets/bootstrap/_forms.scss, crowbar_framework/vendor/assets/stylesheets/bootstrap/_variables.scss
This is required for some visual tweak in crowbar-ha, where a button is
put inside a heading of a list group. Without it, the button doesn't
look correctly aligned vertically.
(cherry picked from commit 5a6223e6cc54a373aa310c530a165cda1387b794)
Backport from https://github.com/crowbar/crowbar-core/pull/1429
=> [4.0] crowbar: Add CSS rule for form-group in heading

chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
The default mode for grep(1) is matching the expression as
regular expression, which means that special characters like "[" are
not handled literally. By using -x (match whole line) and -F (plain
text search) we can avoid that escaping hell.
requests?**
=> crowbar_join: Avoid repeated lines in chef config (bsc#1060692)

crowbar_framework/app/models/dns_service.rb, crowbar_framework/app/models/logging_service.rb, crowbar_framework/app/models/ntp_service.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/app/models/service_object.rb
**crowbar: Add helper for skip_unchanged_node?**
The new "relevant_attributes_changed_if_roles?" helper checks if no
other attribute than the ignored has changed, and only considers this if
the node has no other role than the ones whitelisted.
This is useful to allow skipping "client" nodes when many attributes are
relevant only to "server" nodes.
**dns/logging/ntp/provisioner: Improve skip_unchanged_node?**
Use the new helper :-) Also always apply if the server changed.
=> Improve skip_unchanged_node? for dns, logging, ntp, provisioner

crowbar_framework/app/models/dns_service.rb, crowbar_framework/app/models/logging_service.rb, crowbar_framework/app/models/ntp_service.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/app/models/service_object.rb
**crowbar: Add helper for skip_unchanged_node?**
The new "relevant_attributes_changed_if_roles?" helper checks if no
other attribute than the ignored has changed, and only considers this if
the node has no other role than the ones whitelisted.
This is useful to allow skipping "client" nodes when many attributes are
relevant only to "server" nodes.
**dns/logging/ntp/provisioner: Improve skip_unchanged_node?**
Use the new helper :-) Also always apply if the server changed.
Backport of https://github.com/crowbar/crowbar-core/pull/1420
=> [4.0] Improve skip_unchanged_node? for dns, logging, ntp, provisioner

chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
If chef-client fails twice during `crowbar_join`, the logic is to try running it a third time in `installed` state with `client.pem` removed, to pretend we just come straight from a fresh install.  This is very old logic originally written by Victor, and we don't know of any scenario where this actually helps.  In contrast, we do know that it is quite easy for `chef-client` to fail on nodes which successfully installed a long time ago and are just running `crowbar_join` again on boot up, e.g. after `zypper up` + `reboot`.  And in this case this logic removes a perfectly good `client.pem` forever:
- https://bugzilla.suse.com/show_bug.cgi?id=1063533
Worse, pretending that a previously installed node is being freshly installed could potentially lead to serious data loss, so it's safer to …
=> don't retry with installed state during failing crowbar_join (bsc#1063533)

chef/cookbooks/network/recipes/default.rb
iterate over all the children to obtain the max mtu that we need to
set to a parent nic. Before this, only the first vlan children of a parent
was used to set an mtu value, failing afterwards if the next vlan had a bigger
value.
Backport of https://github.com/crowbar/crowbar-core/pull/1371
=> [4.0] network: set max mtu of a parent to the max of its children

chef/cookbooks/network/recipes/default.rb
iterate over all the children to obtain the max mtu that we need to
set to a parent nic. Before this, only the first vlan children of a parent
was used to set an mtu value, failing afterwards if the next vlan had a bigger
value.
Backport of https://github.com/crowbar/crowbar-core/pull/1434
=> [3.0] network: set max mtu of a parent to the max of its children

chef/cookbooks/ntp/recipes/default.rb
On SLE12, the systemd support does not handle reload anymore:
$ systemctl reload ntpd
Failed to reload ntpd.service: Job type reload is not applicable for
unit ntpd.service.
=> NTP service needs to be restarted (bsc#972299)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
During the upgrade, we replace the node's repositories with the new ones. 
For OS's base repository we need to know current as well as previous SP version, because the template needs to change it explicitly
=> upgrade: Set correct SP version for repositories at cloud nodes

crowbar_framework/app/views/deploy_queue/_dependencies.html.haml
Proposal status for dependencies of queued proposal in deployment_queue was not updated correctly. It referred to 'proposal_status' action in DeployQueueController which was not implemented.
The correct place to query for proposal status is BarclampController.
requests?**
https://trello.com/c/SduJSFvx/216-error-when-fetching-proposal-status-on-deployment-queue-page
=> Fix dependency status updates in deployment_queue

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Upgrade library that is part of this version of crowbar-core package
can be used by
a) 6-7 upgrade: when executing the later steps that are done after
upgrading all crowbar packages at admin server to next product
b) 7-8 upgrade: when executing the initial steps on SOC7 before
upgrading crowbar packages at admin server to next product
So we need a way to correctly distinguish between these 2 cases.
=> [4.0] upgrade: Let the upgrade library work with both 6-7 and 7-8 upgrades.

chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
These are the services we initentionally stop before the OpenStack upgrade.
During the disruptive upgrade, we're explicitly stopping OpenStack (and some related) services at before we go to next step of upgrading the packages. 
The locations have changed for SLES12SP3.
**Note**
It's possible we might rework the whole step or upgrade process. But for now, I'm only focusing on keeping the same functionality of the 6-7 upgrade
=> upgrade: Services are no longer located under /etc/init.d

chef/cookbooks/barclamp/libraries/nic.rb, chef/cookbooks/network/recipes/default.rb
To get the IP of the provisioner we need to read a Data Bag item from
the server. Trying to read directly before the wait loop for the network
to come back doesn't make sense, as we might have connectivity issues at
that point. Move it back to the top of the recipe where it was before
commit 8d9265f.
Added some additional cleanups for the bond creating as suggested in:
https://bugzilla.suse.com/show_bug.cgi?id=1064813
=> Fix wait loop after network reconfiguration (bsc#1064813)

chef/cookbooks/ohai/files/default/plugins/crowbar.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb
[Below is the description of the original PR; I leave it here open whether you really want to have it for SOC6.]
When using bonds, all slave interfaces adopt the same mac address, and
therefore their permanent mac address is "hidden". This results in the
DHCP config not being fully complete since some MAC addresses are not
known, and therefore we cannot configure anything for them.
This may lead to nodes rebooting and reinstalling because there's no
DHCP config telling the node to not boot from that interface, or to boot
from disk, and therefore this falls back to the discovery image, which
will trigger some automatic reinstall (since the node is known).
Backport of #1399
=> [3.0] Find and use permanent addresses of interfaces for dhcp config 

chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/recipes/keys.rb
Provisioner cookbook which deploys authorized_keys is running last in the runlist but sometimes ssh keys can be needed earlier. Original usecase for this change is synchronization of fernet-keys from founder when new/reinstalled node joins the cluster.
This change extracts keys setup into a separate recipe for easier including in other cookbooks.
requests?**
https://trello.com/c/SBMOaFz1/187-reinstalling-node-in-existing-cluster-fails-because-fernet-keys-folder-does-not-exist
=> provisioner: Extract ssh keys deployment

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
This reverts commit 6eabcfc33f79df17d9bf896e140f9c5393dcf78b.
This should allow upgrading from Cloud7 (4.0 branch) to Cloud8
=> Revert "Disable upgrade API in Cloud7"

chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/recipes/keys.rb
Provisioner cookbook which deploys authorized_keys is running last in
the runlist but sometimes ssh keys can be needed earlier. This change
extracts keys setup into a separate recipe for easier including in
other cookbooks.
(cherry picked from commit 1adf5c44571374f468155943845cf4d509ef76a0)
backport of #1451
=> [4.0] provisioner: Extract ssh keys deployment

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/fixtures/offline_chef/node_drbd.crowbar.com.json, crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json, crowbar_framework/spec/models/api/upgrade_spec.rb
When we introduced the new syncmarks for pacemaker
the founder was changed from a boolean indicating
that the node is a founder, to the fqdn of the founder
This results in the upgrade not working as expected because
it expects to find the boolean and the value to mark if
its a founder or not, which doesnt work with the new values
This patch tries to fix that by doing searches for the founder
value, extracting the fqdn of the founder and then loading
the founder node directly
=> upgrade: fix pacemaker founder searchs

crowbar_framework/app/controllers/nodes_controller.rb
Crowbar client didn't accept node aliases in `node group` subcommand.
Added handling of node aliases in API used by `node group` crowbarctl subcommand to match (usage) documentation.
requests?**
https://trello.com/c/T03pTNx0/222-check-fix-crowbarctl-node-alias-support
=> crowbar: accept aliases in groups API

crowbar_framework/app/controllers/nodes_controller.rb
Added handling of node aliases in API used by `node group` crowbarctl
subcommand to match (usage) documentation.
(cherry picked from commit 58153915bd8c199b8694b3abb911cf3156802283)
backport of #1462
=> [4.0] crowbar: accept aliases in groups API

crowbar_framework/app/models/service_object.rb
When applying a proposal with deleted nodes it crashes due to
pre_cached_nodes containing a node with nil value.
requests?**
=> crowbar: Avoid crash on precached deleted nodes

crowbar_framework/vendor/assets/javascripts/jquery/dynamicTable.js, crowbar_framework/vendor/assets/javascripts/jquery/jsonAttribute.js
When supplying a list (eg of hostnames: "host1, host2, , host3" etc)
an empty element "" would be set in the array. This change removes any
empty elements.
This change also stops empty strings from being converted to arrays
such as [""] (ie one empty element).
(bsc#1065903)
=> Filter out empty elements in crowbar lists

chef/cookbooks/crowbar/recipes/default.rb
Fix the call to `gensslcert`, to use the common name parameter, instead the country one
=> crowbar: fix call to gensslcert

chef/cookbooks/apache2/recipes/default.rb, chef/cookbooks/apache2/templates/default/apache.logrotate.erb
Currently only the apache access and error logs are rotated by logrotate
but /var/log/apache also contains access and error logs from keystone,
ceilometer, barbican and other services which are not rotated.
This rotates all the log files in the apache directory.
=> apache: Add all .log file to apache logrotate (bsc#1071317)

crowbar_framework/app/assets/stylesheets/content/alert.scss, crowbar_framework/app/models/service_object.rb, crowbar_framework/vendor/assets/stylesheets/bootstrap/_variables.scss
When `chef-client` fails, the most recent lines of the Chef logs are surfaced in the Crowbar proposal UI.  However they are not wrapped in anything, so the line breaks gets ignored, creating an unholy mess.  Not sure how this was tolerated for so long, but let's fix it.
Also a couple of refactorings to clean up the relevant method.
=> clean up UI display of recent Chef logs on failure

chef/cookbooks/apache2/recipes/default.rb, chef/cookbooks/apache2/templates/default/apache.logrotate.erb
Currently only the apache access and error logs are rotated by logrotate
but /var/log/apache also contains access and error logs from keystone,
ceilometer, barbican and other services which are not rotated.
This adds a file which rotates all the logs in the apache directory.
(cherry picked from commit 7df53dca5f144ac670037d1006d6977241f35cc3)
=> [4.0] Add all .log file to apache logrotate(bsc#1071317)

chef/cookbooks/crowbar/metadata.json, chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/crowbar/templates/suse/epmd.socket-port.conf.erb
With new erlang and rabbitmq-server packages, rabbitmq now depends on
the system-wide epmd service, which will only listen on IP addresses
defined for epmd.socket.
We need epmd to listen on the admin IP address (the one that resolves
the FQDN), so configure things accordingly.
While install-suse-cloud will already do this setup correctly, we also
change the crowbar cookbook to ensure the config stays up-to-date.
=> crowbar: Ensure epmd.socket is configured correctly

crowbar_framework/vendor/assets/javascripts/jquery/dynamicTable.js, crowbar_framework/vendor/assets/javascripts/jquery/jsonAttribute.js
When supplying a list (eg of hostnames: "host1, host2, , host3" etc)
an empty element "" would be set in the array. This change removes any
empty elements.
This change also stops empty strings from being converted to arrays
such as [""] (ie one empty element).
(bsc#1065903)
(cherry picked from commit 247f621)
Backport of https://github.com/crowbar/crowbar-core/pull/1453
=> [4.0] Filter out empty elements in crowbar lists

crowbar_framework/app/assets/stylesheets/content/alert.scss, crowbar_framework/app/models/service_object.rb, crowbar_framework/vendor/assets/stylesheets/bootstrap/_variables.scss
Backport of #1472.
When `chef-client` fails, the most recent lines of the Chef logs are surfaced in the Crowbar proposal UI.  However they are not wrapped in anything, so the line breaks gets ignored, creating an unholy mess.  Not sure how this was tolerated for so long, but let's fix it.
Also a couple of refactorings to clean up the relevant method.
=> [4.0] clean up UI display of recent Chef logs on failure

crowbar_framework/app/assets/stylesheets/content/alert.scss, crowbar_framework/app/models/service_object.rb, crowbar_framework/vendor/assets/stylesheets/bootstrap/_variables.scss
Backport of #1472.
When `chef-client` fails, the most recent lines of the Chef logs are surfaced in the Crowbar proposal UI.  However they are not wrapped in anything, so the line breaks gets ignored, creating an unholy mess.  Not sure how this was tolerated for so long, but let's fix it.
Also a couple of refactorings to clean up the relevant method.
=> [3.0] clean up UI display of recent Chef logs on failure

crowbar_framework/app/models/service_object.rb
When validation errors happened, only error message like "not a string" was displayed.
Attribute path was added to the message to better identify possible source of error.
requests?**
=> crowbar: Attribute names in validation errors

chef/cookbooks/crowbar/metadata.json, chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/crowbar/templates/suse/epmd.socket-port.conf.erb
With new erlang and rabbitmq-server packages, rabbitmq now depends on
the system-wide epmd service, which will only listen on IP addresses
defined for epmd.socket.
We need epmd to listen on the admin IP address (the one that resolves
the FQDN), so configure things accordingly.
While install-suse-cloud will already do this setup correctly, we also
change the crowbar cookbook to ensure the config stays up-to-date.
(cherry picked from commit 7449fbe053979e124ae906addda7c73a725c4e85)
Backport of https://github.com/crowbar/crowbar-core/pull/1481
=> [4.0] crowbar: Ensure epmd.socket is configured correctly

crowbar_framework/app/models/service_object.rb
When applying a proposal with deleted nodes it crashes due to
pre_cached_nodes containing a node with nil value.
(cherry picked from commit af5b3cab4173a45c8c5a584eb9fb934600b6cfcc)
Backport of https://github.com/crowbar/crowbar-core/pull/1469
=> [4.0] crowbar: Avoid crash on precached deleted nodes

crowbar_framework/app/models/service_object.rb
Before this change, when validation errors happened, only error message
like "not a string" was displayed. Attribute path was added to the
message to better identify possible source of error.
(cherry picked from commit 656605aabc9575408151e15ca53c2b3cf43fd24b)
Backport of https://github.com/crowbar/crowbar-core/pull/1479
=> [4.0] crowbar: Attribute names in validation errors

chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb
SP2+ are installing the grub2 efi compat symlink under /usr/lib/grub2
not /usr/lib64/grub2 like on x86_64. adjust paths accordingly
=> provisioner: Update grub.efi location for aarch64

chef/cookbooks/crowbar-hacks/recipes/uefi.rb
HPE servers have some standard UEFI boot entries which are disabled
by default. After crowbar activates them, they are re-created by the
firmware with disabled state. Crowbar activates these duplicates and
the whole cycle repeats after each reboot. This can lead to very long
lists of boot entries which can even cause the machine to fail booting.
The workaround for this problem is a list of entry names which are
skipped during the activation loop. Currently the list includes only
the HPE specific entries but can be extended in the future if needed.
requests?** …
=> crowbar-hacks: Skip activation of HPE UEFI entries

chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/grub.conf.erb
**Don't use net_bootp for PXE-booted EFI-enabled grub**
net_bootp would configure all network interfaces with DHCP (which is
more than what we want, and may be slow).
However, it turns out that the efinet driver in grub2 will already
know the configuration configure of the network interface that was used
for PXE booting (since grub is parsing the DHCP ACK that the EFI
firmware received).
See grub_efi_net_config_real and grub_machine_get_bootlocation from:
http://git.savannah.gnu.org/cgit/grub.git/tree/grub-core/net/drivers/efi/efinet.c
http://git.savannah.gnu.org/cgit/grub.git/tree/grub-core/kern/efi/init.c
and for the patch introducing this:
http://git.savannah.gnu.org/cgit/grub.git/commit/?id=cae730b4526f250a3d5073c00911e35b7abdd7d7
Co-authored-by: Stefan Seyfried …
=> provisioner: Fixes related to PXE-booting in UEFI case

chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/grub.conf.erb
Backport of https://github.com/crowbar/crowbar-core/pull/1487
**Don't use net_bootp for PXE-booted EFI-enabled grub**
net_bootp would configure all network interfaces with DHCP (which is
more than what we want, and may be slow).
However, it turns out that the efinet driver in grub2 will already
know the configuration configure of the network interface that was used
for PXE booting (since grub is parsing the DHCP ACK that the EFI
firmware received).
See grub_efi_net_config_real and grub_machine_get_bootlocation from:
http://git.savannah.gnu.org/cgit/grub.git/tree/grub-core/net/drivers/efi/efinet.c
http://git.savannah.gnu.org/cgit/grub.git/tree/grub-core/kern/efi/init.c
and for the patch introducing this:
http://git.savannah.gnu.org/cgit/grub.git/commit/?id=cae730b4526f250a3d5073c00911e35b7a …
=> [4.0] provisioner: Fixes related to PXE-booting in UEFI case

chef/cookbooks/crowbar-hacks/recipes/uefi.rb
HPE servers have some standard UEFI boot entries which are disabled
by default. After crowbar activates them, they are re-created by the
firmware with disabled state. Crowbar activates these duplicates and
the whole cycle repeats after each reboot. This can lead to very long
lists of boot entries which can even cause the machine to fail booting.
The workaround for this problem is a list of entry names which are
skipped during the activation loop. Currently the list includes only
the HPE specific entries but can be extended in the future if needed.
(cherry picked from commit ea75e39175e1a7ce18d3f18489d3f875054e2d04)
Backport of https://github.com/crowbar/crowbar-core/pull/1486
=> [4.0] crowbar-hacks: Skip activation of HPE UEFI entries

chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/default/crowbarrc.erb, chef/data_bags/crowbar/migrate/crowbar/200_add_insecure_attribute.rb, chef/data_bags/crowbar/template-crowbar.json, chef/data_bags/crowbar/template-crowbar.schema, crowbar_framework/app/views/barclamp/crowbar/_edit_attributes.html.haml, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/data_bags/template-crowbar.json
Update autoyast.xml.erb to install crowbarctl in each node.  This
is the first step to replace `curl` raw calls to the crowbar API,
and use `crowbarctl` instead.
This replacement will fix some issues in relation with `curl`,
https, redirections and BasicAuth passwords.
=> provisioner: Install crowbarctl

chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb, crowbar_framework/app/models/api/upgrade.rb
Do not stop galera and apache:
In the services step, we want to keep database and keystone running.
=> Upgrade services tweaks

chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/default/crowbarrc.erb, chef/data_bags/crowbar/migrate/crowbar/104_add_insecure_attribute.rb, chef/data_bags/crowbar/template-crowbar.json, chef/data_bags/crowbar/template-crowbar.schema, crowbar_framework/app/views/barclamp/crowbar/_edit_attributes.html.haml, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/data_bags/template-crowbar.json
Backport of https://github.com/crowbar/crowbar-core/pull/1305 :
"Update autoyast.xml.erb to install crowbarctl in each node. This
is the first step to replace curl raw calls to the crowbar API,
and use crowbarctl instead.
This replacement will fix some issues in relation with curl,
https, redirections and BasicAuth passwords."
=> [4.0] provisioner: Install crowbarctl

bin/crowbar_batch
the check for alias and hostname should be skipped for the
host_by_alias list as if not we will removing anything that
has an alias "foo" and the hostname starts with "foo." which
can be something usual with the admin node (crowbar alias and
crowbar.foo.bar hostname)
(cherry picked from commit 37ddc8cd9c198ab20310fb7485692dfb9525b42a)
backport-of: https://github.com/crowbar/crowbar-core/pull/1490
=> [4.0] crowbar_batch: fix host_by_alias

bin/crowbar_batch
the check for alias and hostname should be skipped for the
host_by_alias list as if not we will removing anything that
has an alias "foo" and the hostname starts with "foo." which
can be something usual with the admin node (crowbar alias and
crowbar.foo.bar hostname)
=> crowbar_batch: fix host_by_alias

bin/crowbar_batch
the check for alias and hostname should be skipped for the
host_by_alias list as if not we will removing anything that
has an alias "foo" and the hostname starts with "foo." which
can be something usual with the admin node (crowbar alias and
crowbar.foo.bar hostname)
(cherry picked from commit 37ddc8cd9c198ab20310fb7485692dfb9525b42a)
Backport-of: https://github.com/crowbar/crowbar-core/pull/1490
=> [3.0] crowbar_batch: fix host_by_alias

crowbar_framework/app/controllers/api/restart_management_controller.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/config/routes.rb, crowbar_framework/spec/controllers/api/restart_management_controller_spec.rb
The experimental restart management API was enabled only if relevant
option was enabled in experimental.yml. When called with the option
disabled, crowbar returned 404 with no hint on what is wrong.
Replaced routing condition with before_action in the controller to
enable better error reporting.
requests?**
https://bugzilla.suse.com/show_bug.cgi?id=1076240
=> Improve experimental API errors (bsc#1076240)

chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
During provisioning of new nodes, install the microcode packages for
the relevant CPU vendor (ucode-intel and ucode-amd) to help mitigate
against side-channel attacks.
requests?**
https://trello.com/c/etmXBrSm/657-p3-bug-1074665-ucode-intel-is-missing-on-crowbar-deployed-nodes
=> provisioner: Install microcode packages (bsc#1074665)

bin/gather_logs.sh, bin/transition.sh, chef/cookbooks/crowbar/files/default/crowbar, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb, updates/control_lib.sh
This replacement will fix some issues in relation with curl,
https, redirections and BasicAuth passwords."
This is part of ongoing work to use crowbarctl instead of direct curl calls to API. crowbarctl should know everything and no special options that we're building for curl command are necessary..
**Trello card**
https://trello.com/c/2SwQTBg1/399-p3-replace-curl-commands-in-crowbar-with-crowbarctl
**Requires**
sleshammer changes:
https://build.suse.de/package/show/home:jsuchome:branches:Devel:Cloud:8/sleshammer# -> https://build.suse.de/request/show/154768
=> provisioner: replace curl calls to crowbar API with crowbarctl

bin/gather_logs.sh, bin/transition.sh, chef/cookbooks/crowbar/files/default/crowbar, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb, updates/control_lib.sh
Backport of https://github.com/crowbar/crowbar-core/pull/1499
This replacement will fix some issues in relation with curl,
https, redirections and BasicAuth passwords."
Why is this change necessary?
This is part of ongoing work to use crowbarctl instead of direct curl calls to API. crowbarctl should know everything and no special options that we're building for curl command are necessary..
Trello card
https://trello.com/c/2SwQTBg1/399-p3-replace-curl-commands-in-crowbar-with-crowbarctl
requires sleshammer update https://build.suse.de/request/show/157590
=> [4.0] provisioner: replace curl calls to crowbar API with crowbarctl 

bin/gather_logs.sh, bin/transition.sh, chef/cookbooks/crowbar/files/default/crowbar, updates/control_lib.sh
- Added forgotten credentials to crowbarctl call
- Added --no-verify-ssl option to crowbarctl calls 
These commits are coming from https://github.com/crowbar/crowbar-core/pull/1513
=> Several fixes for crowbarctl replacement of curl

chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
During provisioning of new nodes (using either crowbar-register or
autoyast) install the microcode packages for the relevant CPU vendor
(ucode-intel and ucode-amd) to help mitigate against side-channel
attacks.
(cherry picked from commit 89147b09bf984563d4d0c5a35c13896e904a3cff)
requests?**
=> [stable/4.0] provisioner: Install microcode packages (bsc#1074665)

crowbar_framework/lib/offline/role-.template
This isn't used anywhere and it's outdated so let's drop it.
Note: Testbuild will fail as the folder is mentioned in the spec.
=> offline: Remove offline lib

chef/cookbooks/ohai/files/default/plugins/crowbar.rb
ohai: Do not fail when tcpdump output is missing
As we might not have run tcpdump, we need to handle that its output file
might be missing.
ohai: show which interface an error happened on 
Follow up of: https://github.com/crowbar/crowbar-core/pull/1385
=> ohai: Do not fail when tcpdump output is missing

chef/cookbooks/ohai/files/default/plugins/crowbar.rb
ohai: Do not fail when tcpdump output is missing
As we might not have run tcpdump, we need to handle that its output file
might be missing.
(cherry picked from commit fafdeef)
Backport of #1516
ohai: show which interface an error happened on
(cherry picked from commit 2e37db8)
Backport of #1516
=> [4.0] Backport: ohai: Do not fail when tcpdump output is missing

chef/cookbooks/network/recipes/default.rb
One side effect of the change to support xmit_hash_policy means the
network recipe writes the miimon and xmit_hash_policy attributes to
sysfs every time chef runs, which causes the kernel to log that. Only
set the attributes if they are different from the current setting.
requests?**
=> network: Only set bond attributes when they change (bsc#1054268)

chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb
The grub behavior in SP3 appears to have changed, it is looking
for grub.cfg in the same directory like the grub.efi resides, not
in the parent directory like before.
=> provisioner: Fix UEFI based discovery for SP3+

chef/cookbooks/network/recipes/default.rb
One side effect of the change to support xmit_hash_policy means the
network recipe writes the miimon and xmit_hash_policy attributes to
sysfs every time chef runs, which causes the kernel to log that. Only
set the attributes if they are different from the current setting.
(cherry picked from commit 588585ceb306d997472ac1f867d47fd79bb2c582)
requests?**
=> [4.0] network: Only set bond attributes when they change (bsc#1054268)

Dangerfile
Rationale: we use them for rpm changelogs that are visible
to customers, so we want to have a little bit more detail in
there like a crowbar module prefix and an bugzilla id at the end.
The commonly accepted industry standard of 50 chars per commit subject
is therefore extended to 70 chars.
=> Dangerfile: Extend subject check to 70 chars

chef/cookbooks/network/recipes/default.rb
One side effect of the change to support xmit_hash_policy means the
network recipe writes the miimon and xmit_hash_policy attributes to
sysfs every time chef runs, which causes the kernel to log that. Only
set the attributes if they are different from the current setting.
(cherry picked from commit 588585ceb306d997472ac1f867d47fd79bb2c582)
requests?**
=> [3.0] network: Only set bond attributes when they change (bsc#1054268)

crowbar_framework/app/models/dns_service.rb, crowbar_framework/app/models/logging_service.rb, crowbar_framework/app/models/ntp_service.rb
from an env where nodes were forgotten in a state where the dns and ntp barclamp was unclean. the stored proposal still had those deleted nodes, causing everything else to fall apart.
=> crowbar: skip deleted nodes on updating data bags

crowbar_framework/app/models/api/backup.rb
Instead of using "hostname -f" to validate the host name,
just use the /etc/hostname to do so, as that is the source
for the hostname inside the backup, the comparison should
be done against the same file
=> crowbar: use hostname file to validate host name

crowbar_framework/app/models/backup.rb
Instead of using "hostname -f" to validate the host name,
just use the /etc/hostname to do so, as that is the source
for the hostname inside the backup, the comparison should
be done against the same file
(cherry picked from commit b9d8c2ea187b5ed1aa30ef2980277c3d1fa5d53f)
Backport-of: https://github.com/crowbar/crowbar-core/pull/1526
=> [3.0] crowbar: use hostname file to validate host name

crowbar_framework/app/models/api/backup.rb
Instead of using "hostname -f" to validate the host name,
just use the /etc/hostname to do so, as that is the source
for the hostname inside the backup, the comparison should
be done against the same file
(cherry picked from commit b9d8c2ea187b5ed1aa30ef2980277c3d1fa5d53f)
Backport-of: https://github.com/crowbar/crowbar-core/pull/1526
=> [4.0] crowbar: use hostname file to validate host name

crowbar_framework/app/models/dns_service.rb, crowbar_framework/app/models/logging_service.rb, crowbar_framework/app/models/ntp_service.rb
migrating installations with nodes that have been deleted fails
currently on nil nodes, so skip them.
(cherry picked from commit 980bd299903e57dce5064a25ac2639031e3e189f)
requests?**
=> [4.0] crowbar: skip deleted nodes on updating data bags

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
As the iso name has changed from cloud7[0] to cloud8[1] the product
name that zypper return has also changed, so we should make sure
to check the proper product name
[0] SUSE-OPENSTACK-CLOUD-7-x86_64-Media1.iso
[1] SUSE-OPENSTACK-CLOUD-CROWBAR-8-x86_64-Media1.iso
Should fix error `mkcloud error code 11: Some repository is missing on admin server. Cannot upgrade.` on the `cloud-mkcloud8-job-upgrade-disruptive-x86_64` job
=> upgrade: use proper product name for cloud 8

chef/data_bags/crowbar/template-salt.json, crowbar_framework/app/models/service_object.rb
When the salt barclamp is used, a transition to readying is failing
with this error:
salt transition to default failed.
wrong number of arguments (3 for 0)
/opt/dell/crowbar_framework/app/models/service_object.rb:295:in `transition'
/opt/dell/crowbar_framework/app/models/crowbar_service.rb:202:in `block (2 levels) in transition'
/opt/dell/crowbar_framework/app/models/crowbar_service.rb:186:in `each'
/opt/dell/crowbar_framework/app/models/crowbar_service.rb:186:in `block in transition'
/opt/dell/crowbar_framework/app/models/crowbar_service.rb:185:in `each'
/opt/dell/crowbar_framework/app/models/crowbar_service.rb:185:in `transition'
/opt/dell/crowbar_framework/app/controllers/barclamp_controller.rb:126:in `transition'
This is due to incorrect number of arguments being specified on the
base …
=> service: fix failure on transition to readying

crowbar_framework/app/controllers/sanities_controller.rb
As during the crowbar upgrade database step, a sanity check is
called, we need to skip the upgrade filter on the sanity
controller so it can be called even if we are in the middle of the
upgrade, otherwise we will be stuck in the database step
The sanity check was introduced in crowbar-init here: https://github.com/crowbar/crowbar-init/commit/29de8a8e2eeaf135ec028df05e6c285d3965be54
=> Allow sanity controller during upgrade

crowbar_framework/config/repos-cloud.yml
The "crowbar" part was missing for the Update repos for cloud8.
This is checked to match during the 7->8 upgrade and its
currently failing because the tag in the repodata.xml does not match
what we have on the repos-cloud.yml. Probably it was forgotten when
the rename of SOC8->SOCC8 was done.
Rename was done at https://github.com/crowbar/crowbar-core/commit/d7a7a921255225a103ff53ea46a8ec96b15af2d2
=> crowbar: Use proper repo for cloud8 Update

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
As the iso name has changed from cloud7[0] to cloud8[1] the product
name that zypper return has also changed, so we should make sure
to check the proper product name
[0] SUSE-OPENSTACK-CLOUD-7-x86_64-Media1.iso
[1] SUSE-OPENSTACK-CLOUD-CROWBAR-8-x86_64-Media1.iso
(cherry picked from commit b925922289088392fe71c946e8ccb17231cd56f3)
Backport-of: https://github.com/crowbar/crowbar-core/pull/1531/commits
=> [4.0] upgrade: use proper product name for cloud 8

chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.sh.erb
As during the upgrade we first update the packages, and then update
the configuration (via chef) when upgrading the node packages, any
horizon related package will fail to install due to those packages
%postun firing a manage.py command which loads our custom
_100_local_settings.py which contains a deprecated config item.
As by the time those packages are installed, django has already been
updated, it will fail to finish the install.
This patch will replace the outdated configuration in the config
prior to upgrading the packages so the package install can finish
correctly. The configuration will be upgraded by chef afterwards
so it will end up being correct no matter what.
=> upgrade: fix horizon deprecated config

chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
So that new nodes don't get different uids and clash when NFS is used.
Also related to bsc#968251.
This is a forward port of https://github.com/crowbar/crowbar-core/pull/1536
https://bugzilla.suse.com/show_bug.cgi?id=1087896
https://bugzilla.suse.com/show_bug.cgi?id=968251
=> Add common cinder group for all nodes (bsc#1087896)

crowbar_framework/spec/models/node_object_spec.rb
Testing of find_node_by_name_or_alias method of node
Backport of 4bcca85b72fb876e4f0b6b5c7d9d5bb4ebc0c3ff
=> [4.0] Crowbar find node by name or alias test backport

crowbar_framework/app/models/service_object.rb
There's some situation where the proposal validators need to check that
a number of nodes are present. This validator is already present. But if
a cluster is assigned to the proposal, then the cluster it is counted as
a single instance.
A new validator 'validate_multiple_for_role_or_cluster' has beed
added. It does check that at least 2 nodes are present or a cluster is
defined.
This validator would help with https://github.com/crowbar/crowbar-openstack/pull/1550
=> crowbar: add validator for n nodes or cluster

crowbar_framework/app/models/service_object.rb
Backport from: https://github.com/crowbar/crowbar-core/pull/1546
There's some situation where the proposal validators need to check that
a number of nodes are present. This validator is already present. But if
a cluster is assigned to the proposal, then the cluster it is counted as
a single instance.
A new validator 'validate_multiple_for_role_or_cluster' has beed
added. It does check that at least 2 nodes are present or a cluster is
defined.
(cherry picked from commit b4b65638bde309d9eaa1e4eb57af782f61807c57)
=> [4.0] crowbar: add validator for multiple nodes or cluster

chef/cookbooks/ohai/files/default/plugins/crowbar.rb
As the result gets written to the existing struct data, unpacking it can
be skipped. Otherwise unpack("P") with a specified length would be needed.
When unpack("p") is used on a struct it might read too many or not
enough bytes depending on when it finds a zero.
=> ohai: Treat struct as fixed length instead of zero terminated string

chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
netcat is provided by netcat-openbsd and it seems autoyast
started to reject invalid package names recently, so this broke.
=> Adjust installation profile for netcat (bsc#1091250)

chef/cookbooks/provisioner/recipes/base.rb
Now that crowbar_join requires crowbarctl, we need to make sure that previously installed nodes also have it.
=> provisioner: Ensure that crowbarctl is installed on nodes

chef/cookbooks/provisioner/recipes/base.rb
Now that crowbar_join requires crowbarctl, we need to make sure that previously installed nodes also have it.
(cherry picked from commit dbbfe14dfe5d2a893367431808adf4e1a4c59228)
Backport of https://github.com/crowbar/crowbar-core/pull/1562
=> [4.0] provisioner: Ensure that crowbarctl is installed on nodes

chef/cookbooks/ohai/files/default/plugins/crowbar.rb
While the result gets written to the existing memory of the ecmd
variable, unpack it again to avoid violating any assumptions that
existing memory doesn't change. (Testing didn't show anything making
this assumption, but just to be safe.) When unpack("p") is used on a
struct it might read too many or not enough bytes depending on when it
finds a zero. There is no size for pack("P") needed, only on unpack.
(cherry picked from commit 4ba8b87b705806c774add25297d4db6b92cde57b)
Backport of https://github.com/crowbar/crowbar-core/pull/1559
=> ohai: Treat struct as fixed length instead of zero terminated (bsc#1090370)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-chef-upgraded.sh.erb
crowbarctl is required by crowbar-join in SOC7, but proper configuration
was not created when upgrading from SOC6.
So let's do an explicit installation and configuration during the
upgrade.
=> [4.0] upgrade: Make sure crowbarctl is installed with correct setup

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, crowbar_framework/app/models/api/upgrade.rb
This was executed on a node running Liberty, to get some Newton
specific config bits. As we're on Newton now, we do not need them.
There might be other parts in this script that need to be removed or changed.
=> upgrade: Do not add Newton specific config changes

crowbar_framework/app/controllers/api/restart_management_controller.rb, crowbar_framework/spec/controllers/api/restart_management_controller_spec.rb
This commit extends the functionality of 690e9bb6cd71e93f04cdb4ddd1639a5a785894dc. This commit allows to the final user to disable the restart of services when the chef client runs. If it is active for any cookbook and one of its services need to clean the flag is raised. To clean this flag there is the command "clear_restart" that the user will run when after the manual restart. In this command the service name have to be specified. However is interesting to restart all services of the one cookbook or restart all services in a node.
This commit allows to specify the name of the cookbook, cleaning all the service of this cookbook, also allows to don't specify any cookbook that will clean all flags in all cookbooks.
=> crowbar: clean restart flags extended

crowbar_framework/app/controllers/api/restart_management_controller.rb, crowbar_framework/spec/controllers/api/restart_management_controller_spec.rb
This commit extends the functionality of 321436f861773372801d403a887faffc37cd9e60. This commit allows to the final user to disable the restart of services when the chef client runs. If it is active for any cookbook and one of its services need to clean the flag is raised. To clean this flag there is the command "clear_restart" that the user will run when after the manual restart. In this command the service name have to be specified. However is interesting to restart all services of the one cookbook or restart all services in a node.
This commit allows to specify the name of the cookbook, cleaning all the service of this cookbook, also allows to don't specify any cookbook that will clean all flags in all cookbooks.
Backport from #1509
=> [4.0] crowbar: clean restart flags extended

crowbar_framework/app/models/crowbar_service.rb
Default rabbitmq HA setup in SOC8 is using native clustering.
Let's switch to this default when upgrading from the setup that is using
DRBD storage.
Requires  https://github.com/crowbar/crowbar-openstack/pull/1637
Alternative to https://github.com/crowbar/crowbar-core/pull/1552
=> upgrade: Change rabbitmq settings during the upgrade

chef/cookbooks/ohai/files/default/plugins/linux/block_device_extended.rb
This is determined from /sys/block/xxx/removable and is always set for
aacraid. It is useful to distinguish removable and hotswappable.
Removable should mean humans will remove this during normal operation
like an USB stick, where as hotswappable disks are only removed for servicing.
https://github.com/torvalds/linux/blob/7b1cd95d65eb3b1e13f8a90eb757e0ea232c7899/drivers/scsi/aacraid/aachba.c#L3117
gives its reason as: "Do not cache partition table for arrays". I
suspect that there is a better way for a kernel driver to behave, since
this is not the first controller with hotpluggable disks.
(cherry picked from commit a7312a8274312a0b1b0621e2578cf2290748b61c)
Backport of https://github.com/crowbar/crowbar-core/pull/1515
=> ohai: Correct aacraid drivers disk removable flag (bsc#1085170)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
Removal from crowbar: https://github.com/crowbar/crowbar-openstack/pull/1091
Newton release notes for nova: https://docs.openstack.org/releasenotes/nova/newton.html
=> upgrade: When upgrading to SOC8, delete deprecated nova-cert service

crowbar_framework/lib/crowbar/upgrade_timeouts.rb
Latest jobs have been failing because of timeout during OS upgrade.
See
https://ci.suse.de/view/Cloud/view/Cloud8/job/cloud-mkcloud8-job-upgrade-nondisruptive-ha-mariadb-x86_64/
`E, [2018-05-15T07:06:38.294506 #3501:0x00000000bc2640] ERROR -- Error while executing OS upgrade script. Possible error during execution of /usr/sbin/crowbar-upgrade-os.sh at d52-54-77-77-01-01.vn2.cloud.suse.de. Action did not finish after 900 seconds. Check /var/log/crowbar/node-upgrade.log for details.`
=> upgrade: Raise the default timeouts for most time consuming actions

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/offline_chef/node_drbd.crowbar.com.json, crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
For now, we require users to have MariaDB deployed before the
upgrade can be started.
=> [4.0] upgrade: Added pre-check for database type

crowbar_framework/app/controllers/application_controller.rb
On SOC7, there could be 2 files indicating running upgrade: one for 6-7
and one for 7-8. Fix the check to make sure we do not miss one of these
situations.
=> [4.0] upgrade: Correctly check for the presence of various upgrade indication

chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb
It does not seem to be necessary to upgrade openstack packages
to from Newton to Pike version for them to work with Pike-based control plane.
Restart of current services (after control plane upgrade) is enough.
Note: these specific packages will be upgraded at some point,
but together with all packages on the node.
=> upgrade: Do not upgrade compute-related packages to Pike

chef/cookbooks/ntp/recipes/default.rb, chef/cookbooks/ntp/templates/default/ntp.conf.erb, chef/data_bags/crowbar/migrate/ntp/100_add_listens.rb, chef/data_bags/crowbar/template-ntp.json, chef/data_bags/crowbar/template-ntp.schema, crowbar_framework/app/models/ntp_service.rb
In cases where the admin network is firewalled from the outside world,
the cloud ntp servers will not be able to connect to external ntp
servers to synchronize. This patch adds the option to set additional
listen interfaces for nodes with the ntp-server role so those ntp
servers can sync with outside servers.
On the ntp-server host, only packets from configured external NTP servers
and from hosts in the admin network are allowed; everything else is
ignored. In addition to that, the rate-limiting feature has been
enabled for requests coming from the external NTP servers.
On the ntp-client hosts, the NTP configuration is not changed by this patch.
=> ntp: Make listening net configurable (bsc#1047941)

crowbar_framework/config/puma.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Previously we had crowbar-init finishing admin upgrade step at the
point the admin server came back from reboot.
Now, crowbar-init is not needed any more during upgrade so let
crowabr itself make the end of step action once it is started.
=> upgrade: Remove the database step

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
We do not allow the upgrade when ceph roles are present (that is,
if ceph was deployed using crowbar).
We no longer check the ceph cluster health. Unfortunatelly crowbar
does not have a knowledge where the ceph nodes are.
=> [4.0] upgrade: Adapt ceph-related pre-checks to 7-8 upgrade

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/offline_chef/node_drbd.crowbar.com.json, crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
For now, we require users to have MariaDB deployed before the
upgrade can be started.
(cherry picked from commit f44408d2eede37df7c4d3706ee549f1b554e0da5)
Port of https://github.com/crowbar/crowbar-core/pull/1575. This is not exactly needed in [master] (because here it's relevant for non-existing 8-9 upgrade), I'm porting it just for the code consistency.
=> upgrade: Added pre-check for database type

crowbar_framework/app/models/api/crowbar.rb
We're checking the return hash for empty? so we want it empty
when the test passes.
https://github.com/crowbar/crowbar-core/blob/master/crowbar_framework/app/models/api/upgrade.rb#L116 requires empty hash on correct case
=> [4.0] upgrade: Fix check for ceph presence

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
During 7 to 8 upgrade, crowbar database does not need to be changed. Partial port of 
https://github.com/crowbar/crowbar-core/pull/1586
=> [4.0] upgrade: Remove database step from the list of 7-8 upgrade steps

crowbar_framework/lib/schema_migration.rb
https://github.com/crowbar/crowbar/pull/2348 did not seem to help, and here's the reason why: https://github.com/crowbar/crowbar-core/commit/73357d9318084e73abc0a512eaeb5ba8c951c7c6
This is basically a revert of 73357d9318084e73abc0a512eaeb5ba8c951c7c6.
The code made sense in 6-7 upgrade, as we were creating new database and the migration
was explicitely called after data import.
For 7-8 upgrade, we are not changing crowbar database so we need to run the migrations
after package upgrade.
=> upgrade: Allow running schema migrations on upgrade

crowbar_framework/config/puma.rb
This could apparently happen when crowbar-core package is installed
and service restarted during admin server upgrade step.
See also https://jira.prv.suse.net/browse/SCRD-3462
=> upgrade: Do not end admin step while it is still running (bsc#1095420)

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/fixtures/crowbar_repocheck.json
These are checked aready at SOC7 side, as the first part of 7-8 upgrade.
Partial backport of https://github.com/crowbar/crowbar-core/pull/1503
=> [4.0] upgrade: Fix labels for SOC8 repositories

crowbar_framework/app/models/api/crowbar.rb
We already have a different check that does not allow the upgrade
if ceph roles are present _anywhere_. So it does not make sense
to flood user with duplicate error messages.
=> [4.0] upgrade: Do not check if ceph roles are present on compute nodes

crowbar_framework/app/controllers/api/upgrade_controller.rb
After finished 7->8 upgrade, cloud API is disabled. One exception is
upgrade status API which should still be available to let users query
status of finished upgrade (i.e. after upgrade was completed).
=> upgrade: Unblock upgrade status API in Cloud8

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/controllers/application_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Once all other nodes have been upgraded, we want users to allow postponing the upgrade of compute nodes. 
**TODO**
=> Postpone the upgrade of compute nodes

crowbar_framework/app/models/api/upgrade.rb
crowbar-ui package was locked before admin server upgrade. After the
whole upgrade process is completed, the lock can be removed to enable
crowbar-ui update before upgrade to next Cloud release.
Note https://github.com/crowbar/crowbar-core/pull/1593 should be merged first and this one rebased if needed.
=> [4.0] upgrade: Unlock crowbar-ui after completed upgrade

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
(cherry picked from commit b8460e532c8b94acd72281113b652190a63b964d)
This is partial backport of https://github.com/crowbar/crowbar-core/pull/1574
We need it so the value of `compute_nodes_postponed` is present in the progress file from the start of 7-8 upgrade
=> [4.0] upgrade: Added API calls for postponing/resuming compute nodes upgrade

crowbar_framework/lib/crowbar/upgrade_timeouts.rb
It took 321 seconds in https://ci.suse.de/job/openstack-mkcloud/121570/
More than a minute for stopping `cl-cinder-scheduler`
Another case here: https://ci.suse.de/job/openstack-mkcloud/121575
Stopping `cl-cinder-scheduler` took almost 2 minutes. 
(next longest one is 22 seconds for stopping `ms-galera`)
=> upgrade: Increase the timeout for deleting pacemaker resources

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/node.rb
Mistakingly, we were finalizing the nodes that were still not upgraded
which led to deletion of upgrade related scripts on those nodes.
Here it was broken: https://github.com/crowbar/crowbar-core/commit/cdb5be7e52ca5895533aed7c47671123dad543a0
Also, split "finalizing" (removing upgrade related node attributes) from upgrade script deletion. The scripts may still be needed.
=> upgrade: Do not finalize nodes that are not upgraded

crowbar_framework/config/initializers/end_adminupgrade.rb, crowbar_framework/config/puma.rb
This move the step to mark the end of the admin node's upgrade from the
puma startup to the initializer of the rails app. Which seems to be a
more appropriate place. It also removes the need to require additional
modules and update the LOADPATH.
=> upgrade: Move step to mark the admin upgrade end

crowbar_framework/app/controllers/api/upgrade_controller.rb
The else clause for upgrade nodes assumes input is valid, and if it
isn't, returns an unhelpful message about how controller nodes need to
be upgraded first. Validate the input to provide a helpful error.
=> upgrade: Check input is a valid node for nodes

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/spec/models/api/crowbar_spec.rb
Compute nodes need to work even when they are not upgraded
(for live-migration from Newton-based node to Pike-based one).
But cinder has to be fully upgraded everywhere. So let's not allow
any cinder service to run on compute node.
https://jira.prv.suse.net/browse/SCRD-3543
=> [4.0] upgrade: Do not allow cinder-volume on compute nodes

crowbar_framework/app/models/api/upgrade.rb
Seems like that the check for nodes that are 'ready' does not work in 100%.
Maybe some nodes are readying or chef-client did not run for a long time
and they are considered unknown.
So better check the node attributes instead.
Here https://ci.suse.de/view/Cloud/view/Cloud8/job/cloud-mkcloud8-job-upgrade-nondisruptive-ha-mariadb-x86_64/57/ the post-upgrade redeployment of keystone has failed because the founder still thought it's being upgraded.
... well, that's still weird, it should have been deleted in the last `finalize_nodes_upgrade` anyway...
=> upgrade: Better check for upgraded nodes - do not rely on state.

chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
There was a small race condition that caused cron jobs (e.g.
glance-scrubber) to run while the openstack services were offline
already. This polluted the service's log file and confused some of the
test done by mkcloud. Stopping cron a bit earlier during the upgrade
shoud avoid that.
=> upgrade: Stop cron before stopping any other service

chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/node.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
The script was executed in the background and we did not wait for
it to finish. As a result, other scripts were started before this one was done.
=> upgrade: Wait for services shutdown to finish

crowbar_framework/app/controllers/api/upgrade_controller.rb
Forward port from stable/4.0 adding brackets to the check that the
component for upgrade node is a valid node name.
requests?**
=> upgrade: Add missing brackets checking for nodes

crowbar_framework/app/controllers/application_controller.rb, crowbar_framework/app/models/service_object.rb
- When the upgrade is not finished, show a link to wizard.
- Add a validation check to make sure postponed nodes can be skipped.
- Let skip_unready_nodes skip also nodes that are in crowbar_upgrade state 
https://jira.prv.suse.net/browse/SCRD-3745
=> upgrade: Add a validation check for postponed nodes.

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
This could be important for showing the correct status in the UI.
=> upgrade: Save the information which set of nodes should be upgraded

chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb
As nova-compute services were started on compute nodes just shortly before
this step, let's wait for them to correctly report their status before
we start with live-migrations.
This should help with https://jira.prv.suse.net/browse/SCRD-3750
=> upgrade: Wait until all nova-compute services are up before evacuation

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/spec/models/api/crowbar_spec.rb
Compute nodes need to work even when they are not upgraded
(for live-migration from Newton-based node to Pike-based one).
But cinder has to be fully upgraded everywhere. So we extend
the upgrade prechecks to make sure cinder services are not running
on compute nodes.
(cherry picked from commit ee8fa8252c8c4d90827d50357c7d141c46ca55b7)
Forward port of https://github.com/crowbar/crowbar-core/pull/1612
=> upgrade: Do not allow cinder-volume on compute nodes

crowbar_framework/app/controllers/api/upgrade_controller.rb
The else clause for upgrade nodes assumes input is valid, and if it
isn't, returns an unhelpful message about how controller nodes need to
be upgraded first. Validate the input to provide a helpful error.
(cherry picked from commit d3cd42d8816b892b23cb332772a773b1768cd125)
https://github.com/crowbar/crowbar-openstack/pull/1692 is the PR for master.
requests?**
=> [stable/4.0] upgrade: Check input is a valid node for nodes

updates/control_lib.sh
Before the "provisioner: replace curl calls to crowbar API with
crowbarctl" commit, __post_state did an implicit (at least partial)
get_state, updating ADMIN_ADDRESS. Without this, ADMIN_ADDRESS is
unset after allocation, causing the "PXE file contains .*install"
check to fail and the code having to time out after 300 seconds for
the host to be rebooted into installation.
Just add that __get_state in __post_state to fix this, also for other
unidentified cases where this implicit behaviour is expected.
=> control_lib: fix host allocation check

crowbar_framework/app/models/api/crowbar.rb
Non-disruptive upgrade cannot have manila shares on compute nodes.
It seems upgraded (Pike based) control plane cannot communicate with
old (Newton based) shares on (still not upgraded) compute nodes.
=> [4.0] upgrade: Do not allow manila-share on compute nodes

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-delete-pacemaker-resources.sh.erb
RabbitMQ requires re-start of cluster to be started from former master
node or multiple resets are needed before sync status is reached.
It is easier to just reset the nodes before stopping the cluster and
start from scratch with new one after upgrade.
This can help avoid problems when someone tries to use not-yet-ready
RabbitMQ cluster immediately after controllers upgrade. It also
prevents some confusing error messages in logs.
=> upgrade: Reset RabbitMQ nodes during upgrade

crowbar_framework/app/models/api/upgrade.rb
After removing crowbar-ui package lock, new version needs to be installed.
Additional `zypper ref` call was added to ensure repos are up to date before
installation.
=> upgrade: Refresh repos before crowbar-ui update (bsc#1099392)

chef/cookbooks/apache2/templates/default/apache.logrotate.erb
apache2 reload causes responses 406 from keystone. This change was
verified on a customer's setup.
bsc#1083093
=> apache: copytruncate apache logs bsc#1083093

crowbar_framework/lib/crowbar/upgrade_timeouts.rb
Latest jobs have been failing because of timeout during OS upgrade.
(cherry picked from commit 50a68a5901e9fae09a9c58bb245f58d87c1f331b)
Backport of https://github.com/crowbar/crowbar-core/pull/1576
=> [4.0] upgrade: Raise the default timeouts for most time consuming actions

crowbar_framework/app/models/service_object.rb
Error message was referencing pid.log file which is no longer used
since commit fda8ea9c187daaf3a3bbd1c8da4ffa3c17a06981
=> Fix exception handling in get_log_lines

crowbar_framework/app/models/service_object.rb
Error message was referencing pid.log file which is no longer used
since commit fda8ea9c187daaf3a3bbd1c8da4ffa3c17a06981
(cherry picked from commit 10b00fb0ab411e4ffdfb19ee7ee79bd6149cfcef)
Backport of https://github.com/crowbar/crowbar-core/pull/1632
=> [4.0] Fix exception handling in get_log_lines

chef/cookbooks/apache2/templates/default/apache.logrotate.erb
apache2 reload causes responses 406 from keystone. Remove the reload
and copytruncate instead.
(cherry picked from commit bcc0f77cde6f83b25b1770b40da38d845e30e1d7)
Backport-of: https://github.com/crowbar/crowbar-core/pull/1508
=> [4.0] apache: copytruncate apache logs bsc#1083093

chef/cookbooks/bind9/recipes/default.rb, chef/cookbooks/bind9/templates/default/named.conf.erb
The newer bind version in SLE12 SP4 enables listening on IPv6
by default, however we can't deal with that yet. disable it
so that we can bootstrap crowbar.
requests?**
=> bind: Disable listening on IPv6 addresses for now

chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb
When debugging problems it is more useful if the grep results
are not hidden.
(cherry picked from commit 0011d10a5dd3ef57fc02abe1813d4853fa3a5a85)
backport of https://github.com/crowbar/crowbar-core/pull/1637
=> upgrade: Show the grep result when checking for not-migrated instances

Gemfile
(cherry picked from commit 41341a3ba932b730755e9bf756d4780c408a685b)
Backport from #1620
=> [4.0] Update sprockets to 2.12.5 (bsc#1098369, CVE-2018-3760)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-set-network-agents-state.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb
As a workaround for https://bugs.launchpad.net/neutron/+bug/1780453 we
are now setting the "ADMIN_STATE_UP" attribute to "down" before
upgrading a (network)-node. The attribute is reset to "up" after the
node was successfully upgrade and all services are running again. This
should e.g. avoid neutron/neutron-dhcp-agent to try to bring up e.g. a
dhcp port on a node where the Layer 2 agent (openvswitch-/linuxbridge-agent)
is not fully up yet.
=> upgrade: disable network agents during upgrade

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-set-network-agents-state.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb
As a workaround for https://bugs.launchpad.net/neutron/+bug/1780453 we
are now setting the "ADMIN_STATE_UP" attribute to "down" before
upgrading a (network)-node. The attribute is reset to "up" after the
node was successfully upgrade and all services are running again. This
should e.g. avoid neutron/neutron-dhcp-agent to try to bring up e.g. a
dhcp port on a node where the Layer 2 agent (openvswitch-/linuxbridge-agent)
is not fully up yet.
(cherry picked from commit 2c85bc90d38c6b65d09ce83dfb9a1ad5a32eba10)
=> [5.0] upgrade: disable network agents during upgrade

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json, crowbar_framework/spec/models/api/upgrade_spec.rb
This was still relying on postgresql being the database backend for openstack. It went unnoticed for so long because the default values for the postgresql backend related chef attributes pointed the upgrade     procedure to "localhost". So it created a dump of the admin node's database
=> upgrade: Port openstack db backup to mysql

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json, crowbar_framework/spec/models/api/upgrade_spec.rb
This was still relying on postgresql being the database backend for openstack. It went unnoticed for so long because the default values for the postgresql backend related chef attributes pointed the upgrade procedure to "localhost". So it created a dump of the admin node's database
backport of https://github.com/crowbar/crowbar-core/pull/1651
=> [5.0] upgrade: Port openstack db backup to mysql

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-chef-upgraded.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
nova-cert service got deprecated and needs to be removed when upgrading
to Pike. Let's do the removal after the node is fully upgraded and
service's binary is not present, so its accidental (re)start does not cause
recreating deleted nova-cert.
=> [5.0] upgrade: Remove nova-cert service after the node upgrade

chef/cookbooks/crowbar/templates/default/crowbar-set-network-agents-state.sh.erb
"neutron" and "openstack" might be missing when running the script in a
setup with separate network nodes.
=> upgrade: Install missing clients for helper script

chef/cookbooks/crowbar/templates/default/crowbar-set-network-agents-state.sh.erb
"neutron" and "openstack" might be missing when running the script in a
setup with separate network nodes.
(cherry picked from commit dffc64b7d052d39bea0723ab9052b61a1f098477)
Backport of: https://github.com/crowbar/crowbar-core/pull/1654
=> [5.0] upgrade: Install missing clients for helper script

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/spec/models/api/crowbar_spec.rb
Database roles were split into database-server and mysql-server.
For the purpose of the upgrade, correct database should be the one with
mysql-server role.
Requires: https://github.com/crowbar/crowbar-openstack/pull/1746
=> [4.0] upgrade: Check for the presence of correct database role

crowbar_framework/app/models/api/crowbar.rb
Nodes that are placed on compute nodes have to be explicitly allowed
for the upgrade usage, otherwise precheck will complain that such
setup is not possible to upgrade.
New neutron-sdn-cisco-aci-agents was added to 4.0 branch just recently
by commit 3e285f548fd18cc83260b8f0dc51cf18696758a8
See 
- https://ci.suse.de/job/openstack-mkcloud/133567/console for a failed upgrade job
- https://github.com/crowbar/crowbar-openstack/pull/1700 for the addition of a new role
If, on the other hand, it would break upgrade somehow to have such role on compute node, we must adapt the code in neutron service so it is not placed automatically on compute nodes...
=> upgrade: Allow neutron-sdn-cisco-aci-agents role on compute nodes

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.sh.erb
If rabbitmq is using DRBD in SOC7, it's switched to the clustered
setup automatically.
We need to update some configuration files on the nodes temporarily,
so that nova API works when doing live-migration (that is, before the
compute node is fully upgraded).
(cherry picked from commit 043e5aaadc43be65d3b94c0a83903eb5ce8e2d4f)
=> [5.0] upgrade: Adapt the rabbitmq client's config after rabbitmq setup change

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml
The precheck is part of crowbar-ha. Here we are adding the presentation
layer.
Requires https://github.com/crowbar/crowbar-ha/pull/331
=> [4.0] upgrade: New precheck added to check cluster node state

chef/cookbooks/ohai/recipes/default.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb
On a 1000+ VM installation using vxlan tunnel devices the amount
of vxlan-$id devices collected by ohai was overflowing the chef
database causing total deployment outage. Skip virtual vxlan
devices from collection and generation in dhcp list to avoid
slowdowns.
requests?**
=> provisioner: Skip vxlan virtual devices

chef/data_bags/crowbar/migrate/crowbar/300_noop.rb, chef/data_bags/crowbar/migrate/dns/300_noop.rb, chef/data_bags/crowbar/migrate/ipmi/300_noop.rb, chef/data_bags/crowbar/migrate/network/300_noop.rb, chef/data_bags/crowbar/migrate/ntp/300_noop.rb, chef/data_bags/crowbar/migrate/salt/300_noop.rb, chef/data_bags/crowbar/template-crowbar.json, chef/data_bags/crowbar/template-dns.json, chef/data_bags/crowbar/template-ipmi.json, chef/data_bags/crowbar/template-network.json, chef/data_bags/crowbar/template-ntp.json, chef/data_bags/crowbar/template-salt.json, chef/data_bags/crowbar/template-suse_manager_client.json
To give some head room for future schema migrations in the
stable/5.0-pike branch we bump the schema revision for all barclamps to
300. The migration itself is a noop it's just there to ensure the
schema-revision is increased on all existing proposals and roles (mainly
needed for future upgrades from stable/5.0-pike).
=> Bump schema revision to 300 after release

chef/cookbooks/ohai/recipes/default.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb
On a 1000+ VM installation using vxlan tunnel devices the amount
of vxlan-$id devices collected by ohai was overflowing the chef
database causing total deployment outage. Skip virtual vxlan
devices from collection and generation in dhcp list to avoid
slowdowns.
(cherry picked from commit 468b18b6d318e09353650e3d953e060673c592f7)
requests?**
Backport of #1631
=> [5.0] provisioner: Skip vxlan virtual devices

chef/cookbooks/ohai/recipes/default.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb
On a 1000+ VM installation using vxlan tunnel devices the amount
of vxlan-$id devices collected by ohai was overflowing the chef
database causing total deployment outage. Skip virtual vxlan
devices from collection and generation in dhcp list to avoid
slowdowns.
(cherry picked from commit 468b18b6d318e09353650e3d953e060673c592f7)
requests?**
Backport of #1631
=> [4.0] provisioner: Skip vxlan virtual devices

crowbar_framework/config/repos-cloud.yml
The product rename wasn't tested with SMT, obviously.
=> [5.0] repos: Fix product name to be SUSE OpenStack Cloud Crowbar for SMT

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/application.rb, crowbar_framework/config/crowbar.yml, crowbar_framework/config/experimental.yml
it properly.
* Creates a new config file (crowbar.yml) for normal config switches
* Moves the config settings from the experimental to the normal config
* Changes the calls to experimental settings to point tot he new file
=> crowbar: move skip unready nodes out of experimental

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml
The check for cluster nodes is part of crowbar-ha.
It is executed from crowbar-core as part of upgrade prechecks.
(cherry picked from commit f77e483b8247e6fafb0333accd1a3adb792a2e32)
Port of https://github.com/crowbar/crowbar-core/pull/1663
=> upgrade: Cluster health check was extended with one more check

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/application.rb, crowbar_framework/config/crowbar.yml, crowbar_framework/config/experimental.yml
it properly.
* Creates a new config file (crowbar.yml) for normal config switches
* Moves the config settings from the experimental to the normal config
* Changes the calls to experimental settings to point tot he new file
(cherry picked from commit 01a7db936d49bc1af93d3d85dab6e4c1c286f151)
=> [5.0] crowbar: move skip unready nodes out of experimental

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/application.rb, crowbar_framework/config/crowbar.yml, crowbar_framework/config/experimental.yml
it properly.
* Creates a new config file (crowbar.yml) for normal config switches
* Moves the config settings from the experimental to the normal config
* Changes the calls to experimental settings to point tot he new file
(cherry picked from commit 01a7db936d49bc1af93d3d85dab6e4c1c286f151)
=> [4.0] crowbar: move skip unready nodes out of experimental

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, crowbar_framework/app/models/api/upgrade.rb
Originally chef-client was started when running crowbar_join after
the node upgrade. But we still need to save some node data after
this point (in finalize_node_upgrade) and there could be a chance that
chef-client is already running at the node. In such case, our node.save
would not have an effect and running chef-client saves the old reversion
of a node.
To prevent this, do not start chef-client service from that crowbar_join
but only explicitely from finalize_node_upgrade after the node data were
saved.
=> upgrade: Do not start chef-client service from recipe

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/crowbar.yml, crowbar_framework/config/experimental.yml
it properly.
Moves the config settings from the experimental to the normal config
Changes the calls to experimental settings to point tot he new file
=> crowbar: move skip unchanged batches out of experimental

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/crowbar.yml, crowbar_framework/config/experimental.yml
it properly.
Moves the config settings from the experimental to the normal config
Changes the calls to experimental settings to point tot he new file
(cherry picked from commit fabf65e4836d4c40736bfe658044e70099433575)
Backport from #1688
=> [4.0] crowbar: move skip unchanged batches feature out of experimental

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/crowbar.yml, crowbar_framework/config/experimental.yml
it properly.
Moves the config settings from the experimental to the normal config
Changes the calls to experimental settings to point tot he new file
(cherry picked from commit fabf65e4836d4c40736bfe658044e70099433575)
Backport from #1688
=> [5.0] Crowbar: move skip unchanged batches feature out of experimental 5

chef/cookbooks/bind9/templates/default/named.conf.erb
This is a precondition for using rndc to manage bind and also
enables designate integration. Enabling it should not be harmful
as it listens to localhost only and requires a shared secred
from (/etc/rndc.key) to be available to both the client and the server
for proper communication. And that file is only readable by root.
requests?**
=> bind: Allow new zones configured via rndc

chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb
This is necessary after some failure and retry.
When the compute node upgrade fails e.g. during OS installation and
user retries the step, first think that crowbar does is to live-evacuate
the host that has failed the upgrade. However the script for live-evacuation
could fail because nova-compute service might be stopped on the node already.
So we add the initial check that makes sure there are no running instances
on the host (they should not be, otherwise the OS upgrade would not start).
(cherry picked from commit 9e66773db2a339c9d2801ed2f686c1a26da5eed2)
=> [5.0] upgrade: Add an initial check if there's anything running on a host

chef/cookbooks/ohai/files/default/plugins/linux/block_device_extended.rb
The check never worked before. On the 2 variants of machines I have seen
these are nested one deeper. While this may be different on different
hardware, checking every driver in the tree is more expensive.
Follow up for: a7312a8274312a0b1b0621e2578cf2290748b61c
Backport of: https://github.com/crowbar/crowbar-core/pull/1650
=> [5.0] ohai: fix path to check for aacraid driver (bsc#1085170 bsc#1103882)

chef/cookbooks/ohai/files/default/plugins/linux/block_device_extended.rb
The check never worked before. On the 2 variants of machines I have seen
these are nested one deeper. While this may be different on different
hardware, checking every driver in the tree is more expensive.
Follow up for: a7312a8274312a0b1b0621e2578cf2290748b61c
Backport of: https://github.com/crowbar/crowbar-core/pull/1650
=> [4.0] ohai: fix path to check for aacraid driver (bsc#1085170 bsc#1103882)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/crowbar_service.rb
Usage of "systemctl stop" for shutting down the services should be limited
to the case when pacemaker is not managing those services, i.e. clone_stateless_services
is set to false. However, we're changing the value of this variable during the upgrade
so we must save the original one first.
=> [5.0] upgrade: If pacemaker is used to manage the services, don't use systemctl

chef/data_bags/crowbar/migrate/crowbar/200_add_insecure_attribute.rb
The insecure value might be present from before the upgrade. Without
the check for presence, we would always rewrite the value to default one.
=> [5.0] crowbar: Do not rewrite the value of 'insecure' if it already exist

chef/data_bags/crowbar/migrate/crowbar/200_add_insecure_attribute.rb
The insecure value might be present from before the upgrade. Without
the check for presence, we would always rewrite the value to default one.
(cherry picked from commit af3a53e1d9ce21464daf72d5d7d3f28b592c97ae)
Port of https://github.com/crowbar/crowbar-core/pull/1711
=> crowbar: Do not rewrite the value of 'insecure' if it already exist

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/crowbar_repocheck_zypper_prompt.xml, crowbar_framework/spec/models/api/upgrade_spec.rb
Some zypper prompts include important information in <text> while
others also need <message> items to give proper feedback to the
user.
The display is still very ugly but at least it shows more details.
=> [4.0] upgrade: Improve handling of zypper prompts (bsc#1116853)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
The original condition ( "something" || true ) always evaluates to true.
Checking for node["pacemaker"]["clone_stateless_services_orig"] being
nil or true should give the desired result. (clone_stateless=false only
if node["pacemaker"]["clone_stateless_services_orig"] is present and
explicitly set to false.
(this doesn't need any forward or backport)
=> [5.0] upgrade: Fix condition for setting clone_stateless value

crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/helpers/form_helper.rb, crowbar_framework/config/locales/crowbar/en.yml
we did not add this earlier, because RAID level 0 increases the
risk of data loss.
But there are advantages for compute nodes without important data:
- larger available disk space
- higher throughput
=> Support RAID 0

crowbar_framework/app/models/node.rb
The crowbar ui is currently going down when there is a node whithout
provisioner proposal:
FATAL -- NoMethodError (undefined method `[]' for nil:NilClass):
app/models/node.rb:319:in `state'
app/models/node.rb:285:in `status'
app/controllers/nodes_controller.rb:606:in `block in get_nodes_and_groups'
app/controllers/nodes_controller.rb:604:in `each'
app/controllers/nodes_controller.rb:604:in `get_nodes_and_groups'
app/controllers/nodes_controller.rb:59:in `index'
=> crowbar: avoid nil crash when provisioner attributes are not set

salt.yml
To be able to deploy salt on the admin node (and use it via salt-ssh),
the baclamp must be visible. That's done now.
Also move the barclamp in the list down (given that it is not that
important and more an optional feature).
Also change the "proposal_schema_version" to 3 which seems to be the
default in other barclamps.
=> salt: Make the barclamp visible in the UI and adjust order

crowbar_framework/lib/crowbar/conduit_resolver.rb
Some machines, like for example HPE Proliant Gen8/9 do not report
their serial number under dmi.system but under dmi.base_board.
$ knife node show $node -a node.dmi.system.serial_number
node.dmi.system.serial_number:  Not Specified
$ knife node show $node -a node.dmi.base_board.serial_number
node.dmi.base_board.serial_number:  2M2528179N
Treat that as equivalent for matching the serial_number bus_order
specifier.
=> conduits: match base_board.serial_number as well

crowbar_framework/config/crowbar.yml
It is pretty tiresome to fixup bus_order when it blocks on unready
nodes. Allow skipping of unready nodes. the network barclamp will
always be executed by crowbar_join (both in --setup and --start) so
skipping it if the node isn't ready should be safe.
=> allow skip_unready_nodes for network barclamp

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/crowbar_repocheck_zypper_prompt.xml, crowbar_framework/spec/models/api/upgrade_spec.rb
Some zypper prompts include important information in <text> while
others also need <message> items to give proper feedback to the
user.
(cherry picked from commit 41c39ae58b4c2546c80b7809f4d07df714992487)
forward port of #1714
=> [5.0] upgrade: Improve handling of zypper prompts (bsc#1116853)

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/crowbar_repocheck_zypper_prompt.xml, crowbar_framework/spec/models/api/upgrade_spec.rb
Some zypper prompts include important information in <text> while
others also need <message> items to give proper feedback to the
user.
(cherry picked from commit 41c39ae58b4c2546c80b7809f4d07df714992487)
forward port of #1714
=> upgrade: Improve handling of zypper prompts (bsc#1116853)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-delete-cinder-services-before-upgrade.sh.erb, crowbar_framework/app/models/api/upgrade.rb
This reverts commit b27b6d72a56bf7e9a22a4d7d93ce6df6f22db8ba and PR https://github.com/crowbar/crowbar-core/pull/1600
Turns out, it is still correct to delete those services before the upgrade.
Note that this was not clean revert, the code in `upgrade.rb` has changed a bit since the time of the original commit.
=> upgrade: Revert "upgrade: Deleting cinder services from database no longer needed

crowbar_framework/config/initializers/delayed_job_config.rb
The longest method started in the background seems to be Api::Upgrade.nodes.
Assuming 1h per node we could upgrade 168 nodes with 7 days limit.
Default limit is 4 hours which is way too low for this task.
=> upgrade: Increase delayed_job time limit

chef/cookbooks/apache2/definitions/apache_site.rb, chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-delete-pacemaker-resources.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-migrate-keystone-and-start.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-keystone.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-remaining-services.sh.erb, crowbar_framework/app/models/api/upgrade.rb
This tries to reduce the required downtime of keystone during the upgrade. Basically we achieve this by keep keystone running on the non-upgraded nodes for a while longer and by preventing it from being started by crowbar_join on the 1st upgraded node. By doing this we have more control over when we actually run the db migrations for keystone and do the switchover. 
There's a couple of things missing for the PR to be ready for merge:
There is some potential for reducing the downtime even more, by utilizing keystone's rolling upgrade features  (https://docs.openstack.org/keystone/pike/admin/identity-upgrading.html "upgrading without downtime" section). But it's uncertain that this actually works for a newton -> pike upgrade. (It would at least need increased db privileges for the keystone …
=> [5.0] upgrade: reduce keystone downtime

crowbar_framework/app/controllers/api/upgrade_controller.rb
Do it also for the cases when subset of compute nodes was selected.
=> [5.0] upgrade: Mark correctly the set of nodes that was selected for upgrade

crowbar_framework/config/initializers/delayed_job_config.rb
The longest method started in the background seems to be Api::Upgrade.nodes.
Assuming 1h per node we could upgrade 168 nodes with 7 days limit.
Default limit is 4 hours which is way too low for this task.
(cherry picked from commit 15f127ee5659bd4ef376eecfc5e392e1c7af9d80)
port of #1721
=> [5.0] upgrade: Increase delayed_job time limit

crowbar_framework/lib/crowbar/checks/network.rb, crowbar_framework/spec/lib/crowbar/checks/network_spec.rb
Currently the SLE12 iptuils package is using iputils 20121221 which
has separate ping and ping6 binaries. Which is fine, but the ping
command only works with ipv4, even if given a FQDN the qaulifies to
ipv6.
SLE15's iputils is using 20161105, which has both ipv4 and ipv6 in
support in the ping command.
This change modifies the check to test with ping6 if ping fails, so
the check will work on legecy systems.
The other alternative is to update SLE12's iputils package which
may be a better alternative, but this change bypasses the problem.
=> Add ping support for IPv6

crowbar_framework/lib/schema_migration.rb, crowbar_framework/lib/tasks/crowbar.rake
When working with migrations, it's useful to be able to set the schema
revision to a lower value to rerun the latest migration.
With this change, there is a new rake task called
"set_schema_revision". This can be used like:
- get the current revision status for the available proposals
$ RAILS_ENV=production ./bin/rake crowbar:schema_migrate_status
- set the schema-revision to a lower number (in this case 299)
$ RAILS_ENV=production ./bin/rake \
crowbar:set_schema_revision[crowbar,299]
- Now run the migration for the crowbar barclamp again
$ RAILS_ENV=production ./bin/rake crowbar:schema_migrate[crowbar]
=> crowbar: Add rake task to set the schema-revision

crowbar_framework/app/models/api/upgrade.rb
I want to prevent situations like this one:
```:current_step: :nodes
:current_substep: :compute_nodes
:current_substep_status: :running
:current_nodes:
- :name: d8c-dc-d4-0d-59-48.ecp1.cloud.suse.de
:alias: compute21
:ip: 10.86.32.36
:state: upgraded
:role: compute
:current_node_action: live-migrating nova instances from d5c-b9-01-89-b9-08
:remaining_nodes: 73
:upgraded_nodes: 102
```
=> [5.0] upgrade: Reset the current nodes list before new set of nodes

crowbar_framework/app/models/crowbar_validator.rb
The crowbar validator uses the barclamp schema files to determine
if the current values are correct. When attempting to validate the
network.json file for the network barclamp that validator doesn't
understand ipv6 addresses.
This patch adds some extra regexes to the IpAddress validation to
understand not just IPv4 addresses but also IPv6 and CIDR netmasks.
This is one step closer to getting IPv6 support in crowbar.
=> Ipv6 support in the crowbar_validator

chef/cookbooks/network/recipes/default.rb, crowbar_framework/app/models/network_service.rb
The 'network:default' chef recipe attempts to ping the
the admin IP address but fails when the admin node is using
an IPv6 address. It fails because SLE12.* ships an older version
of iputils, whose ping only supports IPv4 addresses and requires
the use of ping6 for IPv6 addresses.
This patch checks the admin ip version and uses the correct ping
binary.
This patch also adds CIDR support to
`crowbar_framework/app/models/network_service.rb`. As without it
it fails to find the admin IP to apply to the chef node causing
the admin node's eth0 interface to be de-configured.
CIDR notation is most common in IPv6 as the writing it as a full
IPv6 mask is alot more work. This patch detects whether the netmask
is in CIDR notation, if it is it'll convert it to the full notation
so it can be used in the …
=> network: add IPv6 and CIDR support

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/crowbar_service.rb
Originally https://github.com/crowbar/crowbar-core/pull/1695
Targeting specific branch to keep the work somewhere
=> upgrade: Skip powered off compute nodes during the upgrade prechecks

chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/node.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
During live migration, we have a check that makes sure all available
nova-compute services are up. This check has to exclude nodes that are shut down.
Originally https://github.com/crowbar/crowbar-core/pull/1697
=> upgrade: Ignore shut down nodes throughout the upgrade

.travis.yml
Bundler version >= 2.0.0 requires rubygems >= 3.0.
There seems to be no simple way to upgrade rubygems with ruby2.1.
Pinning bundler to older version solves the problem.
see:
https://travis-ci.community/t/bundle-is-not-installed-for-ruby-2-3/1641
https://github.com/travis-ci/travis-ci/issues/5290
port of #1755
=> travis fix for bundler problems

.travis.yml
Bundler version >= 2.0.0 requires rubygems >= 3.0.
There seems to be no simple way to upgrade rubygems with ruby2.1.
Pinning bundler to older version solves the problem.
see:
https://travis-ci.community/t/bundle-is-not-installed-for-ruby-2-3/1641
https://github.com/travis-ci/travis-ci/issues/5290
port of #1755
=> [5.0] travis fix for bundler problems

.travis.yml
Bundler version >= 2.0.0 requires rubygems >= 3.0.
There seems to be no simple way to upgrade rubygems with ruby2.1.
Pinning bundler to older version solves the problem.
see:
https://travis-ci.community/t/bundle-is-not-installed-for-ruby-2-3/1641
https://github.com/travis-ci/travis-ci/issues/5290
=> [4.0] travis fix for bundler problems

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb
**Skip already upgraded nodes**
If list of nodes is requested for upgrade, already upgraded nodes will be
skipped. Re-running upgrade procedure on an already upgraded node could
trigger various problems.
+
**Fail if no nodes can be upgraded**
This can happen e.g. if some live evacuation doesn't succeed.
The added condition should ensure non_disruptive_upgrade_compute_nodes()
will not loop forever.
=> [5.0]upgrade: Skip already upgraded nodes+fail with no upgradeable nodes

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb
**Skip already upgraded nodes**
If list of nodes is requested for upgrade, already upgraded nodes will be
skipped. Re-running upgrade procedure on an already upgraded node could
trigger various problems.
+
**Fail if no nodes can be upgraded**
This can happen e.g. if some live evacuation doesn't succeed.
The added condition should ensure non_disruptive_upgrade_compute_nodes()
will not loop forever.
port of #1741
=> upgrade: Skip already upgraded nodes+fail with no upgradeable nodes

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-run-nova-online-migrations.sh.erb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
There are operations (like attaching volume using reserve_block_device_name
method) that cannot be performed with mixed nova setup. So we pin the RPC
version to the latest one that works for Newton. That is achieved with https://github.com/crowbar/crowbar-openstack/pull/1941
After the upgrade, we need to reload (and restart?) the services so they can switch to the latest RPC version.
=> [5.0] upgrade: Signal all nova services after the upgrade is complete 

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-delete-unknown-nova-services.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb
If such (presumably old) services would stay in database, it would not be possible
to convince fully upgraded nova to use the latest RPC API.
(cherry picked from commit d7d9214088a4873a05e207d51ab2af5f2f70e4e8)
Port of https://github.com/crowbar/crowbar-core/pull/1754
=> upgrade: Delete nova services that are registered to unknown nodes

chef/cookbooks/apache2/templates/suse/mods/ssl.conf.erb
apache2: enable sslsessioncache
The if conditionals in this files had a typo which made then
always disabled. We need to list the module name like documented.
Merge it more with the package-provided default config file.
Also update cipher list away from a very insecure default and
use the openssl provided SUSE_DEFAULT cipher list so that we don't
ever have to update this again.
=> apache2: enable sslsessioncache

crowbar_framework/app/controllers/application_controller.rb, crowbar_framework/config/initializers/mime_types.rb
JSONAPI MimeTypes (e.g. application/vnd.crowbar.v2.0+json) are not mapped to symbols in rails by default. This is required to handle JSONAPI requests properly inside code like `respond_to ... format....`.
The case where this was mostly visible is GET requests which should be enabled during upgrade but were mostly returning 406 NotAcceptable.
Better solution to problem from #1774
Before:
```
root@crowbar:~ # crowbarctl backup list
root@crowbar:~ # crowbarctl backup create test
root@crowbar:~ # crowbarctl backup download non-existing-name
Crowbar::Client::SimpleCatchableError
```
After:
```
root@crowbar:~ # crowbarctl backup list
+-------------------------------+--------------------------+--------+---------+
| Name                          | Created                  | Size   | Version | …
```
=> [4.0] upgrade: Map jsonapi for respond_to

chef/cookbooks/apache2/definitions/apache_site.rb, chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-delete-pacemaker-resources.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-migrate-keystone-and-start.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-keystone.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-remaining-services.sh.erb, crowbar_framework/app/models/api/upgrade.rb
This tries to reduce the required downtime of keystone during the upgrade. Basically we achieve this by keep keystone running on the non-upgraded nodes for a while longer and by preventing it from being started by crowbar_join on the 1st upgraded node. By doing this we have more control over when we actually run the db migrations for keystone and do the switchover.
Forward port of #1715
=> upgrade: reduce keystone downtime 

chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb
Sending the signal to all processes of the unit will have unwanted
site-effects. E.g. in the case of nova-compute it might cause the
privsep helper to terminate which brings down the whole service.
=> [5.0] upgrade: Only SIGHUP the main nova processes

crowbar_framework/app/controllers/application_controller.rb, crowbar_framework/config/initializers/mime_types.rb
JSONAPI MimeTypes (e.g. application/vnd.crowbar.v2.0+json) are not mapped to
symbols in rails by default. This is required to handle JSONAPI requests properly
inside code like `respond_to ... format....`.
The case where this was mostly visible is GET requests which should be enabled
during upgrade but were mostly returning 406 NotAcceptable.
(cherry picked from commit 3c6f3d82c95bf346ceece3e88948cfc7ae3239c5)
port of #1775
=> [5.0] upgrade: Map jsonapi for respond_to

crowbar_framework/app/controllers/application_controller.rb, crowbar_framework/config/initializers/mime_types.rb
JSONAPI MimeTypes (e.g. application/vnd.crowbar.v2.0+json) are not mapped to
symbols in rails by default. This is required to handle JSONAPI requests properly
inside code like `respond_to ... format....`.
The case where this was mostly visible is GET requests which should be enabled
during upgrade but were mostly returning 406 NotAcceptable.
(cherry picked from commit 3c6f3d82c95bf346ceece3e88948cfc7ae3239c5)
port of #1775
=> upgrade: Map jsonapi for respond_to

crowbar_framework/app/models/api/upgrade.rb
If do_controllers_substep is called with substep other than :ceph_nodes
or :controller_nodes it should not finish the substep silently.
(cherry picked from commit dbcc949a094a5dab5cd5e5db33dddb0ec41cf9d1)
forward port of #1593
=> [5.0] upgrade: Finish only controllers step

crowbar_framework/app/models/api/crowbar.rb
We're checking the return hash for empty? so we want it empty
when the test passes.
(cherry picked from commit 0f2bc24088010000a14573cd92747d52dd56ea61)
port of https://github.com/crowbar/crowbar-core/pull/1589
=> [5.0] upgrade: Fix check for ceph presence

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Upgrade library that is part of this version of crowbar-core package
can be used by
a) 7-8 upgrade: when executing the later steps that are done after
upgrading all crowbar packages at admin server to next product
b) 8-9 upgrade: when executing the initial steps on SOC8 before
upgrading crowbar packages at admin server to next product
So we need to distinguish these two cases.
(cherry picked from commit cfbdd72914f22f9b2a005420d90b595d6a887dec)
(Original commit was handling 6-7 & 7-8 combination)
Based on https://github.com/crowbar/crowbar-core/pull/1444
=> [5.0] upgrade: Let the upgrade library work with both 7-8 and 8-9 upgrades.

chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb
To workaround a bug in nova-compute, we need to restart the server after
the upgrade instead of just sending a SIGHUP until a fix for
https://launchpad.net/bugs/1715374 is available.
=> [5.0] upgrade: Restart nova-compute instead of relaoding via SIGHUP

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-heat-migrations-after-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-nova-migrations-after-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-run-nova-online-migrations.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb
This is how it went during my test:
```
+ nova-manage db online_data_migrations --max-count 200
3 rows matched query populate_missing_availability_zones, 3 migrated
+---------------------------------------------+--------------+-----------+
|                  Migration                  | Total Needed | Completed |
+---------------------------------------------+--------------+-----------+
| delete_build_requests_with_no_instance_uuid |      0       |     0     |
|    migrate_aggregate_reset_autoincrement    |      0       |     0     |
|              migrate_aggregates             |      0       |     0     |
|      migrate_flavor_reset_autoincrement     |      0       |     0     |
|               migrate_flavors               |      0       |     0     |
| …
```
=> [5.0] Migrations after upgrade

configs/upgrade_timeouts.yml
By default there was no upgrade_timeouts.yml file installed so users
had to create one if they wanted to adjust some timeout. It's easier
for users to modify values in an existing file so file with defaults
was added.
Packaging SR will follow when this PR is merged.
=> [4.0] upgrade: Add default upgrade timeouts file

configs/upgrade_timeouts.yml
By default there was no upgrade_timeouts.yml file installed so users
had to create one if they wanted to adjust some timeout. It's easier
for users to modify values in an existing file so file with defaults
was added.
(cherry picked from commit acdaba53cc52b693c0c7761620c050f84c79f07c)
port of #1782
=> [5.0] upgrade: Add default upgrade timeouts file

configs/upgrade_timeouts.yml
By default there was no upgrade_timeouts.yml file installed so users
had to create one if they wanted to adjust some timeout. It's easier
for users to modify values in an existing file so file with defaults
was added.
(cherry picked from commit acdaba53cc52b693c0c7761620c050f84c79f07c)
port of #1782
=> upgrade: Add default upgrade timeouts file

chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb
Sending the signal to all processes of the unit will have unwanted
site-effects. E.g. in the case of nova-compute it might cause the
privsep helper to terminate which brings down the whole service.
(cherry picked from commit 57e357053378d40da288b370b7edfe83c683f242)
backport of https://github.com/crowbar/crowbar-core/pull/1778
=> upgrade: Only SIGHUP the main nova processes

crowbar_framework/app/controllers/application_controller.rb
This code needs to cover 2 different upgrade paths:
- end of 7-8 upgrade
- start of 8-9 upgrade
So we should not check for just one "running upgrade" indication.
=> [5.0] upgrade: Block access to crowbar UI for both upgrade paths

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/fixtures/crowbar_repocheck.json, crowbar_framework/spec/models/api/upgrade_spec.rb
When upgrading from SOC8 to SOC9, we need to check if admin server
has SOC9 and SLE12SP4 repositories prepared.
=> [5.0] upgrade: Update the repository names required for SOC9

crowbar_framework/lib/crowbar/upgrade_status.rb
In SOC8 we have to check for 7-8 file, since postponed/resume actions
are in the 2nd part of the upgrade.
=> [5.0] upgrade: Check for the correct file indicating postponed upgrade

chef/cookbooks/apache2/templates/suse/mods/ssl.conf.erb
The if conditionals in this files had a typo which made then
always disabled. We need to list the module name like documented.
Merge it more with the package-provided default config file.
Also update cipher list away from a very insecure default and
use the openssl provided SUSE_DEFAULT cipher list so that we don't
ever have to update this again.
(cherry picked from commit 0a3a0d93e0cd213801f7d9e608ce265dc262b094)
=> [4.0] apache2: enable sslsessioncache

chef/cookbooks/apache2/templates/suse/mods/ssl.conf.erb
The if conditionals in this files had a typo which made then
always disabled. We need to list the module name like documented.
Merge it more with the package-provided default config file.
Also update cipher list away from a very insecure default and
use the openssl provided SUSE_DEFAULT cipher list so that we don't
ever have to update this again.
(cherry picked from commit 0a3a0d93e0cd213801f7d9e608ce265dc262b094)
=> [5.0] apache2: enable sslsessioncache

crowbar_framework/app/views/barclamp/provisioner/_edit_attributes.html.haml, crowbar_framework/config/locales/provisioner/en.yml
Hyper-V hosts are no longer supported, so we don't need to expose
this to the UI. with out this patch the occassional user might
be feeling confused.
=> provisioner: Remove references to windows admin password (bsc#1123640)

chef/cookbooks/provisioner/recipes/keys.rb
"nodename" in keys is just a comment; so create a dummy because in case
of no(empty) comment 'keys.sort' in the template fails because in ruby 'nil'
does not have any order
=> assign host to hostless keys

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Previously the "next upgrade" status file was used as soon as "current"
upgrade was finished. This sometimes caused problems when "final" status
was missed because it was already covered with new "not started yet" status.
With this change, "old" status will be returned for 24hrs after upgrade was
finished. After that subsequent calls to status API would return "new" status.
=> [5.0] upgrade: Delay status switch after upgrade ends

chef/cookbooks/crowbar/templates/default/crowbar-prepare-repositories.sh.erb
We want the Update repositories to autorefresh because
they frequently change, and it is convenient if zypper
does the check for us rather than having to manually
"zypper ref -f" all the time.
=> upgrade: Create update repositories with refresh enabled

chef/cookbooks/crowbar/templates/default/crowbar-prepare-repositories.sh.erb
We want the Update repositories to autorefresh because
they frequently change, and it is convenient if zypper
does the check for us rather than having to manually
"zypper ref -f" all the time.
backport of #1793 
(cherry picked from commit 6d3b3549e73a43f233b18344f4e26033a09bc7da)
=> [5.0] upgrade: Create update repositories with refresh enabled

chef/cookbooks/network/recipes/default.rb
When cleaning up vlan interfaces, simply running 'vconfig rem' doesn't have any effect for interfaces that are already managed by wicked. Only running 'wicked ifdown' or the more general 'ifdown' properly cleans up these interfaces.
Fixes [bsc#1063535](https://bugzilla.suse.com/show_bug.cgi?id=1063535)
Also see: https://trello.com/c/tkxpXh9w
=> network: run ifdown for vlan interface cleanup

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Previously the "next upgrade" status file was used as soon as "current"
upgrade was finished. This sometimes caused problems when "final" status
was missed because it was already covered with new "not started yet" status.
With this change, "old" status will be returned for 24hrs after upgrade was
finished. After that subsequent calls to status API would return "new" status.
(based on commit 54907465a537cb1c76504080bfac97c1aad73bc9)
port of #1790
=> [4.0] upgrade: Delay status switch after upgrade ends

chef/cookbooks/network/recipes/default.rb
#1441 backport
When cleaning up vlan interfaces, simply running 'vconfig rem'
doesn't have any effect for interfaces that are already managed
by wicked. Only running 'wicked ifdown' properly cleans up these
interfaces.
Instead of patching only the vlan interfaces in the nic.rb library,
all interfaces are brought down with 'wicked ifdown' in the network
barclamp when removed.
(cherry picked from commit 7dd9b90a5716a84a7a4e6add5173c6a348c51363)
=> network: run wicked ifdown for interface cleanup (bsc#1063535)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
There may be also other compute nodes than just kvm one (bsc#1127129)
(cherry picked from commit 00835eec6bc31512161843b48a46f76e6e23148e)
Port of https://github.com/crowbar/crowbar-core/pull/1800
=> upgrade: Make sure all compute nodes get compute related scripts

chef/cookbooks/crowbar/recipes/default.rb
FileEdit cannot handle multibyte encodings. Let's use ruby directly.
See e.g. https://github.com/chef/chef/issues/7043
=> crowbar: Do not rely on Chef::Util::FileEdit to write the file

chef/cookbooks/ses/README.md, chef/cookbooks/ses/libraries/helpers.rb, chef/cookbooks/ses/metadata.rb, chef/cookbooks/ses/providers/config.rb, chef/cookbooks/ses/resources/config.rb, chef/cookbooks/ses/templates/default/ceph.conf.erb, chef/cookbooks/ses/templates/default/client.keyring.erb, crowbar_framework/app/assets/javascripts/application.js, crowbar_framework/app/controllers/ses_controller.rb, crowbar_framework/app/models/ses.rb, crowbar_framework/app/views/ses/settings.html.haml, crowbar_framework/config/locales/ses/en.yml, crowbar_framework/config/routes.d/ses.routes, ses.yml
Added Crowbar UI part for uploading and viewing SES settings based on
yaml file exported from SES cluster.
Settings are saved in a data bag for future use.
This change is a base for: https://github.com/crowbar/crowbar-openstack/pull/2035
and alternative to: https://github.com/crowbar/crowbar-openstack/pull/1977
TODO:
Some screenshots:
Menu entry:
Empty settings view:
Upload modal (similar to backup upload):
Part of uploaded settings:
=> ses: Configuration upload & SES cookbook

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
This reverts commit 614c4e2f21a2a13ef9d74d09e8639cf7c6332e46.
For now this is just a test PR to see if upgrade of 8 to 9 is already possible. DO NOT MERGE YET
=> [5.0] upgrade-8-9: Revert "Disable upgrade API in Cloud8"

chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
To fix the ones on disk from rpm packages by reinstalling the package in
question with --force.
The rpm package scripts in question just pick a free id. It can not be
ensured that creating the user/groups with specific ids is done before
the packages are installed as crowbar_register may be run on an existing
system that has one or more of the packages already installed. Also
there is the update case, though less likely by now as this code already
existed in the last release.
Note that this does not fix up any on disk uid/gids for files that may
have been created by crowbar (though I don't know any that are) or
manually.
=> Fixup uid/gids if they don't match (SCRD-8014)

chef/cookbooks/bind9/recipes/default.rb, chef/cookbooks/bind9/templates/default/designate-rndc-access.conf.erb, chef/cookbooks/bind9/templates/default/named.conf.erb, chef/data_bags/crowbar/migrate/dns/301_add_rndckey.rb, chef/data_bags/crowbar/template-dns.json, chef/data_bags/crowbar/template-dns.schema, crowbar_framework/app/models/dns_service.rb
Designate needs an rndc key to CRUD zones on the real bind9 master
server, and updates to bind9 can only be sent via a key that is
mentioned in its(bind9) config.
So the key is supposed to be shared across the nodes, (admin and
designate-worker) therefore adding it to the proposal. one could
rsync the key between the nodes but this opens up differnt
types of race conditions/syncronization problems.
- added rndc key field to dns proposal
- a default key is pregnerated (512 bits)
- the designate barclamp will install this key on desginate-worker
nodes as these nodes need authoritative command on the dns-server to
create zones
-  syntax for the controls clause[1]
1 - http://www.zytrax.com/books/dns/ch7/controls.html
=> dns: allow using dns-server as designate target

crowbar_framework/config/initializers/backport_pg_10_support_to_rails_4.rb
PostgreSQL 10 isn't officially supported in rails 4.X, see
https://help.heroku.com/WKJ027JH/rails-error-after-upgrading-to-postgres-10.
As a workaround we can monkeypatch active record code.
=> Fix PostgreSQL 10 support (SCRD-7126)

chef/cookbooks/barclamp/libraries/nic.rb
When add_bridge is set to true, we set the MTU on the bridge interface,
but nothing sets it on the slave interface, so it doesn't work.
So whenever we set the MTU on a bridge, also set it on the slave
interface.
=> barclamp: Fix setting MTU on networks using a bridge

crowbar_framework/app/assets/stylesheets/content/content.scss
Button groups can contain inputs and anchor tags that should be styled similar. Removing this over-ride because they are consistent with out it. This is especially true on barclamp edit pages.
=> Use same line-height for all buttons (SCRD-8582)

bin/gather_logs.sh, bin/transition.sh, chef/cookbooks/crowbar/files/default/crowbar
Both gather_logs.sh and transition.sh seem to use it, for no good reason.
=> Remove dubious uses of machine-install user

bin/barclamp_lib.rb, bin/crowbar_machines, bin/crowbar_node_state
We also stop using the CROWBAR_KEY environment variable and use
CROWBAR_USERNAME and CROWBAR_PASSWORD, like crowbarctl.
This depends on https://github.com/crowbar/crowbar/pull/2379 (which creates /etc/crowbarrc during install-chef-suse, and also removes the use of the crowbar CLI in that script).
This removes a good part of the use of the machine-install user.
=> bin: Read /etc/crowbarrc instead of /etc/crowbar.install.key

crowbar_framework/lib/crowbar/backup/restore.rb
Added code to fix the ownership of admin node log file to crowbar:crowbar after restore since it run chef-client as root and creates the log file with ownership root:root
=> Fix cloud-mkcloud9-job-backup-restore (SCRD-7126)

chef/cookbooks/crowbar/templates/default/apache.conf.erb
This became visible in the CI where SSL is used.
=> crowbar: Also add access to /restricted/ in SSL vhost

crowbar_framework/lib/crowbar/backup/restore.rb
Added code to fix the ownership of admin node log file to
crowbar:crowbar after restore since it run chef-client as root and
creates the log file with ownership root:root
(cherry picked from commit 117d21c372617a98a2157429b07d0ddd27af0d85)
Backport of https://github.com/crowbar/crowbar-core/pull/1822
=> [5.0] Fix cloud-mkcloud9-job-backup-restore (SCRD-7126)

crowbar_framework/lib/crowbar/backup/restore.rb
Added code to fix the ownership of admin node log file to
crowbar:crowbar after restore since it run chef-client as root and
creates the log file with ownership root:root
(cherry picked from commit 117d21c372617a98a2157429b07d0ddd27af0d85)
Backport of #1822
=> [4.0] Fix cloud-mkcloud9-job-backup-restore (SCRD-7126)

cisco_ucs.yml
It's not tested, and is not used. So hide it.
=> cisco-ucs: Hide menu item for Cisco UCS

chef/cookbooks/provisioner/recipes/base.rb
Enable the tuned profiles virtual-host or throughput-performance based
on the current role of the node to get better sysctl settings
=> provisioner: enabled tuned profiles

chef/cookbooks/provisioner/recipes/base.rb
Should remember that we are between GMC1 and 2....
Reverts crowbar/crowbar-core#1796
=> Revert "provisioner: enabled tuned profiles"

chef/cookbooks/network/recipes/default.rb
When cleaning up vlan interfaces, simply running 'vconfig rem'
doesn't have any effect for interfaces that are already managed
by wicked. Only running 'wicked ifdown' properly cleans up these
interfaces.
Instead of patching only the vlan interfaces in the nic.rb library,
all interfaces are brought down with 'wicked ifdown' in the network
barclamp when removed.
Backport-Of: #1441
=> [4.0] network: run wicked ifdown for interface cleanup (bsc#1063535)

crowbar_framework/vendor/assets/javascripts/jquery/ledUpdate.js
JavaScript part of piecharts expected [ready,failed,unknown,upgrade,pending]
but backend was providing [ready,failed,unknown,pending,upgrade].
Backend code is in NodesHelper.piechart_values().
PS. I'm pretty sure I fixed this bug already some time ago... but I couldn't find the git history.
=> Fix order of values in nodes piechart

.travis.yml
SLES 12 only ships Ruby 2.1.9 but nokogiri 1.10.3 requires ruby >=
2.3.0. As we can't update to this version we will ignore the CVE during
travis but we will add a patch to the current SLES 12 nokogiri to fix
the CVE.
=> Ignore CVE-2019-11068 during Travis (SOC-9262)

.travis.yml
SLES 12 only ships Ruby 2.1.9 but nokogiri 1.10.3 requires ruby >=
2.3.0. As we can't update to this version we will ignore the CVE during
travis but we will add a patch to the current SLES 12 nokogiri to fix
the CVE.
(cherry picked from commit e7b9585dc330ed4753119d301c36a16bbcee3c1b)
=> [5.0] Ignore CVE-2019-11068 during Travis (SOC-9262)

.travis.yml
SLES 12 only ships Ruby 2.1.9 but nokogiri 1.10.3 requires ruby >=
2.3.0. As we can't update to this version we will ignore the CVE during
travis but we will add a patch to the current SLES 12 nokogiri to fix
the CVE.
(cherry picked from commit e7b9585dc330ed4753119d301c36a16bbcee3c1b)
=> [4.0] Ignore CVE-2019-11068 during Travis (SOC-9262)

chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/provisioner/recipes/base.rb, crowbar_framework/lib/crowbar/backup/restore.rb
In the case of a restoration from backup, /etc/crowbarrc will already
have been modified by the last installation. During the restore, the
install-suse-chef.sh script runs chef on the admin node, but only with a
select set of roles which at certain points does not include the
provisioner role. The result is that from crowbar's point of view at
that point in time this is a new installation and the proposal values,
including whether to use SSL, are set to default values. However, the
crowbarrc file may already have been modified to use SSL. In this case,
trying to use crowbarctl will fail because the crowbar server is not yet
configured for SSL.
This patch addresses the problem by moving the management of the
crowbarrc file into the crowbar cookbook for the admin node. This way,
if only the …
=> crowbar: Move crowbarrc mgmt into crowbar cookbook (SCRD-8330)

crowbar_framework/vendor/assets/javascripts/jquery/ledUpdate.js
JavaScript part of piecharts expected [ready,failed,unknown,upgrade,pending]
but backend was providing [ready,failed,unknown,pending,upgrade].
Backend code is in NodesHelper.piechart_values().
(cherry picked from commit 5c78f9d872a6b07c92efc61cc4f265a4b408c758)
backport of #1816
=> [5.0] Fix order of values in nodes piechart

crowbar_framework/vendor/assets/javascripts/jquery/ledUpdate.js
JavaScript part of piecharts expected [ready,failed,unknown,upgrade,pending]
but backend was providing [ready,failed,unknown,pending,upgrade].
Backend code is in NodesHelper.piechart_values().
(cherry picked from commit 5c78f9d872a6b07c92efc61cc4f265a4b408c758)
backport of #1816
=> [4.0] Fix order of values in nodes piechart

chef/cookbooks/barclamp/libraries/nic.rb
When add_bridge is set to true, we set the MTU on the bridge interface,
but nothing sets it on the slave interface, so it doesn't work.
So whenever we set the MTU on a bridge, also set it on the slave
interface.
(cherry picked from commit 651d40940d7f80e7a078563dbb3abfeedc47723e)
=> [5.0] barclamp: Fix setting MTU on networks using a bridge

chef/cookbooks/barclamp/libraries/nic.rb
When add_bridge is set to true, we set the MTU on the bridge interface,
but nothing sets it on the slave interface, so it doesn't work.
So whenever we set the MTU on a bridge, also set it on the slave
interface.
(cherry picked from commit 651d40940d7f80e7a078563dbb3abfeedc47723e)
=> [4.0] barclamp: Fix setting MTU on networks using a bridge

chef/cookbooks/network/recipes/role_network.rb
This change provides the possibilty to lock down the network
configuration of specific nodes. It implemented by simply skipping the
whole network cookbook whe the nodes attribute
'node["network"]["config_frozen"]' is set to 'true'. In that case
anychanges to the network barclamp, or any other change that would cause
the network to be reconfigured (e.g. allocation of IPs, enablement of a
network, addition or removal of network devices, ...) will just have no
effect on that node.
=> network: Allow locking down the network config for nodes (bsc#1120657)

crowbar_framework/app/controllers/restricted_controller.rb
The upgrade uses the restricted API to transition nodes from
state "readying" to state "ready" in the course of the
upgrade. Since RestrictedController inherits the update()
method from ApplicationController this is not possible due to
ApplicationController disallowing all POST requests during
API. This commit fixes the problem by giving the restricted
controller an update() method of its own which does allow
them.
Setting to WIP for now - currently testing. I will clear the flag once my test cloud has (hopefully) finished upgrading.
=> Allow restricted API access during upgrade

crowbar_framework/Gemfile
we use brakeman during our travis run. It has a dependency
sexp_processor (deep buried). This gem got a new commit[1] which is not
compatible with brakeman.
The best case would be to fix brakeman and backport it to v2.6.3 (also
pinned) which had a last commit in 2014.  So pinning the dependency is
the easier fix
1 - https://github.com/seattlerb/sexp_processor/commit/ce284487f057203360c41b14d2b25f8c5453fbb9
=> travis: pin sexp_processor to 4.12.0

chef/data_bags/crowbar/migrate/crowbar/303_add_sync_mark.rb, chef/data_bags/crowbar/template-crowbar.json, chef/data_bags/crowbar/template-crowbar.schema, crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/spec/fixtures/data_bags/template-crowbar.json
sync_mark provider from crowbar-ha is using sync_mark attributes from
crowbar-config databag so they need to be transferred from proposal to
this databag.
=> crowbar: Save sync_mark attributes in databag

chef/data_bags/crowbar/migrate/dns/301_add_rndckey.rb
This commit fixes the Designate migration which added the
Designate related keys to deployment rather than attrs.
Without this, the migration will fail upon upgrade from Cloud 8.
=> dns: fix designate migration

chef/cookbooks/network/recipes/role_network.rb
This change provides the possibilty to lock down the network
configuration of specific nodes. It implemented by simply skipping the
whole network cookbook whe the nodes attribute
'node["network"]["config_frozen"]' is set to 'true'. In that case
anychanges to the network barclamp, or any other change that would cause
the network to be reconfigured (e.g. allocation of IPs, enablement of a
network, addition or removal of network devices, ...) will just have no
effect on that node.
(cherry picked from commit 977e4bf05f693487ed9eee878b72bc35837c4eaa)
=> [5.0 ]Stable 5.0 bsc1120657

chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
Backport of #1852 
(cherry picked from commit 80db03a430713debf395b676564f4446aaf6fc50)
=> [5.0] deployer: Use dhcp on crowbar_register only when enable_pxe is set (bsc#1132654)

chef/cookbooks/barclamp/libraries/nic.rb, chef/cookbooks/network/recipes/default.rb, chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
Neutron is now taking care of setting a unique datapath-id. So we don't
need this anymore. See:
https://review.opendev.org/#/c/587244/
=> network: Don't set datapath-ids on ovs-bridges anymore

crowbar_framework/Gemfile
we use brakeman during our travis run. It has a dependency
sexp_processor (deep buried). This gem got a new commit[1] which is not
compatible with brakeman.
The best case would be to fix brakeman and backport it to v2.6.3 (also
pinned) which had a last commit in 2014.  So pinning the dependency is
the easier fix
1 - https://github.com/seattlerb/sexp_processor/commit/ce284487f057203360c41b14d2b25f8c5453fbb9
(cherry picked from commit d124d31daec406f924422571f3360ca46dbaaf23)
port of #1861
=> [5.0] travis: pin sexp_processor to 4.12.0

crowbar_framework/Gemfile
we use brakeman during our travis run. It has a dependency
sexp_processor (deep buried). This gem got a new commit[1] which is not
compatible with brakeman.
The best case would be to fix brakeman and backport it to v2.6.3 (also
pinned) which had a last commit in 2014.  So pinning the dependency is
the easier fix
1 - https://github.com/seattlerb/sexp_processor/commit/ce284487f057203360c41b14d2b25f8c5453fbb9
(cherry picked from commit d124d31daec406f924422571f3360ca46dbaaf23)
port of #1861
=> [4.0] travis: pin sexp_processor to 4.12.0

crowbar_framework/app/controllers/api/upgrade_controller.rb
Do it also for the cases when subset of compute nodes was selected.
(cherry picked from commit a21566ff56533ff55d8bc3cff9923c0a2e32ac73)
Port of https://github.com/crowbar/crowbar-core/pull/1731
=> upgrade: Mark correctly the set of nodes that was selected for upgrade

chef/data_bags/crowbar/migrate/crowbar/201_add_sync_mark.rb, chef/data_bags/crowbar/template-crowbar.json, chef/data_bags/crowbar/template-crowbar.schema, crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/spec/fixtures/data_bags/template-crowbar.json
sync_mark provider from crowbar-ha is using sync_mark attributes from
crowbar-config databag so they need to be transferred from proposal to
this databag.
(cherry picked from commit 429a51bf11e174901266e898139d06bca916cb39)
port of #1863
=> [5.0] crowbar: Save sync_mark attributes in databag

chef/data_bags/crowbar/migrate/crowbar/105_add_sync_mark.rb, chef/data_bags/crowbar/template-crowbar.json, chef/data_bags/crowbar/template-crowbar.schema, crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/spec/fixtures/data_bags/template-crowbar.json
sync_mark provider from crowbar-ha is using sync_mark attributes from
crowbar-config databag so they need to be transferred from proposal to
this databag.
(cherry picked from commit 429a51bf11e174901266e898139d06bca916cb39)
port of #1863
=> [4.0] crowbar: Save sync_mark attributes in databag

chef/cookbooks/network/libraries/helpers.rb, chef/cookbooks/provisioner/recipes/base.rb
To make it easier to write out IP addresses which may be v6, introduce a
wrap_ip method to NetworkHelper. Make use of it in the provisioner
barclamp when writing out the crowbar rc file.
Co-Authored-By: Matthew Oliver <matt@oliver.net.au>
=> ipv6: Add a wrap_ip helper to NetworkHelper

chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
Backport #1852 
(cherry picked from commit 80db03a430713debf395b676564f4446aaf6fc50)
=> [4.0] deployer: Use dhcp on crowbar_register only when enable_pxe is set (bsc#1132654)

chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-remaining-services.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/crowbar_service.rb
Since clone_stateless_services attribute was dropped in
crowbar-ha/1cf82d3ff3142a700ac0e2c55c20944bf364e868 and implicitly
set to false, we don't need some parts of code which were active
when it was set to true.
=> Cleanup clone_stateless_services leftovers (SOC-9842)

chef/data_bags/crowbar/migrate/dns/103_add_rndckey.rb
(cherry picked from commit 38580808e1b8a4a43ae40a4ec0bcfc7352156db2)
=> [5.0] dns: fix migration for designate

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-monasca-cleanups.sh.erb, crowbar_framework/app/models/api/upgrade.rb
Until Cloud 8 we used the Java based Monasca Persister. As of
Cloud 9 we use the Python based Monasca Persister
implementation. Since the two packages conflict, we need to
uninstall the Java based persister when preparing for the
Cloud 8 to Cloud 9 upgrade.
=> monasca: remove Java persister (SOC-9482)

.travis.yml
CVE-2015-3448 is not fixed in rest-client for a long time. As we are
using custom version of the gem, fixing it would require considerable
effort. Whitelisting it in travis config should unblock the gating runs.
Additional commit changes gitlint parameters for easier backporting.
=> travis: Whitelist CVE-2015-3448 (SOC-9911)

bin/crowbar_batch
In case crowbar batch returns an error correctly format the error when
printing to the console.
=> batch: Format crowbar batch error output

chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
When the `of_interface` neutron configuration value is set to
`native` instead of `ovs_ofctl`, the Neutron OVS agent configures
itself as the controller for all OVS bridges that it manages.
This configuration is persisted, so all bridges will immediately
connect to the configured controller as soon as the Neutron OVS
agent comes up - e.g. after a reboot.
When the admin network is on the same interface as the neutron bridge
for the tenant network (i.e. br-fixed is carrying the admin IP in a
"single" or "team" Crowbar network mode), Crowbar ensures that the
`br-fixed` OVS bridge uses a `standalone` fail-mode on startup, to
allow admin traffic to flow uninterrupted until the neutron OVS agent
starts up and takes control of the bridge. However, with a `native`
`of_interface`, this is no …
=> ovs-pre-up: remove controller for admin bridge (SOC-10073)

chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
(backports #1891)
When the `of_interface` neutron configuration value is set to
`native` instead of `ovs_ofctl`, the Neutron OVS agent configures
itself as the controller for all OVS bridges that it manages.
This configuration is persisted, so all bridges will immediately
connect to the configured controller as soon as the Neutron OVS
agent comes up - e.g. after a reboot.
When the admin network is on the same interface as the neutron bridge
for the tenant network (i.e. br-fixed is carrying the admin IP in a
"single" or "team" Crowbar network mode), Crowbar ensures that the
`br-fixed` OVS bridge uses a `standalone` fail-mode on startup, to
allow admin traffic to flow uninterrupted until the neutron OVS agent
starts up and takes control of the bridge. However, with a `native` …
=> [5.0] ovs-pre-up: remove controller for admin bridge (SOC-10073)

chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
(backports #1891)
When the `of_interface` neutron configuration value is set to
`native` instead of `ovs_ofctl`, the Neutron OVS agent configures
itself as the controller for all OVS bridges that it manages.
This configuration is persisted, so all bridges will immediately
connect to the configured controller as soon as the Neutron OVS
agent comes up - e.g. after a reboot.
When the admin network is on the same interface as the neutron bridge
for the tenant network (i.e. br-fixed is carrying the admin IP in a
"single" or "team" Crowbar network mode), Crowbar ensures that the
`br-fixed` OVS bridge uses a `standalone` fail-mode on startup, to
allow admin traffic to flow uninterrupted until the neutron OVS agent
starts up and takes control of the bridge. However, with a `native` …
=> [4.0] ovs-pre-up: remove controller for admin bridge (SOC-10073)

chef/cookbooks/crowbar/templates/default/crowbar-delete-unknown-nova-services.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb
nova-consoleauth is no longer used in Cloud 9, so we should
be removing the service entries related to it.
=> upgrade: remove nova-consoleauth service entries on upgrade (SOC-10164)

chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb
After upgrading from Pike to Rocky, nova-compute services
are all failing with this error message:
Failed to allocate the network(s), not rescheduling.
which is logged as:
NovaException: In shutdown, no new events can be scheduled
This is actually an oslo.service bug:
https://bugs.launchpad.net/nova/+bug/1715374
which has not been fixed so far. Restart is the workaround
that was pushed upstream.
=> upgrade: restart nova services after upgrade

chef/cookbooks/ohai/recipes/default.rb
Sometimes there is a race condition and ohai didn't collect the ruby
version. to_f evalutes then the version to 0.0 and zypper fails to
install the rubygem `ruby0.0-rubygem-cstruct' not found in package
names`.
=> ohai: Hardcode ruby version for package installation (SOC-10010)

chef/cookbooks/ohai/recipes/default.rb
Sometimes there is a race condition and ohai didn't collect the ruby
version. to_f evalutes then the version to 0.0 and zypper fails to
install the rubygem `ruby0.0-rubygem-cstruct' not found in package
names`.
(cherry picked from commit 72a4f6510cc464a3e5309a25823c6a085502f10c)
=> [5.0] ohai: Hardcode ruby version for package installation (SOC-10010)

chef/cookbooks/ohai/recipes/default.rb
Sometimes there is a race condition and ohai didn't collect the ruby
version. to_f evalutes then the version to 0.0 and zypper fails to
install the rubygem `ruby0.0-rubygem-cstruct' not found in package
names`.
(cherry picked from commit 72a4f6510cc464a3e5309a25823c6a085502f10c)
=> [4.0] ohai: Hardcode ruby version for package installation (SOC-10010)

chef/cookbooks/utils/libraries/helpers.rb
Currently CrowbarHelper.get_host_for_public_url() indiscriminately
return the IP instead of FQDN in the situation where the
node's public_name is not set and SSL is not being used.
This behavior was introduced in
https://github.com/crowbar/barclamp-glance/commit/22d3c190f1edc6f4d278982eb58076acdde16505
to address certain situations where the crowbar generated hostnames are not
resolveable externally. For SSL, we need the FQDN or hostname for
certificate validation. However, for WebSSO, certain identity providers
(i.e. Google) requires FQDN to match the authorized domain, regardless of
whether SSL is used.
In theory, we could change the behavior of get_host_for_public_url() to
always return the FQDN instead of IP as we *should be* supporting
external name resolution by now, but doing so …
=> allow user to ask for FQDN as public hostname (SOC-9616)

.travis.yml
A bunch of PRs in the crowbar-core are blocked due to a travis CI check:
bundle-audit check --ignore ...
This is due to a security embargo that was lifted and blocked by a
version of nokogiri:
Name: nokogiri
Version: 1.9.1
Advisory: CVE-2019-5477
Criticality: Unknown
URL: https://github.com/sparklemotion/nokogiri/issues/1915
Title: Nokogiri Command Injection Vulnerability via Nokogiri::CSS::Tokenizer#load_file
Solution: upgrade to >= 1.10.4
I asked about it in the rocketchat #cloud channel, and apparently Rick
has looked into it and it seems we are unaffected by it as we don't use
the version when building the RPM.
I've also done a quick look through IBS and I can't see nokogiri as a
build requirement for crowbar, crowbar-core or crowbar-openstack. Well
it isn't even mentioned in any of …
=> Add CVE-2019-5477 the to travis ignore list

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Previous search for not-upgraded non-compute nodes was just checking for `crowbar_upgrade` state. In case where crowbar_join wait loop would time out but the script would eventually finish, state would be changed to `ready` but the `node_upgrade_state` would still be `upgrading`. 
Old version was skipping such nodes when retrying the upgrade and they were left in half-upgraded state with no easy way to correct things.
The new version of non-compute nodes lookup follows the pattern present in other parts of upgrade code: find some subset of nodes, then exclude those which are upgraded, then sort to move half-upgraded nodes to front and (re)start the upgrade for this list.
=> upgrade: Re-run upgrade on non-compute nodes (SOC-10072)

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml
Additional prechecks were added to detect problematic scenarios before
upgrade is started. These cover:
- Aodh deployment
- Trove deployment
- "Legacy" Ceilometer (without Monasca) deployment
=> upgrade: Add more prechecks for 8->9 (SOC-9868)

chef/cookbooks/barclamp/libraries/nic.rb, chef/cookbooks/network/recipes/default.rb
This adds some additional checks to the network recipe that should help reducing the risk of creating network loops when interfaces need to be reconfigured. This mainly done by
1. Erroring out when the conduit mapping for the node turns out to be broken in a way the would require putting two interfaces into the same bridge.
2. Properly tearing down existing configurations when the conduit mapping change in a way the would move interfaces from one bridge to anther.
3. Erroring out when the interface mapping for a bond changes in an unexpected manner.
=> network: reduce risk of creating network loops

.travis.yml
A bunch of PRs in the crowbar-core are blocked due to a travis CI check:
bundle-audit check --ignore ...
This is due to a security embargo that was lifted and blocked by a
version of nokogiri:
Name: nokogiri
Version: 1.9.1
Advisory: CVE-2019-5477
Criticality: Unknown
URL: https://github.com/sparklemotion/nokogiri/issues/1915
Title: Nokogiri Command Injection Vulnerability via
Nokogiri::CSS::Tokenizer#load_file
Solution: upgrade to >= 1.10.4
I asked about it in the rocketchat #cloud channel, and apparently Rick
has looked into it and it seems we are unaffected by it as we don't use
the version when building the RPM.
I've also done a quick look through IBS and I can't see nokogiri as a
build requirement for crowbar, crowbar-core or crowbar-openstack. Well
it isn't even mentioned in any of …
=> [5.0] Add CVE-2019-5477 the to travis ignore list (SOC-9635)

.travis.yml
A bunch of PRs in the crowbar-core are blocked due to a travis CI check:
bundle-audit check --ignore ...
This is due to a security embargo that was lifted and blocked by a
version of nokogiri:
Name: nokogiri
Version: 1.9.1
Advisory: CVE-2019-5477
Criticality: Unknown
URL: https://github.com/sparklemotion/nokogiri/issues/1915
Title: Nokogiri Command Injection Vulnerability via
Nokogiri::CSS::Tokenizer#load_file
Solution: upgrade to >= 1.10.4
I asked about it in the rocketchat #cloud channel, and apparently Rick
has looked into it and it seems we are unaffected by it as we don't use
the version when building the RPM.
I've also done a quick look through IBS and I can't see nokogiri as a
build requirement for crowbar, crowbar-core or crowbar-openstack. Well
it isn't even mentioned in any of …
=> [4.0] Add CVE-2019-5477 the to travis ignore list (SOC-9635)

chef/cookbooks/bind9/recipes/default.rb, chef/cookbooks/bind9/templates/default/named.conf.erb, crowbar_framework/app/models/dns_service.rb
When crowbar's DNS is set to intergrate with designate we need the DNS
servers to be listening on the public network so tennent users of
designate can access the zones they create via the API.
If designate integration is enabled, this patch allocates a public ip
for each DNS node. Each node's bind9 is also setup to listen on both the
public and admin ips.
=> Public ips for dns nodes when designate integration is in use (SOC-9635)

chef/cookbooks/network/recipes/role_network.rb
This change provides the possibilty to lock down the network
configuration of specific nodes. It implemented by simply skipping the
whole network cookbook whe the nodes attribute
'node["network"]["config_frozen"]' is set to 'true'. In that case
anychanges to the network barclamp, or any other change that would cause
the network to be reconfigured (e.g. allocation of IPs, enablement of a
network, addition or removal of network devices, ...) will just have no
effect on that node.
stable/4.0 Backport of: https://github.com/crowbar/crowbar-core/pull/1854
=> [4.0] network: Allow locking down the network config for nodes (bsc#1120657)

chef/cookbooks/bind9/recipes/default.rb, chef/cookbooks/bind9/templates/default/named.conf.erb, crowbar_framework/app/models/dns_service.rb
When crowbar's DNS is set to intergrate with designate we need the DNS
servers to be listening on the public network so tennent users of
desigante can access the zones they create via the API.
If designate intergration is enabled, this patch allocates a public ip
for each DNS node. Each node's bind9 is also setup to listen on both the
public and admin ips.
(cherry picked from commit 5e74dc28c98c7b6d2910fd702770ffca2f925ae4)
=> 5.0: Public ips for dns nodes when designate integration is in use (SOC-9635)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-dump-monasca-db.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb, crowbar_framework/app/models/api/upgrade.rb
Up until SUSE OpenStack Cloud 8, Monasca ran its own MariaDB
instance on the monasca-server node which hosted Monasca's
metrics database and Grafana's configuration database. As of
Cloud 9 we use the OpenStack cloud's main MariaDB instance for
both of these, hence we need to create a dump of the the data
from both in order to later migrate them to the main MariaDB
instance.
=> upgrade: dump Monasca, Grafana databases (SOC-9772)

chef/cookbooks/bind9/recipes/default.rb, chef/cookbooks/bind9/templates/default/designate-rndc-access.conf.erb
With designate enabled, all Bind servers act as slaves for
designate created zones. These zones are created via rndc addzone
from designate server(s).
Adding permissions and key for allowing rndc access.
=> Allow designate rndc for all nodes (SOC-10339)

chef/cookbooks/network/libraries/helpers.rb, crowbar_framework/config/application.rb
Barclamp horizon need to handle ipv6. NetworkHelper in chef/cookbooks/network/libraries/helpers.rb has methods that can be used to deal with ipv6 in barclamp horizon. 
We assume the addresses used in barclamp horizon are ip addresses. 
This commit includes:
1) Because the methods in Chef NetworkHelper are not exposed to crowbar_framework, added the path of chef/cookbooks/network/libraries/helpers.rb in crowbar_framework/config/application.rb so they can be called from crowbar_framework. 
2) Added boolean ipv6 method to check if the address is in ipv6 form.
=> IPV6 - Expose methods in chef NetworkHelper to crowbar_framework (SOC-6397)

chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb, crowbar_framework/app/models/api/upgrade.rb
As RPC 4.x support was dropped with https://review.opendev.org/#/c/543580/
Rocky controller can't talk to Pike compute anymore. We need to upgrade
nova compute services before the controllers so that everything is running
on new RPC when we get to live-migrate the VMs during upgrade.
=> upgrade: Upgrade compute services early (SOC-10273)

bin/crowbar_batch
easy_diff got fixed some time ago and can now merge the objects. Let's
switch to this and stop using the chef mixin. Also see
https://www.rubydoc.info/github/opscode/chef/Chef%2FMixin%2FDeepMerge:deep_merge!
as the Chef Mixin could cause some issues.
=> batch: Use easy_merge for merging the json (SOC-10505)

bin/crowbar_batch
easy_diff got fixed some time ago and can now merge the objects. Let's
switch to this and stop using the chef mixin. Also see
https://www.rubydoc.info/github/opscode/chef/Chef/Mixin/DeepMerge
as the Chef Mixin could cause some issues.
(cherry picked from commit 7720e25118c76e1db99e4f43c53b71c78b672990)
=> [5.0] batch: Use easy_merge for merging (SOC-10505)

bin/crowbar_batch
This reverts commit ce564c3000e7d58cca236d7c738f258cf6acf2c5.
=> [5.0] Revert "batch: Use easy_merge for merging (SOC-10505)"

crowbar_framework/vendor/assets/stylesheets/_patches.scss
Updates styles applied to input group buttons so that their height computed correctly.
Before:
After:
=> Update input group to be more specific (SOC-10644)

bin/barclamp_lib.rb
All barclamps use a timeout of 3600 seconds just crowbar batch uses 500
second by default which is way to less. Let's sync the timeouts.
(cherry picked from commit 3bf3efd96044c8967f1f39ba52b089399349b8ee)
=> [5.0] barclamp_lib: Sync timeout with other barclamps (SOC-10513, SOC-10011)

bin/barclamp_lib.rb
All barclamps use a timeout of 3600 seconds just crowbar batch uses 500
second by default which is way to less. Let's sync the timeouts.
(cherry picked from commit 3bf3efd96044c8967f1f39ba52b089399349b8ee)
=> [4.0] barclamp_lib: Sync timeout with other barclamps (SOC-10513, SOC-10011)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb
This reverts commit 5c2fece34bdbd51c1700d883dac955ca7b6ff468.
Specifying block migration explicitly is no longer needed as
of Nova API version 2.25 (Mitaka and newer). From this API
version onward Nova will automatically select the appropriate
migration mode.
Setting "do not merge yet" because we are currently testing this on a QA cloud for both the Cloud 7 -> Cloud 8 and Cloud 8 -> Cloud 9 upgrade. I'll update once that's through.
=> Revert "[upgrade] Use block-migration when needed"

chef/cookbooks/barclamp/libraries/nic.rb, chef/cookbooks/network/recipes/default.rb, chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
Neutron is now taking care of setting a unique datapath-id. So we don't
need this anymore. This was backported to Newton in
-------------------------------------------------------------------
Tue May 28 19:07:45 UTC 2019 - Swaminathan Vasudevan <svasudevan@suse.com>
- Add 0001-Change-duplicate-OVS-bridge-datapath-ids.patch
backport based on https://review.opendev.org/#/c/649192/3
https://review.opendev.org/#/c/587244/
(cherry picked from commit 8de91b09c92e52b77306bd7b0970a37eff4af037)
=> [4.0] network: Don't set datapath-ids on ovs-bridges anymore (bsc#1152916)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb
This reverts commit 5c2fece34bdbd51c1700d883dac955ca7b6ff468.
Specifying block migration explicitly is no longer needed as
of Nova API version 2.25 (Mitaka and newer). From this API
version onward Nova will automatically select the appropriate
migration mode.
(cherry picked from commit f6d4e4d8a0b82b870005434f61ba81e67a4723c3)
This is a backport of https://github.com/crowbar/crowbar-core/pull/1936. It's already tested and works against the Cloud 7 -> Cloud 8 upgrade (see Jira issue for details).
=> Revert "Use block-migration when needed" (SOC-10133)

crowbar_framework/app/models/api/node.rb
Some more enterprisy physical servers take a little bit more time
to reboot than just the 5-6 minutes. Wait at least 10 minutes
to be compatible with those vendors.
=> crowbar: Give more time for reboot for physical hardware reboots

crowbar_framework/app/models/api/node.rb
When /etc/crowbar/repos.yml was modified manually, nodes repochecks
sometimes returned old content which could be confusing.
Forcefully reloading the configs each time the repochecks are run
solves the problem.
=> upgrade: Reload repo config in repochecks (SOC-10718)

.travis.yml
Relevant package (rubygem-haml) is going to be fixed to address the
security issue and this occurence can be ignored is at is only affecting
internal CI.
=> [5.0] Ignore CVE-2017-1002201 in CI builds (bsc#1155089)

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/models/api/crowbar_spec.rb
XEN compute nodes are no longer supported in SOC9 so they need
to be removed before the upgrade from SOC8 to SOC9 starts.
=> [5.0] upgrade: Add a precheck for XEN compute nodes presence (SOC-10495)

crowbar_framework/app/models/api/node.rb
When /etc/crowbar/repos.yml was modified manually, nodes repochecks
sometimes returned old content which could be confusing.
Forcefully reloading the configs each time the repochecks are run
solves the problem.
(cherry picked from commit 69581b06d051659258aa3856c61d5811190290d5)
port of #1943
=> [5.0] upgrade: Reload repo config in repochecks (SOC-10718)

chef/cookbooks/barclamp/libraries/barclamp_library.rb, chef/cookbooks/barclamp/libraries/nic.rb, chef/cookbooks/network/recipes/default.rb, chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb, chef/data_bags/crowbar/template-network.schema
This change allows users to enable BPDU forwarding on OVS bridges
that are used for Neutron provider networks (br-fixed, br-floating).
Enabling it will allow the physical network to detect and stop loops
if these bridges are accidentally misconfigured. It is turned off
by default.
More context in:
https://bugzilla.suse.com/show_bug.cgi?id=1133804
=> Allow enabling bpdu-forwarding on OVS bridges

.travis.yml
Relevant package (rubygem-haml) is going to be fixed to address the
security issue and this occurence can be ignored is at is only affecting
internal CI.
(cherry picked from commit 825f6d14c9cc77f1314d376f199a1f754dfbd2c0)
Port of https://github.com/crowbar/crowbar-core/pull/1947
=> [4.0] Ignore CVE-2017-1002201 in CI builds (bsc#1155089)

crowbar_framework/app/models/api/upgrade.rb
There should be no other upgrade related call after finalize, because
finalize deletes all the upgrade scripts and failure in the next step
would try to re-run (now non-existing) scripts.
Also, update the list of scripts that should be deleted.
=> [upgrade] Call finalize_nodes_upgrade at the very end (bsc#1155942)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-stop-nova-services.sh.erb, configs/upgrade_timeouts.yml, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
In order to prevent any and all RPC API incompatibilities
through lingering nova-compute processes, this commit stops
all Nova services (both on controllers and compute nodes)
after the early nova-compute update performed at the end of
the controller upgrade. Subsequently, these services are
restarted in a staggered manner to keep them from DDoSing
RabbitMQ on larger clouds. This ensures all Nova services use
the new Nova RPC API (5.0), thus allowing the live migrations
that are part of non-disruptively upgrading the compute nodes,
to take place.
=> upgrade: cold start nova before live migration (SOC-10761)

.travis.yml
Our rubygem-nokogiri package is not affected.
=> [5.0] Ignore CVE-2019-13117 in CI builds (bsc#1157028)

configs/upgrade_timeouts.yml, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb
crowbar upgrade tool returns the information about the finished
upgrade for some time even after everything has been done.
For the cases where user would like to continue with the upgrade
to the next product version ASAP, we can make the required time
configurable.
=> [5.0] upgrade: Make the time before next upgrade configurable

chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
It is possible that despite general HA setup, cinder-volume is
running on controllers, is not managed by pacemaker while
clone_stateless_services is still true.
In such scenario we missed this service when trying to stop all of them.
=> [5.0] upgrade: Make sure cinder-volume is really stopped (bsc#1156305)

crowbar_framework/app/models/api/upgrade.rb
There should be no other upgrade related call after finalize, because
finalize deletes all the upgrade scripts and failure in the next step
would try to re-run (now non-existing) scripts.
Also, update the list of scripts that should be deleted.
(cherry picked from commit 7defe527e94a82e4aed68988ffb6edc47deb0ff8)
Backport of https://github.com/crowbar/crowbar-core/pull/1952
=> [5.0] Call finalize_nodes_upgrade at the very end (bsc#1155942)

crowbar_framework/app/models/api/node.rb, crowbar_framework/lib/crowbar/repository.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/node_repocheck_missing.json, crowbar_framework/spec/models/api/node_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Cloud repo should not be necessary to have, so if user does not have it, upgrade checks should not complain.
=> [5.0] Ignore Cloud repository when checking for required ones

crowbar_framework/app/models/api/node.rb, crowbar_framework/lib/crowbar/repository.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/node_repocheck_missing.json, crowbar_framework/spec/models/api/node_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Cloud repository is only needed for initial deployment and
not during the upgrade.
Exclude this repository explicitely during the check for availability.
It might not be the cleanest solution, but is consistent with
feature_repository_map method in repository library.
(cherry picked from commit 4e9eba8dcdcecf06f7296ed2a66d170a9fdc9c2a)
Port of https://github.com/crowbar/crowbar-core/pull/1945
=> upgrade: Ignore Cloud repository during repocheck (bsc#1152007)

chef/cookbooks/crowbar/templates/default/crowbar-migrate-keystone-and-start.sh.erb
The script that migrates keystone and starts the service is
immediatelly followed by another script that enables network agents.
However such action might fail if keystone is still not available,
so let's add a wait loop that checks the service status.
(cherry picked from commit ac17ac7517205592d97e09eac6dd40282adba395)
=> [5.0] Wait for keystone to be ready after start (bsc#1157206)

chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
It is possible that despite general HA setup, cinder-volume is
running on controllers, is not managed by pacemaker while
clone_stateless_services is still true.
In such scenario we missed this service when trying to stop all of them.
(cherry picked from commit bbdbf90d209545dc8bf1fff405e9a184f2c1b351)
Port of https://github.com/crowbar/crowbar-core/pull/1957
=> upgrade: Make sure cinder-volume is really stopped (bsc#1156305)

chef/cookbooks/crowbar/templates/default/crowbar-migrate-keystone-and-start.sh.erb
The script that migrates keystone and starts the service is
immediatelly followed by another script that enables network agents.
However such action might fail if keystone is still not available,
so let's add a wait loop that checks the service status.
=> [upgrade] Wait for keystone to be ready after start (bsc#1157206)

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
If such dir exists, it would contain indications of upgrade scripts' runs
from previous upgrade.
If they'd stay, script wouldn't be executed in current upgrade.
=> [5.0] Remove existing upgrade directories from nodes (SOC-10956)

.travis.yml
Our rubygem-nokogiri package is not affected.
(cherry picked from commit c7214f08272471ce5428e61d578942ae25c2e1cc)
=> Ignore CVE-2019-13117 in CI builds (bsc#1157028)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-prepare-repositories.sh.erb
When nodes are installed from SMT, they can have some automatic repo
services configured. These conflict with crowbar repo management and
should be disabled during upgrade (or earlier).
In addition this change disables configuration of install media repo
as it is not needed for upgraded nodes (just for new ones).
=> [5.0] Disable automatic repo services and installation repo (bsc#1152007)

crowbar_framework/app/models/api/crowbar.rb
This commit allows clouds with Pacemaker remote nodes to be
upgraded. To this end it changes the upgrade precheck to
include remote nodes in the list of valid elements.
Please do not merge this, yet. We can only merge it once all other changes required for SOC-10133 have landed and we have verified the upgrade works.
=> [4.0] Allow pacemaker remotes for upgrade (SOC-10133)

crowbar_framework/app/models/api/upgrade.rb
The error message output when a cloud fails the upgrade
precheck was missing the :nodes parameter, leading to an
uninformative error message that didn't list the affected
nodes. This commit fixes the problem.
Note: this is only needed for Cloud 8 since the upgrade to Cloud 9 won't allow any Xen based compute nodes through.
=> List XEN nodes when failing precheck (trivial)

crowbar_framework/app/models/api/upgrade.rb
In normal mode, all compute nodes are full upgraded in parallel
and rebooted after that. So we do not need to specifically stop
and reload nova services because that's done after the reboot automatically.
=> upgrade: Do not stop and reload nova services in normal mode (SOC-10995)

crowbar_framework/app/models/crowbar_service.rb
DRBD support was dropped in SOC8, so SOC9 code does not need to handle
any related setup.
=> upgrade: Remove DRBD specific code from the continuation parts 

.travis.yml
The fix for our rubygem-puma package is currently being tested
and should make it into a maintenance update soon. Meanwhile,
we can add this CVE to the ignore list since Travis consumes
puma-2.16.0 from Ruby Gems which will never have the
backported patch we've got in our package.
=> Ignore CVE-2019-16770

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
DRBD support was dropped in SOC8, so upgrade from this version
does not need to handle it.
=> [5.0] upgrade: Remove DRBD specific code from the upgrade

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Migrations are executed at the end of admin upgrade step and if there was a failure,
there's a big chance services step would fail
(because correct chef templates might not be rendered)
So do the extra check right at the start of services step. Not during
admin upgrade step, beacuse that one is not repeatable after the packages installations.
=> Make sure the crowbar migrations are OK

chef/cookbooks/crowbar/templates/default/crowbar-dump-monasca-db.sh.erb
The upgrade script for dumping the Monasca database was
missing the actual `exit` in its exitok() function. This
commit adds it.
=> upgrade: add missing exit to Monasca DB dump (trivial)

chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb
Compute services are upgraded early and problems which were not detected
at that point can pop up again later when it is harder to correct them.
After this change, pre-upgrade script will fail if nova-compute packages
fail to upgrade correctly.
This happened in test scenarios where new packages were coming from
a different (test) vendor and "allow vendor change" was not enabled.
In real life cases such failures could be caused by e.g. repo problems.
=> upgrade: Stop if nova-compute upgrade fails (SOC-10378)

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
If some packages are incorrectly upgaded during admin server upgrade,
it could blow to our faces later. Better to make some explicit check
if things went well when it's still time and check for the installed
SLES product version.
It is not necessary to check for Cloud product version because another
check for the state of crowbar migrations should cover it.
Do the extra check right at the start of services step. Not during
admin upgrade step, beacuse that one is not repeatable after the reboot.
=> upgrade: Make a check for SLES product version (SOC-3089)

chef/cookbooks/bind9/recipes/default.rb
After commit f7f7ec71acb632e353cf64a2c87654290b8292d7 DNS entries with
network names in names use '-' instead of '.'. During upgrade the DNS
server hosted on the admin node is upgraded first and no longer resolves
old names with '.' in them. Old entries are still used in service
endpoints until the nodes are upgraded and endpoints are updated.
related to #1274
=> bind9: Add legacy public.foo DNS entries (SOC-11006)

.travis.yml
The fix for our rubygem-puma package is currently being tested
and should make it into a maintenance update soon. Meanwhile,
we can add this CVE to the ignore list since Travis consumes
puma-2.16.0 from Ruby Gems which will never have the
backported patch we've got in our package.
(cherry picked from commit a6e4bf5de029a4d76b8995ce56d450e1978d8ef9)
=> Ignore CVE-2019-16770 (SOC-10999)

crowbar_framework/app/models/node.rb
The crowbar ui is currently going down when there is a node whithout
provisioner proposal:
FATAL -- NoMethodError (undefined method `[]' for nil:NilClass):
app/models/node.rb:319:in `state'
app/models/node.rb:285:in `status'
app/controllers/nodes_controller.rb:606:in `block in get_nodes_and_groups'
app/controllers/nodes_controller.rb:604:in `each'
app/controllers/nodes_controller.rb:604:in `get_nodes_and_groups'
app/controllers/nodes_controller.rb:59:in `index'
(cherry picked from commit 6bfcd95130c1b229a2fb01192857df4cc1c8cf91)
port of https://github.com/crowbar/crowbar-core/pull/1733
=> [5.0] crowbar: avoid nil crash when provisioner attributes are not set

crowbar_framework/app/models/node.rb
The crowbar ui is currently going down when there is a node whithout
provisioner proposal:
FATAL -- NoMethodError (undefined method `[]' for nil:NilClass):
app/models/node.rb:319:in `state'
app/models/node.rb:285:in `status'
app/controllers/nodes_controller.rb:606:in `block in get_nodes_and_groups'
app/controllers/nodes_controller.rb:604:in `each'
app/controllers/nodes_controller.rb:604:in `get_nodes_and_groups'
app/controllers/nodes_controller.rb:59:in `index'
(cherry picked from commit 6bfcd95130c1b229a2fb01192857df4cc1c8cf91)
(cherry picked from commit 1b5ca4cf43b0d3ed58f9140ec6160fdc2e63688a)
Port of https://github.com/crowbar/crowbar-core/pull/1989
=> [4.0] Avoid nil crash when provisioner attributes are not set (bsc#1160048)

chef/cookbooks/apache2/recipes/mod_ssl.rb
When SSL flag is enabled in apache's sysconfig file it is translated
into a -DSSL command argument that will be used the next time apache
is (re)started. When apache is reloaded, it is just signaled with
SIGUSR1 but not completely restarted.
Without a restart, the main process doesn't get the -DSSL option and
this causes all configs with <IfDefine SSL> to be skipped.
Additional restart in the mod_ssl recipe after enabling SSL flag is
required to handle this properly.
=> apache2: Restart after enabling SSL flag (SOC-11029)

chef/cookbooks/crowbar/metadata.json
Without this dependency, barclamp application will fail with a
uninitialized constant Chef::Recipe::CrowbarPacemakerHelper
for any node that does not have other barclamps with this
dependency declaration applied. In practice, this problem only
becomes apparent for nodes that have no roles from crowbar-openstack
applied since all Openstack barclamps declare a dependency on
crowbar-pacemaker.
=> crowbar: add crowbar-pacemaker dependency (SOC-10986)

chef/cookbooks/apache2/recipes/mod_ssl.rb
When SSL flag is enabled in apache's sysconfig file it is translated
into a -DSSL command argument that will be used the next time apache
is (re)started. When apache is reloaded, it is just signaled with
SIGUSR1 but not completely restarted.
Without a restart, the main process doesn't get the -DSSL option and
this causes all configs with <IfDefine SSL> to be skipped.
Additional restart in the mod_ssl recipe after enabling SSL flag is
required to handle this properly.
(cherry picked from commit 592f3acd0da27a7b426d0f6fe5f01b3878a6d2b6)
port of #1986
=> [5.0] apache2: Restart after enabling SSL flag (SOC-11029)

chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb
In some cases we start losing network connectivity to VM's when
all nova-compute services are upgraded and live-migration is being
performed. Upgrading neutron agents on the compute nodes seems to help.
Just a note: this is consistent with the code in 4.0 branch, where we also upgraded nova-compute on all nodes during the upgrade...
=> Upgrade neutron agent together with nova-compute package (SOC-11031)

crowbar_framework/app/models/network_service.rb
The code around actually says "return success".
(cherry picked from commit 989aabab65ad21372e3066546965fafc5b4d06a6)
port of https://github.com/crowbar/crowbar-core/pull/1994
=> [5.0] Do not log an error for a case that is correct (trivial)

chef/data_bags/crowbar/migrate/dns/301_add_rndckey.rb
This commit modifies the Designate migration to check for the
presence of the attributes it adds. Otherwise it would
overwrite these attributes with the values from the JSON data
bag, thus breaking any existing Designate deployments in the
course of the upgrade.
Please do not merge, yet, we need to test it first.
=> dns: add checks to designate migration (SOC-11047)

chef/data_bags/crowbar/migrate/dns/103_add_rndckey.rb
This commit modifies the Designate migration to check for the
presence of the attributes it adds. Otherwise it would
overwrite these attributes with the values from the JSON data
bag, thus breaking any existing Designate deployments in the
course of the upgrade.
(cherry picked from commit 507a39cbdfd3f2a0fe5f8ef738af8793ba0d976f)
=> [5.0] dns: add checks to designate migration (SOC-11047)

chef/cookbooks/network/recipes/default.rb, chef/cookbooks/network/templates/default/openvswitch.service-wickedd.conf.erb
According to the official documentation [1], the OVS services need
to start long before the network (wicked) service, to be able to
interact with the service during boot. However, both OVS and wicked
are multi-service applications and the way that OVS and wicked systemd
service files are being set up, using a `Before=network.service` entry
in the OVS systemd unit file is not enough to guarantee that OVS
services are fully started before wicked services start.
The network.service systemd unit is an alias for wicked.service, which
is just a front-end unit for the multiple wickedd-* services that are
part of the wicked application. These wickedd-* services are also configured
to start `Before=wicked.service`, which means that OVS services and
wicked services usually end up being started in …
=> network: start OVS before wickedd (SOC-11067)

chef/cookbooks/network/recipes/default.rb, chef/cookbooks/network/templates/default/openvswitch.service-wickedd.conf.erb
(backports #2000)
According to the official documentation [1], the OVS services need
to start long before the network (wicked) service, to be able to
interact with the service during boot. However, both OVS and wicked
are multi-service applications and the way that OVS and wicked systemd
service files are being set up, using a `Before=network.service` entry
in the OVS systemd unit file is not enough to guarantee that OVS
services are fully started before wicked services start.
The network.service systemd unit is an alias for wicked.service, which
is just a front-end unit for the multiple wickedd-* services that are
part of the wicked application. These wickedd-* services are also configured
to start `Before=wicked.service`, which means that OVS services and
wicked services usually end up …
=> [5.0] network: start OVS before wickedd (SOC-11067)

chef/cookbooks/network/recipes/default.rb, chef/cookbooks/network/templates/default/openvswitch.service-wickedd.conf.erb
(backports #2000)
According to the official documentation [1], the OVS services need
to start long before the network (wicked) service, to be able to
interact with the service during boot. However, both OVS and wicked
are multi-service applications and the way that OVS and wicked systemd
service files are being set up, using a `Before=network.service` entry
in the OVS systemd unit file is not enough to guarantee that OVS
services are fully started before wicked services start.
The network.service systemd unit is an alias for wicked.service, which
is just a front-end unit for the multiple wickedd-* services that are
part of the wicked application. These wickedd-* services are also configured
to start `Before=wicked.service`, which means that OVS services and
wicked services usually end up …
=> [4.0] network: start OVS before wickedd (SOC-11067)

crowbar_framework/app/assets/stylesheets/content/content.scss, crowbar_framework/app/views/deploy_queue/_elements.html.haml
With big list of nodes, the line breaks between status indicators and
names were confusing as sometimes the LED was at the end of row while
the name was already in next one.
=> Fix deployment queue display (SOC-10741)

crowbar_framework/app/assets/stylesheets/content/content.scss, crowbar_framework/app/views/deploy_queue/_elements.html.haml
With big list of nodes, the line breaks between status indicators and
names were confusing as sometimes the LED was at the end of row while
the name was already in next one.
(cherry picked from commit 38e3799e3d5be9bc169d0202845682064887d38d)
port of #2005
=> [5.0] Fix deployment queue display (SOC-10741)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-dhcp-migration.sh.erb, configs/upgrade_timeouts.yml, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb
DHCP agent handles networks and ports in a way similar to L3 agent's
routers. The assignment of these to the network nodes need to be
properly orchestrated to keep things under control in upgrade scenario
where we need to move network agents out from node before upgrading
to make the process non-disruptive.
pre-req: https://github.com/SUSE-Cloud/cookbook-openstack-network/pull/38
=> upgrade: Run DHCP evacuation (SOC-11046)

.travis.yml
The problem is in nokogiri package. We can ignore it for Travis as
we do not control the package versions it itstalls for CI runs.
=> [5.0] Ignore CVE-2020-7595 in CI

chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb, configs/upgrade_timeouts.yml
Also, no need to ping the migration status every 10 seconds
when the task is gonna take minutes.
=> upgrade: Raise the timeout for nodes evacuation (trivial)

chef/cookbooks/ses/providers/config.rb
When some nova service is deployed to a node where none of the cinder services
are present, we still need to install cinder keys which are used by nova.
=> ses: Use cinder user for nova (SOC-5269)

crowbar_framework/app/views/ses/settings.html.haml
When uploaded yaml file is invalid or contains unrecognized parts the UI
would crash and block user from re-uploading a correct file.
With this change the unrecognized parts will not get translated but UI
would be fully operational.
=> ses: Make SES UI safe for unknown options (trivial)

crowbar_framework/app/models/api/upgrade.rb
At the end of upgrade, remove elements of crowbar-upgrade from
crowbar barclamp. Otherwise if user makes changes to crowbar proposal
(or even just reapplies it for some reason), nodes would be moved
into crowbar-upgrade state again.
=> upgrade: Remove the assignement of crowbar-upgrade role (SOC-11166)

.travis.yml, chef/cookbooks/barclamp/spec/spec_helper.rb
Backport of https://github.com/crowbar/crowbar-core/pull/2019
=> [5.0] Ignore latest CVEs in the CI, update default OS version used by CI

crowbar_framework/app/models/api/upgrade.rb
At the end of upgrade, remove elements of crowbar-upgrade from
crowbar barclamp. Otherwise if user makes changes to crowbar proposal
(or even just reapplies it for some reason), nodes would be moved
into crowbar-upgrade state again.
(cherry picked from commit c164fc1c1dfe3493d755f2597bac1a8939935c18)
port of https://github.com/crowbar/crowbar-core/pull/2016
=> [5.0] upgrade: Remove the assignement of crowbar-upgrade role (SOC-11166)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-lbaas-evacuation.sh.erb
use_crm option is there for the cases when lbaas agents are handled
by pacemaker resources. So the script puts the node into the maintenance
mode for the time it is restarting the agent.
However since SOC8 we do not use pacameker for lbaas agents, so there
is no need for maintenance mode and no need to execute the script with
use_crm option.
=> upgrade: Fixes for neutron-evacuate-lbaasv2-agent execution (SOC-11171)

chef/data_bags/crowbar/template-network.json, crowbar_framework/config/locales/network/en.yml
This change adds a network to `network.json` for configuring a
provider network for Octavia management network traffic.
Signed-off-by: Nicolas Bock <nicolas.bock@suse.com>
=> Add lb-mgmt-net to network.json (SOC-10904)

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-lbaas-evacuation.sh.erb
Backport of https://github.com/crowbar/crowbar-core/pull/2018
=> [5.0] upgrade: Fixes for neutron-evacuate-lbaasv2-agent execution (SOC-11171)

chef/data_bags/crowbar/template-network.json, crowbar_framework/config/locales/network/en.yml
The octavia network.json network is not mandatory (customers
may choose to deploy their own provider network). If we add
it to network.json, the network will always be detected and
used by Octavia.
Instead, we need to document this as an optional network
that customers may choose to add to their deployment.
Side-note: this is also a way of resolving the circular dependency
between Octavia (the consumer of this octavia network) and Neutron
(the provider that needs to configure the octavia network only if the
Octavia barclamp is deployed).
This reverts PR #1998
=> Revert: Add lb-mgmt-net to network.json (SOC-10904) 

chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.sh.erb
This commit temporarily sets zypper's psCheckAccessDeleted
(introduced by bsc#945169) setting to 'no' before package
upgrade on nodes. This check launches an lsof command that may
hang indefinitely to check for running processes using files
that were changed by a package upgrade. In our case, this
check is entirely unneccessary since the nodes will be
rebooted after package upgrade anyway. Hence we can safely
turn it off, thus saving the operator the trouble of killing
these lsof processes manually on each node that experiences
the problem.
=> upgrade: disable zypper process check temporarily (SOC-11203)

chef/cookbooks/barclamp/libraries/barclamp_library.rb, chef/cookbooks/barclamp/libraries/ssh_key_parser.rb, chef/cookbooks/provisioner/recipes/keys.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/lib/crowbar/ssh_key_parser.rb, crowbar_framework/spec/lib/crowbar/ssh_key_parser_spec.rb
backport of #2024 and #1699 (for clean cherry-pick)
=> [5.0] provisioner: Fix ssh key validation (SOC-11126)

.travis.yml
The bugs will be fixed in related packages, but we do not update
them in CI server.
=> Ignore latest ruby-related CVEs in the CI

chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/templates/default/tftp.service.erb
The tftp server is for hosts on the admin network only. But it can be
accessed from outside if the admin network is routable. This patch adds
an iptables rule to prevent access from outside the admin network.
=> provisioner: allow tftp access from admin network only (bsc#1019111)

chef/cookbooks/crowbar/templates/default/crowbar-delete-pacemaker-resources.sh.erb
apache service should not be stopped by usual upgrade scripts,
because we need it so the keystone API can function as long as possible.
Recently we found a corner case where apache is stopped because
it is handled by Pacemaker (setting that is non-default for a long time)
and most of pacemaker resources are stopped and deleted at certain point.
Solution is to exclude apache resource from this deletion command.
=> upgrade: Do not stop pacemaker managed apache service (SOC-11298)

chef/cookbooks/crowbar/templates/default/apache.conf.erb
The `/restricted/` path is missing on the SSL vhost configuration.
(cherry picked from commit 5f7b8c4e685a4e3de497714af6d58aca7dc30fba)
=> crowbar: Also add access to /restricted/ in SSL vhost (SOC-11352)

crowbar_framework/lib/crowbar/state.rb
When restricted API was added, some additional cleanup work was done
around the transition state machine.
One missing transition was from "crowbar_upgrade" to "reboot" which
happens when node is rebooted during upgrade. After that, node will
be in "reboot" state which opens usual transitions to "readying" etc.
**NOTE: backport for SOC7 should be added to the main "restricted API" backport**
=> upgrade: Allow transition from crowbar_upgrade to reboot (trivial)

chef/cookbooks/provisioner/recipes/base.rb
This commit adds a check for the presence of the client_user
attribute in the Crowbar barclamp's data bag. This attribute
will only become available in chef once chef-client has run on
the Crowbar admin node or the Crowbar data bag has been
applied. Until that has happened, the code using it would
error out on all other nodes.
Note that this is _not_ a backport from Cloud 9 since the code for writing crowbarrc has changed considerable between Cloud 8 and Cloud 9. I'll create a separate pull request for Cloud 9 once I've come up with and tested a patch that fits the Cloud 9 code base.
=> provisioner: check for client_user (SOC-11389)

.travis.yml
As suse/12.2 is not available anymore in travis, and chefspec tests have
very limited coverage, it's pretty safe to disable these for SOC7.
=> [4.0] Fix travis for SOC7

crowbar_framework/lib/crowbar/state.rb
When restricted API was added, some additional cleanup work was done
around the transition state machine.
One missing transition was from "crowbar_upgrade" to "reboot" which
happens when node is rebooted during upgrade. After that, node will
be in "reboot" state which opens usual transitions to "readying" etc.
(cherry picked from commit 8abb973639de6ab73956a6e6047191440540dba7)
port of #2038
=> [5.0] upgrade: Allow transition from crowbar_upgrade to reboot (trivial)

chef/cookbooks/ntp/templates/default/ntp.conf.erb
https://bugzilla.suse.com/show_bug.cgi?id=1179161
ntp: Do not use rate-limiting
because that can block `crowbar_join`
Nodes go into `problem` state after a long waiting time.
```
/usr/sbin/crowbar_join@139(sync_time): /usr/sbin/ntpdate -u 10.162.184.10 10.162
.184.82 10.162.184.83
18 Nov 19:52:20 ntpdate[12664]: 10.162.184.10 rate limit response from server.
18 Nov 19:52:27 ntpdate[12664]: 10.162.184.83 rate limit response from server.
18 Nov 19:52:27 ntpdate[12664]: no server suitable for synchronization found
/usr/sbin/crowbar_join@142(sync_time): tries_left=108
/usr/sbin/crowbar_join@143(sync_time): echo_verbose 'Waiting for NTP server(s)
```
=> ntp: Do not use rate-limiting

chef/cookbooks/ntp/templates/default/ntp.conf.erb
because that can block crowbar_join
/usr/sbin/crowbar_join@139(sync_time): /usr/sbin/ntpdate -u 10.162.184.10 10.162
.184.82 10.162.184.83
18 Nov 19:52:20 ntpdate[12664]: 10.162.184.10 rate limit response from server.
18 Nov 19:52:27 ntpdate[12664]: 10.162.184.83 rate limit response from server.
18 Nov 19:52:27 ntpdate[12664]: no server suitable for synchronization found
/usr/sbin/crowbar_join@142(sync_time): tries_left=108
/usr/sbin/crowbar_join@143(sync_time): echo_verbose 'Waiting for NTP server(s)
(cherry picked from commit 27bbc4e216a79b4835bc33879a381f8a51d081cb)
Backport of: https://github.com/crowbar/crowbar-core/pull/2046
=> ntp: Do not use rate-limiting (bsc#1179161)
