crowbar/crowbar-core

chef/cookbooks/provisioner/recipes/base.rb

At the first shutdown or reboot systemd assumes that the crowbar_join
service and the coherently crowbar_notify_shutdown service was never
started. Due to this assumption the service will not stopped at the
first shutdown or reboot.

Start crowbar_notify_shutdown service after register

---

updates/control.sh

Those are hard to get rid of otherwise, and they will
screw up a following autoyast install.

Clean MD Raid markers from partitions when wiping disks (bsc#939684)

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

Solves bug: #816746.
Does not add .conf file in /etc/dhcp3/hosts.d/ for virtual interfaces. So no accumulation of conf files in crowbar node for each VM. Constant interfaces (like bridges, physical interfaces) will continue to hold .conf file in this path.

Do not add conf file entries for virtual interfaces (bsc#816746)

---

bin/crowbar_batch

When using "crowbar_batch build" to apply proposals, allow in
addition to a single yaml file multiple yaml files and input
from stdin. So you can now do things like:
- crowbar_batch export nova|crowbar_batch (stupid but an example)
- crowbar_batch build nova.yaml
- crowbar_batch build snippet1.yaml snippet2.yaml
When providing multiple files, the concatenated text
must still be valid yaml syntax.

crowbar_batch: build input from stdin and files

---

bin/crowbar_batch

2b351ca introduced a nice new sanity check for invalid aliases, but it relies on `ALIAS_REGEXP` and was written before 5849ca5 which dropped the definition of `ALIAS_REGEXP`.  So we need to bring back `ALIAS_REGEXP` to make this check work again.
Supercedes https://github.com/crowbar/crowbar-core/pull/23

batch: reintroduce ALIAS_REGEXP

---

chef/cookbooks/provisioner/templates/default/autoyast.xml.erb

Just testing first solution. What is missing:
- partition_nr ? [EDIT: not needed]
- more details about swap (likely not needed) [EDIT: true, not needed]
- size is just a guess EDIT: 1MB should be enough based on https://en.wikipedia.org/wiki/BIOS_boot_partition
- limit this for big disks only (maybe not needed)
Based on real example: https://bugzilla.suse.com/attachment.cgi?id=646431 . Should fix https://bugzilla.suse.com/show_bug.cgi?id=944467

For large disks, we're gonna need to create BIOS boot partition

---

bin/crowbar_batch

Originally https://github.com/crowbar/barclamp-crowbar/pull/1336

prevent crowbar batch from locking itself and the user out

---

chef/cookbooks/barclamp/libraries/nic.rb
chef/cookbooks/network/attributes/default.rb
chef/cookbooks/network/recipes/default.rb
chef/cookbooks/network/templates/default/suse-cfg.erb
chef/data_bags/crowbar/bc-template-network.json
chef/data_bags/crowbar/bc-template-network.schema
chef/data_bags/crowbar/migrate/network/011_add_ovs_attributes.rb

Initial work for moving the ovs creation for neutron to the network barclamp as an alternative approach to https://github.com/crowbar/crowbar-openstack/pull/3
It's not quite ready yet (but it works already on my test system), but I'd like to get some feedback.
This should allow to make the neutron::common_agent recipe a lot simpler. I am still somewhat undecided on the new proposal attributes. An alternative approach to the new ```add_ovs_brigde``` attribute would be to use the existing ```add_bridge``` flag and add an (optional?) ```bridge_type``` attribute. I am open to suggestion. 
Also it might make sense to create a common base class for ```Nic::OvsBridge``` and ```Nic::Bridge``` in barclamp/libraries/nic.rb since they share some code. 
The related change to the neutron barclamp will …

Let the network barclamp create OVS bridges

---

crowbar_framework/Gemfile

SLE12 SP1 has rspec 3.3 integrated, so we need to switch to it.

Switch to Rspec 3.3

---

chef/cookbooks/provisioner/templates/default/tftp.erb

In the Hyper-V case we use name-remapping for the bootmgr.exe
using the \x expanding to the hexadecimal version of the IP-address.
With IPv6 now being used (even when connecting from a IPv4 addr),
this address and thus the remapped name is different than in Cloud5
and thus did not find our symlinks.

fix windows install by using IPv4 tftp symlinks

---

chef/cookbooks/provisioner/libraries/repositories.rb
chef/data_bags/crowbar/bc-template-provisioner.json
chef/data_bags/crowbar/migrate/provisioner/030_add_sle12sp1.rb
crowbar_framework/app/helpers/form_helper.rb
crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/lib/crowbar/product.rb

Right now, the code change should have no effect, but as soon as the repos for SLES 12 SP1 are available on the admin server, it should enable using it.
Note that this conflicts with https://github.com/crowbar/crowbar-core/pull/18. I'll rebase when that other PR will be merged.

Preparation for SLES12 SP1 support

---

crowbar_framework/lib/crowbar/lock/local_blocking.rb

Use the reader instead of instance variable whenever possible.
cc @aspiers

Minor cleaning in the locking code

---

chef/cookbooks/crowbar/templates/default/apache.conf.erb

[N.B. There could well be a good reason why `ProxyErrorOverride On` was included.  I can't think of any, but if there is, this PR will need some more discussion.]
Sometimes Crowbar returns JSON-formatted errors from the REST API.  One easily reproducible example is to attempt to allocate a node which is already allocated.  This is what should happen:
root@crowbar:~ # crowbar machines -d allocate d52-54-01-77-77-01.c19.cloud.suse.de
[... snipped authentication stuff ...]
DEBUG: (post) hostname: 127.0.0.1:80
DEBUG: (post) request: /crowbar/machines/1.0/allocate/d52-54-01-77-77-01.c19.cloud.suse.de
DEBUG: (post) data: {}
DEBUG: (post) return code: 422
DEBUG: (post) return body: {"error":"Node already allocated"}
Failed to talk to service allocate: Node already allocated (422)
However …

fix error responses from REST API

---

crowbar_framework/app/models/service_object.rb

This will reduce the race window that exists when multiple nodes transition to
"ready" at the same time and trigger the processing for the proposal queue.
This will NOT really fix the underlying issue for the race.
The following actions lead to the possible race:
Preconditions:
- 2 Nodes are allocated at roughly the same time (e.g. using bulk edit)
- While the nodes are being installed proposal for some barclamps are created
and at least two independent are assigned to one of the above nodes. (e.g
database and rabbitmq). The proposals are queued for deployment.
Now:
- Node1 transitions to "ready"
- that triggers processing of the proposal queue
- one of the queued proposals is unqueued
- that causes apply_role to be called
- apply_role tries to lock the node (which takes some time), the …

Fix/workaround node-role revision races

---

crowbar_framework/app/assets/stylesheets/variables.css.scss

This change is based on the SUSE branding branch where we changed the
link color to blue. The blue is nearly the same as the default crowbar
blue and the changes also matches the default crowbar design.

Change global link color

---

chef/cookbooks/provisioner/templates/default/autoyast.xml.erb
chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
updates/control.sh

In case we need to install a SLES 12.0 node (for SES2 :-(), don't
try to install additional software on it.

Only install suse-openstack-cloud-release package on SLES 12.1

---

chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb

https://bugzilla.suse.com/show_bug.cgi?id=949513
we need to set the system time when we start booting.
But according to man sntp it changed meaning of params
```
12-GA:
-s, --settod
Set (step) the time with settimeofday().  This option  must  not
appear  in  combination  with any of the following options: adj-
time.
12-SP1:
-S, --step
OK to 'step' the time with settimeofday(2).
-s, --slew
OK to 'slew' the time with adjtime(2).
```

adjust to new sntp (bnc#949513)

---

chef/cookbooks/provisioner/libraries/repositories.rb

SLE12 nodes can only be used for ceph, and no Cloud repos are available
for them.

provisioner: Fix SLE12 nodes requiring Cloud repositories

---

chef/cookbooks/provisioner/templates/default/autoyast.xml.erb

SLE11 nodes have issues while booting/installation for harddisk size > 2
TB. Create a boot partition of type gpt with embeded mbr to allow using
bigger disks for non-raid type.

Create 'bios_boot' partition for installation (bsc#935283)

---

chef/cookbooks/crowbar/templates/default/apache.conf.erb

When this happens, we have this in the logs:
[proxy_http:error] [pid 2580] (104)Connection reset by peer: [client 127.0.0.1:27917] AH01102: error reading status line from remote server 127.0.0.1:3000
[proxy:error] [pid 2580] [client 127.0.0.1:27917] AH00898: Error reading from remote server returned by /crowbar/glance/1.0/proposals/default
It seems to happen due to a timeout for a connection. In theory, we
could increase the timeout, but it's unclear which value would be
correct. The issue actually probably comes from the fact that mod_proxy
tries to re-use connections for performance reasons. Since the
performance of the crowbar rails app should not be much of an issue,
just disable that.
See also
http://stackoverflow.com/questions/169453/bad-gateway-502-error-with-apache-mod-proxy-and-to …

crowbar: Fix issues with some HTTP requests being broken due to proxy

---

crowbar_framework/lib/crowbar/deployment_queue.rb

It can happen that we end up stuck in the deployment queue because a
proposal stays in the queue can't be applied. It happens, for instance,
if the proposal is not valid (or being applied).
So ignore proposals that can't be committed and that results in 4xx or
5xx errors.

Avoid endlessly looping in the deployment queue in some cases

---

chef/cookbooks/provisioner/files/default/crowbar_join.service
chef/cookbooks/provisioner/files/default/crowbar_notify_shutdown.service

I assume the After dependencies were moved to crowbar_notify_shutdown
to avoid duplication, but it's actually a bit confusing. And
crowbar_notify_shutdown doesn't actually depend on services like
libvirtd or xend.

provisioner: Rework dependencies of crowbar_join/crowbar_notify_shutdown

---

crowbar_framework/config/application.rb

Within https://github.com/crowbar/crowbar-core/pull/45/files#diff-787c000d1f70896054fa797cce1b3556R22 the check for the puma server PID have been messed up. This should fix it.

Fixed pid check for puma server

---

chef/cookbooks/provisioner/recipes/base.rb

This got introduced in https://github.com/crowbar/crowbar-core/pull/53

provisioner: Fix use of wrong attribute to get platform version

---

chef/cookbooks/provisioner/recipes/update_nodes.rb
chef/data_bags/crowbar/migrate/network/020_add_hardware-installing_transition.rb
chef/data_bags/crowbar/template-network.json
crowbar_framework/app/models/deployer_service.rb
crowbar_framework/app/models/network_service.rb

https://bugzilla.suse.com/show_bug.cgi?id=941528
Note for backporting to Cloud5: get_network_by_type needs to return nil if network is not there

Allocate node IP from correct (node) range only after the  node itself was already allocated and not when it is only discovered.

---

chef/cookbooks/provisioner/recipes/setup_base_images.rb

this is now also needed for SLES12-based sleshammer images
https://bugzilla.suse.com/show_bug.cgi?id=927997
(and maybe it can help avoid an observed race where node1 comes up without network and thus cannot be discovered)

add netwait=60 (bsc#927997)

---

chef/cookbooks/provisioner/recipes/dhcp_update.rb
chef/cookbooks/provisioner/recipes/setup_base_images.rb
chef/cookbooks/provisioner/recipes/update_nodes.rb
updates/control_lib.sh

We also use a per-architecture directory for discovery now.
~~Note that this contains https://github.com/crowbar/crowbar-core/pull/83, and gating will fail because sleshammer needs to be updated accordingly.~~
~~Note that this contains https://github.com/crowbar/crowbar-core/pull/81~~

provisioner: Better support for multiple architectures for discovery

---

crowbar_framework/Gemfile
crowbar_framework/spec/controllers/crowbar_controller_spec.rb
crowbar_framework/spec/controllers/deploy_queue_controller_spec.rb
crowbar_framework/spec/controllers/machines_controller_spec.rb
crowbar_framework/spec/controllers/nodes_controller_spec.rb
crowbar_framework/spec/controllers/support_controller_spec.rb
crowbar_framework/spec/lib/remote_node_spec.rb
crowbar_framework/spec/models/chef_object_spec.rb
crowbar_framework/spec/models/crowbar_service_spec.rb
crowbar_framework/spec/models/node_object_spec.rb
crowbar_framework/spec/models/proposal_spec.rb
crowbar_framework/spec/models/service_object_spec.rb
crowbar_framework/spec/spec_helper.rb

Rspec has since version 3.0 a similar features and mocha isn't
maintained properly.

Replace mocha mocks with default rspec mocks

---

chef/cookbooks/provisioner/recipes/setup_base_images.rb
chef/cookbooks/provisioner/templates/default/tftp.service.erb

systemd can do the work for us.
WIP because the tftp service is missing a way to specify the mapping file that we use.

provisioner: Use tftp.service on SLE12 instead of xinetd

---

crowbar_framework/.rspec
crowbar_framework/spec/spec.opts

This change helps to get a better overview which checks are failing and
it's at the same time a kind of documentation.

Update rspec conf to get better output

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

If a node has no ohai data for some reason (getting discovered, but ohai
not running in sleshammer for one reason or another), we don't want the
provisioner-server chef-client to crash. So provide a fallback
architecture for that node.

provisioner: Fix possible crash in cookbook when node has no ohai data

---

chef/cookbooks/provisioner/templates/suse/crowbar_register.erb

crowbar_register tries to auto import the GPG key of the PTF repo, but
that doesn't make sense when the repo is disabled.

provisioner: Totally ignore PTF repo in crowbar_register when disabled

---

chef/cookbooks/provisioner/recipes/setup_base_images.rb
chef/cookbooks/provisioner/recipes/update_nodes.rb
chef/cookbooks/provisioner/templates/default/grub.conf.erb

The current setup happened to work, but only because grub2 was nice
enough to understand "(tftp)/discovery/../../../" as "(tftp)/". Let's
play it a bit safer.

provisioner: Cleanup path to kernel/initrd used in boot files

---

chef/cookbooks/crowbar/files/default/crowbar.service
configs/crowbar.service

Starting crowbar without the apache service makes no sense since we use
the apache proxy to reach the crowbar web UI. This change makes sure
that the service is always started.

Start apache2.service while crowbar.service start

---

chef/cookbooks/provisioner/recipes/setup_base_images.rb

This only worked for very old versions of chef, and is not needed
anymore with the specified actions.

provisioner: Remove outdated running/enabled attribute on service

---

crowbar_framework/config/initializers/checks.rb

We can't run this test before crowbar is installed this means the server
will not start. But after the installation the test is not needed
anymore because it's done by install-chef-suse and can't changed later.

Fix crowbar checks while crowbar is not installed

---

updates/control.sh

During the "hardware-installing" transition a new admin IP Address (from the
"host" ranges) gets allocated to the node. Force a DHCP renewal to change to
the new IP Address directly after the transition. This avoids having the IP
Address changed at a later (unpredictable) time during the remainder of the
sledgehammer phase.

Renew DHCP lease after hardware-installing transtion

---

chef/cookbooks/network/templates/default/suse-cfg.erb

According to the SLES12-SP1 documentation STARTMODE can be "auto" for
OvsBridges as well.
We need the OVS_BRIDGE='yes' and OVS_BRIDGE_PORT_DEVICE_* settings as wicked
will remove the bridge during shutdown and recreate them at boottime. (Which
went unnoticed until recently because of a bug in the openvswitch service
dependencies)

Fix ifcfg template for openvswitch device

---

crowbar_framework/config/repos-cloud.yml
crowbar_framework/config/repos-ses.yml

We could probably just use the product name and version (like `SLE-SERVER/12`), but isn't this bit more readable? 
(But I'm fine with any way)

Added partial path to location at SMT server

---

chef/cookbooks/provisioner/recipes/setup_base_images.rb

ifcfg and netwait are not used when booting in standard SLES (no
linuxrc), so they have no effect. Let's drop them.
Instead, these bits have been put in the sleshammer image.
See discussion in https://bugzilla.suse.com/show_bug.cgi?id=953107

provisioner: Remove useless bits from kernel boot line for sledgehammer

---

crowbar_framework/config/repos-cloud.yml

We didn't have the right URL for the official build...

Fix repotag that is used for checking Cloud 6 media

---

crowbar_framework/lib/crowbar/repository.rb

If a repo doesn't exist but is mirrored by the local SMT, automatically
create a symlink to it.

webui: Automatically create symlinks to SMT repositories

---

crowbar_framework/Gemfile
crowbar_framework/config/boot.rb

This should allow us to use the SLE12 packages.

Downgrade versions for a few rubygems we depend on

---

crowbar_framework/lib/tasks/database.rake

To reset the database to a proper state where we can keep the session
information working I have written a custom rake task within the db
namespace. It is in purpose undocumented (no task description) to
prevent a manual execution.

Added undocumented db:cleanup rake task

---

chef/data_bags/crowbar/template-provisioner.json

We need this entry so that the crowbar_register.sh scripts
get generated properly.

Add suse-12.1/s390x

---

crowbar_framework/app/assets/javascripts/application.js
crowbar_framework/app/assets/stylesheets/application.scss
crowbar_framework/app/helpers/application_helper.rb
crowbar_framework/public/403.html
crowbar_framework/public/404.html
crowbar_framework/public/422.html
crowbar_framework/public/500.html

This is an issue when compiling the assets as this means that we can't
simply replace the compiled branding bits, but we have to re-compile the
application assets.
cc @tboerger

webui: Do not have branding js/css compiled in application js/css

---

chef/data_bags/crowbar/template-provisioner.json
crowbar_framework/app/models/crowbar_service.rb
updates/control.sh

This change only makes it possible to enable Leap when allocating a
node (assuming that the install media is available), but several other
changes are needed to have working Leap support.

Minimal work to enable Leap nodes

---

chef/cookbooks/provisioner/templates/default/autoyast.xml.erb
chef/cookbooks/provisioner/templates/suse/crowbar_register.erb

An alternative is to remove the systemd-logger in the cookbook. But this
way seems cleaner (for now).

logging: Prefer rsyslog to systemd-logger on Leap

---

crowbar_framework/lib/crowbar/product.rb

This is suitable only for SES 2.1+

Set SES platform to suse-12.1

---

chef/cookbooks/provisioner/libraries/repositories.rb
chef/cookbooks/provisioner/recipes/base.rb
chef/cookbooks/provisioner/templates/default/autoyast.xml.erb
chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
crowbar_framework/lib/crowbar/repository.rb

This is needed for Leap, where we want to prefer packages from
Cloud:OpenStack:* to the ones from the main Leap repo.

Allow defining a priority for each repo

---

crowbar_framework/config/boot.rb

Assuming that rubygems follow semantic versioning guidelines,
we want to lock on patch level releases. It seems useful to me
to be consistent with the versioning in the Gemfile and this
part of crowbar to ensure that production and dev environments
always have exactly the same rubygem dependency restrictions.
Rebase of https://github.com/crowbar/barclamp-crowbar/pull/1324

Sync config/boot.rb version specifications with Gemfile requirements

---

chef/cookbooks/network/templates/default/suse-cfg.erb

Should be "static" (with no IP Address) for OVS slaves.

Only use bootproto "none" for bond slaves

---

crowbar_framework/app/controllers/network_controller.rb

As tracked on bsc#951550 the method to disable network interfaces is not
implemented yet. To display a proper error message on the crowbar client
instead of "Internal server error" we will return a proper message now.
https://bugzilla.suse.com/show_bug.cgi?id=951550

Throw proper error on disable interface

---

crowbar_framework/vendor/assets/stylesheets/variables.scss

Color before fix:
Color after fix:
@kwwii Are you fine with this change? I changed the color to the same as before but I don't know if this change was by intention. The Problem was that the trash bin item was not visible.

Fix color of list headings

---

chef/cookbooks/crowbar/files/default/crowbar.service
chef/cookbooks/crowbar/templates/default/sysconfig.crowbar.erb
configs/crowbar.service
crowbar_framework/config/crowbar.env
crowbar_framework/config/puma.rb

We need to raise the workers because deploying a proposal and accessing
the web ui at the same time is not possible. Also we need to raise the
workers instead of threads due to crowbar is not thread safe.
PS: This is the amount of workers which I found out while try and error.

Raise CROWBAR_THREADS to 10 (bsc#952171)

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

Commit bf4e98b removed the cloud_available and storage_available
attributes, which broke the is_ses check when setting up the autoyast
profile for storage-only deploys.

provisioner: fix is_ses check for autoyast profile

---

chef/data_bags/crowbar/template-provisioner.json

This makes it easier to discover the setting when you're looking
for it in the raw mode.

Add root_password_hash to provisioner template

---

crowbar_framework/app/controllers/machines_controller.rb

This pull request is required to be able to display the status and the group of a node within the crowbar client. The pull requests for the client implementation is in progress.

Display more details on machines index

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

https://bugzilla.suse.com/show_bug.cgi?id=962397
The instsys we use with autoyast
downloads some RPMs from HTTP and converts these to squashfs
using mksquashfs. Since that uses multiple cores,
it seems that there sometimes is a race
that produces corrupt filesystems and thus breaks the install.
we only started using more than 1 core recently in
https://github.com/SUSE-Cloud/automation/commit/0ff56c95bbc932f2b89a

workaround random mksquashfs race bsc#962397

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

/var/chef/backup is collected by supportutils and we don't want
to collect megabytes of binary garbage in there.

Skip binary files from backup (bsc#961464)

---

crowbar_framework/app/models/node_object.rb

If two roles have the same priority, there was nothing that was
guaranteeing a fixed order. So sort by priority and then name.
This bug could result in issues for HA clusters where one member of the
cluster runs one role while others are running another role with the
same priority -- triggering timeouts on the sync marks.
cc @aspiers; this should fix https://ci.suse.de/job/openstack-mkcloud/15117/console

crowbar: Fix node runlist sorting to be predictable

---

crowbar_framework/app/controllers/setups_controller.rb
crowbar_framework/app/views/setups/show.html.haml
crowbar_framework/config/routes.rb

So, this is obviously wrong from UI perspective, handling of error from `dump_database` is not correct ... (  but maybe that could be solved in the final UI?)
At least the right calls to API are there..

Add backend calls for 'shutdown of services' step

---

crowbar_framework/app/models/crowbar_service.rb

(we need to reboot the nodes for upgrade, but without changing the state)

Do not allow change to shutdown state from crowbar_upgrade

---

crowbar_framework/app/helpers/backups_helper.rb

This change has the advantage that the user can see the URL before
clicking on it.

Use link_to instead of button_to

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

They don't have an admin IP allocated in that state, so we can't use that for
finding out the correct mac address.

Fix updating the PXE config for discovered nodes

---

crowbar_framework/app/models/node_object.rb

introduced by https://github.com/jsuchome/crowbar-core/commit/03f83fc3744449a51916bd07dcd7c5bfb706657a
We need to make sure that all the Proposal Roles (-config-default) (especially those
of the core barclamps) stay assigned to the nodes during the upgrade process.
Otherwise chef-client on the admin server (e.g. provisioner::update_nodes) will fail.
(This is same as https://github.com/crowbar/barclamp-crowbar/pull/1368 for tex)

Revert runlist reduction for crowbar_upgrade

---

crowbar_framework/lib/crowbar/backup/restore.rb

When restoring a directory we only want the contents of the directory be
restored and not the directory itself, otherwise we get e.g. ".ssh" restored
into ".ssh/.ssh".

Fix restoring directories

---

chef/cookbooks/crowbar/recipes/crowbar-db-dump.rb
crowbar_framework/app/models/crowbar_service.rb

This is currently only used by upgrade process, but potentially could offer solution for other cases when we want to report an error from chef recipe.
(Note that this PR contains 2 different solutions for resetting the error flag of node.)

Pass the specific error message from chef recipe to crowbar rails app

---

chef/cookbooks/resolver/templates/default/dnsmasq.conf.erb

so that a 'host foo localhost' does not hit IPv6 timeout

let dnsmasq also listen on ::1

---

crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/lib/crowbar/upgrade.rb

The nodes (including the admin node) still have the old target_platform set
(e.g. suse-11.3) change that to the new default OS.

Update the target_platform attribute before upgrading the OS

---

chef/cookbooks/ohai/recipes/default.rb

Apparently under some circumstances installation of cstruct fails
(maybe has something to do with invalid repositories being listed)
and then the rest goes berserk. Abort early instead.

Abort if cstruct can not be loaded

---

crowbar_framework/lib/crowbar/installer.rb

The strings were not found in the library used; I assume it's because
the library is not the controller, so doesn't get the magic prefix.

crowbar: Fix strings in installer

---

crowbar_framework/config/database.yml

Write-ahead logging seems to be more efficient, and apparently makes the
following SQLite3::BusyException much less frequent:
```
E, [2016-01-29T09:50:45.167185 #27521] ERROR -- : SQLite3::BusyException: database is locked: begin transaction
F, [2016-01-29T09:50:45.168484 #27521] FATAL -- :
ActiveRecord::StatementInvalid (SQLite3::BusyException: database is locked: begin transaction):
config/initializers/sqlite_transaction_monkey_patch.rb:27:in `block in begin_db_transaction'
config/initializers/sqlite_transaction_monkey_patch.rb:27:in `begin_db_transaction'
```
For more details, see https://www.sqlite.org/wal.html

crowbar: Switch sqlite database to use write-ahead logging

---

chef/cookbooks/crowbar/recipes/crowbar-db-dump.rb
chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
crowbar_framework/app/models/crowbar_service.rb

some upgrade role assigned, so it does not lose its state.

Leave some upgrade related role for nodes in crowbar_upgrade state. 

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

The installer fails because it doesn't recognize the product key, but we
don't need one for Hyper-V.
https://bugzilla.suse.com/show_bug.cgi?id=964250

provisioner: Do not set product key for Hyper-V install (bsc#964250)

---

crowbar_framework/lib/crowbar/upgrade.rb

the regex "bc-" is not exact enough as there could be another
string in the json file, that contains "bc-", e.g. a cinder-backend
password.
make sure to determine the barclamps name and use it to replace
only patterns in the file that have "bc-<bc_name>"

refine ambiguous regex for replacing file content

---

chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb

crowbar_join --setup is needed to enable and start chef-client service

Revert 126377520bf7ff8ab4715e044dbfb3a49e790f45

---

crowbar_framework/app/models/crowbar_service.rb

Set the upgrade step to the poing where no further action is done
even when the upgrade recipes are accidentally executed
So, this is the simple solution (er, workaround) for https://trello.com/c/vfykMmnv/787-upgrade-remove-crowbar-upgrade-roles-before-the-upgrade-of-the-nodes

After DB shutdown, do not allow any more actions with crowbar-upgrade role

---

crowbar_framework/lib/crowbar/checks/network.rb

This doesn't matter too much at the moment, as we don't really depend on
IPv6 anywhere, and it's possible that people would have broken DNS
records or broken network config for IPv6 (doc team just hit that, for
instance).
cc @MaximilianMeister

crowbar: Disable check for interface with IPv6 address for our hostname

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

In some weird cases (deleting a node that is discovering, for instance),
there's no grub file defined.

provisioner: Add back missing safety check when deleting grub file

---

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb

They could be re-created once the barclamps are applied again.
1. Maybe it will not be needed, let's see...
2. Maybe some cibadmin command could do it better: cibadmin -E ?

Delete pacemaker resources after stopping.

---

crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/app/views/nodes/_form.html.haml

This is only respected by the autoyast profile.
Also, disable the select tag if the node is allocated because, well,
it's too late to change in that case.

crowbar: Make "Default Filesystem" option only visible on SUSE platforms

---

crowbar_framework/app/assets/javascripts/application.js
crowbar_framework/app/controllers/backups_controller.rb
crowbar_framework/app/controllers/installer/upgrades_controller.rb
crowbar_framework/app/helpers/backups_helper.rb
crowbar_framework/app/models/backup.rb
crowbar_framework/app/views/installer/index.html.haml
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/lib/crowbar/backup/restore.rb

as the restore now happens in the background (see https://github.com/crowbar/crowbar-core/pull/269), a restore from /utils/backup comes back immediately, which is not really wanted.
btw. if we would have restored in the background here as well, the UI would have to be adapted to show the progress, maybe even create a new view (that we also link to from the installer startpage) to show progress. This is the easy solution now due to the remaining open tasks.

Block the UI when restoring _not_ from upgrade

---

chef/cookbooks/crowbar/recipes/stop-services-before-upgrade.rb

Stopping openvswitch  before upgrade causes the nodes to become unreachable and upgrade gets stuck. This patch helps to avoid it.

Do not stop openvswitch-switch before upgrade

---

chef/cookbooks/crowbar/recipes/stop-services-before-upgrade.rb

On SLE12 rabbitmq startup and shutdown logs will be created by the user
rabbitmq. Adjust ownership after shutdown so that it can be cleanly started
on SLE12.

Adapt ownership of rabbitmq logs before upgrade

---

crowbar_framework/lib/crowbar/backup/restore.rb

during testing an exported repo (ptf.json) was treated as a proposal
so just save repos
not sure if there is a better way to determine repos (without having to look into the file)

restore: don't treat repos as proposals

---

chef/cookbooks/crowbar/recipes/stop-services-before-upgrade.rb

Otherwise Horizon doesn't come up cleanly when re-applying barclamps.

Stop apache before upgrading the nodes

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

I've seen that several times, but each time I didn't have time to debug
and this change was "good enough". It's still somehow correct because if
you read the code path that sets the interface list, it can be nil when
a conduit cannot be resolved, for instance.
Of course, now that I'm trying to reproduce, I'm not able to...
cc @rhafer

provisioner: Fix chef crash on admin server when forgetting nodes

---

crowbar_framework/app/controllers/network_controller.rb

The list of known status was outdated in the network controller.
https://bugzilla.suse.com/show_bug.cgi?id=966051

crowbar: Fix network switch view being broken (bsc#966051)

---

crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/lib/crowbar/backup/restore.rb

also the SQLite3Exception came from the migrator, not the initializer
add some more error handling in case the database initializer fails

run migrations before initializing the database (and afterwards)

---

crowbar_framework/lib/crowbar/backup/restore.rb

Otherwise it's not possible to restore mulitple proposals of barclamps that
allow multiple instances (e.g. pacemaker)

On restore check for existing proposals with by name

---

crowbar_framework/app/controllers/logging_controller.rb
crowbar_framework/app/models/backup.rb

It was failing when the name of the archive had a space, and... it was
allowing command injection.

crowbar: Fix system() call when creating backup

---

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb

We might need to reapply the recipe (after some error)
and cibadmin call fails if we stopped openais already.

Call cibadmin only if openais is still running

---

crowbar_framework/app/controllers/installer/upgrades_controller.rb

https://bugzilla.suse.com/show_bug.cgi?id=966461

Fix translation missing: en.installer.upgrades.nodes.failed (bsc#966461)

---

chef/cookbooks/crowbar/recipes/stop-services-before-upgrade.rb

The config file doesn't work with apache 2.4 anymore and cause
the service to fail to start when reapplying the horzion barclamp.

Remove the vhost config file of nova dashboard before upgrade

---

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb

`/etc/init.d/openais status` if is `stop`, will return `7` (error), and will be propagated.

crowbar-upgrade: avoid propagation of error status

---

crowbar_framework/app/views/installer/index.html.haml

This just doesn't work, let's fix it later.

crowbar: Remove from Backup link from installer

---

chef/cookbooks/bind9/recipes/default.rb

install-suse-cloud was failing
when nscd was not installed or not running.
And since there is nothing needing it,
we make this part optional
note: also affects Cloud5, so needs backport.

dont require nscd

---

chef/cookbooks/bind9/recipes/default.rb
chef/cookbooks/provisioner/recipes/update_nodes.rb

It seems there's a bug somewhere that can cause a node to not have ohai data. And this can result in breaking the chef run on the admin server, which is really bad.
So protect against this.

Protect admin server against discovered nodes with missing ohai data

---

bin/crowbar_batch

We were looking for quotes around the alias, while when we expand the
alias, we don't require quotes. This means that batch files not using
quotes (which is valid) for aliases will raise an exception like
/opt/dell/bin/barclamp_lib.rb:532:in `eval': (<unknown>): found character that cannot start any token while scanning for the next token at line 20 column 9 (Psych::SyntaxError)

batch: Fix looking for unknown aliases

---

updates/control.sh

Attempt to https://bugzilla.suse.com/show_bug.cgi?id=943623
This seems to help when installing over previous RAID disks.

Ensure SW RAID is stopped and device signatures really wiped out.

---

chef/cookbooks/provisioner/recipes/dhcp_update.rb

This way, we don't rely on dhcpd guessing the right IP address to use,
which might be wrong in case multiple addresses are set on the
interface.
https://bugzilla.suse.com/show_bug.cgi?id=967489

provisioner: Force server-identifier option for dhcp subnet (bsc#967489)

---

crowbar_framework/app/models/deployer_service.rb

When a node enters discovering state, there's no reason for it to be
able to re-use an old client for chef. So destroy any pre-existing one.
https://bugzilla.suse.com/show_bug.cgi?id=967100

crowbar: Delete client for node when node is in discovering (bsc#967100)

---

chef/cookbooks/network/recipes/default.rb

We need to duplicate the mash because we're changing an attribute of the
variable we set to this mash -- which means, when there's no dup, that
we change the mash too.
Here, it's actually really not intended because it means we move from
IP::IP4 objects to strings. Noone noticed because the rest of the code
can live with both, but it's not intended.
Solves part of https://bugzilla.suse.com/show_bug.cgi?id=967489 (but by
luck): the order of the IP addresses for the interface is not a sorted
one, but the order in which networks are defined. It turns out that
admin is defined before bastion, so it works.

network: Don't modify ifs mash when setting node attributes

---

crowbar_framework/lib/crowbar/backup/restore.rb

single_chef_client.sh runs in the background, and though comes back
immediately. It is better to wait here and not go in the background.
The benefit here is that we can be sure that all necessary changes
after restore are applied, and the user can continue to use the cloud
immediately after restore.
This also helps unbreaking our CI where testsetup needs the chef-server
really quickly after restore is done.

restore: call chef-client directly

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

This enables seeing something in the console.

provisioner: Tell yast to use text mode if serial console is used

---

crowbar_framework/app/models/backup.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/db/migrate/20160223200120_change_backup_version_type.rb

We're treating version as a string since 3e3bc1fa33de7f83f77adcd88b8f2a23011bfd0e.

Fix data type for "version" in Backup

---

crowbar_framework/app/models/batch/base.rb

We were looking for quotes around the alias, while when we expand the
alias, we don't require quotes.
This is a followup PR for
https://github.com/crowbar/crowbar-core/pull/349 which solved this issue
for the old CLI tools.

Fix looking for unknown aliases

---

crowbar_framework/app/assets/javascripts/application.js
crowbar_framework/app/helpers/nodes_helper.rb
crowbar_framework/app/helpers/tag_helper.rb
crowbar_framework/vendor/assets/javascripts/jquery/hideShowText.js

I have refactored the hideShowText jQuery plugin to respect serverside
hidden rendered passwords and license keys. With the old code you can
always see the license for a short amount of time. Now the hidden text
gets already rendered on the serverside.

Hide windows licence properly

---

chef/cookbooks/bmc-nat/recipes/client.rb

I think we dont really need these routes anyway
and this breaks chef on windows in the QA clouds
because they use bmc-nat mode

dont run 'ip' on windows

---

crowbar_framework/Gemfile

In order to import activeresource correctly if we include a Gemfile we
need to define the require: active_resource statement to load this gem
properly, without that it will result in an load error with production
environment if a Gemfile is present in the project root.

Fix import of activeresource

---

crowbar_framework/lib/crowbar/backup/restore.rb

at least in the case a thread disappears somehow we would have
logged the name, id, and status of the thread

enhance restore thread logging

---

crowbar_framework/app/assets/javascripts/upgrader.js
crowbar_framework/app/controllers/installer/upgrades_controller.rb
crowbar_framework/app/views/installer/upgrades/restore.html.haml
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/lib/crowbar/backup/restore.rb
crowbar_framework/lib/crowbar/installer.rb

Instead of a `Retrigger restore` button it was discussed and suggested by @kwwii to simply redirect to the start upgrade page and repeat the process after the conflict is resolved.
After the redirect an error message with details how to solve the conflict is displayed.
**DEPENDS ON** https://github.com/crowbar/crowbar-core/pull/361 where the backup is deleted from the filesystem...

Allow subsequent restores after failure during upgrade (bsc#967848)

---

crowbar_framework/app/assets/javascripts/application.js
crowbar_framework/app/helpers/nodes_helper.rb
crowbar_framework/app/helpers/tag_helper.rb
crowbar_framework/vendor/assets/javascripts/jquery/hideShowText.js

I have refactored the hideShowText jQuery plugin to respect serverside
hidden rendered passwords and license keys. With the old code you can
always see the license for a short amount of time. Now the hidden text
gets already rendered on the serverside.
https://bugzilla.suse.com/show_bug.cgi?id=954911
(cherry picked from commit e1a8d4867a737f204f2bf375b6cc605ec59b30f2)

3.0 | Hide windows licence properly (bsc#954911)

---

chef/cookbooks/bmc-nat/recipes/client.rb

I think we dont really need these routes anyway
and this breaks chef on windows in the QA clouds
because they use bmc-nat mode
(backport of #388 )

[3.0] dont run 'ip' on windows

---

crowbar_framework/app/models/backup.rb

- create archive only if the name is valid
- run custom validations only in upload case
- stop validating size and version due to there are anyway set by the
system and otherwise create_archive after validate will not work
(cherry picked from commit abacbe72389ce59deaa93b893a8c852725d8eab6)

3.0 | Creating tar only if the name is valid (bsc#966424)

---

crowbar_framework/Gemfile

In order to import activeresource correctly if we include a Gemfile we
need to define the require: active_resource statement to load this gem
properly, without that it will result in an load error with production
environment if a Gemfile is present in the project root.
(cherry picked from commit 209ac5d1d625716794f59afc4356d6764bef14ed)

[3.0] Fix import of activeresource

---

crowbar_framework/app/models/batch/base.rb

We were looking for quotes around the alias, while when we expand the
alias, we don't require quotes.
This is a followup PR for
https://github.com/crowbar/crowbar-core/pull/349 which solved this issue
for the old CLI tools.
(cherry picked from commit 7d18a8c894e3740f807fc6207341025912a3a7bd)

[3.0] Fix looking for unknown aliases

---

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb

Actually, save it to all nodes in DB cluster, we don't know
which one will be running DB once they are back online.
(cherry picked from commit 7c32deb212ecbf733a48b1c01a1d7a03b6b3e9bf)

[3.0] Save the location that was used for DB dump to node.

---

crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/config/locales/crowbar/en.yml

When a node went offline during upgrade, the process will fail and partially
commited proposal moves nodes to wrong state. Better check if the nodes
are accessible before applying upgrade related actions.
(cherry picked from commit c9d522008937d5ded7baf63d2c6fd48fb1c01dd4)

[3.0] Check if we can ssh to nodes before trying to apply proposal (bsc#968436)

---

chef/cookbooks/bind9/recipes/default.rb
chef/cookbooks/resolver/recipes/default.rb
crowbar_framework/lib/crowbar/backup/restore.rb

Fixing https://bugzilla.suse.com/show_bug.cgi?id=966419 without iptables rules and instead disable and re-enable dnsmasq service letting only the nameserver listen on 127.0.0.1 during restore. An additional state file "disable_dns" is added since the file "restore_steps" waits for completion of chef-client while enabling dns service can be done immediately after the chef-server is running.

Stop dnsmasq to avoid dns queries on admin network during restore and resume later (bsc#966419)

---

chef/cookbooks/bind9/recipes/default.rb
chef/cookbooks/resolver/recipes/default.rb
crowbar_framework/lib/crowbar/backup/restore.rb

Fixing https://bugzilla.suse.com/show_bug.cgi?id=966419 without iptables rules and instead disable and re-enable dnsmasq service letting only the nameserver listen on 127.0.0.1 during restore. An additional state file "disable_dns" is added since the file "restore_steps" waits for completion of chef-client while enabling dns service can be done immediately after the chef-server is running.
Backport from https://github.com/crowbar/crowbar-core/pull/371 on master

[3.0] Stop dnsmasq to avoid dns queries on admin network during restore and resume later (bsc#966419) 

---

crowbar_framework/app/views/nodes/_form.html.haml
crowbar_framework/config/locales/crowbar/en.yml

Workaround fix for https://bugzilla.suse.com/show_bug.cgi?id=845602
Adds notification to user that the shared disks will be wiped during allocate (hardware and OS installation) of a discovered node.
Link to the UI Screenshot with the popup:

Add user notification about wiping attached disks during Allocate Node(bsc#845602)

---

crowbar_framework/app/models/backup.rb
crowbar_framework/config/initializers/tmpdir.rb

as there are files belonging to root in the rails tmp dir they
need to be removed with higher permissions
from the backup/restore CI:
```
Errno::EACCES (Permission denied @ dir_initialize - /opt/dell/crowbar_framework/tmp/create_archive-20160314-14811-fyefs2/crowbar/root/.ssh):
app/models/backup.rb:110:in `cleanup'
app/controllers/backups_controller.rb:58:in `create'
```

backup: cleanup with higher permissions

---

crowbar_framework/app/models/deployer_service.rb
crowbar_framework/app/models/node_object.rb

The following states are never set anywhere:
"burnin-starting", "burnin-finished", "completing", "completed"
~~**Note:** this contains https://github.com/crowbar/crowbar-core/pull/365~~

crowbar: Remove checks for non-existing node states

---

crowbar_framework/app/views/nodes/_form.html.haml
crowbar_framework/config/locales/crowbar/en.yml

Workaround fix for https://bugzilla.suse.com/show_bug.cgi?id=845602
Adds notification to user that the shared disks will be wiped during allocate (hardware and OS installation) of a discovered node.
(cherry picked from commit 3fdc66bbd8ad32a42f6d2a2e7f66040ced87b34f)

[stable/3.0] Backport from #383 (bsc#845602)

---

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
crowbar_framework/app/controllers/installer/upgrades_controller.rb
crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/config/routes.rb

the whole backend part of the prepare step needed to be forward ported
from cloud 5
cc @jsuchome 
this would replace https://github.com/SUSE-Cloud/automation/pull/912

upgrade: add back end part of prepare in cloud 6

---

crowbar_framework/app/models/crowbar_service.rb

it was messed up after style formatting from the original code
see https://github.com/crowbar/barclamp-crowbar/blob/release/tex/master/crowbar_framework/app/models/crowbar_service.rb#L200
```ruby
not_ready_for_upgrade.push n.name if !n.admin? && !%w(ready crowbar_upgrade).include?(n.state)
```

correct the logic

---

.rubocop.yml

This removes the need to specify `-c .hound.ruby.yml` every time you run `rubocop` from the command-line.
Originally suggested in https://github.com/crowbar/crowbar-core/pull/49#issuecomment-143750159
If this gets merged, I can submit the same change for the other repos.

Make rubocop default to same style as HoundCI

---

crowbar_framework/Gemfile

See [schneems/derailed_benchmarks](https://github.com/schneems/derailed_benchmarks) for more information.
This gems helps us the find performance issues in long term it would be also nice to have a basic benchmarking in the gating.

Add development gems for benchmarking

---

crowbar_framework/spec/fixtures/installer_status.json
crowbar_framework/spec/lib/crowbar/installer_spec.rb

(cherry picked from commit 5190529ab16891470263532e7380b80b9cea8b53)
I think it doesn't hurt to backport the specs, if we make some changes it is good to have
#421

[stable/3.0] backport #421

---

crowbar_framework/app/models/service_object.rb

* log message is misleading when node list is empty
* like this it is easier to see where (on which node) chef-client failed

apply_role: log only when needed and at the right place

---

crowbar_framework/app/models/crowbar_service.rb

Fix to upgrade OS only on nodes marked for upgrade through "crowbar_upgrade" state. Other nodes (in "ready" state are not altered).
Fixes bug: https://bugzilla.suse.com/show_bug.cgi?id=972527
Co-authored by @rhafer

Do OS upgrade only for nodes in crowbar_upgrade state (bsc#972527)

---

crowbar_framework/app/models/crowbar_service.rb

https://github.com/crowbar/crowbar-core/pull/451
Fix to upgrade OS only on nodes marked for upgrade through "crowbar_upgrade" state. Other nodes (in "ready" state are not altered).
Fixes bug: https://bugzilla.suse.com/show_bug.cgi?id=972527
Co-authored by @rhafer

[stable/3.0] Backport #451

---

crowbar_framework/lib/crowbar/chef/upload.rb
crowbar_framework/lib/tasks/chef.rake

- move class methods to instance methods (enables lazy loading)
- move from class chef to module chef (fixes usage from rails)
- check cookbook dependencies just once

Performance improvements for chef upload libary

---

chef/cookbooks/barclamp/libraries/barclamp_library.rb

If ohai can't figure out the supported speed(s) of a NIC (e.g. it currently
lacks support for 40G interfaces), treat it as "normal" 1g interfaces.
This is a workaround to make such interface at least somehow usable.
partially fixes: https://bugzilla.suse.com/show_bug.cgi?id=975473

Treat NICs with unknown speed as 1g interfaces (bsc#975473)

---

crowbar_framework/lib/crowbar/backup/export.rb

partial fix of https://bugzilla.suse.com/show_bug.cgi?id=972527
(cherry picked from commit 43230696aeb354116d6b631f5b82ede9be9d133e)
https://github.com/crowbar/crowbar-core/pull/468

[stable/3.0] backport #468

---

crowbar_framework/app/controllers/application_controller.rb

Reverts crowbar/crowbar-core#455
I have encountered some issues during a manual upgrade. I can't upload the backup without running into `ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)`
This needs to be investigated further, as the authenticity token is not stored in the session, but probably in a cookie.
for now it is better to flip the switch back, and create a card for further manual testing debugging

Revert "only skip verify_authenticity_token on json requests"

---

crowbar_framework/app/controllers/installer/upgrades_controller.rb

the backup data always needs to be wiped, e.g. in case of an upgrade
when the first restore failed and the user tries to upload the backup
again there will be an error that the backup already exists, which is
bad

delete old backup when uploading the same one again

---

crowbar_framework/config/repos-cloud.yml

I have no idea what to enter as `key_md5` values...
Reply from @vuntz at irc: "keeping the same values as for SP1 should be fine anyway, as these are the IBS keys and they're the same between SP1 & SP2 (and Cloud 7 & Cloud 7"

Added support for SLES12SP2 repositories

---

chef/cookbooks/crowbar-hacks/recipes/default.rb

Fix bnc#976048
Execute the UEFI boot order configuration inside a ruby_block, to
be sure that Ohai provides all the information during the compilation
stage.
(cherry picked from commit 4a86b66)
(cherry picked from commit 99f9888)

crowbar-hack: be sure that UEFI is there.

---

crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/config/locales/crowbar/en.yml

The upgrade process will fail if the admin node does not have the
dns_server role applied. Abort upgrade with a warning, if this is
not the case. See also
https://bugzilla.suse.com/show_bug.cgi?id=978060
(cherry picked from commit 3e9955ff99ed4bc2be38b89c16d28ce3145402ad)

Test if admin node has dns_server role for upgrade

---

crowbar_framework/config/repos-cloud.yml

This is needed so we can still install SP1 nodes when cloud
was installed with primary SP2 support.
We need this temporary, when we allow SP2 and SP1 Cloud nodes.
Later, SP1 Cloud repos could be deleted completely, because
we will need SP1 nodes only for Storage. For that, we'll have https://github.com/crowbar/crowbar-core/pull/488

Make Cloud7 SP1 repos optional

---

crowbar_framework/app/assets/javascripts/upgrader.js
crowbar_framework/app/controllers/installer/upgrades_controller.rb
crowbar_framework/app/helpers/nodes_helper.rb
crowbar_framework/app/views/installer/upgrades/finishing.html.haml

after the upgrade of the nodes has finished, the nodes are still
in boot process.
A quick upgrader who switches to the barclamps view right after
the "Go to your Barclamps now" button is available and applies
keystone will get a flash message saying:
"Role keystone-server can't be used for suse"
I am not sure if that really helps though, maybe even another check is necessary here to be really sure we can hit the apply button. this was just my initial idea to query the node status. any ideas?

wait for the nodes to be really available

---

crowbar_framework/app/models/network_service.rb
crowbar_framework/lib/crowbar/chef/upload.rb
crowbar_framework/spec/lib/crowbar/chef/upload_spec.rb

We should not need them: the templates are only ever used when creating
proposals, and the rails app has direct access to the json file.
This should go with https://github.com/crowbar/crowbar/pull/2230

crowbar: Stop uploading proposal templates as chef data bags

---

chef/cookbooks/network/attributes/default.rb

Supposedly it should work well directly with SP2 kernel. See also https://build.suse.de/package/view_file/SUSE:SLE-12-SP2:GA/openvswitch/openvswitch.changes?expand=1

Do not install openvswitch-kmp-default package for SLES12SP2

---

chef/cookbooks/barclamp/libraries/nic.rb

It could potentially lead to the infinite loop
This is technically not needed when we have https://github.com/crowbar/crowbar-core/pull/525, but might still have a logical sense, as the function already suggests it should not be used for other kind of interfaces

barclamp: Do not generate parents list for non-vlan ifaces

---

crowbar_framework/app/views/nodes/list.html.haml

We were not referring to the right name for the tag, and therefore the
license key was always visible.

crowbar: Fix visibility of license key input in bulk edit

---

crowbar_framework/lib/schema_migration.rb
crowbar_framework/lib/tasks/crowbar.rake

To get an overview about the current migration status for the different
proposals, add a new rake task called "schema_migrate_status".
Calling the task with
RAILS_ENV=production rake crowbar:schema_migrate_status
gives a list with the template name, the latest possible revision and a list
of proposals with the currently applied revision. It looks like:
```
*barclamp*           *latest revision*    *proposals revision*
nova                 101                  default:101
keystone             35                   default:35
rabbitmq             11                   default:11
neutron              48                   default:48
```

crowbar: Add rake task "schema_migrate_status" for migration overview

---

crowbar_framework/app/models/service_object.rb
crowbar_framework/app/models/updater_service.rb

This was a horrible workaround for various bugs, mostly in the cookbooks. This shouldn't be needed anymore -- if it still is, then we should fix the real bugs.
Also, for the admin server: This was done in the days where chef had no locking to avoid concurrent runs, since the admin server had some other chef runs started by crowbar (on transitions, for instance). This has been fixed since a long time now, so there's no reason to continue this.

crowbar: Stop running chef a second time on apply if things failed, and in a different way for admin server

---

crowbar_framework/app/controllers/barclamp_controller.rb

```
F, [2016-07-02T10:02:04.196340 #5021:0x000000061d6f90] FATAL -- Failed to iterate over proposal list due to 'undefined method `barclamp' for nil:NilClass'
/opt/dell/crowbar_framework/app/controllers/barclamp_controller.rb:793:in `block in proposal_status'
/opt/dell/crowbar_framework/app/controllers/barclamp_controller.rb:792:in `each'
/opt/dell/crowbar_framework/app/controllers/barclamp_controller.rb:792:in `proposal_status'
```

crowbar: Fix error when trying to get status of non-existing proposal

---

chef/cookbooks/resolver/recipes/default.rb
chef/data_bags/crowbar/migrate/dns/100_dns_client_states.rb
chef/data_bags/crowbar/template-dns.json

This is like nearly all other roles.
The change only really impacts the discovery image, but it turns out
that with the discovery image, we use DHCP, so we get the DNS info from
DHCP in that case.
To be super safe, we should merge https://github.com/crowbar/crowbar-core/pull/529 first, but I doubt it matters in reality.

dns: Run dns-client role only in readying/ready/applying states

---

crowbar_framework/app/models/service_object.rb

This is an API change that we need for later cleaning up the bootstrap
process.
Context: https://github.com/crowbar/crowbar-core/pull/516

crowbar: Add unused bootstrap parameter to ServiceObject.active_update

---

crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/app/models/deployer_service.rb
crowbar_framework/app/models/node_object.rb
crowbar_framework/app/models/service_object.rb

Whether a role should be handled as part of a chef run will now be
decided in the role recipes.
The benefit of this is that the roles will always be assigned to the
node, even if the roles are not used due to the state. This fixes
several issues, including the fact that the search results for nodes are
not reliable when a node is in some state that is not "readying",
"applying" or "ready".
Depends on ~~https://github.com/crowbar/crowbar-core/pull/514, https://github.com/crowbar/crowbar-ha/pull/121, https://github.com/crowbar/crowbar-ceph/pull/56, https://github.com/crowbar/crowbar-openstack/pull/419~~

crowbar: Stop rebuilding node run_list depending on the node state

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

When a node is discovered, but not allocated, it is not assigned an IP
address in the admin network yet. Due to the dhcp template interpreting
"no IP" as "deny booting", this resulted in reboot of discovered nodes
blocking the nodes.
Now in such cases, we simply take the current IP address of the node.
https://bugzilla.suse.com/show_bug.cgi?id=988021
(cherry picked from commit 7711b4c63e1428bf8faeee5179da62878ebded1a)

provisioner: Fix reboot of discovered node (bsc#988021)

---

chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb

https://github.com/crowbar/crowbar-core/pull/470 is not merged yet, so I opened the backport already to trigger upgrade gating for 5to6

[stable/3.0] backport #470

---

crowbar_framework/lib/crowbar.rb

this hasn't been noticed yet as we are loading all libs in application.rb anyways
@vuntz @aspiers shall we fix it here or shall we drop it completely following up on the discussion on the autoloading?

fix autoload of crowbar libs

---

chef/cookbooks/network/attributes/default.rb

On any other architecture we just use the kernel provided kmp,
so stop trying to install it

Fix openvswitch for non-x86

---

crowbar_framework/app/controllers/nodes_controller.rb

We removed some attributes from the bulk edit page, but the controller
was still using them. This resulted in the bulk edit page resetting the
groups of the nodes.
Bug was introduced in https://github.com/crowbar/crowbar-core/pull/353 /
e4d575e8.
https://bugzilla.suse.com/show_bug.cgi?id=989994

crowbar: Do not use non-existing attributes in bulk edit (bsc#989994)

---

crowbar_framework/app/controllers/barclamp_controller.rb
crowbar_framework/app/models/service_object.rb

There was an attempt to fix the internal API so that
ServiceObject.apply_role always returns [int, str], but this actually
breaks the UI-only path in the controller.
So revert this and document with a FIXME that this should eventually be
fixed by moving everything to [int, hash] where we will have more
freedom.
https://bugzilla.suse.com/show_bug.cgi?id=989958

crowbar: Fix queue message when applying a proposal (bsc#989958)

---

chef/data_bags/crowbar/migrate/ipmi/100_merge_roles.rb
chef/data_bags/crowbar/migrate/provisioner/101_remove_bootdisk_finder.rb
crowbar_framework/lib/crowbar/backup/base.rb
crowbar_framework/lib/crowbar/backup/export.rb
crowbar_framework/lib/crowbar/backup/restore.rb

We do not want to restore roles such as provisioner-base, as the role
should be considered as code and not data, and it might be outdated in
the backup.

crowbar: On restore, only restore roles that are for proposals and nodes

---

chef/cookbooks/provisioner/recipes/base.rb
chef/cookbooks/provisioner/recipes/update_nodes.rb

this is partially related to 
* https://bugzilla.suse.com/show_bug.cgi?id=975384
* https://trello.com/c/1VDjvMFc/1036-bsc-975384-issues-in-crowbar-s-repository-handling
* the upgrade CI (where it fails after the upgrade due to old repos still in the registry)
this extends https://github.com/crowbar/crowbar-core/pull/505 a bit further, which was not the complete fix

exclude cloud 6 repos after upgrade

---

crowbar_framework/app/controllers/nodes_controller.rb

We removed some attributes from the bulk edit page, but the controller
was still using them. This resulted in the bulk edit page resetting the
groups of the nodes.
Bug was introduced in https://github.com/crowbar/crowbar-core/pull/353 /
e4d575e8.
https://bugzilla.suse.com/show_bug.cgi?id=989994
(cherry picked from commit 35b696d263d6d82f6be2dad9494b6a842b5e7587)
Backport of https://github.com/crowbar/crowbar-core/pull/557

[3.0] crowbar: Do not use non-existing attributes in bulk edit (bsc#989994)

---

configs/crowbar-rails.conf.partial
configs/crowbar.conf

when crowbar-init is installed there will be a symlink created in
/etc/apache2/conf.d/crowbar/crowbar.conf which first points to:
https://github.com/crowbar/crowbar-init/blob/master/config/crowbar-sinatra.conf.partial
and once the work from crowbar-init is done this symlink will point to:
https://github.com/MaximilianMeister/crowbar-core/blob/apache/conf-sinatra/configs/crowbar-rails.conf.partial
NOTE:
@rsalevsky is working on the packaging side, and once this is done and tested this PR can be merged

crowbar-init: enable inclusion of sinatra/rails partials

---

crowbar_framework/db/migrate/20160223200120_change_backup_version_type.rb

this can unfortunately not be done in another migration on top as
the PG::DatatypeMismatch error happens already within the migration
but it shouldn't be a problem as it is cloud 7 only
~~NOTE: this can only be merged after the final switch to postgres~~ with the if else this statement is not valid anymore
* https://github.com/crowbar/crowbar-core/pull/571
* https://github.com/crowbar/crowbar-init/pull/16

sqlite2postgres: postgres wants explicit info how to convert/cast

---

crowbar_framework/app/models/deployer_service.rb

We found that sometimes node roles are empty in the hardware-installing
phase. This leads to an error that prevents the nodes to be properly
installed and remain just discovered forever.

Fix when node roles are empty

---

crowbar_framework/app/models/deployer_service.rb
crowbar_framework/app/models/node_object.rb

This function was removed before, but now we are hitting the error that the roles list of a node is sometimes empty during transition to hardware-installing.
UPDATE: this is the error we're trying to fix:
```
D, [2016-08-08T07:02:08.344171 #11272:0x007f248dcd5d08] DEBUG -- Deployer transition: entering: d52-54-77-77-77-05.vc2.cloud.suse.de for hardware-installing
F, [2016-08-08T07:02:08.393637 #11272:0x007f248dcd5d08] FATAL -- json/transition for deployer:default failed: undefined method `[]=' for nil:NilClass
F, [2016-08-08T07:02:08.393966 #11272:0x007f248dcd5d08] FATAL -- /opt/dell/crowbar_framework/app/models/deployer_service.rb:103:in `transition'
...
```
This reverts parts of https://github.com/crowbar/crowbar-core/pull/515. @nicolasbock @MaximilianMeister , you've reviewed original …

Return run_list_to_roles method, to prevent empty roles list.

---

chef/cookbooks/ohai/recipes/default.rb

ohai and crowbars ohai plugins (and crowbar) depend heavily on the
system name and serial number to be always available, so make sure
this is installed all the time. Currently it is only conincidentally
installed on x86 and missing on aarch64.

Always install dmidecode

---

crowbar_framework/config/boot.rb
crowbar_framework/config/routes.rb

This change is required to include modules like crowbar-init into
crowbar without adapting the crowbar source code for this.

Automatically register modules into crowbar

---

crowbar_framework/config/environments/production.rb

this will be used by YamlDB to import the schema.rb and the data.yml
dump into the new postgresql database during the upgrade from 6 to 7

dump schema.rb in production

---

crowbar_framework/config/environments/production.rb

this will be used by YamlDB to import the schema.rb and the data.yml
dump into the new postgresql database during the upgrade from 6 to 7
(cherry picked from commit df655856b06191c807aabdf4d2c5aa12342971fc)

[stable/3.0] dump schema.rb in production

---

chef/cookbooks/bind9/recipes/default.rb

This avoids the warning "named: working directory is not writeable"

Set proper permissions on the bind configuration directory

---

chef/cookbooks/crowbar/files/default/crowbar.service
configs/crowbar.service

Crowbar requires the postgressql.service the be up before the
crowbar service.

systemd: Require postgresql.service

---

crowbar_framework/app/controllers/backups_controller.rb

since we changed from httparty to rest-client, we require a different
parameter structure for file uploads.
to be in line with the update in crowbar-client, and to avoid having
to patch the content section in the client, we adapt the permits on
the server side

[stable/3.0] Change permits to be backwards compatible

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/spec/fixtures/crowbar_object.json
crowbar_framework/spec/fixtures/crowbar_upgrade_status.json
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/models/api/crowbar_spec.rb

this is helpful for the UI to determine which checks to perform during
the upgrade, depending on which addon is installed

list addons in the crowbar object

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/config/routes.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb

by adding another api endpoint to reset the nodes to ready
this function has been used in cloud5 as well

enable canceling the upgrade

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb
crowbar_framework/spec/models/api/crowbar_spec.rb

We need it to be filled by new values after the OS upgrade.
`admin_node["provisioner"]["default_os"]` is used to set the new OS for nodes after the server is upgraded

[stable/3.0] Remove target_platform and default_os valus from admin node

---

crowbar_framework/app/controllers/api/crowbar_controller.rb
crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/config/routes.rb
crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb
crowbar_framework/spec/fixtures/crowbar_repocheck.json
crowbar_framework/spec/fixtures/crowbar_repocheck_zypper.xml
crowbar_framework/spec/fixtures/crowbar_repocheck_zypper_locked.xml
crowbar_framework/spec/models/api/crowbar_spec.rb

this endpoint is to make sure that the cloud and sp2 repos are available
before upgrading the admin server

upgrade: add API for admin repocheck

---

crowbar_framework/app/models/service_object.rb

We move some code that must always be run before returning in the global
ensure; this helps make sure that code is actually run in all cases.
We also catch all exceptions that aren't caught from this method to set
the status of the proposal to "failed", to avoid people being blocked by
a proposal staying forever in "applying".

crowbar: Make apply_role a bit more solid

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/repository.rb

this will be used by ceph and ha to make sure that the system
repositories, alongside the addon repositories are available
and enabled during the upgrade

add helper for node repo target platform and enable failed repolist for repochecks

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/crowbar_spec.rb

Ideally we would like to have a check telling us that it will be
possible to migrate all workloads out from one node.
We can't have such check 100% reliable, so we rather won't do any.
(cherry picked from commit 139fd6904ac582db7d4442a9605e63fb3e2ed72d)
Forward port of https://github.com/crowbar/crowbar-core/pull/623

Search for number of compute nodes.

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/spec/models/api/crowbar_spec.rb

Backports part of https://github.com/crowbar/crowbar-core/pull/641 
- unit tests
- search for xen nodes

[stable/3.0] Check for compute resources

---

chef/cookbooks/barclamp/libraries/barclamp_library.rb
chef/cookbooks/barclamp/libraries/nethelper.rb
chef/cookbooks/bmc-nat/recipes/client.rb
chef/cookbooks/bmc-nat/recipes/router.rb
chef/cookbooks/ipmi/recipes/ipmi-configure.rb
chef/cookbooks/network/recipes/default.rb
chef/cookbooks/network/recipes/switch_config.rb
chef/cookbooks/nfs-server/recipes/default.rb
chef/cookbooks/ntp/recipes/default.rb
chef/cookbooks/provisioner/recipes/setup_base_images.rb
chef/cookbooks/provisioner/recipes/update_nodes.rb
crowbar_framework/app/controllers/network_controller.rb
crowbar_framework/app/controllers/nodes_controller.rb
crowbar_framework/app/models/dns_service.rb
crowbar_framework/app/models/network_service.rb
crowbar_framework/app/models/node_object.rb

This makes dealing with the network config more difficult, as some bits might get outdated.
Instead, we centralize the definitions in the network role, and have proper API for accessing this easily.
This goes with https://github.com/crowbar/crowbar-ha/pull/119, https://github.com/crowbar/crowbar-hyperv/pull/25 and https://github.com/crowbar/crowbar-openstack/pull/415.

Avoid duplicating network definitions in multiple locations

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/spec/fixtures/crowbar_repocheck.json
crowbar_framework/spec/models/api/crowbar_spec.rb

when using the repocheck API for nodes and for crowbar the result
should have the same structure
@vuntz @jsuchome that's just one proposal, the other solution would be to rename one of `/api/crowbar/repocheck` or `/api/upgrade/repocheck` to clear a bit the confusion that the check is performed in a different way. (see https://github.com/crowbar/crowbar-core/pull/644)
I am not sure what is best here, but IMO it is nicer to have `crowbarctl` return the same json structure for the `repocheck` subcommand (see https://github.com/crowbar/crowbar-client/pull/104)

adapt admin repocheck response to the nodes repocheck response

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/routes.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/fixtures/node_repocheck.json
crowbar_framework/spec/fixtures/node_repocheck_missing.json
crowbar_framework/spec/models/api/node_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

integrate the repochecks for nodes, which can be performed for the system repos and the addon repos.
expose an accumulated check through the upgrade API
some code moved from https://github.com/crowbar/crowbar-ceph/pull/68

integrate repocheck for nodes in the upgrade api

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/spec/models/api/crowbar_spec.rb

In master, we have this function under api/cluster (which is not present in 3.0), see https://github.com/crowbar/crowbar-ha/pull/138
But here in 3.0, it probably belongs to the same place where the other checks are (ceph_healthy? etc.)

[stable/3.0] upgrade: Move the cluster health check from crowbar_service

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/spec/fixtures/crowbar_repocheck.json
crowbar_framework/spec/models/api/crowbar_spec.rb

https://github.com/crowbar/crowbar-core/pull/652
adapt repocheck response to the nodes repocheck response
when using the repocheck API for nodes and for crowbar the result
should have the same structure
(cherry picked from commit 76fa8fc113b04aeadc896f409a663c1526bca339)

[stable/3.0] backport #652

---

crowbar_framework/config/repos-cloud.yml
crowbar_framework/config/repos-ses.yml

Note: the repomd piece is commented out, so it won't actually check the
repo properly (this means you can mount early SES4 DVD media instead of
a real repo if necessary).

Switch to SES4 repos

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/lib/crowbar/repository.rb
crowbar_framework/spec/fixtures/node_repocheck_missing.json
crowbar_framework/spec/models/api/node_spec.rb

The _repos prefix only provides already given information. We know that
we are working with repos at this point.
It also makes the output better readable, see: https://github.com/crowbar/crowbar-client/pull/104#issuecomment-246263007

Remove _repos prefix from missing and inactive repos

---

crowbar_framework/app/controllers/installer/upgrades_controller.rb
crowbar_framework/app/models/crowbar_service.rb

New methods do not provide full functional replacement yet.
Let's use the old one until we have new solution ready. 
And yes, I've renamed the old method, because it really was misleading, it was not preparation, but really starting of the upgrade....
I'm bringing this back to enable green gating of upgrade CI job. It partially reverts https://github.com/crowbar/crowbar-core/pull/640/commits/b4e2946cda7e4e5753f294d787b7e5095512a829

Bring back the old nodes upgrade method

---

crowbar_framework/lib/crowbar/product.rb

This is suitable only for SES 4 (and has no impact on SOC deploys
of any version).

Set SES platform to suse-12.2

---

chef/cookbooks/ohai/files/default/plugins/linux/s390x.rb

Since DMI does not exist on mainframe, we need to create
a custom ohai plugin to capture the DMI information that
we need for s390x

Provide a s390x ohai subtree similar to the dmi subtree

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

(cherry picked from commit f63124f35ab561de2f986f0de0fcd95f4d1e0e15)
backport of relavant parts of https://github.com/crowbar/crowbar-core/pull/666

api cleanup: move business logic into the model

---

chef/cookbooks/bind9/recipes/default.rb

it has been readable before (see c955804f) and the current permissions
are breaking backup creation, as crowbar isn't allowed to read from
the directory
https://bugzilla.suse.com/show_bug.cgi?id=997530

set bind directory to be readable by everybody (bsc#997530)

---

crowbar_framework/app/controllers/api/backups_controller.rb
crowbar_framework/app/controllers/api/crowbar_controller.rb
crowbar_framework/app/controllers/api/errors_controller.rb
crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/controllers/barclamp_controller.rb
crowbar_framework/app/controllers/docs_controller.rb
crowbar_framework/app/controllers/installer/installers_controller.rb
crowbar_framework/app/controllers/nodes_controller.rb
crowbar_framework/app/controllers/repositories_controller.rb

add api response examples to the api documentation

---

crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/lib/crowbar/checks/network.rb
crowbar_framework/lib/crowbar/sanity.rb
crowbar_framework/spec/lib/crowbar/checks/network_spec.rb

Commit
https://github.com/crowbar/crowbar-core/commit/73a0ce5ff0cd335c51e0bae2175c2d8c675f97fa
exposed an inconsistency between the firewall rules needed for the bmc-nat
barclamp and crowbar's firewall sanity check. The sanity check is too broad as
it does not tolerate _any_ iptables rule. A more sensible sanity check would
need to parse the firewall rules more intelligently to ensure that the admin
node is accessible and yet allow for rules added by individual barclamps.
In the interest of addressing https://bugzilla.suse.com/show_bug.cgi?id=999637
I am removing the sanity check for now.

bsc#999637: Remove firewall sanity check

---

chef/cookbooks/provisioner/recipes/base.rb

"zypper --non-interactive --xmlout repos $non-existing-repo" of course
doesn't contain the attributes that we were expecting.

provisioner: Fix adding missing repos on nodes

---

chef/cookbooks/ohai/files/default/plugins/linux/crowbar_libvirt.rb

This adds a new attribute node[:crowbar_ohai][:libvirt][:guest_uuid]
which contains the UUID of the libvirt instance that the node is running
in. The purpose is to have a common place for this attribute independent
of the node's architecture (currently x86 ist storing this somewhere in
the "dmi" subtree and s390x in "s390x").

ohai: common ohai attribute for libvirt guest uuid

---

crowbar_framework/Gemfile

We always have to use the old mime-types version in the Gemfile
otherwise bundler is not able to resolve the dependencies.

Always use the old mime-types version in Gemfile

---

crowbar_framework/lib/crowbar/repository.rb

this becomes useful in the upgrade UI during the repochecks
(cherry picked from commit 4819c649a7f3acf99694f1518a110b9994670596)

[stable/3.0] enable collecting a repolist of missing/inactive repos

---

crowbar_framework/app/controllers/api/crowbar_controller.rb

when we check the status of the upgrade, we are trying an implicit
enabling of the repositories in the upgrade case.
at this stage this is just wrong, so we drop this check and
sacrifice the api response to just report status 200 instead of
the upgrade status in the response
(cherry picked from commit 3774a12f95b68e686e41b46bd9d71a851bcd7fa1)

[stable/3.0] don't provoke repository enabling

---

chef/cookbooks/provisioner/templates/default/autoyast.xml.erb

For successful installation of a node that is booted via EFI
we need to create a /boot/efi partition.
(cherry picked from commit d3616e56431d0a392df1d5345ae5093a9c63a2c1)

Fix installation of UEFI nodes

---

crowbar_framework/app/models/api/crowbar.rb

it seems that we haven't adapted the values correctly when doing the
backport

[stable/3.0] fix cloud and sles versions in the admin repocheck

---

crowbar_framework/app/controllers/api/upgrade_controller.rb

as crowbar-init doesn't support apipie there is now now way to nicely
document the endpoints that we have there.
and to not have the documentation in yet another place it might be
better to include it directly in the crowbar api docs.
the downside of that is that the methods don't live in the crowbar
codebase, and therefore need to be faked by adding an empty dummy
method

add api documentation for crowbar-init's upgrade related api

---

crowbar_framework/app/controllers/api/crowbar_controller.rb
crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/lib/crowbar/checks/maintenance.rb
crowbar_framework/lib/crowbar/checks/network.rb
crowbar_framework/lib/crowbar/sanity.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/fixtures/crowbar_maintenance.json
crowbar_framework/spec/fixtures/upgrade_prechecks.json
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/lib/crowbar/checks/maintenance_spec.rb
crowbar_framework/spec/lib/crowbar/checks/network_spec.rb
crowbar_framework/spec/models/api/crowbar_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb
crowbar_framework/spec/spec_helper.rb

we are including specific errors now in the response
example:
```json
{
"checks": {
"network_checks": {
"required": true,
"passed": true,
"errors": {}
},
"maintenance_updates_installed": {
"required": true,
"passed": false,
"errors": {
"maintenance_updates_installed": {
"data": [
"ZYPPER_EXIT_INF_UPDATE_NEEDED: patches available for installation."
],
"help": "make sure maintenance updates are installed"
}
}
},
"clusters_healthy": {
"required": true,
"passed": true,
"errors": {}
},
"compute_resources_available": {
"required": false,
"passed": true,
"errors": {}
},
"ceph_healthy": {
"required": true,
"passed": true,
"errors": {}
}
}
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

adapt the prechecks API

---

crowbar_framework/app/controllers/backups_controller.rb

the backup name parameter in the post request should be wrapped now
in an api_backup hash
to test this, just try to create a backup from the UI (utils/backup and restore) and try to create a new backup with and without this patch

fix/adapt UI part of the backup creation

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/spec/fixtures/crowbar_repocheck.json

Use the same key for Cloud product as with nodes repocheck call.

---

crowbar_framework/app/controllers/api/crowbar_controller.rb
crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/routes.rb
crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/crowbar_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

```perl
/api/crowbar/repocheck -> /api/upgrade/adminrepocheck
/api/upgrade/repocheck -> /api/upgrade/noderepocheck
```
`crowbarctl` PR https://github.com/crowbar/crowbar-client/pull/114
needs a (partial) backport

move and rename repocheck api endpoints

---

crowbar_framework/lib/crowbar/conduit_resolver.rb

This is a forward port of 06ed833ca, which was missed when moving to
conduit_resolver.

conduit_resolver: Handle missing DMI information more graceful

---

crowbar_framework/lib/crowbar/conduit_resolver.rb

The previous code never triggered, as an empty list is true.

Fix handling of devices without speed information

---

crowbar_framework/app/controllers/api/crowbar_controller.rb
crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb

use the same format as we have in the prechecks, as this was already discussed as the best format
```ruby
code: {
data: ... whatever data type ...,
help: String # "this is how you might fix the error"
}
```

adapt api error responses for consistency

---

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb

While executing "services" step, we're touching every node. This is a good time to set the pacemaker pre-upgrade attribute

Set the pre-upgrade pacemaker attribute for all nodes

---

crowbar_framework/app/controllers/api/crowbar_controller.rb

when we check the status of the upgrade, we are trying an implicit
enabling of the repositories in the upgrade case.
at this stage this is just wrong, so we drop this check and
sacrifice the api response to just report status 200 instead of
the upgrade status in the response
(this needs a backport)

don't provoke repository enabling

---

chef/cookbooks/barclamp/libraries/barclamp_library.rb

For some reason s390x seems to need the require_relative, while it works
without that on the other archs.

barclamp: Fix conduit_resolver from chef for s390x

---

crowbar_framework/app/controllers/api/crowbar_controller.rb
crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/routes.rb
crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/crowbar_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

the admin repochecks are really upgrade specific and don't belong
to the crowbar namespace
(cherry picked from commit 26371aac9a21cf384c3047f82f799b18744086bf)
partially backports https://github.com/crowbar/crowbar-core/pull/732

[stable/3.0] move admin repochecks to /api/upgrade namespace

---

crowbar_framework/app/controllers/api/crowbar_controller.rb
crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb

the error message format needs to be adapted to be consistent
over the other api responses that could throw an error
we are using the same format here as in the prechecks, as this
was discussed and designed properly
(cherry picked from commit b2bf06c56bb5fe7e69ed1f53023df2145c857370)
partially backports https://github.com/crowbar/crowbar-core/pull/730

[stable/3.0] adapt error messages of responses to be consistent

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/fixtures/upgrade_prechecks.json
crowbar_framework/spec/models/api/upgrade_spec.rb

none: when a required check fails
non-disruptive: when all required checks succeed
disruptive: when only some non-required checks fail
* https://github.com/SUSE-Cloud/automation/pull/1378

determine the best upgrade mode

---

crowbar_framework/lib/crowbar/checks/maintenance.rb

after adapting 8e9dee2 the i18n was falsely re-added, probably
due to copy and paste
see https://github.com/crowbar/crowbar-core/pull/672

fix broken i18n

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb

During the movement of the api repochecks/adminrepochecks
from crowbar to the upgrade namespace a couple of needed
methods were left that are necessary for the calls to work
Reference commit: https://github.com/crowbar/crowbar-core/commit/26371aac9a21cf384c3047f82f799b18744086bf

Move missing methods onto the upgrade api model

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/models/api/upgrade_spec.rb

I made it more special than the other checks, based on current return values of `Api::Pacemaker.health_report`. But maybe it is wrong and I should rather adapt `Api::Pacemaker.health_report` to return `:errors` just like the other checks ... ideas?
This is the kind of response that current `Api::Pacemaker.health_report` could return:
```
{
"crm_failures" => {
"node1" => "reason for crm status failure"
},
"failed_actions" => {
"node2" => "Failed actions at this node",
"node3" => "Failed actions at this node"
}
}
```

Show the response from cluster health check in the upgrade prechecks

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-delete-pacemaker-resources.sh.erb
chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb

We must delete old pacemaker resources from Cloud6 node
before the new ones get created from upgraded node.
See https://github.com/jsuchome/cloud-upgrade/blob/master/Step%2012.md , Step 4

Script for deleting pacemaker resources

---

chef/cookbooks/nfs-client/recipes/default.rb

Without this, we don't have mount.nfs, which is going to be an issue :-)

nfs-client: Install nfs-client package

---

chef/cookbooks/ipmi/recipes/ipmi-configure.rb

The VLAN id is expected as a string, but it comes in as an int.
So it needs to be converted to a string.

fix ipmi vlan setup, convert vlan id to string

---

crowbar_framework/app/models/api/crowbar.rb

The OS values are updated directly by the upgrade script, see https://github.com/crowbar/crowbar/pull/2282
This is a revert of https://github.com/crowbar/crowbar-core/commit/5626f2fc324ddd3f701de2c4a3cd0873f1b9694c

Do not remove the OS values from crowbar

---

crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

Make the library thread-safe, so that multiple clients (web UI or `crowbarctl`) can simultaneously read/write upgrade state in a safe manner.
Still TODO:

Thread-safe locking

---

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/app/models/node_object.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

When done from recipe, it could be possibly executed later when
upgraded node is doing its first chef-client run.
So let's rather do it explicitely at the point when we are preparing
all nodes for the upgrade.
(This partially reverts https://github.com/crowbar/crowbar-core/pull/702)

Do not add the pre-upgrade attribute from the recipe

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

this would (**EDIT**: _partially_) fix https://bugzilla.suse.com/show_bug.cgi?id=997293
(**EDIT**: it wouldn't, it would only fix one particular case, i.e. `/api/upgrade/prepare`)
and would obsolete https://github.com/SUSE-Cloud/automation/pull/1229

perform the prepare in the background (bsc#997293)

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/routes.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb

the backups commit needs to be backported to use the old `Backups` model in the old backups_controller

adding a status to the rest of the upgrade steps on cloud 6 side

---

crowbar_framework/spec/spec_helper.rb

Since codeclimate-test-reporter v1.0 is released our travis runs are
broken for master.
See https://github.com/codeclimate/ruby-test-reporter/blob/master/README.md

Fix breaking change of codeclimate-test-reporter

---

chef/cookbooks/provisioner/templates/suse/crowbar_register.erb

We call ntpdate in the script, so it needs to be installed if we want it
to succeed.

crowbar_register: Ensure ntp is installed

---

crowbar_framework/app/models/api/upgrade.rb

we actually want to join the keys here, which are the node names

[stable/3.0] fix undefined method join for Hash

---

crowbar_framework/lib/crowbar/checks/maintenance.rb

after adapting 8e9dee2 the i18n was falsely re-added, probably
due to copy and paste
(cherry picked from commit dfd77601dfd4cda30d2b07475bf527c9eb7959d3)

[stable/3.0] fix broken i18n

---

crowbar_framework/app/models/api/upgrade.rb

this is just more convenient for the user to see from the upgrade
status which repositories are missing

[stable/3.0] write names of missing repositories to the status

---

crowbar_framework/app/models/api/upgrade.rb

we actually want to join the keys here, which are the node names
(cherry picked from commit 8521d83735c544218a2b90610208b0152e11c875)

fix undefined method join for Hash

---

crowbar_framework/app/models/node_object.rb

Active Support has already a native object dup method.

Replace deep_clone with deep_dup

---

chef/cookbooks/ohai/recipes/default.rb

It is used by the crowbar package, so ensure it is actually installed.

ohai: Install tcpdump package

---

crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

We're already using symbols for step names and even for :pending state.

upgrade: Use the symbols for the state of upgrade steps

---

crowbar_framework/app/models/node_object.rb

Active Support has already a native object dup method.
(cherry picked from commit 79670c10536071d6e627e726e7f890c9fffc5a66)

[3.0] Replace deep_clone with deep_dup

---

chef/cookbooks/crowbar/files/default/crowbar.service
chef/cookbooks/crowbar/templates/default/sysconfig.crowbar.erb
configs/crowbar.service
crowbar_framework/config/puma.rb

Each puma worker will starts it's own ruby stack which consumes a lot of
memory. Instead of doing this we should use more threads.

puma: Reduce puma worker and use more threads

---

chef/cookbooks/crowbar/files/default/crowbar.service
chef/cookbooks/crowbar/templates/default/sysconfig.crowbar.erb
configs/crowbar.service
crowbar_framework/config/puma.rb

Each puma worker will starts it's own ruby stack which consumes a lot of
memory. Instead of doing this we should use more threads.
(cherry picked from commit 529dc484e4bcf7bb2fe4e735fbd249270c30bb9f)
Backport of #809

[3.0] puma: Reduce puma worker and use more threads (bsc#1010211)

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb

We do not need to workaround it by using v2 API any more.

upgrade: switch neutron-ha-tool to use v3 API

---

chef/cookbooks/provisioner/templates/suse/crowbar_register.erb

This helps make sure that, in case the DNS server is down, we can
still resolve our hostname. We already do that in the autoyast profile,
but we forgot to add this to crowbar_register.
See https://github.com/crowbar/barclamp-provisioner/pull/344

crowbar_register: Add entry to /etc/hosts for resolving our hostname

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb

After evacuating routers and stopping the remaining services reset the
fail-mode of the ovs bridges to keep network connectivty during the
package upgrade.
https://bugzilla.suse.com/show_bug.cgi?id=1002734
Additionally adds a workaround for https://bugzilla.suse.com/show_bug.cgi?id=1011889 by forcing a wicked ifreload call in the preupgrade script.

upgrade: workaround potential network issues during the upgrade

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

User might want to repeat some of the steps even when they already
succeeded.
Besides the Cloud6 backport, API change in crowbar-init is also required.

upgrade: Allow repeating some steps

---

crowbar_framework/app/models/crowbar_service.rb

I think it makes sense to do both action from the point where we're accessing all nodes (to be upgraded), and before we actually do the upgrades.

upgrade: Unset db-sync flag before upgrading the nodes, skip keystone bootstrap

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

User might want to repeat some of the steps even when they already
succeeded.
(cherry picked from commit f88889317a7937150f4d8cce2aceb60a7c946319)
Backport of https://github.com/crowbar/crowbar-core/pull/816

[3.0] upgrade: Allow repeated execution of selected steps

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-chef-upgraded.sh.erb
chef/cookbooks/crowbar/templates/default/crowbar-post-upgrade.sh.erb
crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

The DRBD-sync actions in post-upgrade script could take lot of time,
let's decouple them from crowbar_join (and chef-client) runs.

upgrade: Execute crowbar_join from extra script

---

crowbar_framework/app/controllers/api/upgrade_controller.rb

start_step requires an argument (step name)
This change is already included in https://github.com/crowbar/crowbar-core/pull/830 , but we might need to merge this sooner, as the review of the other PR could take longer time. 
This Pr is fixing the bug that currently the upgrade is failing in crowbar backup step.

[3.0] upgrade: Fix the API call for Crowbar::UpgradeStatus.start_step

---

crowbar_framework/app/controllers/api/crowbar_controller.rb
crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/lib/crowbar/error/upgrade_status.rb
crowbar_framework/lib/crowbar/lock.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
crowbar_framework/spec/models/api/crowbar_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb
crowbar_framework/spec/spec_helper.rb

there is also a backport of https://github.com/crowbar/crowbar-core/pull/772 in here
and it needs a forward port of the other commits about the api restriction

[3.0] upgrade: restrict api access through the status library

---

bin/crowbar_batch

It may be useful to simply re-create the proposals without committing
them. Such pre-population can be used for trainings, or to copy an
environment and then to tweak settings in the webui before committing.
https://bugzilla.suse.com/show_bug.cgi?id=1012173

batch: Add an import subcommand (bsc#1012173)

---

crowbar_framework/config/database.yml

in a fresh cloud setup this file gets overwritten by crowbar-init's
chef recipe, there is a template for that file.
nevertheless it should reflect the adapter that we have nowadays
which is postgres.
the other benefit of this patch is that when we use a development
environment the file gets overwritten by guard and the values are
still the correct defaults as we use from crowbar-init's template.
https://github.com/crowbar/crowbar-init/pull/55 and https://github.com/SUSE-Cloud/automation/pull/1489

update database configuration

---

chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
chef/cookbooks/utils/libraries/helpers.rb

When we're in crowbar_register, we're not in sledgehammer. So we have
access to everything, like the ability to install packages.
This enables the ohai cookbook to install the cstruct gem in
crowbar_register. Without this, there's a period of time during the
crowbar_register call where the node has incomplete ohai data, resulting
in the inability to resolve conduits, which then causes crashes on the
admin server:
```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/provisioner/recipes/role_provisioner_server.rb
================================================================================
NoMethodError
-------------
undefined method `[]' for nil:NilClass
Cookbook Trace:
--------------- …
```

Fix chef-client crash on admin server during a crowbar_register

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-router-migration.sh.erb
crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

As part of the founder upgrade, we moved all routers to a different node
in order to keep connectivity to the VMs. Once the founder node has been
upgraded it is safe to move back the routers.
**Requires:** https://github.com/crowbar/crowbar-openstack/pull/619

Do router migration back to founder node

---

chef/cookbooks/provisioner/recipes/setup_base_images.rb

If for some reason /srv/tftpboot/validation.pem gets overwritten, then
it's impossible to allocate new nodes. We should make sure that
we converge properly here.

provisioner: Ensure /srv/tftpboot/validation.pem is correct

---

crowbar_framework/app/controllers/api/upgrade_controller.rb

in the upgrade_status library the step has an underscore

[3.0] upgrade: make step name consistent

---

crowbar_framework/config/initializers/yaml_db.rb
crowbar_framework/lib/crowbar/backup/export.rb

This just makes the size go exponential.

crowbar: Avoid exporting backups in the backup

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/app/models/node_object.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/models/api/upgrade_spec.rb

~~https://github.com/crowbar/crowbar-core/pull/830~~ https://github.com/crowbar/crowbar-core/pull/847
@jsuchome I thought about doing the node upgrade status as well, but I'd like to wait for the implementation to be done before setting the status, because there are many different cases for setting the status as I saw in the code, and I am not sure if the model will still change, so I kept it untouched for now.

upgrade: set status and restrict api for noderepochecks and service shutdown

---

crowbar_framework/app/models/service_object.rb

The node is not necessarily cached.

crowbar: Fix crash when displaying chef log on error

---

crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

PR #839 wasn't fully rebased at the time of merging, so another
change in the upgrade status lib requires the unit tests to be adapted

rspec: fix unit tests

---

chef/cookbooks/network/recipes/default.rb

This reworks the fix for https://bugzilla.suse.com/show_bug.cgi?id=1011889
to ensure that wicked ifreload is only execute at most once for a single
chef-client run. Previouly it was triggered once per updated ifcfg file
and that caused problems for certain configurations. E.g. when a single
chef-client run set up an "normal" physcial interface and a vlan
interface on top of that. (Happens e.g. in "dual" network setups when
allocating a public IP and when public and admin are on different
physical interfaces.)
https://bugzilla.suse.com/show_bug.cgi?id=1012587

network: Run wicked ifreload only once per chef-client run (bsc#1012587)

---

crowbar_framework/app/controllers/machines_controller.rb

this change complements the PR https://github.com/crowbar/crowbar-client/pull/128 and introduces a custom failure for alias rename failure

return err406 on alias rename failure

---

crowbar_framework/Gemfile

Rake 12.0.0 got released on Dec 6 but our rspec version still uses
removed code.

[3.0] travis: Use rake < 12.0.0

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

when just one product has missing repositories and another one
shows empty (successful) repochecks, we need to skip trying to
parse the missing repositories when there aren't any.
fixes: NoMethodError (undefined method `to_sym' for nil:NilClass)

[3.0] upgrade: fix adminrepochecks on missing repositories

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

when just one product has missing repositories and another one
shows empty (successful) repochecks, we need to skip trying to
parse the missing repositories when there aren't any.
fixes: NoMethodError (undefined method `to_sym' for nil:NilClass)
(cherry picked from commit 55489c0ba1e5eb9aacde1f461e7fbbdffe637f8f)
forwardport of https://github.com/crowbar/crowbar-core/pull/874

upgrade: fix adminrepochecks on missing repositories

---

crowbar_framework/lib/crowbar/error/upgrade_status.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

(cherry picked from commit 1055d79e3f705bd5dc1c411ab5a8f01d4e7ec343)
Hound was not configured correctly on the `stable/3.0` branch, so some violations that came to daylight in https://github.com/crowbar/crowbar-core/pull/847 need to be backported

[3.0] fix hound complaints

---

crowbar_framework/app/models/node_object.rb
crowbar_framework/spec/fixtures/offline_chef/node_admin.crowbar.com.json

To avoid heavy spamming of the log due to the regular database queries
let's cache the value till it changes.

provisioner: Cache chef_client_runs (bsc#1013556)

---

crowbar_framework/app/models/node_object.rb
crowbar_framework/spec/fixtures/offline_chef/node_admin.crowbar.com.json

(cherry picked from commit bb0d3ec299b62847eae1e1891c753f493be973ef)
Backport of #860

[3.0] provisioner: Use chef_client_runs from node (bsc#1013556)

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
crowbar_framework/app/models/node_object.rb

See Known Issues at http://docs.openstack.org/releasenotes/cinder/newton.html#id4
Cinder services are now automatically downgrading RPC messages to be understood
by the oldest version of a service among all the deployment. Disabled and dead
services are also taken into account. It is important to keep service list up to date,
without old, unused records. This can be done using cinder-manage service remove command.

upgrade: Remove unsupported cinder services right before the upgrade

---

crowbar_framework/app/controllers/barclamp_controller.rb

otherwise it can't set the node status

upgrade: open transition api for crowbar_join

---

chef/cookbooks/ohai/recipes/default.rb

While I don't have any hard proof yet, I believe the bigger the node data is, the slower chef (server & solr) is going to be.
@rhafer cc'ing you as I'd prefer to have your opinion on whether it's okay or not to drop all these interfaces from the ohai data.

Keep less ohai data

---

chef/cookbooks/crowbar/templates/default/crowbar-post-upgrade.sh.erb
chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb
chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.erb

To enable running scripts again after the failure, we need
to remove failure indications when executing the script.

upgrade: Remove the indication of previous script failure

---

crowbar_framework/lib/crowbar/deployment_queue.rb

(cherry picked from commit b060d3f94d13923f6b6bd37e3d7dd12110f2bcef)
Backport of #892

[3.0] queue: Only dequeue if there is a proposal to dequeue

---

crowbar_framework/app/models/service_object.rb
crowbar_framework/config/locales/crowbar/en.yml

The barclamp controller expects an array as return value.
(cherry picked from commit c9298fc6197a8a84d7c6e2c01e51db0d7048f5b0)
Backport of #885

[3.0] proposal: Fix wrong return on proposal reset (bsc#1014835)

---

crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

We need this for detailed information during the last part of upgrade,
upgrading cloud nodes.

upgrade: Let the progress library track substeps and current node

---

chef/cookbooks/provisioner/templates/default/autoyast.xml.erb
chef/cookbooks/provisioner/templates/suse/crowbar_register.erb

For certain service users we fix their uid/gid combination to ensure
that the combination is consistent across multiple nodes. This is
necessary for interoperability with NFS for instance. By moving the
fixed uid/gid combinations to lower values we avoid (until there are
several hundred more service users in a default SLES installation)
collisions with the OS.

bsc#998598: Move uid/gid lower to avoid collision

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-delete-cinder-services-before-upgrade.sh.erb
chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/app/models/node_object.rb
crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json
crowbar_framework/spec/models/api/upgrade_spec.rb

As part of services shutdown, we're deleting cinder services from database.
For that, we need them to be stopped everywhere.
Also, we need until this step finishes before continuing with next steps.

upgrade: Ensure cinder controller runs shutdown of services as last node

---

chef/cookbooks/dhcp/providers/host.rb

The log is useless because it assumes chef will fail to create a file;
if that's the case, chef would actually fail.

dhcp: Remove useless log

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/controllers/application_controller.rb
crowbar_framework/app/views/errors/during_upgrade.html.haml
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/controllers/machines_controller_spec.rb

backport of https://github.com/crowbar/crowbar-core/pull/861
NOTE: the difference to the original commit is that i dropped the check for `/var/lib/crowbar/upgrade/6-to-7-upgraded-ok`

[3.0] only allow requests to the upgrade api during the upgrade

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb

Somehow this was removed and the actions for shutting down the
services were not executed anywhere.
... I broke it here: https://github.com/crowbar/crowbar-core/pull/890

upgrade: Do not forget to pass cluster founder info to the script

---

crowbar_framework/lib/crowbar/upgrade_status.rb

After the failure, the step could be started again. While
it is in the 'running' state, there's no point in showing
the errors from the previous execution.

upgrade: Reset the errors hash once the step was started

---

crowbar_framework/app/models/network_service.rb

Logging the backtrace makes it easier to debug issues like:
```
Error finding address: undefined method `[]' for nil:NilClass`
```

network_service: Log backtrace in error case

---

chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.erb

The packages in Newton have a new configuration structure. Instead of
using the /etc/$project/$project.conf file, the different projects
have a /etc/$project/$project.conf.d/ directory which should be used.
Because package upgrades do not override the config files modified by Crowbar,
we need to reset theses files once.
If a user afterwards changes the files again, we do not override theses then.

upgrade: Use .rpmnew configs for OpenStack services

---

crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

This is not extended to the upgrade of compute nodes, as relevant PR is not merged yet. I think it could be solved as a followup.

upgrade:Track the sub steps and nodes status in the progress library

---

crowbar_framework/Gemfile
crowbar_framework/config/boot.rb

We are in the process to update puma to 2.16.0. This means that we have
to allow puma both versions for now. Once the update is completed we
have to fix the version again.
Related to #926

[3.0] gems: Allow puma ~> 2.11

---

crowbar_framework/config/puma.rb
crowbar_framework/tmp/pids/.gitignore

this folder is usually created by puma, but it needs to be available
even before puma because delayed_job runs as a separate process

delayed_job: create a folder to store pid's

---

chef/cookbooks/bind9/recipes/default.rb
chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/logging/recipes/client.rb
chef/cookbooks/network/recipes/default.rb
chef/cookbooks/network/recipes/switch_config.rb
chef/cookbooks/ntp/recipes/default.rb
chef/cookbooks/provisioner/recipes/base.rb
chef/cookbooks/provisioner/recipes/dhcp_update.rb
chef/cookbooks/provisioner/recipes/setup_base_images.rb
chef/cookbooks/provisioner/recipes/update_nodes.rb
chef/cookbooks/repos/recipes/default.rb
chef/cookbooks/resolver/recipes/default.rb
chef/cookbooks/utils/libraries/helpers.rb
chef/cookbooks/utils/libraries/search.rb
chef/cookbooks/uwsgi/providers/default.rb

Most of the time, we're happy with node attributes that are not older than the start of the chef-client run. So we can cache things.
~~The last commit looks huge, but it's mostly an indentation change after removing a useless test, so you may want to use `w=1` for reviewing.~~

Implement (and use) a search with cached results for cookbooks

---

crowbar_framework/public/docs/batch.md

The URL in [crowbar batch doc](https://github.com/crowbar/crowbar-core/blob/master/crowbar_framework/public/docs/batch.md) is broken now

Fix link to crowbar_batch executable in documentation 

---

crowbar_framework/app/controllers/application_controller.rb

if you don't have an UI which lists you the sanity errors, it is very
difficult from the back end to determine what went wrong

[3.0] show sanity check errors in the json response

---

configs/crowbar-jobs.service

because crowbar.service already requires crowbar-jobs.service

delayed_job: don't wait for crowbar-service

---

crowbar_framework/app/models/api/node.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/node_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

the ptf repo is not tracked under any feature so we need to enable
it by hand.
enabling it as a feature would not make sense as it may not be
available, and the api response would show it as missing and
make the repocheck appear as failed. Also conceptually the ptf
repo does not seem to be a feature.

upgrade: enable ptf repo during the noderepochecks (bsc#1015827)

---

chef/cookbooks/network/recipes/default.rb

This change seems to be required in order to make wicked aware of config
file changes and to avoid it applying outdated configurations to the
interfaces.
https://bugzilla.suse.com/show_bug.cgi?id=1011889
(cherry picked from commit 1d9160aa3d474cd7bbeb15bc09e5bd124ed795a2)

[3.0] network: Run wicked ifreload when ifcfg files change (bsc#1011889)

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb

When nova is deployed without shared storage we need to use
--block-migrate for live migrating instances away from compute nodes.

[upgrade] Use block-migration when needed

---

crowbar_framework/app/controllers/application_controller.rb

if you don't have an UI which lists you the sanity errors, it is very
difficult from the back end to determine what went wrong
(cherry picked from commit d80b3c12421bd91f4d0e92ee3d510806c8e4b254)
Forwardport https://github.com/crowbar/crowbar-core/pull/886

show sanity check errors in the json response

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/lib/crowbar/error.rb
crowbar_framework/lib/crowbar/error/upgrade_cancel.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

after certain steps it shouldn't be allowed to cancel the upgrade
anymore
(cherry picked from commit 1630d09592d85a9cb0bcc028a92ac17fc95a68dc)
Backport https://github.com/crowbar/crowbar-core/pull/881

[3.0] upgrade: restrict cancelation of the upgrade

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/backup.rb
crowbar_framework/config/locales/crowbar/en.yml

Currently any error/exception during backup creation propagates up the stack and causes 500 response with not explanation plus traceback in the logs. In the UI this triggers generic error message:
With these changes, failure during backup creation will look like this:

Backup errors

---

crowbar_framework/app/controllers/nodes_controller.rb

(cherry picked from commit dad6ecf42309d0af003d72c893419155ce3e331e)
backport of https://github.com/crowbar/crowbar-core/pull/911

[3.0] upgrade: open index action during the upgrade

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-chef-upgraded.sh.erb

This is temporary workaround for bsc#1016302 (service might not
be running after initial chef-client run). It should be removed
once the proper patch is released.

upgrade: Explicitely start nova-compute service after the upgrade

---

chef/cookbooks/crowbar/templates/default/crowbar-router-migration.sh.erb

It's needed so the next invocation does not exit with failure automatically.
This script is bit tricky, because we're explicitely removing the file after the execution, but I think we're missing the failed case. Other solution would be to ensure we delete both indications from `evacuate_network_node`

upgrade: Remove possibly existing failed indication on start

---

crowbar_framework/app/models/api/upgrade.rb

When the prepare failed it makes no sense to continue with the code
below so return and exit in this case.

upgrade: Fix services shutdown

---

crowbar_framework/app/controllers/barclamp_controller.rb
crowbar_framework/app/models/crowbar_service.rb
crowbar_framework/app/models/network_service.rb
crowbar_framework/app/models/service_object.rb
crowbar_framework/lib/crowbar/deployment_queue.rb

When there are many nodes in a proposal, things can start to be slow. Part of it can easily be avoided (by not reloading nodes all the time and skipping useless bits).
This is the safe part of https://github.com/crowbar/crowbar-core/pull/896

Make applying proposal slightly faster

---

crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/error/upgrade_error.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

Also, end the upgrade step for non-upgrade error, so it is not
stuck as running.
This should fix  https://bugzilla.suse.com/show_bug.cgi?id=1019179
Requires https://github.com/crowbar/crowbar-core/pull/968

upgrade: Raise and catch upgrade specific Exceptions during upgrade

---

crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/app/models/node.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

- for DRBD - slave node gets changed, so if first node upgrade failed, next attempt will pick the other one as first ... this means e.g. that router migration will be done again, but from another node... - should be fixed by 4th commit
- most of the upgrade scripts are skipped when there's attempt to run them second time, but `reboot_and_wait` is not ... and after reboot, who starts the pacemaker if initial crowbar_join was already done (and thus is now skipped?) - should be fixed by 3rd commit

upgrade: after failure and restart of failed step, continue from the same point

---

chef/cookbooks/provisioner/recipes/setup_base_images.rb
chef/cookbooks/provisioner/recipes/update_nodes.rb
chef/cookbooks/provisioner/templates/suse/crowbar_register.erb

For SES-only deploys, install ses-release instead of
suse-openstack-cloud-release.  Also, make the messaging slightly
more generic.

crowbar_register: handle storage-only deploys (bsc#993475)

---

crowbar_framework/lib/crowbar/deployment_queue.rb

If the lock creation failed then the lock is nil and the ensure will
raise an error.

deployment_queue: Release lock only if there is a lock

---

crowbar_framework/app/models/api/upgrade.rb

It takes the node objects, not the names

upgrade: Fix arguments for upgrade_next_cluster_node

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

Do not process the nodes that have been already upgraded.
If there's a node for which we already started the upgrade, continue with this
one next time we retry the upgrade method.

upgrade: During the retry of nodes upgrade, stick to the original order

---

crowbar_framework/Gemfile
crowbar_framework/app/controllers/machines_controller.rb
crowbar_framework/app/models/node.rb
crowbar_framework/spec/controllers/machines_controller_spec.rb
crowbar_framework/spec/controllers/nodes_controller_spec.rb
updates/control.sh

The update state conflicts with the ActiveRecord update methods. To
avoid any confusion about the state lets rename it.
Splitted out of #920

node: Rename update state to confupdate

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

When the synchronous API call fails, it saves error in a form
of 'data' and 'help' touple. We need to do it in all other cases
as well.
This should be a fix for  https://bugzilla.suse.com/show_bug.cgi?id=1019298
Here's the result of new error output, cli: http://pastebin.nue.suse.com/19090/src and json: http://pastebin.nue.suse.com/19094/src

upgrade: Save the upgrade errors in consistent format

---

chef/cookbooks/network/recipes/default.rb
chef/data_bags/crowbar/template-network.json

This was disabled for bsc#910298 which mentioned a "wellknown vlan
offloading bug". However, with the newer kernel that we have now, this
should hopefully be better.
https://bugzilla.suse.com/show_bug.cgi?id=1015266

network: Enable rx/tx offloading by default (bsc#1015266)

---

crowbar_framework/app/models/api/upgrade.rb

When the synchronous API call fails, it returns the error in a form
of 'data' and 'help' touple. We should save it the same way in the
progress file, especially because for aynchronous format, the content
of progress file is returned by the status API call.
(cherry picked from commit 44f7a55da5b79412480846d5de80603b3ab21559)
Backport of https://github.com/crowbar/crowbar-core/pull/972

[stable/3.0] upgrade: Save the upgrade errors in consistent format

---

chef/cookbooks/barclamp/libraries/barclamp_library.rb
chef/cookbooks/barclamp/recipes/default.rb
chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/logging/recipes/client.rb
chef/cookbooks/network/recipes/default.rb
chef/cookbooks/ntp/recipes/default.rb
chef/cookbooks/provisioner/recipes/base.rb
chef/cookbooks/provisioner/recipes/dhcp_update.rb
chef/cookbooks/provisioner/recipes/setup_base_images.rb
chef/cookbooks/repos/recipes/default.rb
chef/cookbooks/repos/templates/default/gemrc.erb
chef/cookbooks/resolver/recipes/default.rb
chef/cookbooks/uwsgi/providers/default.rb
crowbar_framework/app/models/dns_service.rb
crowbar_framework/app/models/logging_service.rb
crowbar_framework/app/models/ntp_service.rb
crowbar_framework/app/models/provisioner_service.rb
crowbar_framework/lib/crowbar/data_bag_config.rb

The static config items are actually data bag items (for now).
The main benefits are:
- performance improvement (as a search query can be expensive)
- going in the direction of not depending on centralized chef-server
- in some cases, simplification of the cookbooks
The rake task will be used from barclamp_install.rb so that the config items get regenerated when the code is updated (so that there's no need to reapply a barclamp to get an up-to-date config item with the new fields).
~~Marking as WIP as I'd like to gather feedback; but this seems to work quite well.~~

Start moving away from search queries to static config items for cookbooks

---

chef/cookbooks/provisioner/templates/suse/crowbar_register.erb

The user `qemu` can not be created unless the group `kvm` was created
beforehand.
Thanks goes to Bryan Gartner <bryan.gartner@suse.com> for pointing this out.

provisioner: Fix order of creating groups and users

---

crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/controllers/crowbar_controller_spec.rb
crowbar_framework/spec/controllers/machines_controller_spec.rb
crowbar_framework/spec/controllers/nodes_controller_spec.rb
crowbar_framework/spec/lib/crowbar/backup/export_spec.rb
crowbar_framework/spec/models/api/crowbar_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb
crowbar_framework/spec/models/crowbar_service_spec.rb

This commit unifies the way how we search and use the name in the spec
tests.

node: Use always the full name in spec

---

crowbar_framework/app/models/api/upgrade.rb

Before, the status API returned array of error hashes when some of
the prechecks failed. Everything was enclosed in one more hash.
This change converts this array to one hash and removes extra nesting
to match the common error format used in other places.
The error keys are assumed to be unique.

upgrade: Fix format of precheck errors in status

---

updates/control.sh

When running `nuke_everything()` on newly allocated node skip CD
drives that are in `/dev/sr*`.

Skip CD drives

---

chef/cookbooks/utils/libraries/role_recipe.rb
crowbar_framework/app/models/service_object.rb

Add a new recipe skipping mechanism, and use it to fix sync marks drift during application of the `nova-ha-compute` role (bsc#1004758).
https://bugzilla.suse.com/show_bug.cgi?id=1004758
Requires https://github.com/crowbar/crowbar-ha/pull/163

new recipe skipping mechanism to fix nova-ha-compute sync drift (bsc#1004758)

---

crowbar_framework/app/models/api/upgrade.rb

This was (partially) removed by https://github.com/crowbar/crowbar-core/commit/f88889317a7937150f4d8cce2aceb60a7c946319
Ideally, we should not need it and user should not be allowed to run the prechecks later when some other steps have already been run. But UI might need to do it in some special cases

upgrade: Enable running prechecks also out of order

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb

(cherry picked from commit 60e9f5cba0dd0cbff687c5724d44ee6952ed9e06)
backport of https://github.com/crowbar/crowbar-core/pull/988

upgrade: set the status when there are some zypper errors

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/crowbar_spec.rb

if we only check if it is enabled on the repository level, we will
have a false result within the repochecks in case a repository is
disabled, but necessary to have, because it has been deployed.
so if an ha repo becomes unavailable at some point during the upgrade
it will not even show up in the repochecks anymore, because it gets
disabled on the repository level once it is not available anymore.

upgrade: Check if a feature/addon is deployed, not enabled

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/repository.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/fixtures/crowbar_repocheck.json
crowbar_framework/spec/fixtures/node_repocheck.json
crowbar_framework/spec/fixtures/node_repocheck_missing.json

this is useful information for any client (UI/crowbarctl)
```bash
root@crowbar:/opt/dell/crowbar_framework # crowbarctl upgrade repocheck nodes
+----------------------------------+--------------------------------+
| Status                           | Value                          |
+----------------------------------+--------------------------------+
| ha.available                     | true                           |
| ha.repos                         | SLE12-SP2-HA-Pool              |
|                                  | SLE12-SP2-HA-Updates           |
| os.available                     | false                          |
| os.repos                         | SLES12-SP2-Pool                |
|                                  | SLES12-SP2-Updates             |
| …
```

upgrade: Map features to repository names

---

crowbar_framework/app/models/api/upgrade.rb

(cherry picked from commit 4233d8106706f7d4dcb9481064da6bb1c94af6ac)
Backport of https://github.com/crowbar/crowbar-core/pull/1007

[stable/3.0] upgrade: Enable running prechecks also out of order

---

crowbar_framework/config/initializers/puma_worker_killer.rb
crowbar_framework/config/puma.rb

We switched recently to puma 2.16 which gives us the possibility to
start the PumaWorkerKiller directly via puma. This change has the
advantage that puma is aware of the restart.

puma: Start puma worker killer via puma

---

chef/cookbooks/apache2/definitions/apache_conf.rb
chef/cookbooks/apache2/definitions/apache_module.rb
chef/cookbooks/apache2/definitions/apache_site.rb
chef/cookbooks/apache2/definitions/web_app.rb
chef/cookbooks/apache2/recipes/default.rb

This causes the magic to override the LWRP in crowbar-pacemaker to not
fully work, as it only overrides the second definition, and not the
first one. Which results in the :enable action to always be done for the
apache2 service, even when pacemaker is used.
https://bugzilla.suse.com/show_bug.cgi?id=1021106

apache2: Do not define apache2 service twice (bsc#1021106)

---

crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/lib/crowbar/backup/restore.rb
crowbar_framework/lib/schema_migration.rb

(cherry picked from commit 2b97aec1ab5d63b1af1f4739193d1eeb81c7914f)
Backport of one commit from https://github.com/crowbar/crowbar-core/pull/491
Juist saw this happen recently.

Fix exception handling

---

chef/cookbooks/provisioner/recipes/dhcp_update.rb

The host pool has static ip address assignments, a short lease
timeout is actually hindering the initial crowbar installation when
it hits the timeout while the chef-client run is not yet finished

provisioner: change lease time only for dhcp pool

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

(cherry picked from commit 35655f034aefe3833e41bbb678734497b3167794)
Partial backport of #1029

[stable/3.0] Save the backup location info in the progress file

---

crowbar_framework/app/controllers/application_controller.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

The file can be used by crowbar so the non-upgrade related
requests are blocked during the upgrade.
Fixes bsc#1016923

upgrade: Indicate running upgrade process

---

chef/cookbooks/provisioner/recipes/update_nodes.rb
chef/cookbooks/provisioner/templates/default/autoyast.xml.erb

Using the UEFI attribute from the admin server doesn't help figure out
if the node is using UEFI.
Similarly, be a bit safer for the domain.
https://bugzilla.suse.com/show_bug.cgi?id=1021596

provisioner: Use correct attributes for autoyast profile (bsc#1021596)

---

crowbar_framework/app/models/api/crowbar.rb

If nova-controller role is not applied correctly, prechecks were
failing with 500 response and status was left at running.

upgrade: Fix no_live_migration check without nova

---

crowbar_framework/app/models/api/crowbar.rb

If nova-controller role is not applied correctly, prechecks were
failing with 500 response and status was left at running.
backport of #1033

[stable/3.0] upgrade: Fix no_live_migration check without nova

---

chef/cookbooks/barclamp/libraries/nic.rb
chef/cookbooks/network/recipes/default.rb

Openvswitch by default sets the datapath-id based on the MAC address of
the bridges. If the underlying interfaces share the same MAC address
(i.e.  when using eth0 for br-fixed and eth0.300 for br-public) we will
endup with duplicate datapath-ids, which break neutron-openvswitch-agent.
https://bugzilla.suse.com/show_bug.cgi?id=1022074

network: Manually set datapath-ids on the ovs-bridges (bsc#1022074)

---

crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

Remove strage 'finished' step, mark the upgrade end directly
after the nodes upgrade.

upgrade: Treat 'nodes' step as a last one

---

crowbar_framework/app/controllers/api/crowbar_controller.rb
crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/routes.rb
crowbar_framework/lib/crowbar/error.rb
crowbar_framework/lib/crowbar/error/upgrade.rb
crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

What we need to test here:
- correct handling of progress lib errors (step out of order, step already running)
- correct handling of real upgrade errors (e.g. failure during some node action in nodes step)
- correct handling of non-upgrade errors (syntax errors, calling methods on nil objects etc.)

upgrade: cleanup and catch unforeseen exceptions

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

this saves us from setting the upgrade status again by caching the checks
during invocation of best_method
(cherry picked from commit 0aa7a493aba4e3b39d87dcc365d35989cf03c6cc)
Backport of https://github.com/crowbar/crowbar-core/pull/1013

[3.0] upgrade: Include best_method within the prechecks

---

chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb

It's better then just starting, in case we need to run the script
again after a failure.

upgrade: Restart the newly upgraded services on compute nodes

---

chef/cookbooks/barclamp/libraries/barclamp_library.rb

We were iterating over all instances based on keys, but the id of the
data bag item was included in the keys, leading to a crash:
```
NoMethodError
-------------
undefined method `key?' for "openstack":String
```

barclamp: Fix fetching config item when no instance is specified

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/config/routes.rb

when a client on cloud 6 requests an upgrade route that only exists
in cloud 7, a StartStepOrder exception should be thrown

[3.0] upgrade: Implement a dummy cloud 7 api

---

crowbar_framework/app/models/api/upgrade.rb

That way we should know that there's no need to run the script again.
An alternative to https://github.com/crowbar/crowbar-core/pull/1045

upgrade: Mark successfull router migration on the target node

---

crowbar_framework/app/models/api/upgrade.rb

There can be more than one `<prompt>` element in zypper xml output.
In such cases, `Hash.from_xml()` returns array of hashes instead of
a hash for those subtrees.
In this particular case, the simplest solution is to show only first
prompt as the user needs to complete the actions in sequence anyway
when running it in the terminal.

upgrade: Fix handling of multiple zypper prompts

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

this lists all upgraded and all non upgraded nodes
~~`crowbarctl` PR will follow~~
here it is https://github.com/crowbar/crowbar-client/pull/147
```bash
{
"upgraded": [
],
"not_upgraded": [
"d52-54-77-77-77-03.emil.suse.de",
"d52-54-77-77-77-01.emil.suse.de",
"d52-54-77-77-77-02.emil.suse.de",
"d52-54-77-77-77-04.emil.suse.de"
]
}
```

upgrade: Enable node upgrade status api

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml

if the upgrade status is called at a later step we don't want to
get a 500 error from the API, but instead render the usual json
error response

upgrade: Catch status exceptions during prechecks on cloud7

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb

Before is the compute node fully upgraded, we upgrade only selected
services that are needed for instances live-migration.
The configuration needs to be adapted as well, to be able to talk
to upgraded services at controller nodes.

upgrade: Adapt the swift configuration on compute nodes

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

'all' triggers the upgrade of all nodes
'controllers' upgrades only controller nodes
<NAME> upgrades the node identified by NAME

upgrade: Enable different modes for upgrading the nodes

---

crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/app/models/node.rb

If node_upgrade_state is saved into the node object, it could get
rewritten from chef-client running at the node.

upgrade: Save 'node_upgrade_state' into the role, not node

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

Partial backport of https://github.com/crowbar/crowbar-core/pull/1062 - node status should be just always empty here

[stable/3.0] Enable node upgrade status api 

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

Original ready_after_upgrade? is not 100% correct, there are still some
later node actions after this is set. So let's check node.upgraded?
However, this does only return correct results during the upgrade, so
additional check if full upgrade is finished is needed.
Requires https://github.com/crowbar/crowbar-core/pull/1071

upgrade: Change the check for list of upgraded/not upgraded nodes

---

chef/cookbooks/provisioner/templates/default/tftp.service.erb

It seems that a variety of tftp clients can be picky about
the options, so there is a mechanism to restrict what
options the server offers to the clients to increase compatibility
with a wide variety of clients.
The qemu uefi tftp client doesnt seem to work very well negotiating the
blocksize. Forcing it to be 1024 makes it work.

provisioner: set blocksize option on tftp server to 1024

---

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/app/models/crowbar_service.rb

Similar to the previous "node_upgrade_state" change this is done to
prevent a race condition with a chef-client running on the node that
might overwrite "crowbar_wall".

upgrade: Move "crowbar_upgrade_step" attribute to node role

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/lib/crowbar/checks/maintenance.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

Before the upgrade starts we need to check if Cloud6 and SOC6 repos
are correctly in place so user can get the latest updates.
UPDATE: By using the same method as for "admin repo check", we're actually checking for products, not repositories. That's actually https://bugzilla.suse.com/show_bug.cgi?id=999946
This should be fixed (for all usages of the method), I'd propose in some later PR....

upgrade: Precheck for Cloud6 repositories

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/models/api/upgrade_spec.rb

1st commit is about the fix of https://github.com/crowbar/crowbar-core/pull/1088
Surprisingly, this was not properly checked when merging .
@skazi0 with 2nd commit, we actually can make the check somewhat usable even with the products - if user did not clean Cloud7/SP2 repos after cancel, this should show an error in next precheck.

upgrade: Fix showing missing repositories in prechecks

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

As part of the node upgrade we're replacing all the product repositories
with the ones from the new product version. To be able to cleanup
correctly we need disable the old product repositories in crowbar (i.e.
remove the associated data bags) before the repository configuration
files (/etc/crowbar/repos.yml and ./crowbar_framework/config/repos-*.yml)
are replaced.
If the upgrade is canceled, we re-enable them.
(cherry picked from commit 394221e1a3859d2c4c5185b7b0a2f33bb121aed6)

Disable all current repos before starting the upgrade

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

This removes some redundancy from the condtions by which we try to
figure out the best upgrade method (disruptive vs. non-distruptive).
It also adds a more specific wording to the description of the unit
tests.

upgrade: simplify conditions for determining best upgrade method

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

Ceph nodes should already be upgraded, there's no need to
mark an upgrade step there and it would be wrong to shut down
their services.
TODO: start chef-client & crowbar_join on ceph nodes, move them to ready state -missing, will be done in a followup

upgrade: Do not touch ceph nodes during services shutdown

---

chef/cookbooks/dhcp/providers/host.rb
chef/cookbooks/dhcp/providers/subnet.rb
chef/cookbooks/dhcp/recipes/default.rb

We don't want to start the dhcp server in that case, it should stay
stopped.

dhcp: Don't send restart notifications to dhcp server if PXE is disabled

---

crowbar_framework/app/assets/javascripts/application.js
crowbar_framework/app/controllers/api/backups_controller.rb

After we did some minor changes to the API v2 we forgot to adapt the
backup code as well. This change adapts the code to work with the latest
API version.

backup: Fix backup upload

---

chef/cookbooks/crowbar/templates/default/crowbar-router-migration.sh.erb

This uses the newly introduced "--exit-on-first-failure" argument for
neutron-ha-tool to immediately exit when a single router migration
fails.
We want the user to give a chance to debug/fix failing router
migrations to prevent all routers going offline at once in case
something is wrong on the target nodes (e.g. non-running l2-agents).
https://bugzilla.suse.com/show_bug.cgi?id=1020914

update: Error out on first failed router-migration (bsc#1020914)

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

We need to track the upgrade mode that is decided at the start of upgrade, so we can later do different upgrade actions for disruptive and non-disruptive upgrade.
Saves the info into the file that we are already using for similar purposes

upgrade: Save the upgrade mode into the progress library

---

crowbar_framework/app/controllers/repositories_controller.rb

This might make it easier to debug/fix problems with the new
repositories when upgarding.

upgrade: Allow access to the repositories page during the Upgrade

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

This is just a cleanup, we use symbols mostly in the progress library, so let's do it for substeps as well.

Unify values we save in progress library to symbols

---

chef/cookbooks/crowbar/files/default/crowbar
chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb
chef/cookbooks/provisioner/templates/default/autoyast.xml.erb
chef/cookbooks/provisioner/templates/default/crowbar_join.redhat.sh.erb
chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
chef/cookbooks/provisioner/templates/default/crowbar_join.ubuntu.sh.erb
chef/cookbooks/provisioner/templates/default/net-post-install.sh.erb
chef/cookbooks/provisioner/templates/suse/crowbar_register.erb

This is not really helpful (it's way too detailed), and this exposes
potentially sensitive data.
https://bugzilla.suse.com/show_bug.cgi?id=1023972

provisioner: Stop calling crowbar_join with --debug (bsc#1023972)

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

Ceph nodes were upgraded independently, we need to make them ready again.
When the upgrade is finished, all nodes should be ready. UPDATE: Actually we might do it earlier, e.g. before all other nodes.
Executes crowbar_join on ceph  nodes.

upgrade: Bring ceph nodes back to ready state

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-prepare-repositories.sh.erb

Since we now disable all repositories in crowbar before starting the
upgrade, we don't have a definitive list of repos to remove anymore.
So we just remove all configured repositories from the node. This
shouldn't do any harm as the nodes' repositories should be managed by
crowbar anyway.
We needed to adapt this because of: https://github.com/crowbar/crowbar-core/pull/1094

upgrade: Remove all current repositories from the node to upgrade

---

crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

We need to make writing of progress library atomic.
While saving, we load the data under the same lock as is used for writing.

upgrade: Before saving updated progress, read the latest from file

---

chef/cookbooks/crowbar/templates/default/crowbar-chef-upgraded.sh.erb
chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb

Some existing cron jobs might try to start services that were
not fully configured yet.

upgrade: Disable cron during the node upgrade

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml

Newton's Swift does not allow number of replicas bigger than number
of disks.

upgrade: Check if Swift configuration is compatible with the upgrade

---

updates/control.sh

(cherry picked from commit b5288b8fe588b86e741299bd2378a6e683fb8e6e)
backport of #502
https://bugzilla.suse.com/show_bug.cgi?id=985422
There seems to have been a behaviour change of fdisk
in that it does not write out a newly created partition table
if there are no other changes
we switch to parted to create the partition table with unique ID instead

workaround bootloader installed to wrong disk (bsc#985422)

---

crowbar_framework/app/models/api/upgrade.rb

If substep is immediatelly following after previous successfull
substep, we have to mark it as running (like controller nodes
after ceph ones).

upgrade: Mark the next substep as running

---

crowbar.yml
crowbar_framework/app/controllers/ceph_pre_upgrade_controller.rb
crowbar_framework/app/views/ceph_pre_upgrade/index.html.haml
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/config/navigation.rb
crowbar_framework/config/routes.rb

Before the Cloud upgrade, ceph nodes must be manually upgraded to
the latest version of SES. Before that, we need to move them to
crowbar_upgrade state.
There is no UI for SES upgrade, but we can provide simple UI for
the preparation that is needed for both SES and following SOC upgrades.
Requires https://github.com/crowbar/crowbar-core/pull/1077

[stable/3.0] Extra page for preparing ceph nodes for the upgrade

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml

Hybrid backend is not upgradable (or is it not supported with Cloud7 at all?), so we are adding precheck at the start of the upgrade.

upgrade: Precheck for keystone hybrid backend.

---

chef/cookbooks/resolver/recipes/default.rb
chef/cookbooks/resolver/templates/default/resolv.conf.erb
chef/data_bags/crowbar/migrate/dns/102_additional_search_domains.rb
chef/data_bags/crowbar/template-dns.json
chef/data_bags/crowbar/template-dns.schema
crowbar_framework/app/models/dns_service.rb
crowbar_framework/app/views/barclamp/dns/_edit_attributes.html.haml
crowbar_framework/config/locales/dns/en.yml

This may be convenient as the domain for the cloud is generally not the
only domain used by the user of the cloud in his infrastructure.
Closes https://github.com/sap-oc/crowbar-core/issues/2

dns: Add ability to configure additional search domains in resolv.conf

---

crowbar_framework/config/initializers/delayed_job_config.rb
crowbar_framework/config/initializers/filter_sql_log.rb

We didnt have traceback logging enabled for
delayed jobs. This enables it and also filters
the SQL insert/update for them from the crowbar
log as to not pollute the log with uneeded and
unreadable lines

delayed_jobs: Enable traceback logging

---

crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb

The services step call shutdown_services_before_upgrade which tries to
call "sudo ssh ...". Avoid that by mocking the ssh_cmd method.
This should fix local rspec runs. 
(Apart from a log message it doesn't seem to be an issue in  travis. See e.g.: https://travis-ci.org/crowbar/crowbar-core/builds/206615051#L890)

upgrade: avoid sudo/ssh calls during unit tests

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/error/upgrade_status.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

This is needed as we want to provide a way to force a "normal" upgrade on system that would support a "non-disruptive" upgrade.
This PR also include quite a bit of cleanup and fixes for the related unit tests.
As this got a bit more complex than initially expected as decided to split this into two pull requests. This one just changes the status library. The follow up PR will add the new Rest API .

upgrade:Allow overriding the detected upgrade mode

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml

We only allow lbaas v2 during the upgrade.
UPDATE: Added check if lbaas config is active. If I read https://docs.openstack.org/admin-guide/networking-adv-features.html#basic-load-balancer-as-a-service-operations correctly, pool is needed for all other kind of objects, so I'm only listing pools in the check ... correct me if I'm wrong

upgrade: Precheck for lbaas version

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/routes.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

Base on the recent status library changes it is now possible to request
a certain upgrade mode using POST/GET on /api/upgrade/mode.

upgrade: New API to set/get the current upgrade mode

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

When an action is being done to set of nodes, we should
indicate the list of nodes being processed via the status library.

upgrade: Save the state of more nodes being upgraded at once

---

crowbar_framework/spec/spec_helper.rb

The old way of creating the temporary filename for the status file
during the unit test caused a lot of test failures lately, because the
state file randomly disappeared during the test. This seemed to be
caused by our weird usage of Tempfile.open() and File.unlink().
This commit changes the code to generate a just temporary filename
(instead of actually creating and deleting the file again). File
deletion now happens explicitly in an "after"-hook.

Try to fix tempfile handling for UpgradeStatus lib

---

crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

Partial backport of https://github.com/crowbar/crowbar-core/pull/1060 (commit related to status library)
Partial backport of https://github.com/crowbar/crowbar-core/pull/1133 (only parts related to status library)

[stable/3.0] sync the status library changes with master

---

crowbar_framework/config/puma.rb

For debugging we should log puma's std{out,err}.

crowbar: Log puma std{out,err}

---

crowbar_framework/vendor/assets/javascripts/jquery/nodeList.js

Found while investigating https://bugzilla.suse.com/show_bug.cgi?id=956582
If a role specifies a platform constraint, the JavaScript validation will
try to enforce this when assigning a cluster to that role.  But, clusters
don't actually have platform information attached, so the check will always
fail (this isn't a problem for platform *exclusion* tests, which effectively
work by accident).  This commit skips all platform checks for clusters,
which seems to be the approach taken by the backend code in service_object.rb
(violates_platform_constraint? and violates_exclude_platform_constraint?)

Don't do platform checks against clusters in JS validation

---

chef/cookbooks/provisioner/recipes/setup_base_images.rb

If for some reason /srv/tftpboot/validation.pem gets overwritten, then
it's impossible to allocate new nodes. We should make sure that
we converge properly here.
Also, using a File resource is much more chef-y than the bash code.
(cherry picked from commit 686b95a2ad2316dee010320aecec285c7faf94fd)
Backport of https://github.com/crowbar/crowbar-core/pull/750

[3.0] provisioner: Ensure /srv/tftpboot/validation.pem is correct

---

chef/cookbooks/barclamp/libraries/barclamp_library.rb
crowbar_framework/app/models/node_object.rb

Uses World Wide Name as most persistent name for disks
Cherry-picked from 5697817479c0a7a71805d5935e09a46d95aaa62c

[3.0] Uses World Wide Name as most persistent name for disks (bsc#1022302)

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/fixtures/data_bags/template-cinder.json
crowbar_framework/spec/models/api/crowbar_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

cinder-volume needs to be configured with HA to enable non-disruptive upgrade

upgrade: Add a precheck for cinder-volume backends

---

crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/fixtures/upgrade_status.json
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb

It seems useful to show more about what we are doing to nodes,
especially when it takes more time.
This extends the previous information saved as part of current_node,
which is marked only at the beginning and end of upgrade.

upgrade: Save more detailed information about current upgrade activity

---

crowbar_framework/lib/crowbar/upgrade_status.rb

To make the progress file better readable (e.g. in one page in terminal window), let's try to remove
some unnecessary information like the empty error hash for each
step.
This is how the progress file looks now (without the errors hashes removed):
```
---
:current_step: :nodes
:current_substep: :controller_nodes
:current_node:
:remaining_nodes: 3
:upgraded_nodes: 2 
:crowbar_backup: "/var/lib/crowbar/backup/crowbar_upgrade_1489054667.tar.gz"
:openstack_backup: "/var/lib/crowbar/backup/6-to-7-openstack_dump.sql.gz"
:suggested_upgrade_mode: :normal
:selected_upgrade_mode:
:steps:
:prechecks:
:status: :passed
:errors: {}
:prepare:
:status: :passed
:errors: {}
:backup_crowbar:
:status: :passed
:errors: {}
:repocheck_crowbar:
:status: :passed
:errors: {}
:admin:
:status: :passed
:errors: {} …
```

upgrade: Do not save the empty error hash to the progress file

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/fixtures/offline_chef/node_ceph.crowbar.com.json
crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json
crowbar_framework/spec/models/api/upgrade_spec.rb

Nodes that do not hold controller role but are not compute nodes
must be upgraded before compute nodes, so live migration
(executed during compute nodes upgrade) can rely on fully upgraded
services.
Currently conflicts with https://github.com/crowbar/crowbar-core/pull/1126 with `upgrade_one_node` method

upgrade: Upgrade the nodes that are neither controllers nor compute

---

crowbar_framework/lib/crowbar/upgrade_status.rb

To make the progress file better trackable, let's try to remove
some unnecessary information like the empty error hash for each
step.
(cherry picked from commit bd00154d666ca1358ba22e1d27d826358f409731)
Backport of https://github.com/crowbar/crowbar-core/pull/1140

[stable/3.0] upgrade: Do not save the empty error hash to the progress file

---

crowbar_framework/lib/crowbar/upgrade_status.rb

Once the upgrade is finished, there's no point in showing the 'current' information that was used during the upgrade.

upgrade: Cleanup the current progress at the end of upgrade

---

chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/app/models/node.rb
crowbar_framework/lib/crowbar/error.rb
crowbar_framework/lib/crowbar/error/upgrade.rb
crowbar_framework/spec/fixtures/data_bags/template-cinder.json
crowbar_framework/spec/fixtures/data_bags/template-database.json
crowbar_framework/spec/fixtures/data_bags/template-nova.json
crowbar_framework/spec/fixtures/offline_chef/node_drbd.crowbar.com.json
crowbar_framework/spec/models/api/upgrade_spec.rb

Disruptive upgrade is needed for users without the setup that allows non-disruptive upgrade
Implements the proposal described at https://etherpad.nue.suse.com/p/cloud-upgrade-disruptive
**For followup** 
- ~~Showing some nice status when doing paralel parts: https://github.com/crowbar/crowbar-core/pull/1133~~ **Merged**
- More paralelization (currently it is done only for OS upgrade of nodes)

Disruptive upgrade

---

chef/cookbooks/provisioner/recipes/update_nodes.rb
chef/cookbooks/provisioner/templates/default/autoyast.xml.erb

After the installation, but before chef is run, DNS resolution won't
work without this. This is critical in case the repositories are
configured with a DNS name, as this means the nodes won't be able to be
automatically configured (since packages won't be installable).
https://bugzilla.suse.com/show_bug.cgi?id=1026837
requests?**

provisioner: Define nameservers in autoyast.xml (bsc#1026837)

---

chef/cookbooks/network/recipes/default.rb

If a physical interface has VLAN(s) configured with a custom MTU set but
the underlying physical network is not used directly and has no MTU in
its config, use the MTU from the VLAN interface for the parent device.
If there are multiple VLANs, use the highest MTU for the parent.

network: Set MTU for VLAN parent interface (bsc#1024279)

---

chef/cookbooks/network/recipes/default.rb

Commit 46998819996 introduced a regression which cause the wicked
ifrelaod to be never actually called. Which reintroduced the original
bug that caused new deployments to loose their network connectivity
after the very first reboot.

network: Really run wicked ifreload when ifcfg files change (refix bsc#1011889)

---

crowbar_framework/app/models/provisioner_service.rb

Commit ff6d7d14f9d3a802b463b4f07c6f87fd3cfd0a06 missed to
move one call to the proper Repository namespace

provisioner: fix wrong parameter call

---

crowbar_framework/app/models/api/upgrade.rb

Somehow this slipped into the main code, I thought I've already removed those...
UPDATE: OK, actually all those arguments should be passed correctly, so there's probably no bug here. Anyway, it's unnecessary.

upgrade: Do not rewrite global value of upgrade_mode

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml

Tries to provide a small help or refer to the HA docs in case of failures
on the cluster resources. Also moves the references of the node names
to the data field and pairs the node name with the error found at it.
In the crowbar backend for the upgrade usually it seems data contain error message and help has additional message. For some cases though, the help part is not helpful at all.
In the "help" part there should probably be something pointing to the possible solution, like reading the troubleshooting section of documentation, or trying the cleanup the resources errors via crm.
Provides a generic+documents to try to help the user fixing the underlying issue.
**Is there additional information worth sharing like links …

upgrade: provide better help for pacemaker issues

---

crowbar_framework/spec/spec_helper.rb

The old way of creating the temporary filename for the status file
during the unit test caused a lot of test failures lately, because the
state file randomly disappeared during the test. This seemed to be
caused by our weird usage of Tempfile.open() and File.unlink().
This commit changes the code to generate a just temporary filename
(instead of actually creating and deleting the file again). File
deletion now happens explicitly in an "after"-hook.
(cherry picked from commit 8166dc1417b36061330cfbe3c0e619b723a69d3f)
Backport of https://github.com/crowbar/crowbar-core/pull/1137

[3.0] Try to fix tempfile handling for UpgradeStatus lib

---

chef/cookbooks/network/recipes/default.rb
chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
chef/cookbooks/network/templates/default/suse-cfg.erb

During a clean shutdown wicked will delete any ovs bridges that it feels
responsible for. This means that any customer settings on tha brigde
will get lost and need to be restored. As we set a custom datapath_id
for our bridge to prevent bsc#1022074. We need to restore that setting
when the bridge is recreated during startup. Normally chef-client would
do that as part of crowbar_join, but we also need it to happen when the
admin server is down for some reason.
OTOH, when the node is shutdown uncleanly (e.g. during a fencing
operation) the ovs bridge will not get deleted, which for the bridges
that are touch by the neutron-openvswitch-agent means they will stay in
"secure" mode (without any flows defined) even after reboot. This means
that the node will be disconnected until …

Restore ovs bridge settings after reboot (bsc#1029180, bsc#1029179)

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml

Tries to provide a small help or refer to the HA docs in case of failures
on the cluster resources. Also moves the references of the node names
to the data field and pairs the node name with the error found at it.
(cherry picked from commit ba5f4bad3f53c556f788411471810fb37dc5f2c2)

[3.0] upgrade: provide better help for pacemaker issues

---

crowbar_framework/lib/crowbar/error/upgrade_status.rb
crowbar_framework/lib/crowbar/upgrade_status.rb
crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

upgrade: Extend running? method to check if any step is running (bsc#1028950)
(cherry picked from commit ad0d13e8f86c0842bf993c72a3d3adf49d7d7ec1)
Backport.
requests?**
https://bugzilla.suse.com/show_bug.cgi?id=1028950

[3.0] upgrade: Extend running? method to check if any step is running (bsc#1028950)

---

crowbar_framework/app/controllers/api/upgrade_controller.rb

When some compute node was already upgraded, the 'nodes' step is left as running
(the change is indicated by substep state value).
But user might want to upgrade all remaining compute nodes by using 'all' argument,
so we should not try executing the start_step command in this case.

upgrade: Allow running 'upgrade nodes all' after previous upgrade of a compute node

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/models/api/crowbar_spec.rb

(cherry picked from commit 393830d098d33abbc089a9005d21e897a13deb9b)
Backport of https://github.com/crowbar/crowbar-core/pull/1108
We do not actually need ceph health checks on cloud7 side, but we need the check if Ceph (SES) addon is installed, so the repocheck for nodes can correctly activate also SES repositories.

upgrade: Fixes for ceph cluster health checks

---

crowbar_framework/app/models/api/crowbar.rb

this provides an error message that syncs the node with the actual error
in order to show it properly to the user on the error message
Backport of https://github.com/crowbar/crowbar-ha/pull/185 adapted to 3.0

[3.0] upgrade: Provide a better error

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/fixtures/offline_chef/role_cinder-controller.json
crowbar_framework/spec/models/api/crowbar_spec.rb

1. Make really sure controller nodes are HA
2. Make sure compute nodes do not have controller roles.
1+2 are the checks that when failing, still allow "normal" upgrade
3. Make sure nova-compute cannot go before nova-controller
3 is a special case of 2, (as described in https://github.com/crowbar/crowbar-core/pull/1109#issuecomment-285008466), but does not allow any kind of upgrade. So it belongs to extra method with `required = true`

upgrade: Extend the deployment prechecks

---

crowbar_framework/app/models/api/node.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_timeouts.rb
crowbar_framework/spec/lib/crowbar/upgrade_timeouts_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

Have all the timeouts for upgrade related timeouts on the
same location and makes it easier to track and change them at any time

upgrade: use constants for scripts timeouts

---

crowbar_framework/lib/crowbar/upgrade_status.rb

Provide the step that is currently running in the error output
for more clarity
Not necessary but provides a better error message
Provide the step that is currently running in the error output
for more clarity
requests?**
Maybe complementary to https://trello.com/c/OolO2TT3/368-s57p14-bsc-1028950-confusing-message-when-running-crowbarctl-upgrade-repocheck-crowbar

upgrade: better error output for wrong step order

---

chef/cookbooks/network/recipes/default.rb

Commit 46998819996 introduced a regression which cause the wicked
ifreload to be never actually called. Which reintroduced the original
bug that caused new deployments to loose their network connectivity
after the very first reboot.

[stable/3.0] network: Really run wicked ifreload when needed (refix bsc#1011889)

---

chef/cookbooks/network/recipes/default.rb
chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
chef/cookbooks/network/templates/default/suse-cfg.erb

During a clean shutdown wicked will delete any ovs bridges that it feels
responsible for. OTOH, when the node is shutdown uncleanly (e.g. during
a fencing operation) the ovs bridge will not get deleted, which for the
bridges that are touched by the neutron-openvswitch-agent means they
will stay in "secure" mode (without any flows defined) even after
reboot.  This means that the node will be disconnected until
neutron-openvswitch-agent is started. To prevent this we now reset the
bridge's fail-mode before the interface is coming up.

[stable/3.0] Restore ovs bridge settings after reboot (bsc#1029179)

---

crowbar_framework/app/controllers/api/upgrade_controller.rb
crowbar_framework/config/locales/crowbar/en.yml

When there was some exception during prechecks execution, the info was
stored in the status file but not returned to the client as a response.
Instead a generic 500 response was generated by the framework as a result
of exception propagation.
Now the exceptions are caught in the controller and returned in proper
JSON response.
requests?**
https://trello.com/c/39CCSguR/329-ui-failures-on-crowbar-crash

upgrade: Expose precheck failures to client

---

crowbar_framework/app/models/api/upgrade.rb

As Api::Upgrade is used only as a singleton, we can't use initialize() to set up the @timeouts variable.
It changes @timeouts to method which will load the timeouts on demand.

upgrade: Fix timeouts initialization

---

crowbar_framework/app/models/api/upgrade.rb

It is possible the service was already stopped by the first (failed)
run of 'services' step so during a retry, check for running instances
could not be done again.

upgrade: Check if nova-api is running before using it

---

crowbar_framework/app/controllers/docs_controller.rb

Documentation served from crowbar should be available during upgrade.

upgrade: Allow access to docs during upgrade

---

crowbar_framework/lib/crowbar/upgrade_status.rb

Provide the step that is currently running in the error output
for more clarity
(cherry picked from commit 192165d4a4bc2af4139d827a5613be627231fcb1)

[3.0] upgrade: better error output for wrong step order

---

crowbar_framework/app/controllers/backups_controller.rb

After crowbar-client >= 3.2.2 the backup params are sent differenty.
We need to account for that and make the params be able to deal with both
ways of sending the params.
To fix the Jenkis CI job https://ci.suse.de/view/Cloud/view/Cloud6/job/cloud-mkcloud6-job-backup-restore-x86_64/
Also to prevent any customers to update crowbar-client on a cloud 6 and fail to be able to do a backup.
It allows for both types of arguments to be send to the backup endpoint. One for crowbar-client >= 3.2.2 and for older versions.
**Is there …

backup: Fix upload params

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/fixtures/data_bags/template-cinder.json
crowbar_framework/spec/models/api/crowbar_spec.rb

Backend for cinder cannot be raw or local for non-disruptive upgrade.
This reverts commit 26a195da0d22fb99efc127542a2b1e28c8049c72 and brings commit 7281972c3b4a7d7fbc0d5308708a75c7696d124c back.

upgrade: Precheck to make sure cinder is using correct backend

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/models/api/crowbar_spec.rb

The non-disruptive process supports only limited number of cluster
configurations.
This precheck is there to verify that the detected configuration matches one of the whitelisted options.
requests?**
https://trello.com/c/of0FMzfd/361-s57p6-5-add-upgrade-precheck-for-unusual-configs-that-might-not-work-for-our-process

upgrade: Precheck for supported cluster configs

---

crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/models/api/crowbar_spec.rb

1. Precheck for presence of non-KVM nodes
2. Remove rest of XEN specific searches
3. Deployment check needs to check all compute nodes (relevant for disruptive upgrade)

upgrade: Remove checking for XEN nodes

---

crowbar.yml
crowbar_framework/config/navigation.rb

Without proper entry in crowbar.yml the link would be removed by `barclamp_install`.
Add upgrade entry in crowbar.yml and fix key in navigation.rb.
requests?**
this is a followup for PR #664
https://trello.com/c/cdtWLx6h/391-2-s58p5-add-the-upgrade-link-from-crowbar-ui

upgrade: Fix upgrade link

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
crowbar_framework/app/models/api/crowbar.rb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/config/locales/crowbar/en.yml
crowbar_framework/spec/models/api/crowbar_spec.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

If they are any XEN compute nodes, the would be upgraded in normal
mode only.
Other 2 commits are port of https://github.com/crowbar/crowbar-core/pull/1189

upgrade: Do not treat xen nodes upgradable in non-disruptive mode

---

crowbar_framework/app/models/api/node.rb

It may happen that the script executing crowbar_join succeeded,
although the chef-client run left the node in non-ready state.
In such case, remove the indication, so the step could be restarted,
otherwise it would be skipped during restart.

upgrade: Remove success indication for crowbar_join run when node is not ready

---

crowbar_framework/lib/schema_migration.rb

Schema migration code checked for local postgresql service even if
the actual config used remote database.
Simple check was added for the database host configured in the application.

Fix schema migration for remote PSQL

---

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb

At SP2, systemctl disable complains when disabling service that is not installed.
This is normally not a problem, since we execute this code at SP1 (Cloud6)
nodes only, but it can fail in the corner case when user has Ceph nodes, upgrades them
(so they have SP2 and are staying in the crowbar-upgrade state) and the reapplies
some barclamp (e.g. for fixing some setting required for the Cloud upgrade).

upgrade: Do not try to disable non-existing service

---

configs/crowbar-jobs.service
configs/crowbar.service

With remote postgresql service, it's not possible for crowbar(-jobs) to `Require=` postgresql.
Use `Wants=` which is a less strict alternative.
requests?**
See systemd docs for more details: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Wants=

Loosen crowbar/psql service dependencies

---

chef/cookbooks/crowbar/templates/default/crowbar-delete-pacemaker-resources.sh.erb
chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb

It's not necessary to delete remote primitives during the upgrade,
the agents aren't systemd based.  (*EDIT for clarity:* we have to delete primitives for LSB resources to allow upgrading them to `systemd` resources.)

upgrade: Do not delete remote resources

---

chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb

Stopping corosync (unlike stopping pacemaker) initiates also sbd stop.
But it cat take some time to stop sbd so wait until it is really down
before proceeding with other actions.

upgrade: Shutdown corosync instead of pacemaker and wait for sbd to stop

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-lbaas-evacuation.sh.erb
chef/cookbooks/crowbar/templates/default/lbaas-connection.conf
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_timeouts.rb
crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
crowbar_framework/spec/lib/crowbar/upgrade_timeouts_spec.rb

When evacuating the neutron routers from a network node before upgrading
it also evacuate any existing LBaaSv2 load balancers.
This needs: https://github.com/SUSE-Cloud/cookbook-openstack-network/pull/29

upgrade: evacuate LBaaSv2 loadbalancers

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb
chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.sh.erb
crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

We should not manually restart services at remote nodes if these services are managed by pacemaker.
~TODO: after node upgrade, nova-compute is not immediately started (not with chef-client run on the node). It's probably started by chef-client run on cluster node, but I assume we cannot afford that.~
~crm status shows `cl-g-nova-compute` and `remote-d52-54-77-77-01-05` stopped for freshly upgraded node. So it should be possible to just restart these somehow?~
~`crm node ready` might help...~ -> implemented in 4th commit

upgrade: Correctly restart services managed by pacemaker at remote nodes

---

chef/cookbooks/crowbar/templates/default/crowbar-rails.conf.partial.erb
configs/crowbar-rails.conf.partial

At the moment we have several different timeouts in crowbar (apache, pume, old CLI, new CLI).
Syncing the timeout to one common timeout (60min).
requests?**
https://github.com/SUSE-Cloud/automation/pull/1859

apache: Set timeout to 3600 to sync with the common crowbar timeout

---

chef/cookbooks/network/recipes/default.rb

Calling ifreload here seems to have been a bad idea as it cause various
issue in HA setups:
- pacemaker mananged VIPs assigned to any of the reloaded interfaces are
temporary lost, Causing resource failures in the cluster.
- reloading an interface causes a small network outage that can
de-stabilize the cluster, leading to fenced nodes and other bad
things.
https://bugzilla.suse.com/show_bug.cgi?id=1032751
(cherry picked from commit 41e310cf21642cf0dc2f2fa0b7294c1db7821b59)

Revert wicked ifreload related changes (bsc#1032751)

---

crowbar_framework/app/models/api/crowbar.rb

After prepare call, nodes can't be found using roles anymore. Some of the prechecks which rely on this are not prepared to not find the nodes they expect.
Code relying on nodes found by role is guarded with additional condition.
requests?**
Problem was reported in commends under https://bugzilla.suse.com/show_bug.cgi?id=1032377

upgrade: Fix prechecks after prepare

---

crowbar_framework/app/controllers/api/upgrade_controller.rb

Exceptions are caught in api endpoints to return proper json responses instead of default 500.html. This disables default exception handling and doesn't log the backtraces to production.log.
The backtraces need to be manualy logged to not lose this information. Already existing function log_exception() was used for logging.

upgrade: Log api exceptions to production.log

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/lib/crowbar/upgrade_timeouts.rb

It takes some time before nova-compute finishes starting.
So let's wait until we know it is running before proceeding with next
live-migration.
Followup after https://github.com/crowbar/crowbar-core/pull/1181

upgrade: After changing node state to ready, wait for nova-compute to start

---

chef/cookbooks/crowbar/templates/default/crowbar-chef-upgraded.sh.erb

When crowbar_join fails, user should know about it. Until now, the success indication was created even after crowbar_join failure. That means that user cannot repeat this step because it appears as correctly finished.
Check the exit value of crowbar_join.

upgrade: Check the return value of initial crowbar_join

---

chef/cookbooks/updater/recipes/default.rb

Force a refresh for the PTF repository in the updater barclamp
before updating, to make sure that PTF packages are picked up
regardless of the minimum repository auto-refresh delay.
Fixes [bsc#1030462](https://bugzilla.suse.com/show_bug.cgi?id=1030462)

updater: refresh PTF repository (bsc#1030462) 

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
chef/cookbooks/crowbar/templates/default/crowbar-chef-upgraded.sh.erb

Download and execute latest crowbar_join from the provisioner server
so it is not rewritten during chef-client run.

upgrade: Download the latest crowbar_join from the server

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb

When the controller nodes are not the same as the network nodes, we have
to retrieve the SQL connection needed for the lbaasv2 migration from the
neutron server.
Reference: https://bugzilla.suse.com/show_bug.cgi?id=1033632

Fix for lbaasv2 migration with several clusters

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

When non-kvm compute nodes do not have other role
(that would group them with 'controller' or 'other' nodes)
we need to remember to upgrade them during compute_nodes substep.
We didn't see this before probably because xen nodes in other tests had some additional role, so they were upgraded before the real compute_nodes substep (which is not a problem in "normal" mode).

upgrade: Do not skip non-kvm nodes

---

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb

neutron-agents, nova-compute and libvirtd are managed by cluster
and should only be stopped from there

upgrade: Do not stop services at remote node

---

crowbar_framework/app/controllers/nodes_controller.rb

We were not excluding the admin node from the target_platform and license_key checks as
it doesnt have an allocated value sent on POST.
Also, we didnt check for a blank value (nil or empty or "") in the public_name values.
Both of this issues triggered a save of all nodes, even if the values were the same.

Fix node bulk edit to save only the changed nodes (bsc#1008838)

---

crowbar_framework/config/initializers/puma_worker_killer.rb

This change disables the puma reaper logs which look like
`PumaWorkerKiller: Consuming 100 mb with master and 2 workers.`.

puma: Disable puma_worker_killer reaper logs

---

crowbar_framework/app/models/api/upgrade.rb
crowbar_framework/spec/models/api/upgrade_spec.rb

We've met some situations where the node was not upgraded during the controller phase, but was also missing nova-compute role. The effect was that such node was not upgraded at all.
UPDATE: Bug 1035528 is dedicated to this situation I was referring to

upgrade: Make sure to upgrade all nodes in normal node

---

crowbar_framework/app/views/barclamp/dns/_edit_attributes.html.haml
crowbar_framework/config/locales/dns/en.yml

The domain field should not be changed after deployment. Chef uses this
field to identify nodes, including the admin node, and changing it
causes crowbar and chef to be able to unable to fetch data about a node.
This changes makes the field in the DNS barclamp UI disabled and adds a
note about it to discourage trying to make this change.

dns: Disable domain field in UI (bsc#1033537)

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

The previous change accidentally always only handled "x86_64" because
it was never looking up the machine's architecture but only the fallback
case.

provisioner: Fix UEFI on non-x86 hosts again

---

chef/cookbooks/network/recipes/default.rb

Previously we allowed custom MTU values only for the "admin", "storage"
and "os_sdn" networks. This prevents users to create custom networks
with MTU!=1500 so allow custom MTUs for all networks.
For example, a network.json containing a network like:
"storageclient": {
"add_bridge": false,
"broadcast": "10.1.5.255",
"conduit": "intf4",
"mtu": 9000,
"netmask": "255.255.255.0",
"ranges": {
"host": {
"end": "10.1.5.239",
"start": "10.1.5.10"
}
}
works now.

network: Allow custom MTU for all networks (bsc#1024277)

---

chef/cookbooks/network/recipes/default.rb

Previously we allowed custom MTU values only for the "admin", "storage"
and "os_sdn" networks. This prevents users to create custom networks
with MTU!=1500 so allow custom MTUs for all networks.
For example, a network.json containing a network like:
"storageclient": {
"add_bridge": false,
"broadcast": "10.1.5.255",
"conduit": "intf4",
"mtu": 9000,
"netmask": "255.255.255.0",
"ranges": {
"host": {
"end": "10.1.5.239",
"start": "10.1.5.10"
}
}
works now.
(cherry picked from commit 9d242e6bab5d79dfaa04a04f803b8efc0fa2e022)

[3.0] network: Allow custom MTU for all networks (bsc#1024277)

---

chef/cookbooks/provisioner/recipes/update_nodes.rb

If the IP range for the admin network is too small, then an allocated node may not get an admin IP address. In that case, we should not crash (current behavior), nor should we proceed with the installation process.
Instead, we re-run discovery for that node to get that fixed (this will be fixed eventually, if a free IP address appears).

provisioner: Don't crash if a node is moved past discovery without an admin IP address

---

chef/cookbooks/crowbar/templates/default/crowbar-post-upgrade.sh.erb

We should try to do a better detection that the replication has started and is running.
So, the first output, after the drbd is started might look like
```
postgresql role:Secondary
disk:Inconsistent
d52-54-77-77-01-01 connection:Connecting
```
Then we have the replication phase, looking like
```
postgresql role:Secondary
disk:Inconsistent
d52-54-77-77-01-01 role:Primary
replication:SyncTarget peer-disk:UpToDate done:0.08
```
After this is done, drbd reports something like this:
```
postgresql role:Secondary
disk:UpToDate
d52-54-77-77-01-01 role:Primary
peer-disk:UpToDate
```

upgrade: Use more robust check to ensure DRBD replication started (bsc#1038826)

---

bin/network-json-resolve
crowbar_framework/lib/crowbar/conduit_resolver.rb

When debugging data from a deployment that we don't have access to, we
usually only get json describing the nodes and the network.json file.
Without direct access to the chef-server, we can't query chef to get the
data about the node.
So add a --node-json option to allow not using chef to get that
information. If used together with --network-json, it means we need no
access to chef-server at all.

Enhance network-json-resolve to also work with exported json for nodes

---

crowbar_framework/app/models/service_object.rb

For admin nodes, we were calling single_chef_client.sh. The problem is
that this calls looper_chef_client.sh and can enter a never-ending loop
if looper_chef_client.sh was not run before, or if
/var/run/crowbar/looper-chef-client.lock is not existing. The latter
condition is true whenever the crowbar service is restarted.
This basically means that if applying a proposal that involves the admin
server after the crowbar service has been restarted, we can have this
block for quite some time.
It turns out that we don't need to call single_chef_client.sh anymore
and can use chef-client directly instead: single_chef_client.sh was
created in the days where chef had no locking to avoid concurrent runs,
since the admin server had some other chef runs started by crowbar (on
transitions, for …

crowbar: Call chef-client instead of single_chef_client.sh on apply

---

crowbar_framework/app/models/service_object.rb

When a chef call fails in apply_role, we try a second time to run chef.
However, for admin nodes, we were not remembering the pid/host pair
correctly, resulting in the second chef call to be invalid (for no
host).
This resulted in the creation of /var/log/crowbar/chef-client/.log,
which is a long-standing bug.

crowbar: Fix re-running chef after failure in apply_role for admin nodes

---

crowbar_framework/app/models/node_object.rb
crowbar_framework/app/models/service_object.rb

When we add a role to a node, we need the role in the run_list_map and
in the run_list, but if it was in one or the other, we were not doing
anything. This resulted in semi-broken setups (which could happen due to
crashes, or manual editing) not getting fixed when re-applying a
barclamp.
Now, when we change the run_list, we really ensure that it's how we want
it to be.
(cherry picked from commit b341f0b9b7ec70e6b2131f94ef3f39e6da60a89b)

[3.0] crowbar: Ensure run_list is how we want it to be

---

chef/cookbooks/barclamp/libraries/nic.rb
chef/cookbooks/network/recipes/default.rb
chef/cookbooks/network/templates/default/interfaces.erb
chef/cookbooks/network/templates/default/redhat-cfg.erb
chef/cookbooks/network/templates/default/suse-cfg.erb
chef/data_bags/crowbar/migrate/network/101_add_bonding_miimon_xmit_hash_policy.rb
chef/data_bags/crowbar/template-network.json
chef/data_bags/crowbar/template-network.schema

Add support for the xmit_hash_policy property of NIC bonding to be queried
and set, as well as adding the existing miimon property and new
xmit_hash_policy property to the network schema.
Drive-by correctly setting miimon rather than hardcoding 100 for the
interfaces(5) template.

network: Add support for xmit_hash_policy (bsc#1033917)

---

crowbar_framework/config/crowbar.env

Crowbar 5.0 development started, which will be shipped in Cloud 8.

crowbar: Change version to 5.0

---

chef/cookbooks/barclamp/libraries/nic.rb
chef/cookbooks/network/recipes/default.rb
chef/cookbooks/network/templates/default/interfaces.erb
chef/cookbooks/network/templates/default/redhat-cfg.erb
chef/cookbooks/network/templates/default/suse-cfg.erb
chef/data_bags/crowbar/migrate/network/022_add_bonding_miimon_xmit_hash_policy.rb
chef/data_bags/crowbar/template-network.json
chef/data_bags/crowbar/template-network.schema

Add support for the xmit_hash_policy property of NIC bonding to be queried
and set, as well as adding the existing miimon property and new
xmit_hash_policy property to the network schema.
Add support for miimon to be set (or overloaded) on a per-network basis,
like xmit_hash_policy.
Drive-by correctly setting miimon rather than hardcoding 100 for the
interfaces(5) template.
(cherry picked from commit 08559ef)

[3.0] network: Add support for xmit_hash_policy (bsc#1033917)

---

crowbar_framework/Gemfile

Newer versions of rails-observers need ruby 2.2.2 which is not shipped
on SLES.

Gemfile: Lock rails-observers to <= 0.1.2

---

chef/data_bags/crowbar/migrate/network/101_add_bonding_miimon_xmit_hash_policy.rb

When downgrading the schema after applying xmit_hash_policy, we should
iterate over the conduits defined and remove team_miimon and
team_xmit_hash_policy if they exist.
I'm not 100% certain it is, but it addresses a bug in the original migration as it landed.
requests?**

network: Also remove optional keys during downgrade

---

chef/cookbooks/barclamp/libraries/nic.rb
chef/cookbooks/network/recipes/default.rb

Currently, when adding slaves to a bond, the interface will be brought
down and then back up. If wicked is not told about this state of
affairs, wicked will add the configured IP address back onto the
interface when it is bought back up.
To counteract this, we run wicked ifdown for any slave interface, and
then run wicked ifup once the template files have been written.
requests?**

network: Use wicked to control bond slaves (bsc#1035127)

---

crowbar_framework/Gemfile

Newer versions of rails-observers need ruby 2.2.2 which is not shipped
on SLES.
(cherry picked from commit 9f6d3a7dc76659a128b38476aa238d2d9e937067)

[stable/3.0] Gemfile: Lock rails-observers to <= 0.1.2

---

crowbar_framework/config/repos-cloud.yml
crowbar_framework/lib/crowbar/product.rb

SUSE Enterprise Storage 5 (SES5) is only built for SP3, while
SES4 is only built for SP2.
Only SES4 is deployable with crowbar.
(We tried to switch everything to SP3 in https://github.com/crowbar/crowbar-core/pull/1247)
~Also this (or some extension of it) will be needed https://github.com/SUSE-Cloud/automation/pull/2002~

Remove SES5 references; support SES4 which is based on SP2.

---

chef/cookbooks/network/attributes/default.rb

Look for "Merge openvswitch and openvswitch-switch into a single package since there
was no compelling reason to keep the switch functionality in a separate subpackage" in https://build.suse.de/package/rdiff/SUSE:SLE-12-SP3:GA/openvswitch?linkrev=base&rev=2

openvswitch-switch package was merged with main package in SLES12SP3

---

chef/cookbooks/network/recipes/default.rb

When 08559ef4d6d0c32fd1244b2cdaccf0cb41947553 was cherry-picked from
stable/4.0, it missed one change -- network.conduit is not defined in
stable/3.0, and is instead named conduit.
requests?**

[stable/3.0] network: Correct checking for per-bond settings

---

chef/data_bags/crowbar/migrate/network/022_add_bonding_miimon_xmit_hash_policy.rb

When downgrading the schema after applying xmit_hash_policy, we should
iterate over the conduits defined and remove team_miimon and
team_xmit_hash_policy.
(cherry picked from commit 02ec0507069c2e23fc2aabe540d5e545f71966b5)
requests?**

[stable/3.0] network: Also remove optional keys during downgrade

---

chef/data_bags/crowbar/migrate/network/101_add_bonding_miimon_xmit_hash_policy.rb

When downgrading the schema after applying xmit_hash_policy, we should
iterate over the conduits defined and remove team_miimon and
team_xmit_hash_policy.
(cherry picked from commit 02ec0507069c2e23fc2aabe540d5e545f71966b5)
requests?**

[stable/4.0] network: Also remove optional keys during downgrade
