chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
otherwise, we would add ourselves to the list of valid ntp servers
and timeout later
=> stop ntp server before checking for ntp availability

bin/crowbar_batch
input_file got dropped with the move to ARGF.
=> batch: Fix use of non-existing variable

chef/cookbooks/provisioner/recipes/bootdisk.rb, updates/control.sh, updates/control_lib.sh
This pull request adopt barclamp-provisioner for SLES_12 based images
=> Changes for SLES_12 based sleshammer

crowbar_framework/app/assets/javascripts/jquery/dynamicTable.js, crowbar_framework/app/assets/javascripts/jquery/nodeList.js
Obsoletes https://github.com/crowbar/crowbar-core/pull/75 and https://github.com/crowbar/crowbar-core/pull/74
=> Fixed jquery event triggering

chef/cookbooks/bind9/recipes/default.rb, chef/cookbooks/logging/recipes/common.rb, chef/cookbooks/nfs-server/recipes/default.rb, chef/cookbooks/ntp/recipes/default.rb
Also fix outdated Chef resource syntax.
=> avoid case where bind9 was started without named.conf

chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/default.elilo.erb, chef/cookbooks/provisioner/templates/default/default.erb, chef/cookbooks/provisioner/templates/default/grub.conf.erb
These are just some bits I fixed during multi-architecture, but that aren't related to this.
=> Minor fixes in provisioner

chef/cookbooks/provisioner/libraries/repositories.rb, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/data_bags/crowbar/migrate/provisioner/031_remove_autoyast_repos.rb, chef/data_bags/crowbar/template-provisioner.json, chef/data_bags/crowbar/template-provisioner.schema, crowbar_framework/app/controllers/repositories_controller.rb, crowbar_framework/app/helpers/application_helper.rb, crowbar_framework/app/helpers/repositories_helper.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/app/views/nodes/_form.html.haml, crowbar_framework/app/views/repositories/index.html.haml, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/config/repos-cloud.yml, crowbar_framework/config/repos-ses.yml, crowbar_framework/config/repos.yml, crowbar_framework/config/routes.rb, crowbar_framework/lib/crowbar/repository.rb, crowbar_framework/spec/lib/crowbar/repositories_spec.rb
This is a follow up to https://github.com/crowbar/crowbar-core/pull/18.
Comments not addressed yet:
=> Followup PR to fix issues in new repo magic

chef/cookbooks/provisioner/libraries/repositories.rb, chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb, chef/cookbooks/repos/recipes/default.rb, chef/data_bags/crowbar/migrate/provisioner/032_arch_repos.rb, chef/data_bags/crowbar/template-provisioner.json, chef/data_bags/crowbar/template-provisioner.schema, chef/roles/provisioner-server.rb, crowbar_framework/app/controllers/repositories_controller.rb, crowbar_framework/app/helpers/application_helper.rb, crowbar_framework/app/helpers/form_helper.rb, crowbar_framework/app/helpers/repositories_helper.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/app/views/nodes/_form.html.haml, crowbar_framework/app/views/nodes/list.html.haml, crowbar_framework/app/views/repositories/index.html.haml, crowbar_framework/config/repos-cloud.yml, crowbar_framework/config/repos-ses.yml, crowbar_framework/lib/crowbar/repository.rb, crowbar_framework/spec/lib/crowbar/repositories_spec.rb
~~Note that this contains https://github.com/crowbar/crowbar-core/pull/81 and https://github.com/crowbar/crowbar-core/pull/82 https://github.com/crowbar/crowbar-core/pull/84, so please review these first.~~
Also, this depends on https://github.com/SUSE-Cloud/automation/pull/613.
=> Support multiple architecture for repo layout and OS attributes

chef/cookbooks/provisioner/recipes/dhcp_update.rb, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/data_bags/crowbar/template-provisioner.json
~~Note that this contains https://github.com/crowbar/crowbar-core/pull/84 https://github.com/crowbar/crowbar-core/pull/83.~~
=> provisioner: Support for discovery/allocation of ppc64le nodes

chef/cookbooks/utils/providers/line.rb, chef/cookbooks/utils/resources/line.rb
The search is done with regex expressions and the replace is string
https://github.com/crowbar/crowbar-core/pull/96
reopening for idiomatic chef
=> Adding the functionality to search and replace a line

chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
It's missing the architecture.
=> provisioner: Fix URL to crowbar_register script

chef/cookbooks/network/recipes/default.rb, chef/cookbooks/network/templates/default/suse-cfg.erb
They are no longer needed with the latest wicked (>= 0.6.28)
=> Don't create ovs-system related pieces anymore

chef/cookbooks/provisioner/libraries/repositories.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/lib/crowbar/repository.rb
cc @tboerger @MaximilianMeister
=> Go back to one data bag item per repository

chef/cookbooks/barclamp/libraries/barclamp_library.rb, chef/cookbooks/bind9/recipes/default.rb, chef/cookbooks/nfs-client/recipes/default.rb, chef/cookbooks/updater/recipes/default.rb, chef/data_bags/crowbar/migrate/network/010_add_rx_offloading.rb, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/models/nfs_client_service.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/app/models/proposal.rb, crowbar_framework/app/models/service_object.rb, crowbar_framework/app/models/updater_service.rb
According to our now master of style, Hash#has_key? is deprecated in
favor of Hash#key?.  (https://github.com/bbatsov/ruby-style-guide#hash-key)
=> Avoid HoundCI bitching about has_key?

crowbar_framework/lib/crowbar/checks/network.rb
The crowbar user is part of the sudoer's so we can just run iptables
as root.
=> Run iptables network check as root (bsc#955984)

crowbar_framework/app/assets/javascripts/installer.js, crowbar_framework/lib/crowbar/installer.rb
otherwise a reload of the page is necessary after triggering the
install
=> installer fixup: don't fail on empty steps

chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/helpers/form_helper.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/app/views/nodes/_form.html.haml, crowbar_framework/config/locales/crowbar/en.yml
Tested manually. 
The fs type values were took from /etc/sysconfig/storage
=> Added option to select FS type for a node.

crowbar_framework/app/controllers/installers_controller.rb, crowbar_framework/lib/crowbar/installer.rb
=> refactoring the installers_controller responses

crowbar_framework/storage/.gitignore
This PR is needed to prepare #144.
=> Add storage folder to store data in development environment

bin/barclamp_lib.rb, bin/crowbar, bin/crowbar_batch, bin/crowbar_machines, bin/crowbar_network, bin/crowbar_node_state, chef/cookbooks/crowbar/files/default/crowbar.sh, chef/cookbooks/crowbar/recipes/default.rb
**There are also some missing parts for the crowbar-client, tracked at ~~https://github.com/crowbar/crowbar-client/issues/31~~, ~~https://github.com/crowbar/crowbar-client/issues/30~~, ~~https://github.com/crowbar/crowbar-client/issues/29~~ and ~~https://github.com/crowbar/crowbar-client/issues/28~~**
~~The new crowbar-client itself requires https://github.com/crowbar/crowbar-core/pull/104 as well to work properly.~~
=> Old cli tools wrapper rewrite

bin/barclamp_lib.rb, bin/crowbar, bin/crowbar_batch, bin/crowbar_machines, bin/crowbar_network, bin/crowbar_node_state, chef/cookbooks/crowbar/files/default/crowbar.sh, chef/cookbooks/crowbar/recipes/default.rb
Reverts crowbar/crowbar-core#129
=> Revert "Old cli tools wrapper rewrite"

crowbar_framework/app/assets/javascripts/installer.js, crowbar_framework/app/controllers/installers_controller.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/checks/network.rb, crowbar_framework/lib/crowbar/installer.rb, crowbar_framework/lib/crowbar/validator/network_validator.rb
this will replace the check in the installation script
As long as the network.json is not valid, the user is not
allowed to start the installation
cc @vuntz
=> add network.json validation

chef/cookbooks/network/templates/default/suse-cfg.erb
Also some smaller adjustments to the formatting. Hopefully slighly better
readable now.
=> Added some clarifying comments to ifcfg template

crowbar_framework/app/models/ipmi_service.rb
They clearly come from copy & paste.
=> Fix debug messages in state transition for IPMI barclamp

chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb, chef/data_bags/crowbar/migrate/provisioner/034_os_upgrading_state.rb, chef/data_bags/crowbar/template-provisioner.json, crowbar_framework/app/controllers/barclamp_controller.rb, crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/app/models/node_object.rb
This is the contains the base work for an autoyast profile to upgrade a SLE11 openstack controller to SLE12-SP1.
Currently this just creates autoyast-upgrade.xml just in parallel to the "normal" autoyast profile and hardcodes the autoupgrade parameter into the pxe config for all nodes that get allocated. This was just done to be able to test the profile. The final solution will have to handle it differently of course. This PR is just meant to be input for whoever is going to implement the "upgrade" state in crowbar.
=> AutoYaST Upgrade profile

crowbar_framework/app/assets/javascripts/barclamps/crowbar/application.js, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/config/locales/crowbar/en.yml
This pull request is required to be able to update the assigned group of a node properly through the crowbar-client. The pull requests for the client implementation is in progress.
=> Give a proper json response on node group change

chef/cookbooks/crowbar/recipes/crowbar-db-dump.rb, chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, crowbar_framework/app/models/crowbar_service.rb
Followup for https://github.com/crowbar/crowbar-core/pull/179
=> Cleanup stopping openstack and pacemaker

chef/cookbooks/crowbar/recipes/crowbar-db-dump.rb, chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, crowbar_framework/app/models/crowbar_service.rb
cc @rhafer 
Backport to tex: https://github.com/crowbar/barclamp-crowbar/pull/1365
=> Nicer recognition of current step in the upgrade process.

crowbar_framework/app/models/backup.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/backup/export.rb, crowbar_framework/lib/crowbar/backup/restore.rb, crowbar_framework/lib/crowbar/upgrade.rb, crowbar_framework/spec/models/backup_spec.rb
https://trello.com/c/9tQEIY2K/573-5-p1-5-finishing-crowbar-backup-restore-upgrade-pr
=> Fixups for Crowbar Backup/Restore

chef/cookbooks/provisioner/recipes/update_nodes.rb
node.macaddress can't be used for that as that might be changing. Depending on
which interface is used for the default route it might even point to a
ovs-bridge or bond device. This fix is required for the operating system
upgrade process.
=> Use pxe config for correct mac address (admin interface)

crowbar_framework/app/controllers/backups_controller.rb, crowbar_framework/app/models/backup.rb
This makes it possible to download an image by the name. Specilly for
the crowbar-client this is very helpful.
=> Backup: Search by name and id

crowbar_framework/lib/crowbar/upgrade.rb
* rename files/content from nova_dashboard to horizon
* getting rid of DRY
* make more use of the Pathname Object
I hope I caught all the specific places/files where we need to rename/sed nova_dashboard to horizon...
I have just performed a `grep -R nova_dashboard *` and a `find . | grep nova_dashboard` inside the cloud5 backup.
=> migrate horizon renaming and refactor knife upgrade

crowbar_framework/app/models/crowbar_service.rb
This is needed to keep the non-core Cookbooks from being executed when a
node is coming back to "ready" after performing and OS upgrade. It's supposed
to be called before running the actual upgrade (i.e. before calling
prepare_nodes_for_os_upgrade()). Unfortunately we can't use
ServiceObject.destroy_active() for this, because that would cause (queued)
chef-client runs on the non-upgrades nodes. We don't want that here.
=> Added method to disable all non-core Proposals

crowbar_framework/app/models/crowbar_service.rb
(bugs found during testing on Cloud6)
=> Fixes for crowbar service

crowbar_framework/lib/crowbar/upgrade.rb
=> remove unwanted attributes.rails as it cannot be restored

crowbar_framework/app/controllers/backups_controller.rb, crowbar_framework/config/initializers/wrap.rb
Obsoletes https://github.com/crowbar/crowbar-client/pull/64
=> Wrap parameters

crowbar_framework/lib/crowbar/backup/restore.rb, crowbar_framework/lib/crowbar/upgrade.rb, crowbar_framework/lib/schema_migration.rb
=> make sure to update the (core) proposals that are already created

crowbar_framework/app/models/backup.rb, crowbar_framework/lib/crowbar/backup/export.rb, crowbar_framework/lib/crowbar/backup/restore.rb, crowbar_framework/spec/models/backup_spec.rb
discussion happened in https://github.com/crowbar/crowbar-core/pull/199
cc @rhafer @vuntz
=> preserve ownership/permissions on backup and restore

crowbar_framework/app/helpers/nodes_helper.rb
@rsalevsky  is this what you need for the Upgrade UI?
=> Fill Upgrade related counters with real values

crowbar_framework/app/controllers/ucs_controller.rb
Resolve errors during login to UCS manager from crowbar UI.
s/True/true/ and s/False/false/.
=> Fix login to UCS Manager

crowbar_framework/public/docs/cisco_ucs.md, crowbar_framework/public/docs/ucs_vm1.xml
Added a sample .xml file for running the emulator using KVM with additional steps for clarity.
=> Update documentation to run UCS emulator.

crowbar_framework/app/models/crowbar_service.rb
Relying on chef search to find relevant nodes which have the element roles
assinged doesn't work as the nodes are in "crowbar_upgrade" state, where they
the lack the element roles.
This implementation also reduces the amount of node.save calls to one per node.
=> Rework and fix "disable_non_core_proposals"

chef/cookbooks/crowbar/recipes/crowbar-db-dump.rb
=> Indicate the node where the dump is actually located

crowbar_framework/app/models/service_object.rb
This needs to be backported to tex if approved.
=> Fix issues when failing to acquire a lock on apply

crowbar_framework/app/assets/javascripts/application.js, crowbar_framework/app/assets/javascripts/upgrader.js, crowbar_framework/app/controllers/application_controller.rb, crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/helpers/installer/upgrades_helper.rb, crowbar_framework/app/views/installer/upgrades/_nav.html.haml, crowbar_framework/app/views/installer/upgrades/backup.html.haml, crowbar_framework/app/views/installer/upgrades/finish.html.haml, crowbar_framework/app/views/installer/upgrades/install.html.haml, crowbar_framework/app/views/installer/upgrades/nodes.html.haml, crowbar_framework/app/views/installer/upgrades/repos.html.haml, crowbar_framework/app/views/installer/upgrades/restore.haml, crowbar_framework/app/views/installer/upgrades/services.html.haml, crowbar_framework/app/views/installer/upgrades/start.html.haml, crowbar_framework/app/views/layouts/application.html.haml, crowbar_framework/config/initializers/assets.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/config/routes.rb
https://github.com/crowbar/crowbar-openstack/pull/224 is required
=> Upgrader backend

crowbar_framework/lib/crowbar/checks/network.rb
system call already returns a bool
so we can just return it as is
@rsalevsky might want to review this change of his code
=> simplify ping_succeeds and firewall_disabled

chef/cookbooks/crowbar-hacks/recipes/default.rb
https://bugzilla.suse.com/show_bug.cgi?id=964327
=> deployer: Fix wrong reference to variable (bsc#964327)

crowbar_framework/lib/crowbar/repository.rb
I'm not sure why this check was missing, possibly there was a reason for that? @MaximilianMeister
=> Check if repository is physically available.

crowbar_framework/lib/crowbar/logger/formatter.rb
It's not really an ID (I think it's the pointer to the thread object),
but it's good enough to allow us finding which log line is for a
specific thread.
With threads, logs look like this:
I, [2016-02-01T14:27:51.597500 #9963:0x00000002dece50]  INFO -- Completed 200 OK in 28ms (Views: 1.0ms | ActiveRecord: 0.2ms)
Without threads, they look like this:
I, [2016-02-01T14:39:47.425383 #11702]  INFO -- Completed 200 OK in 544ms (Views: 0.8ms | ActiveRecord: 0.0ms)
=> crowbar: Improve logging to also contain a thread "id"

crowbar_framework/app/controllers/barclamp_controller.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/app/models/service_object.rb, crowbar_framework/app/models/tableless.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/config/routes.rb
Those API endpoints are required for the crowbar-client, that way we keep the client as a pure API wrapper.
**Required for https://github.com/crowbar/crowbar-client/pull/46**
=> Integrated API for proposal and node reset

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
Needed to start new version of postgresql.
=> rename postgres data directory after data dump

chef/cookbooks/crowbar/files/default/crowbar-sessions-sweep.cron, chef/cookbooks/crowbar/recipes/default.rb, configs/crowbar-sessions-sweep.cron, crowbar_framework/lib/tasks/sessions.rake
This is not done automatically by rails, and is important to do. See
http://guides.rubyonrails.org/security.html#session-expiry
=> crowbar: Add rake task and cron job to sweep sessions from database

crowbar_framework/config/initializers/sqlite_transaction_monkey_patch.rb
This is of course not a perfect solution, and can still fail after the
retries.
I still believe that there's a deeper issue because every time this
happens, it seems that two threads (not necessarily in the same worker,
though) are entering a deadlock while acquiring the sqlite lock while
this clearly should not happen (one should acquire the lock, while the
other would be blocked on acquiring).
But it makes the original bug extremely hard to reproduce now with the
following stress test:
- having 8 nodes being rediscovered in a loop (this requires removing
the nodes from the core proposals, and transitioning them from
discovering to discovered)
- having 10 requests to crowbar listing the nodes (and therefore
creating sessions in the database) in a loop …
=> crowbar: Retry transaction when sqlite is busy (bsc#963738)

crowbar_framework/app/assets/javascripts/installer.js, crowbar_framework/app/controllers/installer/installers_controller.rb
https://bugzilla.suse.com/show_bug.cgi?id=958766
=> bsc#958766 fix failed installation not returning any error message

crowbar_framework/app/controllers/utils/batch_controller.rb, crowbar_framework/app/models/batch/base.rb, crowbar_framework/app/models/batch/build.rb, crowbar_framework/app/models/batch/export.rb, crowbar_framework/config/routes.rb, crowbar_framework/lib/utils/extended_hash.rb
This API can directly get used by the new crowbarctl. I'm storing the exported batch configs on the file system, later on we can provide them for downloading multiple times on an index page.
=> Integrated batch export API

crowbar_framework/app/helpers/installer/upgrades_helper.rb
=> Return true if repos are present (or not needed)

crowbar_framework/config/locales/crowbar/en.yml
This is based on https://github.com/rhafer/crowbar-core/commit/a30d6fc4e6b7dd85dc9aa795e487ac605dc6fa20 but without #278.
=> Add proper i18n strings for the upgrade process

crowbar_framework/config/navigation.rb
=> crowbar: Fix default navigation

crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/app/views/installer/upgrades/backup.html.haml, crowbar_framework/config/locales/crowbar/en.yml
Check if database proposal exists in case,
when somebody is trying to upgrade undeployed nodes
or only with Ceph cluster
=> Check if database proposal exists in CrowbarService::dump_openstack_database

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, chef/cookbooks/crowbar/recipes/stop-services-before-upgrade.rb
Not yet tested, still investigating it this can help...
=> Fixes for shutting down pacemaker resources

crowbar_framework/lib/crowbar/backup/restore.rb
any idea where this databag comes from?
=> exclude swift databag

crowbar_framework/app/controllers/barclamp_controller.rb
trying to create a nova proposal without neutron led to the page
"We are sorry, but something went wrong"
=> catch RuntimeError instead of failing

crowbar_framework/app/controllers/ucs_controller.rb
=> crowbar: Do not create cisco-ucs credentials.xml file world-readable

crowbar_framework/app/assets/javascripts/application.js
https://bugzilla.suse.com/show_bug.cgi?id=966356
=> bsc#966356 selectors were OR chained, not AND

crowbar_framework/config/locales/crowbar/en.yml
Update the wizard i18n with the last changes from @kwwii.
=> Update update wizard i18n

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
"df" is returning kilobytes (making that more explicit by adding the -k
option).  The db_dump we use returns bytes. Convert that to kilobytes and add
some additional reserve (currently 10MB).
=> Use the same units when comparing for enough diskspace

crowbar_framework/lib/crowbar/backup/base.rb
At least on tex, we backup these files...
=> crowbar: Add missing files to backup

crowbar_framework/lib/crowbar/backup/base.rb
install-chef-suse will pick up the files from there
=> also backup /etc/crowbar to restore before the installation

chef/cookbooks/bind9/recipes/default.rb
This is needed to avoid a running cloud accessing the (incomplete) DNS info
that the admin node would handout when the installer runs as that might cause
services to fail when upgrading the admin node.
Ideally we would reconfigure bind to only listen on 127.0.0.1 during that
stage, but that requires some more changes as dnsmasq is already running on
that (to be done in a later commit).
https://bugzilla.suse.com/show_bug.cgi?id=966419
=> Reject incoming DNS requests while restoring/upgrading (bsc#966419)

chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb
An attempt to fix https://bugzilla.suse.com/show_bug.cgi?id=966452
=> Cleanup old openvswitch config during the upgrade

crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/models/backup.rb, crowbar_framework/config/locales/crowbar/en.yml
but only when it is not an upgrade
=> don't allow restoring backup from different crowbar version

crowbar_framework/app/models/crowbar_service.rb
@rhafer fist test shows that this approach is actually working
=> Remove the crowbar_upgrade role from all nodes when it is no longer needed

chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/data_bags/crowbar/migrate/provisioner/035_discovery_append.rb, chef/data_bags/crowbar/template-provisioner.json, chef/data_bags/crowbar/template-provisioner.schema
There's a new discovery.append attribute in the proposal.
=> provisioner: Add ability to set kernel parameters to discovery image

crowbar_framework/app/controllers/backups_controller.rb, crowbar_framework/config/locales/crowbar/en.yml
this is just nicer than saying nothing at all
=> show success message after restore

crowbar_framework/app/models/backup.rb
- create archive only if the name is valid
- run custom validations only in upload case
- don't validate version and size
=> Creating tar only if the backup name is valid (bsc#966424)

crowbar_framework/app/helpers/application_helper.rb, crowbar_framework/public/403.html, crowbar_framework/public/404.html, crowbar_framework/public/422.html, crowbar_framework/public/500.html
=> Switch app name and page name in title (bsc#967423)

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
Alternative solution to https://github.com/crowbar/crowbar-openstack/pull/308
=> Save the location that was used for DB dump to node.

crowbar_framework/app/helpers/application_helper.rb, crowbar_framework/public/403.html, crowbar_framework/public/404.html, crowbar_framework/public/422.html, crowbar_framework/public/500.html
(cherry picked from commit f28764b5dabb5d912f701605338d4072804da0ce)
=> 3.0 | Switch app name and page name in title (bsc#967423)

crowbar_framework/app/assets/javascripts/upgrader.js, crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/views/installer/upgrades/restore.html.haml, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/backup/restore.rb, crowbar_framework/lib/crowbar/installer.rb
https://github.com/crowbar/crowbar-core/pull/382
=> [stable/3.0] backport #382

crowbar_framework/app/controllers/backups_controller.rb, crowbar_framework/config/locales/crowbar/en.yml
https://github.com/crowbar/crowbar-core/pull/347
=> [stable/3.0] backport #347

crowbar_framework/app/models/backup.rb, crowbar_framework/lib/crowbar/backup/restore.rb, crowbar_framework/spec/models/backup_spec.rb
https://github.com/crowbar/crowbar-core/pull/361
=> [stable/3.0] backport #361

crowbar_framework/lib/crowbar/backup/restore.rb
https://github.com/crowbar/crowbar-core/pull/381
=> [stable/3.0] backport #381

crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/config/locales/crowbar/en.yml
=> Check if we can ssh to nodes before trying to apply proposal.

crowbar_framework/config/crowbar.env
This PR needs coordination with packaging changes.
=> Raise crowbar version to 4.0

crowbar_framework/app/models/backup.rb, crowbar_framework/db/migrate/20160215120522_add_migration_level_to_backups.rb, crowbar_framework/db/schema.rb, crowbar_framework/lib/crowbar/backup/export.rb, crowbar_framework/lib/crowbar/backup/restore.rb, crowbar_framework/lib/crowbar/migrate.rb, crowbar_framework/spec/models/backup_spec.rb
backup the migration level in the meta.yml, and restore it before loading the database
=> respect the migration level in the backup

crowbar_framework/app/controllers/application_controller.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/installer.rb
=> proper handling of json requests before crowbar is installed

crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/helpers/installer/upgrades_helper.rb, crowbar_framework/config/locales/crowbar/en.yml
=> inform the user that some upgrade steps are repeatable after an error

crowbar_framework/lib/crowbar/backup/restore.rb
=> [stable/3.0] backport #376

crowbar_framework/app/assets/javascripts/application.js, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/helpers/backups_helper.rb, crowbar_framework/app/helpers/installer/upgrades_helper.rb, crowbar_framework/app/helpers/proposals_helper.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/app/views/nodes/_buttons_power.html.haml, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/controllers/nodes_controller_spec.rb
To avoid the situation that it looks like nothing happens we have
removed the AJAX functionality from the power buttons, added a blockui
message, refactored the controller properly to redirect on default html
requests and also refactored the blockui functionality to accept the new
data attribute `data-blockui-click`.
Obsoletes #354
=> Refactor dropdown menu for power actions (bsc#955810)

crowbar_framework/app/models/backup.rb, crowbar_framework/db/migrate/20160215120522_add_migration_level_to_backups.rb, crowbar_framework/db/schema.rb, crowbar_framework/lib/crowbar/backup/export.rb, crowbar_framework/lib/crowbar/backup/restore.rb, crowbar_framework/lib/crowbar/migrate.rb, crowbar_framework/spec/models/backup_spec.rb
=> [stable/3.0] backport #343

crowbar_framework/app/assets/javascripts/application.js, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/helpers/backups_helper.rb, crowbar_framework/app/helpers/installer/upgrades_helper.rb, crowbar_framework/app/helpers/proposals_helper.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/app/views/nodes/_buttons_power.html.haml, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/controllers/nodes_controller_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/375
=> [3.0] Refactor dropdown menu for power actions (bsc#955810)

chef/cookbooks/provisioner/recipes/setup_base_images.rb
This is one commit from https://github.com/crowbar/crowbar-core/pull/164 that can be merged already.
=> provisioner: Rename variable for clarity

crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/helpers/installer/upgrades_helper.rb, crowbar_framework/config/locales/crowbar/en.yml
https://github.com/crowbar/crowbar-core/pull/410
=> [stable/3.0] backport #410

crowbar_framework/app/controllers/application_controller.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/installer.rb
=> [stable/3.0] backport #409

crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/models/backup.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/backup/restore.rb, crowbar_framework/lib/crowbar/upgrade.rb
* add json endpoint for triggering the upgrade from the command line without being redirected (see also https://github.com/SUSE-Cloud/automation/pull/915)
* allow 3.0 to 4.0 upgrade
=> Upgrade additions

crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/models/backup.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/backup/restore.rb, crowbar_framework/lib/crowbar/upgrade.rb
https://github.com/crowbar/crowbar-core/pull/345
~~have to rebase on https://github.com/crowbar/crowbar-core/pull/411 so please wait for it to be merged~~
EDIT: done
=> [stable/3.0] backport #345 and parts of #428

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/config/routes.rb
https://github.com/crowbar/crowbar-core/pull/430
https://github.com/crowbar/crowbar-core/pull/440
=> [stable/3.0] backport #430 and #440

crowbar_framework/app/controllers/backups_controller.rb, crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/models/backup.rb, crowbar_framework/lib/crowbar/backup/restore.rb
Backport of https://github.com/crowbar/crowbar-core/pull/445
=> [3.0] fix too early cleanup of our extracted and upgraded tmpdir

crowbar_framework/lib/crowbar/backup/export.rb, crowbar_framework/spec/fixtures/meta.json, crowbar_framework/spec/fixtures/offline_chef/node_admin.crowbar.com.json, crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json, crowbar_framework/spec/fixtures/offline_chef/nodes_crowbar.json, crowbar_framework/spec/fixtures/offline_chef/roles_crowbar.json, crowbar_framework/spec/lib/crowbar/backup/export_spec.rb, crowbar_framework/spec/models/chef_object_spec.rb, crowbar_framework/spec/support/offline_chef.rb
I think it doesn't hurt to backport the specs, if we make some changes it is good to have
#423
=> [stable/3.0] backport #423

crowbar_framework/app/controllers/installer/upgrades_controller.rb
this avoids redirections when called from mkcloud and opens the
possibility to add an upgrade subcommand to crowbarctl
=> add missing json endpoints for upgrade steps

crowbar_framework/app/controllers/installer/upgrades_controller.rb
https://github.com/crowbar/crowbar-core/pull/453
=> [stable/3.0] backport #453

crowbar_framework/lib/crowbar/chef/upload.rb
this was missing from the last PR
=> Create data_bag before uploading the items

.lgtm
this has been enabled now (see https://github.com/lgtmco/lgtm/issues/11)
=> lgtm: turn off self approvals

crowbar_framework/app/models/node_object.rb
Checks existing disk claims against disks in ohai data and
returns list of unclaimed disks.
Co-Authored-By: Rick Salevsky <rsalevsky@suse.com>
=> Checks disk claims after upgrade

crowbar_framework/lib/crowbar/backup/export.rb
partial fix of https://bugzilla.suse.com/show_bug.cgi?id=972527
=> bsc#972527 make sure to insert a new line character after each forwarder

crowbar_framework/lib/crowbar/backup/base.rb
https://github.com/crowbar/crowbar-core/pull/464
=> [stable/3.0] backport #464

crowbar_framework/app/controllers/application_controller.rb
http://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html
=> only skip verify_authenticity_token on json requests

chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
https://bugzilla.suse.com/show_bug.cgi?id=968251
for making HA glance on shared NFS backend storage work
=> add common glance user+group (bsc#968251)

chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
Backport of https://github.com/crowbar/crowbar-core/pull/414
=> Bsc968251 cloud6

crowbar_framework/app/controllers/installer/upgrades_controller.rb
=> replace find with find_by as we don't use an id

chef/cookbooks/crowbar-hacks/recipes/default.rb
=> crowbar-hack: be sure that UEFI is there.

crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/backup/restore.rb, crowbar_framework/lib/schema_migration.rb
Small fix for https://github.com/crowbar/crowbar-core/pull/486.
=> crowbar: Fix upgrade from 3.0

crowbar_framework/app/models/crowbar_service.rb
using fatal logging for debug style logging is not nice
=> Fix incorrect logging levels

chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb
#389 didn't work as expected. I opened this PR to trigger a gating, as @vuntz is likely not available
this hopefully fixes the upgrade CI and would be the better solution for https://github.com/SUSE-Cloud/automation/pull/944
=> enhancing/fixing #389

chef/cookbooks/suse-manager-client/files/default/README, chef/cookbooks/suse-manager-client/recipes/default.rb, chef/data_bags/crowbar/migrate/suse_manager_client/100_only_bootstrap_script_url.rb, chef/data_bags/crowbar/migrate/suse_manager_client/100_remove_activation_key.rb, chef/data_bags/crowbar/template-suse_manager_client.json, chef/data_bags/crowbar/template-suse_manager_client.schema, crowbar_framework/app/helpers/barclamp/suse_manager_client_helper.rb, crowbar_framework/app/views/barclamp/suse_manager_client/_edit_attributes.html.haml, crowbar_framework/config/locales/suse_manager_client/en.yml
Fix suse-manager barclamp to actually work with SP1 clients and prepare it for SP2
=> Fix suse-manager barclamp to actually work with SP1 clients

chef/cookbooks/barclamp/libraries/nic.rb
This is actually triggered on SLE 12 SP2.
=> barclamp: Fix potential infinite loop in Nic.dependent

chef/cookbooks/barclamp/libraries/barclamp_library.rb, crowbar_framework/app/models/node_object.rb
This was part of https://github.com/crowbar/crowbar-core/pull/427
(this is just the small part of that other PR that I think is fully correct and can go in)
Co-Authored-By: Jiří Suchomel <jiri.suchomel@suse.com>
=> chef, crowbar: Fix unclaiming a disk with no owner

bin/crowbar_batch
It got broken when we stopped uploading the proposal templates as data
bags.
=> Fix crowbar batch export

crowbar_framework/app/controllers/machines_controller.rb, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/helpers/application_helper.rb, crowbar_framework/app/helpers/form_helper.rb, crowbar_framework/app/helpers/nodes_helper.rb, crowbar_framework/app/helpers/repositories_helper.rb, crowbar_framework/app/models/chef_object.rb, crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/app/models/service_object.rb, crowbar_framework/app/views/barclamp/_index.html.haml, crowbar_framework/app/views/barclamp/proposal_show.html.haml, crowbar_framework/app/views/barclamp/show.html.haml, crowbar_framework/app/views/nodes/_buttons_chef.html.haml, crowbar_framework/app/views/nodes/_form.html.haml, crowbar_framework/app/views/nodes/families.html.haml, crowbar_framework/app/views/nodes/list.html.haml, crowbar_framework/app/views/repositories/index.html.haml, crowbar_framework/lib/crowbar/platform.rb, crowbar_framework/lib/crowbar/settings.rb, crowbar_framework/spec/models/node_object_spec.rb, crowbar_framework/spec/spec_helper.rb
There's quite some code in there that shouldn't be in this file. So let's start cleaning that up.
FWIW, a lot of the upgrade methods should likely be moved, but I'm unclear where to move them (I don't believe they should go in lib/). I guess someone else could do that in a later PR, though.
=> Move code away from CrowbarService

chef/cookbooks/provisioner/recipes/dhcp_update.rb
We were hardcoding the admin IP address there.
But we want to allow people to host the DNS server on other nodes than the admin-node.
=> provisioner: Fix list of DNS servers hinted by DHCP

chef/cookbooks/utils/libraries/helpers.rb
Depends on https://github.com/crowbar/crowbar-ha/pull/120
=> utils: Use new HA helpers to fetch the VIP of a hostname

crowbar_framework/Gemfile, crowbar_framework/app/controllers/backups_controller.rb, crowbar_framework/app/controllers/barclamp_controller.rb, crowbar_framework/app/controllers/docs_controller.rb, crowbar_framework/app/controllers/installer/installers_controller.rb, crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/controllers/sanities_controller.rb, crowbar_framework/app/controllers/support_controller.rb, crowbar_framework/app/controllers/utils/batch_controller.rb, crowbar_framework/config/boot.rb, crowbar_framework/config/initializers/apipie.rb, crowbar_framework/config/routes.rb
this renders a static site which is currently at `/apidoc` (in this configuration)
https://github.com/Apipie/apipie-rails
=> add some API documentation

crowbar_framework/app/models/node_object.rb, crowbar_framework/app/models/service_object.rb, crowbar_framework/spec/fixtures/offline_chef/role_crowbar-admin_crowbar_com.json, crowbar_framework/spec/fixtures/offline_chef/role_crowbar-testing_crowbar_com.json
This is a recent regression from https://github.com/crowbar/crowbar-core/pull/515
=> Fix deactivation of proposals to really remove roles from nodes

crowbar_framework/app/models/batch/export.rb, crowbar_framework/lib/crowbar/backup/export.rb
this could be used during an upgrade if a user chooses to apply all
barclamps at once
depends on https://github.com/crowbar/crowbar-core/pull/477
=> save a batch file in the backup for convenience

crowbar_framework/config/initializers/filter_sql_log.rb
it could contain sensitive data which you don't want in the logs
=> don't log the raw proposal

crowbar_framework/config/repos-cloud.yml
For some reason or signing key changed. Adjust
=> Fix key checksum

crowbar_framework/app/controllers/barclamp_controller.rb
Was introduced in https://github.com/crowbar/crowbar-core/pull/536 /
27eb9b34.
https://bugzilla.suse.com/show_bug.cgi?id=989966
=> crowbar: Fix bug when fetching status of all proposals (bsc#989966)

crowbar_framework/app/controllers/barclamp_controller.rb
Was part of https://github.com/crowbar/crowbar-core/pull/560
=> crowbar: Fix regression in 1ad06648, with wrong test condition

chef/cookbooks/barclamp/libraries/barclamp_library.rb, chef/cookbooks/dhcp/resources/subnet.rb, chef/cookbooks/network/recipes/default.rb, chef/cookbooks/provisioner/recipes/dhcp_update.rb, chef/data_bags/crowbar/migrate/network/100_add_mtu_os_sdn.rb, chef/data_bags/crowbar/template-network.json
Forward port of https://github.com/crowbar/crowbar-core/pull/503.
=> Neutron mtu master

crowbar_framework/config.ru
After the switch to puma, Rack::Chunked and Rack::ContentLength are
handled by puma.
=> Cleanup config.ru

crowbar_framework/Gemfile, crowbar_framework/config/boot.rb
this will be used for the connecting to postgresql via ruby
=> require the pg gem

crowbar_framework/app/models/service_object.rb
this fixes https://bugzilla.suse.com/show_bug.cgi?id=985987
=> return the proper http code for role not found (bsc#985987)

crowbar_framework/app/models/service_object.rb
this fixes https://bugzilla.suse.com/show_bug.cgi?id=985987
(cherry picked from commit ee92564576116d20148c78430b15bc31076598c6)
=> [stable/3.0] return the proper http code for role not found (bsc#985987)

crowbar_framework/app/models/service_object.rb
has been fixed with:
https://github.com/crowbar/crowbar-core/commit/f229d43f3e5be18043876dce95ece26c50f115ca
=> remove relict of running chef-client 2 times

chef/data_bags/crowbar/template-nfs_client.json, nfs_client.yml
Rewrite the description of the nfs-client barclamp.
=> Rewrite NFS client description

crowbar_framework/app/models/deployer_service.rb
This is a clean up suggested by @rhafer in PR#585.
=> Rewrote assignment into ternary operation

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
It's not needed currently. Note: This commit just removes the chef part of the
database dump. It's just enough to make the upgrade work again. The crowbar
side (i.e. the steps in the upgrade wizard) is not changed.
=> Do not create a postgresql db dump when upgrading

crowbar_framework/lib/crowbar/upgrade.rb
I'm not fully sure this is fully correct, feedback welcome.
=> Add code path for 3.0 to 4.0 upgrade

crowbar_framework/lib/crowbar/upgrade.rb
SchemaMigration.migrate_proposal_from_json needs a proposal hash and
cannot deal with any Chef::Role as the attributes is called
default_attributes (and could be different) and there is no deployment
information either
=> migrate from proposal instead of role

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/upgrade_prechecks.json, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb, crowbar_framework/spec/spec_helper.rb
~~depends on https://github.com/crowbar/crowbar-core/pull/604~~
merged
=> Implement prechecks step

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/upgrade_prechecks.json, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb, crowbar_framework/spec/spec_helper.rb
https://github.com/crowbar/crowbar-core/pull/605
=> [stable/3.0] backport #605

crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb, crowbar_framework/spec/fixtures/crowbar_maintenance.json
this has simply been forgotten
=> add maintenance check to the crowbar_controller

crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb, crowbar_framework/spec/fixtures/crowbar_maintenance.json
this has simply been forgotten
(cherry picked from commit 210e77ef864a4cd980a42eaa6c9a91734ef1bbf1)
=> [stable/3.0] add maintenance check to the crowbar_controller

crowbar_framework/app/models/service_object.rb
When the forked process (used to run the chef-client) exit, the database
connection is closed which leads to errors like:
PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly
We currently catch this exception but we ran recently into something similar:
PG::UnableToSend: server closed the connection unexpectedly
https://bugzilla.suse.com/show_bug.cgi?id=995027
Hopefully this will be fixed when we use threads instead of processes.
=> Run chef-client in a thread instead of a process (bnc#995027)

crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/app/models/node_object.rb
We should do such check before we initiate the upgrade
=> check if HA clusters report some problems

crowbar_framework/app/models/node_object.rb
ssh to the node and wait until the command exits
This is partial forward-port of https://github.com/crowbar/crowbar-core/pull/614 . The other commits from that PR are here: https://github.com/crowbar/crowbar-ha/pull/138
=> Added function to execute command at remote nodes

crowbar_framework/app/models/crowbar_service.rb
it is just Proposal now. the change was a mistake from copying old code
=> ProposalObject does not exist anymore

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, chef/data_bags/crowbar/migrate/crowbar/100_crowbar-upgrade-states.rb, chef/data_bags/crowbar/template-crowbar.json, crowbar_framework/app/models/crowbar_service.rb
This is the addition to https://github.com/crowbar/crowbar-core/pull/628
Needs to be ported to 3.0
=> Additional actions for reverting the upgrade

crowbar_framework/app/helpers/installer/upgrades_helper.rb, crowbar_framework/app/models/api/backup.rb
simplify an if-else statement and two return if statements
=> Simplify if

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/app/models/node_object.rb
additionally added one commit from https://github.com/crowbar/crowbar-core/pull/619
=> [stable/3.0] Invoke cluster health checks

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/config/routes.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
https://github.com/crowbar/crowbar-core/pull/628
=> [stable/3.0] backport #628

crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/config/routes.rb, crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb, crowbar_framework/spec/fixtures/crowbar_repocheck.json, crowbar_framework/spec/fixtures/crowbar_repocheck_zypper.xml, crowbar_framework/spec/fixtures/crowbar_repocheck_zypper_locked.xml, crowbar_framework/spec/models/api/crowbar_spec.rb
https://github.com/crowbar/crowbar-core/pull/630
=> [stable/3.0] backport #630

chef/cookbooks/barclamp/libraries/barclamp_library.rb, chef/cookbooks/ohai/files/default/plugins/crowbar.rb, crowbar_framework/app/models/node_object.rb
Backport of: https://github.com/crowbar/crowbar-core/pull/624
=> [stable/3.0] More nic speeds v3

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/fixtures/upgrade_prechecks.json, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/models/api/crowbar_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/637
=> [stable/3.0] Make ceph cluster health check part of upgrade pre-checks

chef/cookbooks/provisioner/recipes/base.rb
Less error prone than dissecting the lines of string output
=> Use zypper --xmlout for parsing zypper

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, chef/cookbooks/crowbar/recipes/prepare-os-upgrade.rb, chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.erb, crowbar_framework/app/models/crowbar_service.rb
Create an upgrade script on nodes.
=> Prepare the node OS upgrade

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/routes.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Uses research from https://github.com/crowbar/crowbar-core/pull/653  and https://github.com/crowbar/crowbar-core/pull/655
=> Shutdown non-essential services before the upgrade

crowbar_framework/config/repos-cloud.yml
We also need to have Pool/Updates and HA repos
=> Fix repos list for s390x setups

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.erb
Also, fix redirection of logs as in https://github.com/crowbar/crowbar-core/pull/655
=> Fix services recipe

crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/node_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb, crowbar_framework/spec/spec_helper.rb
=> prefer class methods over instance methods and fix the addon availability check

crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/crowbar_object.json, crowbar_framework/spec/fixtures/crowbar_upgrade_status.json, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb, crowbar_framework/spec/spec_helper.rb
https://github.com/crowbar/crowbar-core/pull/674
=> [stable/3.0] partially backport #674

crowbar_framework/app/controllers/nodes_controller.rb
that has been overlooked somehow
=> document node show api

chef/cookbooks/crowbar/templates/default/apache.conf.erb
The [l] is a trick to allow the pattern to be zero in case the file does
not exist at all.
(cherry picked from commit 3e637879bd98ff2d888aaa76a83995de8c560eba)
=> Optional include the crowbar-ui config

crowbar_framework/app/controllers/api/backups_controller.rb, crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/app/controllers/api/errors_controller.rb, crowbar_framework/app/controllers/api/nodes_controller.rb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/controllers/barclamp_controller.rb, crowbar_framework/app/controllers/docs_controller.rb, crowbar_framework/app/controllers/installer/installers_controller.rb, crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/controllers/repositories_controller.rb, crowbar_framework/app/controllers/sanities_controller.rb, crowbar_framework/app/controllers/support_controller.rb, crowbar_framework/app/controllers/utils/batch_controller.rb
=> adding required headers to the api documentation

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/routes.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/models/api/node_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Execute the upgrade action via
`curl -s -X POST -H "Accept: application/vnd.crowbar.v2.0+json" localhost:3000/api/upgrade/nodes`
(after the initialization done in `services` step)
=> Orchestrate the upgrade of first controller node

chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/crowbar/templates/default/apache.conf.erb, chef/cookbooks/crowbar/templates/default/crowbar-rails.conf.partial.erb, configs/crowbar.conf
This change enables crowbar-ui while crowbar-init is running.
=> Cleanup apache conf

chef/cookbooks/crowbar/recipes/default.rb, crowbar_framework/Gemfile, crowbar_framework/config/boot.rb
Please review but don't merge yet. I need to coordinate this with some build service changes.
=> Switch to non prefixed mime-types package

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb
this has been accidentally not cherry-picked in #683
=> [stable/3.0] add missing target_platform method and target_platform cleanup on the node

crowbar_framework/config/repos-cloud.yml
We don't need Mitaka staging anymore, allow Newton staging
=> Allow the Newton repositories

crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/checks/maintenance.rb, crowbar_framework/lib/crowbar/checks/network.rb, crowbar_framework/lib/crowbar/sanity.rb, crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/crowbar_maintenance.json, crowbar_framework/spec/fixtures/upgrade_prechecks.json, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/lib/crowbar/checks/maintenance_spec.rb, crowbar_framework/spec/lib/crowbar/checks/network_spec.rb, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb, crowbar_framework/spec/spec_helper.rb
as https://github.com/crowbar/crowbar-core/pull/672 can't be merged yet due to the CI/infrastructure, and also because it is green and has 2 approvals, I decided to already open the backporting PR here to speed up the UI/Service integration
cc @skazi0
=> [stable/3.0] backport #672

crowbar_framework/app/models/service_object.rb
The reboot handler at the end of a chef run will cause /sbin/reboot,
which will result in the ssh session with chef-client to be suddenly
closed, resulting in what looks like a failure.
However, if we reach that reboot handler, then the chef run actually
completed since the handlers are run after the run itself.
This should fix the case of Xen compute nodes that cause the nova
proposal to fail to apply.
=> crowbar: Properly handle nodes rebooting at the end of chef

crowbar_framework/app/controllers/backups_controller.rb
this makes it easier to integrate with crowbar-ui
=> [stable/3.0] return backup instead of just 200

crowbar_framework/lib/crowbar/lock.rb, crowbar_framework/lib/crowbar/lock/local_blocking.rb, crowbar_framework/lib/crowbar/lock/shared_non_blocking.rb, crowbar_framework/spec/lib/crowbar/lock/local_blocking_spec.rb
This will be needed for https://github.com/crowbar/crowbar-core/pull/692
=> Added shared locks

crowbar_framework/app/controllers/api/backups_controller.rb, crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/app/controllers/api/errors_controller.rb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/controllers/barclamp_controller.rb, crowbar_framework/app/controllers/installer/installers_controller.rb, crowbar_framework/app/controllers/installer/upgrades_controller.rb, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/controllers/repositories_controller.rb, crowbar_framework/app/controllers/sanities_controller.rb
=> add error codes to the api docs

crowbar_framework/lib/crowbar/lock.rb, crowbar_framework/lib/crowbar/lock/local_blocking.rb, crowbar_framework/lib/crowbar/lock/shared_non_blocking.rb, crowbar_framework/spec/lib/crowbar/lock/local_blocking_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/719
=> [stable/3.0] Added shared locks

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/upgrade_prechecks.json, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
This is based on responses introduced in https://github.com/crowbar/crowbar-core/pull/672
Requires https://github.com/crowbar/crowbar-ha/pull/147 for HA presence check
=> Adapt the checks API to what pre-checks is expecting

crowbar_framework/config/boot.rb, crowbar_framework/config/routes.rb
We can't load crowbar-init in the development env via a Gemfile.
=> Only load crowbar-init in production

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
otherwise we run into problems when trying to access hash keys
=> symbolize all keys

crowbar_framework/app/models/api/upgrade.rb
=> Always return the result of a check if ha is present

crowbar_framework/app/controllers/api/upgrade_controller.rb
Depends on: https://github.com/crowbar/crowbar-core/pull/721
=> apidocs: update /api/crowbar/repocheck example to sync with the real output from the api

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/upgrade_prechecks.json, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Mostly it's backport of https://github.com/crowbar/crowbar-core/pull/729 + parts of https://github.com/crowbar/crowbar-core/pull/689/commits/905dbae00e267e21fdeda314eae76b11536e4e5d
=> [stable/3.0] Backport various pre-check commits to 3.0

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/upgrade_prechecks.json, crowbar_framework/spec/models/api/upgrade_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/744
=> [stable/3.0] determine the best upgrade mode

crowbar_framework/app/models/api/upgrade.rb
https://github.com/crowbar/crowbar-core/pull/748
=> [stable/3.0] Backport #748

crowbar_framework/app/models/api/upgrade.rb
Use the proper versions of suse linux and suse cloud for the 6->7 upgrade
=> Use the proper checks for the upgrade 6 -> 7

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/756
=> Show the response from cluster health check in the upgrade prechecks

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-post-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.erb, crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
See https://github.com/jsuchome/cloud-upgrade/blob/master/Step%2012.md , step 6
Depends on
- ~~https://github.com/crowbar/crowbar-core/pull/716 for deleting resources~~ merged
- ~~https://github.com/crowbar/crowbar-ha/pull/152 for changing the cluster founder~~ merged
=> Execute the post-upgrade actions for the node

crowbar_framework/lib/crowbar/upgrade_status.rb
save also failed state for the steps
=> don't forget to save the failed state

crowbar_framework/app/models/api/upgrade.rb
=> add a status when running the prechecks

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Backport of 
- https://github.com/crowbar/crowbar-core/pull/736
- https://github.com/crowbar/crowbar-core/pull/660
Depends on https://github.com/crowbar/crowbar-core/pull/773
=> [stable/3.0] Backport status library usage

crowbar_framework/app/controllers/api/upgrade_controller.rb
this is basically a synchronisation with:
https://github.com/crowbar/crowbar-ui/wiki/Upgrade67-Create-or-Connect-To-PostgreSQL-Database
=> update database parameter validations

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/routes.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/770
@MaximilianMeister please check closely esp. that backup part...
=> [stable/3.0] adding a status to the rest of the upgrade steps on cloud 6 side

crowbar_framework/app/controllers/installer_controller.rb
=> Redirect to installer for SES-only deploys

crowbar_framework/app/models/api/upgrade.rb
=> initialize state after canceling the upgrade

crowbar_framework/app/models/api/upgrade.rb
https://github.com/crowbar/crowbar-core/pull/789
=> [Forwardport] #789

crowbar_framework/app/models/api/upgrade.rb
https://github.com/crowbar/crowbar-core/pull/788
=> [Forwardport] #788

crowbar_framework/app/models/api/upgrade.rb
it has to be handeled the same way as the prechecks, because the user
might call it multiple times, especially when the repochecks failed
=> [stable/3.0] let adminrepocheck be called multiple times

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-post-upgrade.sh.erb, crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
This also includes fixes for both  DRBD and non-DRBD cases
=> Fixes for cluster controllers upgrade

crowbar_framework/app/models/api/upgrade.rb
When both resources (postgres, rabbitmq) have different allocations
of master/slave nodes, previous call would not be able to find
the slave node.
=> Check only for one drbd resource when picking first node for upgrade

crowbar_framework/app/models/api/upgrade.rb
https://github.com/crowbar/crowbar-core/pull/799
=> [forwardport] #799

crowbar_framework/app/models/api/upgrade.rb
this format is used in the noderepochecks through the repos-cloud.yml
file
=> [3.0] upgrade: bring repo names in consistent format

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb
forward-port https://github.com/crowbar/crowbar-core/pull/819
=> [forward-port] upgrade: bring repo names in consistent format

chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/crowbar/templates/default/sysconfig.crowbar.erb, chef/data_bags/crowbar/migrate/crowbar/101_crowbar-workers-and-threads.rb, chef/data_bags/crowbar/template-crowbar.json, chef/data_bags/crowbar/template-crowbar.schema, crowbar_framework/spec/fixtures/data_bags/template-crowbar.json
(cherry picked from commit 4aabda9ce962b9f5ee5b698b4e854678c57edea8)
backport of https://github.com/crowbar/crowbar-core/pull/817
=> [3.0] webserver: enable crowbar to change workers/threads itself

chef/cookbooks/network/recipes/default.rb
This change seems to be required in order to make wicked aware of config
file changes and to avoid it applying outdated configurations to the
interfaces.
https://bugzilla.suse.com/show_bug.cgi?id=1011889
=> network: Run wicked ifreload when ifcfg files change (bsc#1011889)

chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/templates/default/chef_client.erb, chef/data_bags/crowbar/migrate/provisioner/036_chef_client_runs.rb, chef/data_bags/crowbar/template-provisioner.json, chef/data_bags/crowbar/template-provisioner.schema, crowbar_framework/app/models/node_object.rb
=> [3.0] chef-client: Make chef_client runs configurable (bsc#1010211)

crowbar_framework/app/controllers/api/upgrade_controller.rb
start_step requires an argument (step name)
(cherry picked from commit 04c1e1ca1bc7cc4787b6e0b8ba90e16c69d54478)
Port from https://github.com/crowbar/crowbar-core/pull/833
=> upgrade: Fix the API call for Crowbar::UpgradeStatus.start_step

chef/data_bags/crowbar/migrate/crowbar/014_chef-solr.rb
backport of https://github.com/crowbar/crowbar-core/pull/838
=> [3.0] fix typo and comparison in migration

.lgtm
We don't use lgtm anymore so let's drop it.
=> Drop .lgtm config

crowbar_framework/app/assets/stylesheets/content/content.scss, crowbar_framework/app/views/barclamp/proposal_show.html.haml, crowbar_framework/app/views/dashboard/_link_proposal.html.haml
Thanks to Kenneth Wimer <wimer@suse.com>
http://bugzilla.suse.com/show_bug.cgi?id=1013250
=> crowbar: Fix invisible icons due to font-awesome update (bsc#1013250)

crowbar_framework/app/models/proposal.rb, crowbar_framework/app/models/service_object.rb
=> Fix proposals always considered as applied after being applied once

crowbar_framework/app/models/api/upgrade.rb
(cherry picked from commit 3e592028f3e6bfdaa74ebba115a33471fe1d7790)
forward port of https://github.com/crowbar/crowbar-core/pull/787
=> upgrade: make naming consistent

chef/cookbooks/provisioner/recipes/update_nodes.rb
This could happen if some ohai data is missing, or if the network
proposal is not providing a conduit map that is valid for a node.
If we keep crashing, then this actually breaks chef-client on the admin
server, which can then break DHCP, DNS and more for new nodes, or on
state transitions. However, there's nothing the admin server can do
about a node with wrong data, and we should avoid breaking the
deployment infrastructure because of this.
https://bugzilla.suse.com/show_bug.cgi?id=990745
=> provisioner: Avoid crashing if node has incomplete admin network mapping

crowbar_framework/app/assets/stylesheets/content/content.scss, crowbar_framework/app/assets/stylesheets/content/footer.scss, crowbar_framework/app/assets/stylesheets/content/header.scss, crowbar_framework/vendor/assets/stylesheets/variables.scss
=> Modified crowbar theme as per new colors

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
(cherry picked from commit 3f6086b4767604002c8b320609a672a5e97afda5)
Port of https://github.com/crowbar/crowbar-core/pull/855
=> upgrade: Allow repetition of Admin backup step

crowbar_framework/app/controllers/api/upgrade_controller.rb
this was forgotten during implementation
=> upgrade: document best_method in the apidoc

crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/error/upgrade_status.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
partially forward-ports https://github.com/crowbar/crowbar-core/pull/830
=> upgrade: restrict api access through the status library

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
https://github.com/crowbar/crowbar-core/pull/786
=> Forwardport #786

crowbar_framework/config/locales/crowbar/en.yml
(cherry picked from commit dc75401b1380b0370233c4630eed032e8160793a)
Forward-port of https://github.com/crowbar/crowbar-core/pull/876
=> upgrade: Fix the argument for error message

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
This will need adaptations elsewhere, e.g. in mkcloud scripts...
=> upgrade: Rename the progress file, mark the end of whole upgrade

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/883
=> [3.0] upgrade: Rename the progress file, mark the end of whole upgrade

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/controllers/application_controller.rb, crowbar_framework/app/views/errors/during_upgrade.html.haml, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/controllers/machines_controller_spec.rb
UPDATE (jsuchome): requires https://github.com/crowbar/crowbar-core/pull/883
=> upgrade: only allow requests to the upgrade api during the upgrade

crowbar_framework/config/initializers/yaml_db.rb, crowbar_framework/lib/crowbar/backup/export.rb, crowbar_framework/spec/lib/crowbar/backup/export_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/326
=> [3.0] Avoid exporting backups in the backup

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/locales/crowbar/en.yml
The barclamp controller expects an array as return value.
=> proposal: Fix wrong return on proposal reset (bsc#1014835)

chef/cookbooks/ohai/recipes/default.rb
Backport of https://github.com/crowbar/crowbar-core/pull/895
=> Keep less ohai data

chef/cookbooks/ohai/recipes/default.rb
Followup to https://github.com/crowbar/crowbar-core/pull/895. Unfortunately, I hadn't realized while testing that it wasn't fully working :/
=> Fix ohai cleanup

chef/cookbooks/bmc-nat/recipes/client.rb, chef/cookbooks/repos/recipes/default.rb
Backport of https://github.com/crowbar/crowbar-core/pull/904
=> bmc-nat, repos: Avoid useless searches

chef/cookbooks/barclamp/libraries/nic.rb
Backport of https://github.com/crowbar/crowbar-core/pull/525 and https://github.com/crowbar/crowbar-core/pull/526
=> [3.0] Fix potential infinite loop in Nic.dependent

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
https://github.com/crowbar/crowbar-core/pull/899
=> upgrade: execute services shutdown in the background

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/lib/crowbar/error.rb, crowbar_framework/lib/crowbar/error/upgrade_cancel.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
after certain steps it shouldn't be allowed to cancel the upgrade
anymore
=> upgrade: restrict cancelation of the upgrade

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-prepare-repositories.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.sh.erb, crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
This currently solves only one case, there are missing parts needed for non-ovs network setup. I believe that could be solved later
=> upgrade: upgrading compute nodes, live-migrate VM's in the process

crowbar_framework/spec/models/api/upgrade_spec.rb
* remove error mesage in success case
* we have to mock the wait_for_script_to_finish method
=> upgrade: enhance service shutdown specs

crowbar_framework/app/models/service_object.rb
(cherry picked from commit 114b413d3089907b9308c7b2451b1c310775dfd8)
=> [3.0] proposal: Initialize response with something useful (bsc#1014835)

crowbar_framework/app/models/network_service.rb, crowbar_framework/spec/fixtures/offline_chef/role_crowbar-admin_crowbar_com.json
~~Contains (and therefore depends on) https://github.com/crowbar/crowbar-core/pull/510 (merged)~~
=> Do not put network definition in data bag

chef/cookbooks/provisioner/recipes/update_nodes.rb
There's an "if" test which is useless.
This looks big, but use https://github.com/crowbar/crowbar-core/pull/949/files?w=1 to review. Also, there are many hound comments (which are valid), but they are actually not introduced by this change and I didn't want to fix all of them as this would make things less reviewable.
=> provisioner: Remove one level of indentation in update_nodes recipe

chef/cookbooks/provisioner/recipes/update_nodes.rb
We can hit a crash when a node has an incomplete admin network mapping.
This could happen if some ohai data is missing, or if the network
proposal is not providing a conduit map that is valid for a node.
If we keep crashing, then this actually breaks chef-client on the admin
server, which can then break DHCP, DNS and more for new nodes, or on
state transitions. However, there's nothing the admin server can do
about a node with wrong data, and we should avoid breaking the
deployment infrastructure because of this.
https://bugzilla.suse.com/show_bug.cgi?id=990745
(cherry picked from commit c00413c455a4d2f83b8557079f724f566e555912)
Backport of https://github.com/crowbar/crowbar-core/pull/803
=> provisioner: Avoid crash with incomplete network mappings (bsc#990745)

chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-router-migration.sh.erb, crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/node_object.rb, crowbar_framework/spec/fixtures/offline_chef/node_admin.crowbar.com.json, crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json, crowbar_framework/spec/models/api/upgrade_spec.rb
This is still very much work in progress. Especially the migration for subsequent nodes is largely untested. Just to give an overview where things are heading. Also there is a small conflict with compute node work in #875 (but that should be easy to solve)
=> upgrade: Rework router migration

crowbar_framework/app/controllers/barclamp_controller.rb, crowbar_framework/app/models/service_object.rb
While this may not seem strictly needed (although there are number of interesting fixes), it will ease backporting future work.
=> Backport various cleanups for (mostly) ServiceObject.apply_role

crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb
The exception should provide good error message. Once catched,
we must end the upgrade step with failure.
This is how the progress file looks when the error happens in prepare-repositories script: http://pastebin.suse.de/18858
=> upgrade: Raise exceptions on node upgrade errors and end the step

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/backup.rb, crowbar_framework/config/locales/crowbar/en.yml
=> [3.0] Backup errors backport

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/lib/crowbar/error/upgrade_status.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb, crowbar_framework/spec/spec_helper.rb
raise a custom exception when save fails, otherwise we might continue
silently
=> upgrade: handle failures on save (bsc#1018110)

crowbar_framework/lib/tasks/crowbar.rake
This will be used when updating barclamps to forcefully regenerate the
configs, in order to avoid the need of reapplying a barclamp to get the
matching data bag item.
=> crowbar: Add rake task to regenerate data bag configs

crowbar_framework/app/models/api/upgrade.rb
For better tracking of progress, indicate what the upgrade
is currently doing to the compute nodes.
=> upgrade: Save the node progress during the upgrade of compute nodes

crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/node.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
I've broke the testsuite by merging some PR's that were probably conflicting.
I had to cherry pick the commit from one existing PR (#950), seems like parts of it were already used and merged (wondering why it allowed me to merge without noticing the conflict)
=> Fix testsuite

chef/cookbooks/crowbar/templates/default/crowbar-chef-upgraded.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-delete-cinder-services-before-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-delete-pacemaker-resources.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-post-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-prepare-repositories.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-router-migration.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.sh.erb
The output of the scripts looks like this: http://pastebin.nue.suse.com/18770/src
=> upgrade: Added basic time stamps to the scripts executed by upgrade

crowbar_framework/app/models/node.rb
The scripts are deleting this file when they start. But if something
would slow them too much, crowbar could detect the presence of -failed file
from previous failed execution and assume the script has failed.
=> upgrade: Remove -failed indication right before starting the script (again)

crowbar_framework/app/controllers/barclamp_controller.rb, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/app/models/deployer_service.rb, crowbar_framework/app/models/dns_service.rb, crowbar_framework/app/models/ipmi_service.rb, crowbar_framework/app/models/logging_service.rb, crowbar_framework/app/models/network_service.rb, crowbar_framework/app/models/node.rb, crowbar_framework/app/models/ntp_service.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/app/models/service_object.rb, crowbar_framework/app/models/updater_service.rb, crowbar_framework/lib/crowbar/deployment_queue.rb, crowbar_framework/lib/remote_node.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/controllers/crowbar_controller_spec.rb, crowbar_framework/spec/controllers/nodes_controller_spec.rb, crowbar_framework/spec/lib/crowbar/backup/export_spec.rb, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb, crowbar_framework/spec/models/crowbar_service_spec.rb, crowbar_framework/spec/models/node_object_spec.rb
This is change is part of the switch to a ActiveRecord based Node
object.
=> node: Rename find_node_by_name to find_by_name

crowbar_framework/app/models/api/upgrade.rb
Before, the status API returned array of error hashes when some of
the prechecks failed. Everything was enclosed in one more hash.
This change converts this array to one hash and removes extra nesting
to match the common error format used in other places.
The error keys are assumed to be unique.
(cherry picked from commit c17fcc21658b65a707342fb6856a00ef707f9abd)
backport of #987
=> [stable/3.0] upgrade: Fix format of precheck errors in status

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/crowbar_spec.rb
backport https://github.com/crowbar/crowbar-core/pull/997
=> [3.0] upgrade: Check if a feature/addon is deployed, not enabled

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/fixtures/crowbar_repocheck.json
this is not a straight backport, so I haven't cherry-picked it
https://github.com/crowbar/crowbar-core/pull/989/commits/24302a8e48b2e63da9d88894d4a1faf00ea89540
partial backport of https://github.com/crowbar/crowbar-core/pull/989
=> upgrade: Adapt admin repository check

chef/cookbooks/crowbar/templates/default/crowbar-router-migration.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/controllers/crowbar_controller_spec.rb, crowbar_framework/spec/fixtures/offline_chef/node_drbd.crowbar.com.json, crowbar_framework/spec/fixtures/offline_chef/role_crowbar-drbd_crowbar_com.json, crowbar_framework/spec/models/api/upgrade_spec.rb
Requirs https://github.com/crowbar/crowbar-openstack/pull/780
=> upgrade: Orchestrate the upgrade of more controller clusters

crowbar_framework/app/models/api/upgrade.rb
=> [3.0] upgrade: Fix handling of multiple zypper prompts

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json, crowbar_framework/spec/fixtures/prechecks.json, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
```
{
"best_method": "none",
"checks": {
"cloud_healthy": {
"errors": {
"nodes_not_ready": {
"data": "Some nodes are not in the state \"ready\": d52-54-77-77-77-04.vo6.cloud.suse.de,crowbar.vo6.cloud.suse.de,d52-54-77-77-77-03.vo6.cloud.suse.de,d52-54-77-77-77-02.vo6.cloud.suse.de,d52-54-77-77-77-01.vo6.cloud.suse.de.",
"help": "Check the chef logs for identifying the problem. Make sure all the nodes are in state \"ready\" before proceeding with the upgrade."
}
},
"passed": false,
"required": true
},
"clusters_healthy": {
"errors": {},
"passed": true,
"required": true
},
"compute_resources_available": {
"errors": {},
"passed": true,
"required": false
},
"ha_configured": {
"errors": {},
"passed": true,
"required": false
},
"maintenance_updates_installed": {
"errors": {},
"passed": true, …
```
=> upgrade: Add more upgrade prechecks

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json, crowbar_framework/spec/fixtures/prechecks.json, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
foward-port of https://github.com/crowbar/crowbar-core/pull/1008
=> More prechecks

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/models/api/crowbar_spec.rb
```
+-------------------------------+--------+----------+-----------------------------------------------------+-------------------------------------------------------------------------------------------------------+
| Check ID                      | Passed | Required | Errors                                              | Help                                                                                                  |
+-------------------------------+--------+----------+-----------------------------------------------------+-------------------------------------------------------------------------------------------------------+
| network_checks                | true   | true     |                                                     | …
```
=> [stable/3.0] upgrade: Check if there are any failed proposals before starting the upgrade

chef/cookbooks/bind9/templates/default/db.erb, chef/data_bags/crowbar/migrate/dns/101_CNAME_records.rb, chef/data_bags/crowbar/template-dns.json, chef/data_bags/crowbar/template-dns.schema, crowbar_framework/app/assets/javascripts/barclamps/dns/application.js, crowbar_framework/app/helpers/barclamp/dns_helper.rb, crowbar_framework/app/models/dns_service.rb, crowbar_framework/app/views/barclamp/dns/_edit_attributes.html.haml, crowbar_framework/config/locales/dns/en.yml, crowbar_framework/vendor/assets/javascripts/jquery/dynamicTable.js
http://bugzilla.suse.com/show_bug.cgi?id=1016033
=> dns: Allow defining custom CNAME records (bsc#1016033)

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Requires https://github.com/crowbar/crowbar-core/pull/1011
=> upgrade: Save the backup location info in the progress file

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
follow up for https://github.com/crowbar/crowbar-core/pull/1011
=> upgrade: follow up for openstack backup creation

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/node.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/offline_chef/node_testing.crowbar.com.json, crowbar_framework/spec/models/api/upgrade_spec.rb
Needed together with https://github.com/crowbar/crowbar-ha/pull/168
=> Final actions needed after upgrade of cluster / compute node is done

crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/routes.rb, crowbar_framework/lib/crowbar/error.rb, crowbar_framework/lib/crowbar/error/upgrade.rb, crowbar_framework/spec/controllers/api/crowbar_controller_spec.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
https://github.com/crowbar/crowbar-core/pull/1031
=> upgrade: partially backport #1031

crowbar_framework/lib/crowbar/error/upgrade_status.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/922
=> [stable/3.0]  If upgrade step is out of order, tell what should be correct 

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
https://github.com/crowbar/crowbar-client/pull/145
=> upgrade: Prepare the nodes upgrade api for granular upgrades

crowbar_framework/app/controllers/api/crowbar_controller.rb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb
https://github.com/crowbar/crowbar-core/pull/1048
=> upgrade: partial forwardport of #1048

crowbar_framework/app/models/api/node.rb
Not nice, I know, but I've met some timeouts  already several times, so let's raise them.
Ideally, we would make them configurable.
=> Increase timeouts for upgrade related actions

crowbar_framework/lib/crowbar/upgrade_status.rb
(cherry picked from commit a4a027f05acc0f8a05356984964fb41325237dfe)
Backport of https://github.com/crowbar/crowbar-core/pull/1071
=> [stable/3.0] upgrade: Fix the check for upgrade finish

crowbar_framework/app/controllers/api/upgrade_controller.rb
When controller nodes have been upgraded previously,
whole nodes step was not actually finished, just a substep.
It make sense then to upgrade the rest with 'all'
=> upgrade: Allow upgrading all the rest of nodes after controllers

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/controllers/crowbar_controller_spec.rb, crowbar_framework/spec/fixtures/offline_chef/node_ceph.crowbar.com.json, crowbar_framework/spec/fixtures/offline_chef/role_crowbar-ceph_crowbar_com.json, crowbar_framework/spec/models/api/crowbar_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/1076
=> [stable/3.0] Ceph prechecks update

crowbar_framework/lib/crowbar/conduit_resolver.rb
This is a forward-port of the first commit of #575 (893bfbb5) in an attempt to make this code even clearer.  #575 never got merged because it took too long to review it, and in the meantime all of this code got significantly rewritten during extraction of the conduit resolver code into a library to be shared between Chef and Crowbar.
Since I don't have much clue what happened during the rewrite, I'm relying on @vuntz and particularly @rhafer to check that the comments I've ported over to here are all correct.
The other (fix) part of #575 was superseded by #803.
=> deobfuscate the network conduit resolver

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Backport of https://github.com/crowbar/crowbar-core/pull/1101
=> [stable/3.0] Save the upgrade mode into the progress library

crowbar_framework/lib/crowbar/upgrade_status.rb
(cherry picked from commit 892bad31ee95178598c46291351d23153adaa095)
Backport of https://github.com/crowbar/crowbar-core/pull/1103
=> upgrade: Before saving updated progress, read the latest from file

chef/cookbooks/network/recipes/default.rb
Regression introduced in 73a0ce5ff0cd335c51e0bae2175c2d8c675f97fa
=> network: Fix undefined variable

crowbar_framework/app/models/api/crowbar.rb
This was broken in https://github.com/crowbar/crowbar-core/pull/1118
=> upgrade: Look at correct place for proposal attributes

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/error/upgrade_status.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
This is a forward port of https://github.com/crowbar/crowbar-core/pull/1129 to master.
=> upgrade: Allow overriding the detected upgrade mode

crowbar_framework/app/models/service_object.rb
(cherry picked from commit ea271244e66575e3cb6e058bc033526c31436858)
This change gives the admin a better overview which batch gets currently applied,
More logging.
requests?**
https://github.com/sap-oc/crowbar-core/issues/6
based on https://github.com/crowbar/crowbar-core/pull/1020
=> [3.0] apply_proposal: Log current batch

crowbar_framework/config/locales/crowbar/en.yml
=> Add missing translation for unready state (bsc#1027230)

crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/fixtures/upgrade_status.json, crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
(cherry picked from commit fd7fc1675e38baa5daed9471dadd5362bcb76811)
Status library related changes ported from https://github.com/crowbar/crowbar-core/pull/1136
=> [stable/3.0] upgrade: Save more detailed information about current upgrade activity

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/models/api/crowbar_spec.rb
Current health check might be too strict. I currently do not know how to make it better. 
Some options were suggested here https://github.com/crowbar/crowbar-core/pull/1076#issuecomment-278481474 and here https://github.com/crowbar/crowbar-core/pull/1076#issuecomment-278771739
@tserong @smithfarm, please take a look and comment
UPDATE: I decided not to change the health check method, it seems to be too complicated. However, I've found several other errors while playing with it...
=> upgrade: Better check for health of ceph cluster

chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/error.rb, crowbar_framework/lib/crowbar/error/upgrade.rb
Additionally to better checking during the migration itself,
try to offer more information about how to solve the problem.
=> upgrade: Detect and report that some VM failed to migrate

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Cleanup of some minor stuff, DRY, etc.
Touches these cards 
https://trello.com/c/a630zeyt/347-move-save-substep-inside-the-methods-executing-the-substeps
https://trello.com/c/fGtuEsRe/343-no-comput-enodes-controller-substep-remains-running-atfter-the-whole-upgrade
Not really tested - I think the part with moving those substeps needs some testing to see if I broke something...
UPDATE: Tested manually
=> Cleanup the upgrade code

crowbar_framework/app/models/node.rb
=> upgrade: Make sure the check ssh output before treating it as string

crowbar_framework/app/models/api/upgrade.rb
=> upgrade: Fix the path to the log file in the error message

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/offline_chef/role_cinder-controller.json, crowbar_framework/spec/models/api/crowbar_spec.rb
Forward port of https://github.com/crowbar/crowbar-core/pull/1170
=> Extend the deployment prechecks

crowbar_framework/app/models/api/upgrade.rb
Another cleanup. Not yet tested
=> upgrade: Clean the current nodes once the substep is finished

chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-router-migration.sh.erb, crowbar_framework/app/models/api/upgrade.rb
https://bugzilla.suse.com/show_bug.cgi?id=1031499
=> upgrade: Update openstack commands for insecure SSL setup

crowbar_framework/lib/crowbar/upgrade_status.rb
(cherry picked from commit 92267107d69ba9ad26054c82e82003c4cc1adc07)
Backport of https://github.com/crowbar/crowbar-core/pull/1142
=> [stable/3.0] upgrade: Cleanup the current progress at the end of upgrade

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/models/api/crowbar_spec.rb
=> upgrade: Precheck for supported cluster configs (forward port to SOC7)

crowbar_framework/app/controllers/api/upgrade_controller.rb
forward port of #1205 
direct cherry-pick was not possible due to conflicts
=> upgrade: Log api exceptions to production.log (forward port to SOC7)

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/initializers/progress_logger.rb
At the moment there is no easy way to watch the progress of applying a
proposal. This change introduces a new logger which logs progress
relevant messages to a seperate log. But also adds this messages as
"PROGRESS" messages to the production log.
Interesting for https://github.com/sap-oc/crowbar-core/issues/6
=> apply_role: Add progress logging

chef/cookbooks/network/recipes/default.rb
Calling ifreload here seems to have been a bad idea as it cause various
issue in HA setups:
- pacemaker mananged VIPs assigned to any of the reloaded interfaces are
temporary lost, Causing resource failures in the cluster.
- reloading an interface causes a small network outage that can
de-stabilize the cluster, leading to fenced nodes and other bad
things.
https://bugzilla.suse.com/show_bug.cgi?id=1032751
=> Revert wicked ifreload related changes (bsc#1032751)

chef/cookbooks/crowbar/templates/default/apache.conf.erb, configs/crowbar.conf
(cherry picked from commit ba7bcc2)
Backport of #1206
=> [3.0] apache: Set timeout to 3600 to sync with the common crowbar timeout

chef/cookbooks/network/recipes/default.rb
Fixed network name reference in creating bridge name
=> Fixed network name reference in creating bridge name

chef/cookbooks/provisioner/recipes/dhcp_update.rb, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/provisioner/templates/default/grub.conf.erb
=> provisioner: Secure boot support

crowbar_framework/spec/controllers/api/backups_controller_spec.rb, crowbar_framework/spec/fixtures/crowbar_object.json, crowbar_framework/spec/fixtures/crowbar_upgrade_status.json, crowbar_framework/spec/fixtures/meta.json
=> Adjust tests for crowbar version bump

chef/cookbooks/provisioner/recipes/update_nodes.rb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/controllers/application_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/repos-cloud.yml, crowbar_framework/config/repos-ses.yml, crowbar_framework/lib/crowbar/product.rb, crowbar_framework/lib/crowbar/repository.rb, crowbar_framework/lib/crowbar/upgrade_status.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/controllers/machines_controller_spec.rb, crowbar_framework/spec/fixtures/node_repocheck.json, crowbar_framework/spec/fixtures/node_repocheck_missing.json, crowbar_framework/spec/models/api/node_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
=> Ocata Porting

crowbar_framework/app/models/service_object.rb, crowbar_framework/config/application.rb, crowbar_framework/lib/crowbar/lock/shared_non_blocking.rb
Backport of https://github.com/crowbar/crowbar-core/pull/1266 which I screwed up and didnt squash before merge :(
=> [4.0] Use threads to acquire/release locks in apply_role

chef/cookbooks/network/recipes/default.rb, chef/cookbooks/ohai/recipes/default.rb, chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/suse-manager-client/recipes/default.rb, chef/cookbooks/updater/recipes/default.rb
Saving is not cheap, and most of the time, it's not needed (as no attribute changed, or because we will already save later).
=> Decrease the amount of node saves

chef/cookbooks/network/recipes/default.rb, chef/cookbooks/ohai/recipes/default.rb, chef/cookbooks/provisioner/recipes/base.rb, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/cookbooks/suse-manager-client/recipes/default.rb, chef/cookbooks/updater/recipes/default.rb
only save the node when we are sure that some attributes have changed
(cherry picked from commit 5a5023e7e4f4bdd619b399b150431bfefde45237)
=> [4.0] Decrease the amount of node saves

bin/barclamp_lib.rb, bin/crowbar_machines, bin/crowbar_node_state, bin/gather_logs.sh, bin/transition.sh, chef/cookbooks/apache2/definitions/apache_module.rb, chef/cookbooks/crowbar/files/default/crowbar, chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/crowbar/templates/default/apache.conf.erb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/default/compute.ks.erb, chef/cookbooks/provisioner/templates/default/crowbar_join.redhat.sh.erb, chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb, chef/cookbooks/provisioner/templates/default/crowbar_join.ubuntu.sh.erb, chef/cookbooks/provisioner/templates/default/net-post-install.sh.erb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb, chef/data_bags/crowbar/migrate/crowbar/103_add_ssl_attributes.rb, chef/data_bags/crowbar/template-crowbar.json, chef/data_bags/crowbar/template-crowbar.schema, crowbar_framework/app/helpers/barclamp/crowbar_helper.rb, crowbar_framework/app/views/barclamp/crowbar/_edit_attributes.html.haml, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/spec/fixtures/data_bags/template-crowbar.json, updates/control_lib.sh
Interesting for https://github.com/sap-oc/crowbar-core/issues/7
=> crowbar: Add https support for the crowbar apache server

crowbar_framework/app/models/service_object.rb
The syntax was just wrong, we have to join the backtrace frist and then
print it.
=> service_object: Fix error logging (bsc#1051436)

crowbar_framework/app/models/service_object.rb
Backport of https://github.com/crowbar/crowbar-core/pull/1284
=> [4.0] service_object: Fix error logging (bsc#1051436) 

chef/cookbooks/ipmi/recipes/ipmi-discover.rb, chef/cookbooks/provisioner/recipes/update_nodes.rb, chef/cookbooks/utils/libraries/helpers.rb
=> Stable 4.0 bsc1054081

crowbar_framework/lib/remote_node.rb
Before running commands we check if a node is ready or the chef-client
is still running. Before doing that, we try to resolve the hostname
and continue with the resolved IP.
It seems that in some cases, resolve_host() does not work and returns
an empty string. The crowbar production.log then tells us:
INFO -- Waiting for already running chef-client on
d52-54-77-77-01-03.vk2.cloud.suse.de (); next attempt in 10 seconds
until 2017-08-31 04:36:53 +0000
but inside of "()" should be the resolved IP address. This message is
repeated until we reach the timeout. This repetition is useless
because we retry with an empty IP.
To minimize the impact of this problem, retry to resolve the hostname
for some time.
=> Retry to resolve a hostname before continue

chef/data_bags/crowbar/migrate/ipmi/102_bmc_nat_enable.rb, chef/data_bags/crowbar/template-ipmi.json, chef/data_bags/crowbar/template-ipmi.schema, crowbar_framework/app/models/ipmi_service.rb, crowbar_framework/app/views/barclamp/ipmi/_edit_attributes.html.haml, crowbar_framework/config/locales/ipmi/en.yml
=> ipmi: Option to disable BMC NAT (forward port)

chef/cookbooks/ipmi/recipes/ipmi-configure.rb, chef/data_bags/crowbar/migrate/ipmi/103_bmc_reconfigure.rb, chef/data_bags/crowbar/template-ipmi.json, chef/data_bags/crowbar/template-ipmi.schema, crowbar_framework/app/models/ipmi_service.rb, crowbar_framework/app/views/barclamp/ipmi/_edit_attributes.html.haml, crowbar_framework/config/locales/ipmi/en.yml
=> ipmi: Read-only mode (forward port)

crowbar_framework/app/controllers/dashboard_controller.rb
=> [3.0] Add json version of /clusters endpoint

crowbar_framework/app/controllers/dashboard_controller.rb
=> [4.0] Add json version of /clusters endpoint

crowbar_framework/app/models/node.rb
=> [4.0] Add chef_splay to allowed time without update

crowbar_framework/app/models/api/upgrade.rb
If only the admin (crowbar) node is deployed, an upgrade from SOC6 to
SOC7 currently fails with:
Creating OpenStack database backup failed
undefined method `[]' for nil:NilClass
There is no node with the role "database-config-default" in that
case. Do not fail but continue the normal upgrade process if the role
was not found.
=> upgrade: Don't fail without openstack db (bsc#1061777)

crowbar_framework/app/models/service_object.rb
Until now, we saved the role for the applied proposal early in
apply_role. However, apply_role could fail after that but still before
apply_role_pre_chef_client, resulting in the role containing incomplete
data (since apply_role_pre_chef_client is used to process the role and
add some info, like "use HA").
In case of such a failure (and that can happen when we fail to get a
lock for a node), then a periodic chef-client run would use a role with
incomplete information, possibly leading to changing the config on the
node wrongly.
This partially addresses
https://bugzilla.suse.com/show_bug.cgi?id=857375
Closes https://github.com/sap-oc/crowbar-openstack/issues/34
(cherry picked from commit 23dbcca77ff55eda45f46413d8bdc9762023f38e)
Backport of https://github.com/crowbar/crowbar-core/pull/1225
=> [4.0] crowbar: Do not save applied proposal as role too early in apply_role

bin/looper_chef_client.sh
I need a change to merge in order to test whether crowbar-trackupstream still works. 
requests?**
=> crowbar shell scripts: whitespace cleanup

crowbar_framework/app/models/chef_object.rb, crowbar_framework/app/models/node.rb, crowbar_framework/app/models/role_object.rb, crowbar_framework/spec/fixtures/offline_couchdb/roles_all.json, crowbar_framework/spec/support/offline_couchdb.rb
=> [4.0] Prefetch all roles during node listing

chef/cookbooks/provisioner/recipes/base.rb, chef/data_bags/crowbar/template-provisioner.json, crowbar_framework/app/models/node.rb
=> [4.0] Increase default chef_splay

crowbar_framework/app/helpers/nodes_helper.rb, crowbar_framework/app/models/node.rb, crowbar_framework/app/views/nodes/_buttons_power.html.haml, crowbar_framework/app/views/nodes/_show.html.haml
=> [4.0] Show IPMI links earlier

crowbar_framework/app/models/service_object.rb
As a side effect of introducing the experimental options for unchanged
and unready nodes into apply_role, there could be some cases in which
even if the nodes where removed from the list to be deployed we still
deployed them. For that issue, a check is done before adding the nodes
into the batches to check that indeed those nodes are going to be
deployed.
There was also a wrong comparision being done of the old_nodes vs
new_nodes in which we used the filtered list of nodes, but we want to
use the original node list without unfiltered to make sure that the
deployments didnt change. For this,the unfiltered list of nodes in the
new deployment is regenerated and used for the role comparision.
=> crowbar_framework: fix filtered nodes in apply_role

crowbar_framework/app/models/service_object.rb
As a side effect of introducing the experimental options for unchanged
and unready nodes into apply_role, there could be some cases in which
even if the nodes where removed from the list to be deployed we still
deployed them. For that issue, a check is done before adding the nodes
into the batches to check that indeed those nodes are going to be
deployed.
There was also a wrong comparision being done of the old_nodes vs
new_nodes in which we used the filtered list of nodes, but we want to
use the original node list without unfiltered to make sure that the
deployments didnt change. For this,the unfiltered list of nodes in the
new deployment is regenerated and used for the role comparision.
(cherry picked from commit adaa2b548543faa3c88c7262415bde369c1f7650)
Backport-of: …
=> [4.0] crowbar_framework:fix filtered nodes in apply_role

crowbar_framework/app/models/service_object.rb
Saving node data takes a lot of time when applying proposal for barclamps like dns or network which affect most of the nodes.
With multiple chef-server workers running, saving multiple nodes in parallel gives significant performance improvement in large scale installations.
requests?**
https://trello.com/c/jGyRtgrr/195-save-node-data-in-parallel
=> Multi-threaded node saving

crowbar_framework/app/models/service_object.rb
=> [4.0] Multi-threaded node saving

crowbar_framework/app/models/service_object.rb
We provide some more data as there are several steps that are
time-consuming, and it's useful to get progress reports about them.
This also removes a few progress lines that don't provide any real value
(especially the one for threads, which is just spammy).
=> crowbar: Add more progress output to apply_role

crowbar_framework/app/models/service_object.rb
We provide some more data as there are several steps that are
time-consuming, and it's useful to get progress reports about them.
This also removes a few progress lines that don't provide any real value
(especially the one for threads, which is just spammy).
(cherry picked from commit af41d69e8c012d3ec229ae132c0f29201833366e)
Backport of https://github.com/crowbar/crowbar-core/pull/1423
=> [4.0] crowbar: Add more progress output to apply_role

chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/models/node.rb, crowbar_framework/spec/controllers/nodes_controller_spec.rb
There were two issues when clicking "reinstall" for a node:
- a race where we were rebooting the node too fast
- the fact that the reboot of the node was actually triggering a state change, which could break the expected PXE config
(note that this contains https://github.com/crowbar/crowbar-core/pull/1430)
=> Fix issues when reinstalling a node

chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb, crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/models/node.rb, crowbar_framework/spec/controllers/nodes_controller_spec.rb
There were two issues when clicking "reinstall" for a node:
- a race where we were rebooting the node too fast
- the fact that the reboot of the node was actually triggering a state change, which could break the expected PXE config
Backport of https://github.com/crowbar/crowbar-core/pull/1430 and https://github.com/crowbar/crowbar-core/pull/1431
=> [4.0] Fix issues when reinstalling a node

crowbar_framework/app/views/deploy_queue/_dependencies.html.haml
=> [4.0] Fix dependency status updates in deployment_queue

chef/cookbooks/barclamp/libraries/nic.rb, chef/cookbooks/network/recipes/default.rb
Backport of https://github.com/crowbar/crowbar-core/pull/1449
=> [stable/4.0] Fix wait loop after network reconfiguration (bsc#1064813)

chef/cookbooks/crowbar/recipes/default.rb
This patch refactors the SSL implementation for crowbar and adds some logging info to make
debugging easier.
=> Add log info for crowbar SSL(bsc#1073998)

chef/cookbooks/provisioner/files/default/crowbar_join.ps1, chef/cookbooks/provisioner/files/default/set_hostname.ps1, chef/cookbooks/provisioner/recipes/setup_base_images.rb, chef/data_bags/crowbar/migrate/provisioner/202_no_supported_windows.rb, chef/data_bags/crowbar/template-provisioner.json
I don't think it makes sense to remove half of the code and half of the files. So instead, restore small bits, add an exception to the code in case the Hyper-V setup is done and would fail due to the large files missing, and properly remove the OS from the list of supported OS, with a migration.
=> Cleanup the Hyper-V cleanup

crowbar_framework/app/controllers/barclamp_controller.rb
crowbarctl node transition <name> <state> didn't accept alias
as name of the node. The problem was in API controller. To fix it
first it tries to get the node information from name or alias and
then calls to transition function using the real name.
=> crowbar : accept alias in node transition call

crowbar_framework/app/controllers/barclamp_controller.rb
crowbarctl node transition <name> <state> didn't accept alias
as name of the node. The problem was in API controller. To fix it
first it tries to get the node information from name or alias and
then calls to transition function using the real name.
(cherry picked from commit 9273c1c2a29a1a8f28b0e45114fd657de70116a4)
=> [4.0] crowbar : accept alias in node transition call

chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb, chef/cookbooks/provisioner/templates/default/autoyast.xml.erb, chef/cookbooks/provisioner/templates/suse/crowbar_register.erb, crowbar_framework/config/repos-cloud.yml
=> repos: Switch to new crowbar media

chef/cookbooks/network/recipes/default.rb
https://bugzilla.suse.com/show_bug.cgi?id=1075368
In some cases, the 'wicked ifup all' call executed after the
network barclamp updates all wicked and sysconfig configuration files
has the unwanted effect that it removes the default route.
This PR adds a step that restores the default route when missing.
Several other solutions have been attempted, without success (see 
bsc#1075368).
=> network: restore default route after 'wicked ifup all' (bsc#1075368)

chef/cookbooks/network/recipes/default.rb
(backport of #1491)
https://bugzilla.suse.com/show_bug.cgi?id=1075368
In some cases, the 'wicked ifup all' call executed after the
network barclamp updates all wicked and sysconfig configuration files
has the unwanted effect that it removes the default route.
This PR adds a step that restores the default route when missing.
Several other solutions have been attempted, without success (see
bsc#1075368).
=> [4.0] network: restore default route after 'wicked ifup all' (bsc#1075368)

crowbar_framework/app/models/salt_service.rb, crowbar_framework/app/models/suse_manager_client_service.rb, crowbar_framework/app/models/updater_service.rb
=> Expect the logger argument in the constructor (bsc#1089448)

crowbar_framework/app/models/suse_manager_client_service.rb, crowbar_framework/app/models/updater_service.rb
(cherry picked from commit 9c40bb3d512149f0e3bbd46ac708d56e50c31443)
Backport of https://github.com/crowbar/crowbar-core/pull/1544
=> [4.0] Expect the logger argument in the constructor (bsc#1089448)

crowbar_framework/spec/models/node_object_spec.rb
Testing of find_node_by_name_or_alias method of node
=> crowbar: test for find_node_by_name_or_alias

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, crowbar_framework/app/models/crowbar_service.rb
The bash code will fail if we try to disable something that is not present.
=> [4.0] upgrade: Fixes for prepare step

chef/cookbooks/ohai/files/default/plugins/linux/block_device_extended.rb
This is to make https://github.com/crowbar/crowbar-core/pull/1537 pass CI.
=> ohai: fix hound style errors

chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.sh.erb
this reverts commit 876952b89f5d63f6d45d3d43f4cc4d4d8966fbbb
as the package has been properly fixed
=> upgrade: revert openvswitch systemd unit fix

chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
nova service-disable is not available anymore.
Also, use --insecure option everywhere.
=> upgrade: Use correct commands for disabling and enabling nova-compute

crowbar_framework/app/models/api/upgrade.rb
The logic was broken for non-4.0 version.
=> upgrade: Fix platform retrieval

crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/node.rb
Multiple error handling/message improvements. Please check commit messages for details.
Includes https://github.com/crowbar/crowbar-core/pull/1585
=> upgrade: Improve various error messages

crowbar_framework/app/models/api/upgrade.rb
crowbar-ui package was locked before admin server upgrade. After the
whole upgrade process is completed, the lock can be removed and
crowbar-ui can be updated.
(cherry picked from commit 1aeb6459f6eaa60f134b6252b6210d11ce1412b9)
forward port of #1592
=> upgrade: Unlock crowbar-ui after completed upgrade

Gemfile
=> Update sprockets to 2.12.5 to fix a CVE

crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/node.rb
Multiple error handling/message improvements. Please check commit messages for details.
backport of #1610
=> [4.0] upgrade: Improve various error messages

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
pre-upgrade constraints ensure that the service is not running at the
node with active pre-upgrade attribute. This is necessary during the upgrade
when we need to control which nodes can run services and which cannot.
So we must do a cleanup before we start the upgrade, otherwise all services would
stop at all nodes once we set pre-upgrade attribute to all nodes (which is the
initial step of the upgrade).
(cherry picked from commit e9d93dcdad1da698060829e874bdf1f1f7492211)
Forward-port of https://github.com/crowbar/crowbar-core/pull/1534
=> upgrade: Remove pre-upgrade constraints from existing locations

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
pre-upgrade constraints ensure that the service is not running at the
node with active pre-upgrade attribute. This is necessary during the upgrade
when we need to control which nodes can run services and which cannot.
So we must do a cleanup before we start the upgrade, otherwise all services would
stop at all nodes once we set pre-upgrade attribute to all nodes (which is the
initial step of the upgrade).
(cherry picked from commit e9d93dcdad1da698060829e874bdf1f1f7492211)
Forward port of https://github.com/crowbar/crowbar-core/pull/1534
=> [5.0] upgrade: Remove pre-upgrade constraints from existing locations

chef/data_bags/crowbar/migrate/provisioner/300_add_sle12sp4.rb, chef/data_bags/crowbar/template-provisioner.json, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/repos-cloud.yml, crowbar_framework/lib/crowbar/platform.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/crowbar_repocheck.json, crowbar_framework/spec/models/api/node_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
=> crowbar: add support for SLES12 sp4

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb, crowbar_framework/spec/fixtures/node_repocheck.json, crowbar_framework/spec/fixtures/node_repocheck_missing.json
Fixes https://github.com/crowbar/crowbar-core/pull/1640
=> Fix travis test for SP4 and Cloud 9

crowbar_framework/app/models/api/crowbar.rb
Port of https://github.com/crowbar/crowbar-core/pull/1708
(cherry picked from commit 6128026427cedc31b40ac4482bd803a63cabfd5f)
=> upgrade: Allow upgrade with monasca agents on compute nodes

crowbar_framework/app/models/api/crowbar.rb
Port of https://github.com/crowbar/crowbar-core/pull/1708
(cherry picked from commit 6128026427cedc31b40ac4482bd803a63cabfd5f)
=> [5.0]upgrade: Allow upgrade with monasca agents on compute nodes

crowbar_framework/app/models/provisioner_service.rb
The chef recipes crash with a very weird error message when
the additional ssh keys section is malformatted, which can easily
be the case given that ssh keys are usually copy&pasted. Provide
some useful hints for troubleshooting formatting errors and enforce
that we have at least 3 sections because the chef recipes
are doing unification based on the "comment" field.
Backport of: https://github.com/crowbar/crowbar-core/pull/1696
(cherry picked from commit 33b52622dbc23e82a411209e897161bd8cc81899)
=> [4.0] provisioner: validate format of additional ssh keys section

crowbar_framework/app/models/provisioner_service.rb
The chef recipes crash with a very weird error message when
the additional ssh keys section is malformatted, which can easily
be the case given that ssh keys are usually copy&pasted. Provide
some useful hints for troubleshooting formatting errors and enforce
that we have at least 3 sections because the chef recipes
are doing unification based on the "comment" field.
(cherry picked from commit 33b52622dbc23e82a411209e897161bd8cc81899)
Backport from #1696
=> [5.0] provisioner: validate format of additional ssh keys section

crowbar_framework/config/crowbar.yml, crowbar_framework/lib/crowbar/conduit_resolver.rb
These were not merged yet, but we need them now for the ECP upgrade
=> [5.0] important patches for ECP upgrade

crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/node.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/node.rb
port of https://github.com/crowbar/crowbar-core/pull/1702
=> upgrade: Introduce parallelism into the upgrade of compute nodes

crowbar_framework/app/models/api/upgrade.rb
Last action for compute nodes is re-enabling the compute service.
If it fails, there should be an option to run the step again, but
that is not possible if the nodes are already marked as upgraded.
Additionally, make the check for ssh command run a bit more robust.
(cherry picked from commit bef6800be1dcc739f497f5c610fbad08529c6bf7)
port of https://github.com/crowbar/crowbar-core/pull/1740
=> upgrade: Do not mark nodes as upgraded before the last action

.travis.yml, crowbar.yml, crowbar_framework/app/controllers/ceph_pre_upgrade_controller.rb, crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/app/models/crowbar_service.rb, crowbar_framework/app/views/ceph_pre_upgrade/index.html.haml, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/config/navigation.rb, crowbar_framework/config/routes.rb, crowbar_framework/spec/models/api/crowbar_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Originally https://github.com/crowbar/crowbar-core/pull/1693. Only to archive the work.
=> Bring back the suport for ceph nodes during the upgrade

crowbar_framework/app/models/api/node.rb
(cherry picked from commit f5b34668cf1c6ea5aca1e23a1a747754df726db3)
=> upgrade: Mention the name of failed node in the error message

chef/cookbooks/crowbar/templates/default/crowbar-delete-unknown-nova-services.sh.erb
(cherry picked from commit 44c7de36adcdb1237a24ff1a3adb9e206d4a2499)
=> [5.0] upgrade: Fix syntax error (missing "done") in script

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-run-nova-online-migrations.sh.erb, crowbar_framework/app/controllers/api/upgrade_controller.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
Port of https://github.com/crowbar/crowbar-core/pull/1734
=> upgrade: Signal all nova services after the upgrade is complete 

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb, chef/cookbooks/crowbar/templates/default/crowbar-heat-migrations-after-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-nova-migrations-after-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-run-nova-online-migrations.sh.erb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/lib/crowbar/upgrade_timeouts.rb
Port of https://github.com/crowbar/crowbar-core/pull/1779
=> Call the migrations after the upgrade is done

crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/helpers/form_helper.rb, crowbar_framework/config/locales/crowbar/en.yml
=> [5.0] Support RAID 0

crowbar_framework/app/controllers/nodes_controller.rb, crowbar_framework/app/helpers/form_helper.rb, crowbar_framework/config/locales/crowbar/en.yml
Backport of  #1713 
wanted for small-HDD nodes in cloud.suse.de
=> [4.0] Support RAID 0

chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
There may be also other compute nodes than just kvm one , see https://bugzilla.suse.com/show_bug.cgi?id=1127129
=> upgrade: Make sure all compute nodes get compute related scripts

crowbar_framework/vendor/assets/stylesheets/_patches.scss
Update Codemirror to overive attribute set by bootstrap.
=> Remove arrows (SCRD-8737)

crowbar_framework/app/assets/javascripts/application.js, crowbar_framework/vendor/assets/stylesheets/jquery/ledUpdate.scss
* Updates led animations to be more apparent and easy to see.
* Updates all led animations to use css animations so they blink at the same rate.
=> Update in_process led animation (SCRD-8786)

chef/cookbooks/crowbar/recipes/default.rb, chef/cookbooks/provisioner/recipes/base.rb
There were some comments in https://github.com/crowbar/crowbar-core/pull/1821 that I didn't address due to the urgency to merge that PR. Here are the requested changes.
=> Code cleanups after #1821

crowbar_framework/app/assets/stylesheets/content/content.scss, crowbar_framework/app/assets/stylesheets/content/footer.scss, crowbar_framework/app/views/backups/index.html.haml, crowbar_framework/app/views/barclamp/proposal_show.html.haml, crowbar_framework/vendor/assets/stylesheets/_eos-branding.scss, crowbar_framework/vendor/assets/stylesheets/_patches.scss
* Updates navbar styles to closer match CLM Day2
* Updates default button styles
* Updates table headers
* Updates info alert colors
=> Update some styles for readability (SCRD-8787)

crowbar_framework/app/views/backups/index.html.haml, crowbar_framework/app/views/barclamp/proposal_show.html.haml, crowbar_framework/app/views/deploy_queue/index.html.haml, crowbar_framework/app/views/nodes/_form.html.haml, crowbar_framework/app/views/nodes/_show.html.haml, crowbar_framework/app/views/nodes/index.html.haml, crowbar_framework/app/views/nodes/list.html.haml, crowbar_framework/app/views/repositories/index.html.haml, crowbar_framework/app/views/ses/settings.html.haml, crowbar_framework/app/views/ucs/settings.html.haml, crowbar_framework/vendor/assets/stylesheets/_eos-branding.scss
* Updates the add button on dashboard
* Updates save/edit buttons on node screens
* Updates success background color and border color
* Remove header button from bulk edit screen
* Remove more button groups
* Move primary buttons to right side consistently
* Center dequeue button on deployment queue
=> Update some buttons and table bg color (SCRD-8787)

crowbar_framework/app/models/crowbar_validator.rb
This commit allows setup more relaxed domain names folowing a more
recent RFC https://tools.ietf.org/html/rfc1123#page-13
=> Crowbar: DomainName verification relaxed

crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/spec/controllers/machines_controller_spec.rb, crowbar_framework/spec/models/api/upgrade_spec.rb
This commit updates the file names for the upgrade from Cloud
8 to Cloud 9.
=> upgrade: update file names for 8 -> 9 (SOC-9029)

.travis.yml
port of #1884 and #1869 (with modifications)
=>  [4.0] travis: Whitelist CVE-2015-3448 (SOC-9911) + Travis Improvements (SOC-9565) 

crowbar_framework/config/repos-cloud.yml
because of ses5 was provided only 12sp3, repocheck of SOC9 got error.
=> repochecks errors for ses5-pool on SOC9

bin/crowbar_batch
The out param is a json sting which we first have to parse.
=> batch: Format crowbar batch error output (SOC-9954)

chef/cookbooks/barclamp/libraries/nic.rb, chef/cookbooks/network/recipes/default.rb
Backport of: https://github.com/crowbar/crowbar-core/pull/1853
=> [5.0] network: reduce risk of creating network loops

bin/gather_logs.sh, bin/transition.sh, chef/cookbooks/crowbar/files/default/crowbar
port of #1819 
NOTE: this part is independent of the restricted APIs and should be safe to merge without other deps
=> [5.0] Remove dubious uses of machine-install user

bin/gather_logs.sh, bin/transition.sh, chef/cookbooks/crowbar/files/default/crowbar
port of #1819 
NOTE: this part is independent of the restricted APIs and should be safe to merge without other deps
=> [4.0]  Remove dubious uses of machine-install user

chef/cookbooks/barclamp/libraries/nic.rb, chef/cookbooks/network/recipes/default.rb
Backport of https://github.com/crowbar/crowbar-core/pull/1853
=> [4.0]  network: reduce risk of creating network loops

bin/crowbar_batch
This reverts commit 7720e25118c76e1db99e4f43c53b71c78b672990.
=> Revert "batch: Use easy_merge for merging (SOC-10505)"

crowbar_framework/app/models/dns_service.rb
The DNS barclamp fails to apply when designate is enabled. This is
because in that case we try and add the admin node to the public
network.
In our CI this fails as the admin node only has 1 NIC and the admin
network has a lower router preference then public, so the default route
is killed.
Due to the topology supported by designate and potential security
concerns it's better that we never connect the admin node.
There is a crowbar-openstack PR to filter the admin node out in the
designate barclamp. This is the core side.
=> Designate: Don't add the admin node to the public network (SOC-10658)

crowbar_framework/app/models/api/crowbar.rb, crowbar_framework/app/models/api/upgrade.rb, crowbar_framework/config/locales/crowbar/en.yml
Forward port of https://github.com/crowbar/crowbar-core/pull/1684 & https://github.com/crowbar/crowbar-core/pull/1949
=> [5.0] upgrade: Precheck for unsaved proposals (SOC-10912)

chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb, crowbar_framework/app/models/crowbar_service.rb
=> [5.0] upgrade: Fixes for prepare step

crowbar_framework/app/models/dns_service.rb
The DNS barclamp fails to apply when designate is enabled. This is
because in that case we try and add the admin node to the public
network.
In our CI this fails as the admin node only has 1 NIC and the admin
network has a lower router preference then public, so the default route
is killed.
Due to the topology supported by designate and potential security
concerns it's better that we never connect the admin node.
There is a crowbar-openstack PR to filter the admin node out in the
designate barclamp. This is the core side.
(cherry picked from commit 5a5c6a94544c2226cb04914054d87bad88ae6a6f)
=> [5.0] Designate: Don't add the admin node to the public network (SOC-10658)

crowbar_framework/app/models/api/upgrade.rb
If the cluster is unhealthy, it could lead to errors during upgrade.
At this point all services are still running so it should be possible to
fix the problems.
I'm reusing existing health check functions here we are normally using for prechecks ... but why not?
=> upgrade: Make cluster health check at the start of services step 

crowbar.yml, crowbar_framework/config/locales/crowbar/en.yml, crowbar_framework/config/navigation.rb
Port of https://github.com/crowbar/crowbar-core/pull/1636
=> [5.0] Show upgrade menu item in SOC8

chef/cookbooks/ses/README.md, chef/cookbooks/ses/libraries/helpers.rb, chef/cookbooks/ses/metadata.rb, chef/cookbooks/ses/providers/config.rb, chef/cookbooks/ses/resources/config.rb, chef/cookbooks/ses/templates/default/ceph.conf.erb, chef/cookbooks/ses/templates/default/client.keyring.erb, crowbar_framework/app/assets/javascripts/application.js, crowbar_framework/app/controllers/ses_controller.rb, crowbar_framework/app/models/ses.rb, crowbar_framework/app/views/ses/settings.html.haml, crowbar_framework/config/locales/ses/en.yml, crowbar_framework/config/routes.d/ses.routes, ses.yml
port of #1799 and #2009 and #2010
=> [5.0] ses: Configuration upload & SES cookbook + other fixes

crowbar_framework/app/models/api/upgrade.rb
When going through the elements of nova barclamp,
properly recognize the case with remote computes.
=> upgrade: proper check for remote elements (trivial)

chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-remaining-services.sh.erb, chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
=> [5.0] upgrade: Fix systemd unit listing (trivial) 

crowbar_framework/app/models/api/upgrade.rb
Services must be restarted so they decide to use the right version of RPC API.
=> upgrade: Restart nova services at the end of disruptive upgrade (SOC-11202)

chef/cookbooks/barclamp/libraries/barclamp_library.rb, chef/cookbooks/barclamp/libraries/ssh_key_parser.rb, chef/cookbooks/provisioner/recipes/keys.rb, crowbar_framework/app/models/provisioner_service.rb, crowbar_framework/lib/crowbar/ssh_key_parser.rb, crowbar_framework/spec/lib/crowbar/ssh_key_parser_spec.rb
Fixed ssh keys validation wrt (optional) options field before the
type/method in key line.
Additional improvement is proper handling of comments with spaces and
extended list of supported key types.
Parsing is based on rules described here: https://man.openbsd.org/sshd#AUTHORIZED_KEYS_FILE_FORMAT
Test input:
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5pApJQ6rC+KAMSeXSLhqJTTcyNKrl7EU41XYzJoj0/AmwNtAt4eVNwVgJ3q0Uvw8DUtSYrb6d6jQCzsm4qdpc7dk1u8lIIYOlv/QYveAnsfkQTslocXZBsgBNcEUNguVVutUWDux4q/O5y8VU7wIr+5KtnEuFNO6V1h0TrC6wP+TcHCC5NnESBj/RHUkQc22xuc19HR/1pJf9WrUz+1pSK8dD96ckPIs3H6E0U6uVYuqn7GT9KeETxPKYZhs2qtwS/BBxtZZ/BbXQtzF0yHkLPBnutdIwcG74TF7QAAsECTkAsMi0FdABJeLTQA/7i7tv/KNBiHmf0wH9eHuGdXHx skazi@linux-ofh6.suse
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDX3SgWvI+w3uKlffi6Xbl0s4KIHek3lg69qdGuDrSsevU …
```
=> provisioner: Fix ssh key validation (SOC-11126)
